### ISSUE TITLE
single SK for crypto_sign() and crypto_box_*()

### ISSUE THREAD

**Issue by niXman** [jedisct1/libsodium#1000]
Hi,

in my app I need the possibility to sign the one type of messages using `crypto_sign()` and to crypt the another type of messages using `crypto_box_*()`.

my question is, since `crypto_sign_keypair()` and `crypto_box_keypair()` both generate a private keys, can I use the same private key for both `crypto_sign()`/`crypto_box_*()` ?

how can I solve this task?

thanks!

**Comment by jedisct1** [comment]
See https://doc.libsodium.org/quickstart#do-i-need-to-add-a-signature-to-encrypted-messages-to-detect-if-they-have-been-tampered-with and the next paragraph https://doc.libsodium.org/quickstart#how-can-i-sign-and-encrypt-using-the-same-key-pair

**Comment by niXman** [comment]
thank you, but I think we did not understand each other.
I will try to explain.

there is a server that can respond to users with two types of responses:
1) signed (`crypto_sign()`) only.
2) encrypted (`crypto_box_*()`).

my question is, can I use the same PK/SK pair for both `crypto_sign()`/`crypto_box_*()` ?

thanks.

**Comment by niXman** [comment]
> - How can I sign and encrypt using the same key pair?

paraphrasing on my way it would sound like this: `How can I sign **OR** encrypt using the same key pair?`

**Comment by jedisct1** [comment]
The title of the section has been changed from `sign and encrypt` to `sign and/or encrypt`.
Thanks!

**Comment by jedisct1** [comment]
Reverted, it was actually more confusing :)

**Comment by niXman** [comment]
ok %)
