### ISSUE TITLE
Libsodium in Google App Engine

### ISSUE THREAD

**Issue by dmuensterer** [jedisct1/libsodium#1001]
I know that this is propably not a fault of the Libsodium development team, however, since it is a question regarding Libsodium I might as well state it as an issue here.
Is there a way to use Libsodium in a PHP 7.3 environment on Google App Engine?
I am getting an undefined function error: `Fatal error: Uncaught error: Call to undefined function sodium_crypto_box_keypair()`
[Google states that it is pre-installed and enabled](https://cloud.google.com/appengine/docs/flexible/php/runtime#using_php_extensions):

> The following PHP extensions are pre-installed and enabled on the system:
> [..]
> libsodium

`phpinfo()` suggests that the module is not activated as there is no module section for Sodium. Other than on my local PHP environment where Sodium also works as expected.

How do I proceed with this?
Thank you.

**Comment by jedisct1** [comment]
The PHP extension for libsodium is [a different project](https://github.com/jedisct1/libsodium-php).

But this is really an issue with Google App Engine or the way you set it up.

The [documentation](https://cloud.google.com/appengine/docs/flexible/php/runtime) says:

> You can enable an extension by adding a php.ini file in the root of your application and using the extension directive: [...]
> [...]
> Alternatively, you can also enable an extension by adding a require to your composer.json [...]

Check that you followed Google's documentation. If that doesn't work, try contacting their support.

If you don't want to contact their support, maybe you can use [`sodium-compat`](https://github.com/paragonie/sodium_compat) which is a reimplementation of the libsodium PHP extension in pure PHP.
