### ISSUE TITLE
Linux / macOS prebuilt binaries

### ISSUE THREAD

**Issue by bric3** [jedisct1/libsodium#1008]
I would like to package libraries in application, in order to avoid system dependencies.
However there's no pre-built binaries for these platform / architectures: https://download.libsodium.org/libsodium/releases/

This would be awesome if the project could publish these.

Thanks in advance.

**Comment by angt** [comment]
Hello,
In the meantime, you can watch [here](https://github.com/angt/glorytun/blob/master/sodium.sh) how I build libsodium to build the static binaries of glorytun.
Maybe it will help you.

**Comment by bric3** [comment]
@angt, Thank you for the quick response. unfortunately the project I work with uses a different build tool (gradle) and a different language (java / kotlin) with libsodium bindings, I don't know how to translate the build steps in the gradle. Utimately I would like a reproducible build with a versionned artefact (along with a signature or a hash).

**Comment by jedisct1** [comment]
Precompiled packages are available for most Linux distributions and on macOS, it can be installed with Homebrew.

It's also fairly easy to compile it yourself as shown by @angt or as documented in the documentation.

If you need to ship an application that doesn't need external dependencies to be present, the easiest way to go is to statically link the libraries you need. By default, libsodium installs both as a static and a dynamic library, so you can use both.

**Comment by bric3** [comment]
@jedisct1 I know that, but I would like to ship the library as part of the application without requiring to install the library on the host OS. Currently I'm hacking my way through unpacking a deb package, homebrew bottles.

**Comment by jedisct1** [comment]
If the library is statically linked with your application, you don't need to ship in in addition to the application.

**Comment by bric3** [comment]
Yes but that doesn't work this way with bindings (Java in particular). I
need to use the library form. Did I misunderstood something.

-- Brice

**Comment by jedisct1** [comment]
Compiling the library as described above would produce exactly the same files as if done by someone else.

You can also set up a CI workflow if you need the compiled library to be updated every time changes are made to the stable branch. The resulting artifacts can be modified for the needs of your application.

**Comment by bric3** [comment]
OK, thanks for considering the idea though.
-- Brice

**Comment by ektrah** [comment]
Fwiw, the [libsodium NuGet package](https://www.nuget.org/packages/libsodium/1.0.18) for .NET contains prebuilt binaries for Linux (glibc & musl), macOS and Windows. Maybe it's possible to repackage those for Java?

**Comment by bric3** [comment]
@ektrah Cool thank you for this information !
