### ISSUE TITLE
Add cmake support?

### ISSUE THREAD

**Issue by DinoStray** [jedisct1/libsodium#1011]
Why not a cmake support?  
At least support find package?

**Comment by jedisct1** [comment]
There was a `Findsodium.cmake` file, but it was eventually [removed](https://github.com/jedisct1/libsodium/issues/929) because it never worked properly and was unmaintained.

**Comment by jedisct1** [comment]
The `Findsodium.cmake` file [is still present](https://github.com/jedisct1/libsodium/blob/stable/contrib/Findsodium.cmake) in stable releases, in case you ever can make something useful with it.
