### ISSUE TITLE
Wasm target benchmark

### ISSUE THREAD

**Issue by vimsiin** [jedisct1/libsodium#1023]
Hello! I am currently on research of various WebAssembly runtimes. After some googling, found out your amazing benchmark test-suite and gave it a shot. After setting some variables, the test went great!

I got results like this in the log file
```
12374340000
PASS xchacha20 (exit status: 0)
```
So the question is, what is the unit of this number? I searched in your docs and issues, but couldn't find it! I am a beginner, so any help is welcome. Thank you.

**Comment by jedisct1** [comment]
Hi!

These are nanoseconds.

Cranelift got a new backend, Wasmer made tons of progress, new LLVM versions are out, and new promising runtimes are available, so now would be a good time to run these benchmarks again!

**Comment by vimsiin** [comment]
Thank you for your kind reply. That was great help!
And yeah, I'm looking forward to the results!
