### ISSUE TITLE
This library support Ed25519 signatures and keys aggregation?

### ISSUE THREAD

**Issue by AlexiaChen** [jedisct1/libsodium#1029]
Ed25519 is a variant of Schnorr Signature on Tiwsited Edward Curve,   this library supports signature aggregation like this ( https://github.com/ZenGo-X/multi-party-eddsa/wiki/Aggregated-Ed25519-Signatures)?   I cannot found this aggregation function through the document.

**Comment by jedisct1** [comment]
This scheme is not (and will not) implemented in libsodium.

You can easily implement it using existing functions, though.
