### ISSUE TITLE
What is the difference between sodium_malloc and sodium_allocarray?

### ISSUE THREAD

**Issue by Chewhern** [jedisct1/libsodium#1037]
I am wondering what's the difference between sodium_malloc and sodium_allocarray?

Can anyone explains them in a simple explanation with easy to understand examples?

**Comment by jedisct1** [comment]
Just copy/pasting the [documentation](https://libsodium.gitbook.io/doc/memory_management#guarded-heap-allocations):

> The `sodium_allocarray()` function returns a pointer from which `count` objects that are `size` bytes of memory each can be accessed.
> It provides the same guarantees as `sodium_malloc()` but also protects against arithmetic overflows when `count * size` exceeds `SIZE_MAX`.
