### ISSUE TITLE
invalid usage on desktop chrome when running crypto_pwhash

### ISSUE THREAD

**Issue by neha-rai07** [jedisct1/libsodium#1038]
Error: invalid usage
    at h (sodium.js:formatted:17589)
    at Object.qA [as crypto_pwhash] (sodium.js:formatted:19328)

**Comment by jedisct1** [comment]
?

**Comment by karelbilek** [comment]
(I was thinking you overstated the annoying bug requests in your blog, but... nope. I feel for you. :) sorry to budge in, going out again)
