### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [jedisct1/libsodium#1041]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by jedisct1** [comment]
This happens very frequently; the latest release was even made today.

Get `-stable` releases [here](https://download.libsodium.org/libsodium/releases/).

**Comment by kloczek** [comment]
Hmm nevertheless https://github.com/jedisct1/libsodium/releases/tag/1.0.18 says that 1.0.18 has been released on 30 May 2019.
Since then there is any new tags.

**Comment by jedisct1** [comment]
If you want to pull code directly from the repository, use the `stable` branch.

**Comment by kloczek** [comment]
I did not said anything about what I want :)
I'm only noticing that youngest existing git tag still is almost two years old and still there is no any new/yesterday added tags :P
If almost two years old 1.0.18 tagged code has some stable branch updates I think that it would be good to release 1.0.18.1 or 1.0.19 should be released and tagged., and after two years at least sometbing like 1.0.19 if ot 1.1.0 should be released and tagged. Which one tags versions should ve used that depends on your tagging methodology.
