### ISSUE TITLE
New feature: Hybrid Public Key Encryption

### ISSUE THREAD

**Issue by chris-wood** [jedisct1/libsodium#1044]
Hybrid public key encryption is a well-known cryptographic construction that allows a sender to encrypt arbitrarily-sized messages under a receiver’s public key. ECIES, for example, is one variant of this particular construction built on elliptic curve Diffie Hellman for non-interactive key exchange. However, there exists a number of standardized versions of ECIES, each of which differs in [features, flexibility, security properties and, importantly, interoperability](https://ieeexplore.ieee.org/abstract/document/5604194/). 

HPKE is an emerging IRTF standard aimed at providing a single standard for all applications and use cases wherein public key encryption is required. This includes several other IETF standards, such as the [Message Layer Security protocol](https://datatracker.ietf.org/doc/draft-ietf-mls-protocol/), [TLS Encrypted Client Hello](https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html), and [Oblivious DNS over HTTPS](https://tools.ietf.org/html/draft-pauly-dprive-oblivious-doh-06). HPKE is flexible in almost every dimension, being built primarily on Key Encapsulation Mechanisms (KEMs), Key Derivation Functions, and AEAD algorithms. (Parameterization by KEMs is particularly useful in making the protocol ready for post-quantum algorithms.)

HPKE has a growing number of interoperable implementations in widely used [cryptographic libraries](https://github.com/cfrg/draft-irtf-cfrg-hpke#existing-hpke-implementations). The draft has [test vectors](https://github.com/cfrg/draft-irtf-cfrg-hpke/blob/master/test-vectors.json) available for all supported features.

HPKE is through the CFRG review process, is currently under review by the ISRG, and will likely be an RFC within the next couple of months. Given the maturity of the specification, growing number of dependent protocols and use cases, and wide community support, it seems like a fine candidate to include in libsodium. Picking a suite that is MTI for protocols like ECH seems like a perfectly fine approach. Assuming there’s support, I am definitely willing to contribute code or reviews to help land the feature!

**Comment by jedisct1** [comment]
> Oh, great! Can you share a pointer to the Zig change(s)?

https://github.com/jedisct1/zig-hpke - unfinished, as I paused it to write the compact Go one.

Something a little bit annoying in implementing HPKE, which is transparent in Go and Rust, is the fact that it requires dynamic memory allocations. In libsodium, absolutely nothing (besides memory-hard KDFs) does heap allocations, and in Zig, these must be explicit and tend to be avoided as much as possible.

**Comment by chris-wood** [comment]
> Something a little bit annoying in implementing HPKE, which is transparent in Go and Rust, is the fact that it requires dynamic memory allocations.

Yeah, that is annoying. Could you put a cap on the amount of arbitrary information (`info`, `psk_id`, etc.) that clients provide and allocate on the stack internally based on that? I definitely agree that avoiding allocations is something we should try and avoid.

**Comment by jedisct1** [comment]
> Yeah, that is annoying. Could you put a cap on the amount of arbitrary information (info, psk_id, etc.) that clients provide and allocate on the stack internally based on that? I definitely agree that avoiding allocations is something we should try and avoid.

Yes, capping the sizes is probably what we will have to do.

Not sure that this is desirable, but for interoperability purposes, documenting caps in the specification may be worth it.
