### ISSUE TITLE
The libsodium cocapods is outdated

### ISSUE THREAD

**Issue by Skycoder42** [jedisct1/libsodium#1048]
The current version of this library is not available at cocapods - it is stuck at Version 1.0.12 (See https://cocoapods.org/pods/libsodium). I do not know if you maintain this directly, but if you do, or have contact to those who do, please update to the latest version.

**Comment by jedisct1** [comment]
The page you linked shows the list of maintainers for that package. It would be best to contact them directly.

I don't completely understand what this package is for, and if it is still relevant, though.

On macOS, the library can be installed system-wide with Homebrew.

If you need Swift Packages, or something that can be installed with CocoaPods, there is [swift-sodium](https://github.com/jedisct1/swift-sodium)

**Comment by Skycoder42** [comment]
Okay. I'll try to contact them. I need the c library for bindings and want to automate deployment by bundling the c binary. For macos/ios, the easiest way to do this is by using cocapods.

**Comment by Skycoder42** [comment]
As I found out, swift-sodium already provides the C-API as well. See https://github.com/jedisct1/swift-sodium/issues/247
