### ISSUE TITLE
[Question] How to properly clean up the critical section created by sodium_init()?

### ISSUE THREAD

**Issue by TSchick90** [jedisct1/libsodium#1050]
Hey guys!

As the title says. I have some code checks in place which tell me about the critical section which is created during the `sodium_init()` but never really destroyed? Is there some `sodium_cleanup()` function or something I'm missing?

I would expect something like this in the core.c
```c
void sodium_crit_destroy()
{
   // if initialized, check _sodium_lock_initialized
   DestroyCriticalSection(&_sodium_lock);
} 
```

Stay save and best, Thomas

**Comment by jedisct1** [comment]
There's nothing to do. sodium_init() doesn't do any heap allocations.

**Comment by jedisct1** [comment]
Ah, I see what you are referring to. On windows, an `InitializeCriticalSection()` section is called by `sodium_init()`.
There's no `sodium_deinit()` function, so that value will not be deallocated. Not a big deal since it's only initialized once.

**Comment by jedisct1** [comment]
If that worries you, the following diff should destroy the critical section on release.

```diff
--- a/src/libsodium/sodium/core.c
+++ b/src/libsodium/sodium/core.c
@@ -94,14 +94,23 @@ sodium_crit_enter(void)
 int
 sodium_crit_leave(void)
 {
+    LONG status = 0L;
+
     if (locked == 0) {
 # ifdef EPERM
         errno = EPERM;
 # endif
         return -1;
     }
+    while ((status = InterlockedCompareExchange(&_sodium_lock_initialized,
+                                                1L, 0L)) == 1L) {
+        Sleep(0);
+    }
     locked = 0;
     LeaveCriticalSection(&_sodium_lock);
+    DeleteCriticalSection(&_sodium_lock);
+    _sodium_lock = NULL;
+    InterlockedAnd(&_sodium_lock_initialized, 0L);
 
     return 0;
 }
```

Completely untested, and probably not something that's going to be merged.

**Comment by TSchick90** [comment]
Ah yes, that I saw this on Windows would have been a useful information ... anyway, thanks for your answers :)
