### ISSUE TITLE
Unity builds unsupported due to repeated symbol names

### ISSUE THREAD

**Issue by SuperV1234** [jedisct1/libsodium#1051]
Hello, 

I'd like to build `libsodium` using a unity build, [which provides several advantages](https://onqtam.com/programming/2019-12-20-pch-unity-cmake-3-16/). This is currently not possible out of the box as some TU-specific objects with internal linkage have the same name, e.g.:

```
In file included from _deps\libsodium-cmake-build\CMakeFiles\sodium.dir\Unity\unity_9_c.c:13:
_deps/libsodium-cmake-src/libsodium/src/libsodium/randombytes/internal/randombytes_internal_random.c:128:1: warning: 'thread' attribute directive ignored [-Wattributes]
  128 | static TLS InternalRandom stream = {
      | ^~~~~~

In file included from _deps\libsodium-cmake-build\CMakeFiles\sodium.dir\Unity\unity_9_c.c:17:
_deps/libsodium-cmake-src/libsodium/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c:119:18: error: conflicting types for 'stream'
  119 | static SysRandom stream = {
      |                  ^~~~~~

In file included from _deps\libsodium-cmake-build\CMakeFiles\sodium.dir\Unity\unity_9_c.c:13:
_deps/libsodium-cmake-src/libsodium/src/libsodium/randombytes/internal/randombytes_internal_random.c:128:27: note: previous definition of 'stream' was here
  128 | static TLS InternalRandom stream = {
      |                           ^~~~~~
```

In order to fix the above error and support unity builds, all that's necessary is to give these `static` objects distinct names (e.g. `streamSysRandom` and `streamInternalRandom`).

**Comment by jedisct1** [comment]
Hi,

These are static symbols.

Static symbols are only visible in the files they are defined in. 

I'm not sure why your build system changes this, but that sounds like a bug or a configuration error.

Renaming static symbols to work around this doesn't seem like the right thing to do.

Libsodium uses autotools and Visual Studio projects. This is the only configuration it is tested and developed for.

Feel free to build it using your own system, but please understand that you are then completely on your own.

**Comment by SuperV1234** [comment]
Hello @jedisct1,

You might have closed this a tad too early. Are you aware of what a Unity build is, and why someone might want to perform such a thing? 

You should read the link I posted in the original post:
https://onqtam.com/programming/2019-12-20-pch-unity-cmake-3-16/

Here's an excerpt for you:

> ## Unity builds
>
> The idea is to cram the .cpp files of a CMake target into a few .cpp files which include the original .cpp files
>
> - up to 7-8 times faster builds (usually x3 or x4)
>
> - example: a project of 200 .cpp files might be divided into 16 unity .cpp (or .cxx - whatever) files each including about 13 of the original .cpp files => 16 .cpp files to build in parallel and 16 .obj files to link
>
> - the reasons for the speedup are:
>     - common headers from the different .cpp files end up being included and parsed fewer times (this is beneficial even when using PCHs!)
>     - common template instantiations with the same types in separate .cpp files (vector<int>) end up being done in fewer places
>     - the linker has to stitch much fewer .obj files in the end - there are a lot less weak symbols to deduplicate (inline/template
>     - functions from headers end up in every .obj => linkers leave just 1)
>          - surprisingly incremental builds (changing a single .cpp) will probably also be faster instead of slower (even though you compile more .cpp files together) - precisely because of the reduced number of weak duplicated symbols!
>     - less compiler invocations and less .obj files are written to disk

I am not asking `libsodium`'s build system to change, I am asking for a simple name refactoring of `static` symbols so that users of `libsodium` building it from source are able to perform a Unity build, if desired.

You mentioned:

> Renaming static symbols to work around this doesn't seem like the right thing to do.

This is exactly the right thing to do to support Unity builds. From the article:

> Initial problems when trying to compile a project as unity
>
> - there will be static globals (or in anonymous namespaces) in different .cpp files with identical names which would clash
>    - either rename them or put such globals into an additional namespace - perhaps with the name of the file: for GraphVisitor.cpp I would recommend GRAPH_VISITOR_CPP (putting static symbols inside of a named namespace in a .cpp keeps their linkage to internal , and the same is true with nesting anonymous namespaces into named ones)

Would you reject a PR that simply renames the conflicting `static` objects?

**Comment by jedisct1** [comment]
This is horrible. Please don't do that.

**Comment by SuperV1234** [comment]
> This is horrible. Please don't do that.

Thank you for the reminder that if I ever become the maintainer of a popular open-source project I should never be a dick and actually consider users' needs and opinions.

It really sucks to be on the receiving end.

**Comment by tancred** [comment]
Frank does an excellent job as an open source software maintainer!

One can't cater to everyone's needs. Why not write a small patch that you apply to the source tree before building with Unity? That should be really easy.

**Comment by SuperV1234** [comment]
> Frank does an excellent job as an open source software maintainer!

I don't doubt that.

> One can't cater to everyone's needs. 

Agreed as well.

My problem is with the attitude and non-technical response.

Is *"This is horrible. Please don't do that."* the kind of answer you want to give someone who wants to contribute something to your project? 

That's an inconsiderate answer, that shows how somebody good at maintaining software is not necessarily a good person or has poor communication skills. It demonstrates zero consideration for a user's needs and provides zero technical arguments. I expect something better from someone maintaining a project being used worldwide.

@jedisct1 let me help you out for next time, here's what you could do:

1. Actually read the suggestion and try to understand the user's requirements and needs, before closing the issue without understanding it as demonstrated by [your first reply](https://github.com/jedisct1/libsodium/issues/1051#issuecomment-819106921).

2. After considering the benefits/drawbacks of the proposed change, make a judgement in good faith.

3. If the suggestion is declined, politely and briefly mention why on a *technical* level, then close the issue. Here's an example I just came up with: *"Hello, I have looked at your suggestion and decided that unity builds is not something I want to support in `libsodium` as the compilation time benefits do not outweigh the maintenance burden of manually providing unique names for `static` symbols."*

See, it's not hard, you might learn something you didn't know before (i.e. the benefits and drawbacks of unity builds), and you won't come across like an asshole. :)
