### ISSUE TITLE
Add new binding to libsodium page

### ISSUE THREAD

**Issue by Chewhern** [jedisct1/libsodium#1077]
Currently my self made libsodium binding named ASodium have been published to nuget.

I feel that it can be added to libsodium
https://doc.libsodium.org/bindings_for_other_languages
page

Here's my libsodium binding for nuget,
https://www.nuget.org/packages/ASodium/

It is not as good as NSec, but in most cases, it can
be a substitute to the old Sodium.Core or libsodium-net

Could Jedisct1 consider adding my binding to the libsodium page?

**Comment by jedisct1** [comment]
This is great!

The documentation has its own repository: https://github.com/jedisct1/libsodium-doc

Would you mind sending a pull request there?

Thank you!
