### ISSUE TITLE
It's possible to forge messages that crypto_sign_open verifies if the public key is zero.

### ISSUE THREAD

**Issue by orlp** [jedisct1/libsodium#112]
If the public key is zero, the signature is zero and the message is a randomly generated public key there is a chance the message will verify.

Example code: https://gist.github.com/nightcracker/8597602

I think the solution is simple, and that is to check for a zero public key. That's never a valid public key anyway, and I don't think this attack generalizes outside of zero public keys.

**Comment by jedisct1** [comment]
Following the irtf-cfrg-eddsa draft, the `0<S<l` test was reintroduced.

Even though the security implications of a small order `R` are unclear, points of order <= 8 are now rejected.
