### ISSUE TITLE
RPI4 doesnt support AEGIS?

### ISSUE THREAD

**Issue by niXman** [jedisct1/libsodium#1200]
Hello,

the function `crypto_aead_aegis256_is_available()` returns FALSE.

perhaps the bug in the implementation?

If not, is there any software AEGIS implementation I can use on RPI4?

best!

**Comment by jedisct1** [comment]
It should be available if you're using your RPI4 with a 64-bit operating system.

There may eventually be a software version, but it's going to be super slow.
