### ISSUE TITLE
WSL with GCC11 build error

### ISSUE THREAD

**Issue by yingkee** [jedisct1/libsodium#1202]
crypto_generichash/blake2/ref/blake2.h:126:5: error: size of array element is not a multiple of its alignment
  126 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
crypto_generichash/blake2/ref/blake2.h:127:5: error: size of array element is not a multiple of its alignment
  127 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~

**Comment by jedisct1** [comment]
I don't understand.

There's no line 126 in that file, and no `blake2b_state S[4][1]`  anywhere in the code either.

What version did you get? Where did you download it?
