### ISSUE TITLE
AEGIS-[128,256]X

### ISSUE THREAD

**Issue by victorstewart** [jedisct1/libsodium#1292]
saw your aegis-X repository and was curious... are these on the agenda?

[https://github.com/jedisct1/aegis-X](https://github.com/jedisct1/aegis-X)
[https://eprint.iacr.org/2023/523.pdf](https://eprint.iacr.org/2023/523.pdf)

**Comment by jedisct1** [comment]
Hi,

If you're looking for C implementations, they will be added to https://github.com/jedisct1/libaegis

Code from that library may be merged to libsodium later. But please, as the message you deleted said, use the discussions section for discussions. The bug tracker is for bugs.

Thanks!

**Comment by victorstewart** [comment]
thank you very much! 

haha and sorry, i didn't delete it i just clicked "blank issue"— i always forget discussions exist now.
