### ISSUE TITLE
strict-aliasing violation in blkxor pwhash_scryptsalsa208sha256_nosse.c

### ISSUE THREAD

**Issue by MatzeB** [jedisct1/libsodium#1301]
The `blkxor` function in `pwhash_scryptsalsa208sha256_nosse.c` breaks strict aliasing rules (for `ARCH_BITS==64`). It load/stores from a buffer via `uint64_t*` that is otherwise accessed via `uint32_t*` only. We just had trouble with this in core scrypt and clang-15 LTO mode and found upstream scrypt had already fixed it in https://github.com/Tarsnap/scrypt/commit/209fd279c9357010d1dabd446c458dfeb9820e6c

I noticed a copy / similar problematic code for `ARCH_BITS==64` in libsodum version.

**Comment by jedisct1** [comment]
Thanks for the heads up!

It should be fixed now, including in `stable`.

Thanks again!
