### ISSUE TITLE
android-ndk-r26-rc1 build error for stable

### ISSUE THREAD

**Issue by calvin2021y** [jedisct1/libsodium#1314]
```sh
toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/include/arm_neon.h:62829:32: error: always_inline function 'vget_high_p64' requires target feature 'crypto', but would be inlined into function 'vmull_high_p64' that is compiled without support for 'crypto'
  __ret = vmull_p64((poly64_t)(vget_high_p64(__p0)), (poly64_t)(vget_high_p64(__p1)));
```

**Comment by jedisct1** [comment]
Can you provide a little bit more context?

Is it when running the `dist-build/android-armv8-a.sh` script?

**Comment by jedisct1** [comment]
This has been tested with the stable version of the NDK.

But I tried with `r26-rc1`, and the scripts seem to be working fine as well.

I just ran `dist-build/android-aar.sh`, which compiles for all architectures and creates an `AAR` file.

Are you using an older version of these scripts?

**Comment by jhheider** [comment]
I am also seeing this error for linux aarch64 with 1.0.19:

https://github.com/teaxyz/pantry/actions/runs/6170060283/job/16745594856

**Comment by jedisct1** [comment]
@jhheider  Try adding `-march=armv8-a+crypto`.
