### ISSUE TITLE
Shouldn't crypto_pwdhash_PRIMITIVE be 'argon2id' ?

### ISSUE THREAD

**Issue by zedalaye** [jedisct1/libsodium#1331]
Hi,

As almost all constants in this file references those of `crypto_pwhash_argon2id.h`, shouldn't crypto_pwdhash_PRIMITIVE be, in fact "argon2id" ? 

https://github.com/jedisct1/libsodium/blob/6ee5a7345296a0a104fc3630bcea56e2f9f0f513/src/libsodium/include/sodium/crypto_pwhash.h#L138C14-L138C14

**Comment by jedisct1** [comment]
Good catch!

We should list both, as they are both supported by the high-level APIs.

Thanks!
