### ISSUE TITLE
LATEST.tar.gz.sig is missing

### ISSUE THREAD

**Issue by oluwandabira** [jedisct1/libsodium#1344]
Trying download libsodium and [LATEST.tar.gz.sig](https://download.libsodium.org/libsodium/releases/LATEST.tar.gz.sig) from https://download.libsodium.org/libsodium/releases/ returns a 404.

Not an actual bug but have its not a discussion topic either so I'll just put it here.

**Comment by jedisct1** [comment]
Link removed, thank you!
