### ISSUE TITLE
Request to add amalgamation build

### ISSUE THREAD

**Issue by tahaghafuri** [jedisct1/libsodium#1346]
Hello
Please provide the possibility of building in the form of amalgamation like the miniz library, so that libsoudium can be used in the form of a C and header file.

Example:https://github.com/richgel999/miniz

**Comment by jedisct1** [comment]
This is not planned, sorry.

You may want to consider [libhydrogen](https://github.com/jedisct1/libhydrogen) instead.

**Comment by tahaghafuri** [comment]
[libhydrogen](https://github.com/jedisct1/libhydrogen) Is Very Minimal And it does not have many features of libsodium
