### ISSUE TITLE
Zig build for windows platform issue

### ISSUE THREAD

**Issue by meiyese** [jedisct1/libsodium#1371]
Hi, I use zig build for windows, and found that the dll with cause crash.

but msvc build is ok. It may caused by `HAVE_AMD64_ASM` macro.

HAVE_AMD64_ASM is on by default for zig build, which is off for msvc.

**Comment by jedisct1** [comment]
Good catch, thank you!

Yes, absolutely, the calling conventions are different on Windows.

This should be fixed now. Thanks again!
