### ISSUE TITLE
Assert failure observed on box_seal test

### ISSUE THREAD

**Issue by byron-hawkins** [jedisct1/libsodium#1388]
While benchmarking performance on the libsodium tests, we encountered an assert failure in the `box_seal` test at line 68 in the stable branch (May 24):

    assert(m_len == 0 || memcmp(cm, m2, m_len) != 0);

It appears to be a special case because this assert has only failed once over millions of iterations of the test. A core file is attached. Binaries were built with a local toolchain of `clang` and `ld.lld` (LLVM 17) with `-flto` on Fedora 38 x86_64.  

[box_seal.core.tar.gz](https://github.com/user-attachments/files/16045352/box_seal.core.tar.gz)

**Comment by jedisct1** [comment]
Good catch, thank you!
