### ISSUE TITLE
Documentation on crypto_secretstream API

### ISSUE THREAD

**Issue by byron-hawkins** [jedisct1/libsodium#1393]
This issue is specific to the [gitbook page on the crypto_secretstream API](https://libsodium.gitbook.io/doc/secret-key_cryptography/secretstream). On other similar pages, the documentation clearly indicates whether the plaintext and ciphertext buffers may point to the same address for in-place encryption/decryption. When I've tried it with this API, specifically `crypto_secretstream_xchacha20poly1305_pull()`, it works fine. But I don't have a way to know for sure if this usage is always expected and supported. Would it be possible to have this detail added to the gitbook page?

**Comment by jedisct1** [comment]
Sure! Feel free to send a pull request. The documentation has its own repository: https://github.com/jedisct1/libsodium-doc
