### ISSUE TITLE
Compilation issue on SunOS 5.10 with gcc: __stack_chk_guard undefined

### ISSUE THREAD

**Issue by dorvardi2** [jedisct1/libsodium#1400]
Issue Description:

Summary:
I’m encountering a test failure when running make check on libsodium version 1.0.18 on a Solaris 10 (SunOS 5.10) system. The failure occurs specifically in the randombytes test, where it seems that certain symbols (__stack_chk_fail and __stack_chk_guard) are not found during the linking phase.

Environment:

	•	OS: Solaris 10 (SunOS 5.10)
	•	Architecture: x86_64
	•	GCC Version: 9.5.0
	•	libsodium Version: 1.0.18

Steps to Reproduce:

	1.	Download and extract the libsodium 1.0.18 source code.
	2.	Build and install libsodium using the following commands:
	
cd /usr/local/src
wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
tar -xzvf libsodium-1.0.18.tar.gz
cd libsodium-1.0.18
./configure 
make
make check

  CC       aead_aes256gcm.o
  CCLD     aead_aes256gcm
Undefined                       first referenced
 symbol                             in file
__stack_chk_fail                    ../../src/libsodium/.libs/libsodium.so
__stack_chk_guard                   ../../src/libsodium/.libs/libsodium.so
ld: fatal: symbol referencing errors. No output written to .libs/aead_aes256gcm
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1282: aead_aes256gcm] Error 1
make[3]: Leaving directory '/usr/libsodium-1.0.18/test/default'
make[2]: *** [Makefile:2489: check-am] Error 2
make[2]: Leaving directory '/usr/libsodium-1.0.18/test/default'
make[1]: *** [Makefile:402: check-recursive] Error 1
make[1]: Leaving directory '/usr/libsodium-1.0.18/test'
make: *** [Makefile:514: check-recursive] Error 1

**Comment by jedisct1** [comment]
Google returns quite a lot of results for `__stack_chk_guard undefined`.

If you can't update your operating system/compiler toolchain, try adding `--disable-ssp` to your `./configure` flags.
