### ISSUE TITLE
undefined vrf symbol in master branch

### ISSUE THREAD

**Issue by calvin2021y** [jedisct1/libsodium#1411]
`crypto_vrf_bytes` , `crypto_vrf_rfc9381_sk_to_pk`, `crypto_vrf_rfc9381_sk_to_seed` is in header file but without body.

**Comment by jedisct1** [comment]
Do you see a warning message after every line when you type the `make` or `zig build` command in that development branch?

**Comment by calvin2021y** [comment]
I am not notice warning message, just try link the function and get error
