### ISSUE TITLE
Is it on the roadmap to add any post-quantum encryption or signature algorithms?

### ISSUE THREAD

**Issue by getify** [jedisct1/libsodium#1412]
I didn't see any details/plans documented, but apologies if I missed it. Is there plans to bring any of the PQ algorithms into libsodium (and in particular, libsodium.js)?

Was prompted to ask after discovering this library: https://github.com/paulmillr/noble-post-quantum

I prefer Libsodium over Noble (from previous attempts/experiences), so it made me wonder about any PQ support here. Thanks for any info/plans you can share.

**Comment by jedisct1** [comment]
https://github.com/jedisct1/libsodium/discussions/1275

**Comment by jedisct1** [comment]
And there's also a [roadmap](https://doc.libsodium.org/roadmap).

**Comment by getify** [comment]
Apologies!
