### ISSUE TITLE
CI failure with NET packages 

### ISSUE THREAD

**Issue by jedisct1** [jedisct1/libsodium#1414]
.NET packages have been failing on CI since 53a746c , but it doesn't seem to be related to that specific commit. Reverting to a past commit such as 1.0.20-RELEASE doesn't fix the issue.

https://github.com/jedisct1/libsodium/actions?query=branch%3Astable

The artifacts build fine, but the upload/download-artifacts script doesn't find anything.

**Comment by samuel-lucas6** [comment]
Could it be `include-hidden-files: false`? When it worked, that [wasn't](https://github.com/jedisct1/libsodium/actions/runs/10376137687/job/28727678357) there, but it appears [here](https://github.com/jedisct1/libsodium/actions/runs/10920526476/job/30310913243) in `Run actions/upload-artifact@v3`.

In [later jobs](https://github.com/jedisct1/libsodium/actions/runs/11053405830/job/30708200478), there are other settings appearing as well for the `upload-artifact` step, which aren't in the [dotnet-core.yml](https://github.com/jedisct1/libsodium/blob/master/.github/workflows/dotnet-core.yml#L271) file.

**Comment by jedisct1** [comment]
Bingo!

Good catch, @samuel-lucas6 !
