### ISSUE TITLE
Xcode prompts an error about blake2b_state S[1];

### ISSUE THREAD

**Issue by ParallelSpaceAndTimeAlone** [jedisct1/libsodium#1425]
Using Xcode import,   pod 'libsodium'

The following code indicates an error.
blake2b_state S[1];   
Size of array element of type 'blake2b_state' (aka 'struct crypto_generichash_blake2b_state') (361 bytes) isn't a multiple of its alignment (64 bytes)

Please help to check this issue.

**Comment by jedisct1** [comment]
https://github.com/jedisct1/libsodium/discussions/1424
