### ISSUE TITLE
blake2b symbols conflict with static Qt6

### ISSUE THREAD

**Issue by valaczka** [jedisct1/libsodium#1434]
Ld error when linking libsodium and static Qt 6.8.1, because Qt Core also includes blake2b in the cryptographic hash module.
The bug occurred with emscripten compiler, but is probably possible with all static builds.

wasm-ld: error: duplicate symbol: blake2b_init_param
>>> defined in /home/valaczka/libsodium-1.0.20/libsodium-js/lib/libsodium.a(libsodium_la-blake2b-ref.o)
>>> defined in /home/valaczka/Qt/6.8.1/wasm_singlethread/lib/libQt6Core.a(qcryptographichash.cpp.o)

wasm-ld: error: duplicate symbol: blake2b_init
>>> defined in /home/valaczka/libsodium-1.0.20/libsodium-js/lib/libsodium.a(libsodium_la-blake2b-ref.o)
>>> defined in /home/valaczka/Qt/6.8.1/wasm_singlethread/lib/libQt6Core.a(qcryptographichash.cpp.o)

wasm-ld: error: duplicate symbol: blake2b_init_key
>>> defined in /home/valaczka/libsodium-1.0.20/libsodium-js/lib/libsodium.a(libsodium_la-blake2b-ref.o)
>>> defined in /home/valaczka/Qt/6.8.1/wasm_singlethread/lib/libQt6Core.a(qcryptographichash.cpp.o)

wasm-ld: error: duplicate symbol: blake2b_final
>>> defined in /home/valaczka/libsodium-1.0.20/libsodium-js/lib/libsodium.a(libsodium_la-blake2b-ref.o)
>>> defined in /home/valaczka/Qt/6.8.1/wasm_singlethread/lib/libQt6Core.a(qcryptographichash.cpp.o)
em++: error: '/home/valaczka/emscripten/emsdk/upstream/bin/wasm-ld @/tmp/emscripten_p1maxkpu.rsp.utf-8' failed (returned 1)

This bug is also reported in Qt: https://bugreports.qt.io/browse/QTBUG-132347

**Comment by jedisct1** [comment]
Looks like that has been fixed in QT.
