### ISSUE TITLE
Emscripten no name functions

### ISSUE THREAD

**Issue by valls** [jedisct1/libsodium#178]
Hi!

After running emscripten.sh generates libsodium-js folder with "includes" (.h files folder) and "lib". inside lib creates libsodium.js. How can I run on browser client? It seems that name functions aren't inside libsodium.js. How can I work with that file?

Thanks!

**Comment by jedisct1** [comment]
Closing this, because Javascript work is now happening here https://github.com/jedisct1/libsodium.js
