### ISSUE TITLE
amd64 optimized version of ed25519

### ISSUE THREAD

**Issue by stv0g** [jedisct1/libsodium#184]
Hi, after some back-and-forth I decided to go with libsodium for my application which requires pretty fast ed25519 signatures.

The only disadvantage was that libsodium doesn't use the amd64 optimized reference implementation from djb.

Do you've plans to integrate this? I think @floodyberry 's donna implementation [1] is pretty neat in this regard. I would be pretty happy if this becomes integrated in the future :-)

Cheers,

stv0g

[1] https://github.com/floodyberry/ed25519-donna

**Comment by jedisct1** [comment]
Closing - We gonna have a faster one.
