### ISSUE TITLE
multiple definition of `realpath', due to older glibc with newer gcc bug

### ISSUE THREAD

**Issue by M-Shell** [jedisct1/libsodium#202]
The build system for libsodium-1.0.0 trips on a bug which is found in older
glibc versions (<2.8, most certainly < 2.6) under newer versions of gcc
(say > 4.4).

Given that it is a problem with such an older glibc, some developers may
not wish to address a fix. A search of Google for

"multiple definition of" D_FORTIFY_SOURCE

shows there still are some people running into this problem and so there
should be at least some info on the cause and a workaround for it.
Hence, this report.

-----
The glibc/gcc bug is triggered whenever the *all* of the following appear
in the C/CPP flags:

-O2 (>0) 
-D_FORTIFY_SOURCE=2 (>0)
-std=gnu99 (or -c99)

A simple test found at:

https://gforge.inria.fr/tracker/?func=detail&group_id=131&atid=607&aid=14070

can detect and demonstrate the problem.

Let main.c contain the two lines:

#include <stdlib.h>
int main() {return 0;}

and let stdlib.c contain the single line:

#include <stdlib.h>

Attempting to compile (with, in my case, gcc 4.6.3) with

gcc -O2 -D_FORTIFY_SOURCE=2 -std=c99 main.c stdlib.c -o foo

yields:

/tmp/ccnGK3nv.o: In function `realpath':
stdlib.c:(.text+0x0): multiple definition of `realpath'
/tmp/cc84CSqV.o:main.c:(.text+0x0): first defined here
.
.
.

Also, as mentioned at:

http://stackoverflow.com/questions/15285776/multiple-definitions-when-linking-collect2-error-ld-returned-1-exit-status

Adding 

-fgnu89-inline

to the C/CPP flags also seems to fix the problem.

-----

With regard to libsodium under gcc 4.6.3 and glibc 2.5, configuration
appears to go normally:

./configure --prefix=/usr

but during the build attempt

make

the linker errors out with:

  CCLD     libsodium.la
crypto_auth/hmacsha256/.libs/libsodium_la-auth_hmacsha256_api.o: In function `realpath':
/usr/include/bits/stdlib.h:33: multiple definition of `realpath'
crypto_auth/.libs/libsodium_la-crypto_auth.o:/usr/include/bits/stdlib.h:33: first defined here
crypto_auth/hmacsha256/.libs/libsodium_la-auth_hmacsha256_api.o: In function `ptsname_r':
/usr/include/bits/stdlib.h:49: multiple definition of `ptsname_r'
crypto_auth/.libs/libsodium_la-crypto_auth.o:/usr/include/bits/stdlib.h:49: first defined here
.
.
.

One quick workaround is simply to remove the -D_FORTIFY_SOURCE=2 from the
C/CPP flags. This can be accomplished by issuing a sed command to delete
all instances of -D_FORTIFY_SOURCE=2 from all the Makefiles.

After running ./configure, run:

find . -type f -name Makefile -exec sed -i 's:-D_FORTIFY_SOURCE=2::g' {} \;

<OR>
alternatively, and perhaps a better approach, *add* the -fgnu89-inline flag
whenever -D_FORTIFY_SOURCE=2 is used:

find . -type f -name Makefile -exec sed -i 's:-D_FORTIFY_SOURCE=2:-D_FORTIFY_SOURCE=2 -fgnu89-inline:g' {} \;

and then

make

works correctly. The libsodium configure script should check for this
glibc/gcc problem and adjust the C/CPP flags accordingly.

Likewise, dnscrypt-proxy-1.4.1 is also affected by this problem.

  Cheers and thank you for creating libsodium,

  Mike Shell
  http://www.michaelshell.org

**Comment by jedisct1** [comment]
25e467bd might work around this.

But it is an usual setup, that will becomes less and less relevant as people upgrade their system, so if the above change doesn't work around it, doing something more complicated (and possibly breaking more common systems) is probably a bad idea.

As you mentioned, configuring with env CFLAGS='-fgnu89-inline' ./configure ... works around this bug, so maybe we should just document this or refer to this ticket.
