### ISSUE TITLE
Guidance on large messages

### ISSUE THREAD

**Issue by jamessantiago** [jedisct1/libsodium#208]
For asymmetric methods such as crypto_sign and crypto_box, as well as symmetric methods crypto_secretbox and crypto_auth, are there guidelines for using large messages?  

I created a ICryptoTransform class to perform encryption on a block by block basis of 4096 sized blocks using libsodium-net:
https://github.com/jamessantiago/PoSH-Sodium/blob/master/PoSH-Sodium/SodiumCryptoTransform.cs

Is that blocksize ok?  Can a similar method (i.e. block by block signing) be used to produce a signature?

**Comment by jedisct1** [comment]
Old ticket, but here is an implementation: https://github.com/jedisct1/blobcrypt
