### ISSUE TITLE
Streaming mode for stream ciphers?

### ISSUE THREAD

**Issue by quantum1423** [jedisct1/libsodium#220]
It would be nice if there was a way to encrypt an endless stream with a single stream cipher key/nonce combination. SSL, for example, uses this kind of model when working with stream ciphers.

In my use case, I don't want authentication. I wish to use Salsa20/8 as a TCP stream obfuscator, and this requires that my protocol does not have message boundaries that might be signatures of the protocol. I just want to use a single key/nonce combination and stream things through it.

If this isn't possible, is there a trick to simulate this? The Salsa20/8 doesn't seem to have an _ic variant, which is probably needed if message boundaries don't exist?

**Comment by jedisct1** [comment]
Hi,

The salsa20/20 implementation provides the `_ic` variant.

Reduced-round versions of salsa20 are available to ensure full binary compatibility with NaCl. But exposing alternatives to the default parameters that have a lower security margin doesn't seem like the best route to take.

On modern hardware, salsa20/20 is usually fast enough to encrypt every single packet and saturate the network. The NEON (ARM) optimized implementations of Salsa20 and Poly1305 will be added to Sodium soon. 

To make a long story short, I'd suggest you use salsa20/20. Which provides the `_ic` variant, and which is the only version that is likely to get other additions.
