### ISSUE TITLE
sodium_malloc can't be used for many (most?) sodium data structures

### ISSUE THREAD

**Issue by stouset** [jedisct1/libsodium#221]
By the docs, the memory returned by `sodium_malloc` isn't guaranteed to be aligned, which makes it unsuitable for use by structs whose members aren't all the same size. This rules out the use of using `sodium_malloc` for many of the structs used by sodium. For instance, [`crypto_hash_sha512_state`](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/crypto_hash_sha512.h#L24) (and by extension [`crypto_auth_hmacsha512_state`](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/crypto_auth_hmacsha512.h#L15)).

What steps would need to be taken in order to lift this requirement? As someone building on top of libsodium, it would be incredibly useful to me to be able to allocate all memory for crypto operations with `sodium_malloc`. I realize that one victim of this would likely be immediate SEGVs on overflow, since it would necessitate moving the end of the user-accessible region away from being adjacent to the guard page. Perhaps there could be another function, `sodium_memalign` (and ideally a corresponding, `sodium memalignarray`)?

In the meantime, is there a workaround I can do to ensure that the memory is properly aligned? I'm not incredibly well-versed in the specifics of memory alignment, so advice would be helpful. I've been under the impression that the C spec requires (non-packed) structs to be padded to the next alignment multiple, so arrays of structs would be properly aligned; this would seem to ensure that memory allocated for structs (even through `sodium_malloc`) would be properly aligned, but libsodium documentation states that this is not the case so clearly something in my understanding is off.

**Comment by stouset** [comment]
Thanks for your response! It might be useful to include a clearer explanation, like the one you just gave, in the docs.

**Comment by jedisct1** [comment]
Done in:
- 8ba7fbd06214906bc471a4270acab91902eaf363
- https://github.com/jedisct1/libsodium-doc/commit/6458d0a331997575d5b27484da89a7ea9cbe28e5
- https://github.com/jedisct1/libsodium-doc/commit/84d9c24bef9f574fbc4394d8d7d566de349addd8

Thanks!
