### ISSUE TITLE
Missing autogen.sh in build SOP

### ISSUE THREAD

**Issue by tjyang** [jedisct1/libsodium#229]
Reference: http://doc.libsodium.org/installation/README.html

```
$ ./autogen.sh && ./configure
$ make && make check
# make install
```

**Comment by jedisct1** [comment]
`autogen.sh` is only needed if you clone the development repository.

Unless you are willing to contribute code or test potentially unstable/broken/dangerous/insecure features, you should use a release tarball as documented on this page.

And releases don't require running `autogen.sh`. Neither do they require dependencies such as libtool, autoconf and automake.
