### ISSUE TITLE
Feature request: crypto_seal() and crypto_seal_open()

### ISSUE THREAD

**Issue by sarciszewski** [jedisct1/libsodium#231]
Given Alice's public key, this should allow Bob to encrypt a message only Alice can read.

**Comment by sarciszewski** [comment]
Kind of stuck on how to properly append the public key to this structure then read it during the inverse operation. Hopefully this example is illustrative enough though.

```c
int
sodium_seal(unsigned char *c, const unsigned char *m,
           unsigned long long mlen, const unsigned char *pk)
{
    unsigned char* sender_sk = sodium_malloc(crypto_box_SECRETKEYBYTES);
    unsigned char* sender_pk = sodium_malloc(crypto_box_PUBLICKEYBYTES);
    unsigned char* n = sodium_malloc(crypto_box_NONCEBYTES);
    
    crypto_box_keypair(sender_pk, sender_sk);
    randombytes_buf(n, crypto_box_NONCEBYTES);
    
    return crypto_box(c, m, mlen, n, pk, sender_sk);
}
```

**Comment by adamcaudill** [comment]
This property of `crypto_box` is something that I've had to work around myself for a couple projects, it's also being worked around in [reop](https://github.com/tedu/reop), and as @sarciszewski, we are working around it in [EncryptingCamera](https://github.com/EncryptingCamera/encryptingcamera-spec).

I'm guessing there are many other people doing what I've done (create a temporary keypair, include the public key with the encrypted data, then toss the private key) - or they don't realize that `crypto_box` works this way, and should be doing it.

While I'm not sure what the right way to do this is, without adding confusion, it would be nice if libsodium provided a standard way of doing this (and by keeping it within libsodium, less concern about the private key somehow hanging around in memory when used from a garbage collected language).

**Comment by sarciszewski** [comment]
However it is implemented, I do believe the verb "seal" is appropriate. It's neatly analogous to a feature that openssl already exposes.

http://php.net/openssl_seal
http://php.net/openssl_open

**Comment by jedisct1** [comment]
`seal` is already being used as a method name by some bindings as the reciprocal of `open`, for `box` and `secretbox`, but it's probably okay to use it as an operation name.

So how will the recipient verify the authenticity of the message? Or is the intent of this operation to send unauthenticated messages?

What to do with the nonce since you apparently don't want to include it? Use a static nonce? Or at least `h(k || ephemeral_pk || recipient_pk)`?

**Comment by sarciszewski** [comment]
That's correct, sender authentication is not in scope here. Though, ciphertexts probably should be authenticated. The idea is that only the recipient can decrypt the message.

I was, in my example, aiming to abstract the nonce and sender sk from the API. Does generating a 32-byte one-time curve25519 key and a 32-byte nonce seem like overkill? If not, we should probably include that in the output too.

**Comment by adamcaudill** [comment]
I think there are two scenarios that apply here:

1). Unauthenticated dead-drop - Bob wants to be able to receive messages that only he can open, but doesn't care who they are from. Could be from Alice, or Malory - all that Bob cares about is that once a message is encrypted, nobody has the ability to view the message but him.

2). Signed, write-only messages - The case would be that Alice encrypts a message with an ephemeral private key and Bob's public key, then uses Ed25519 to sign the encrypted message with her private key. This way Bob knows it's from Alice, but once encrypted, Alice will be unable to access the message again.

In either case, this is a protection against someone getting Alice's private key and decrypting what she has sent - thus impacting her and Bob both.

**Comment by AGWA** [comment]
Since the sender key is ephemeral, it's safe to use a static nonce since the `{sender, receiver}` pair will never be used again.

One way to authenticate the sender is to put the ephemeral public key in a box from the sender's long-term secret key to the recipient's public key.  This is what reop does.  Signing the whole message with Ed25519 also works, but is nonrepudiable.

Noise boxes use a somewhat complicated scheme that hides the identity of the sender: https://github.com/trevp/noise/wiki/Overview

One observation: a "seal" API seems higher level than the functions that Sodium currently provides.  It would be closer to a protocol than to a primitive.  It would make Sodium more useful to a typical application developer, who probably wants something that takes care of nonces and has sender forward secrecy.  On the other hand, Sodium would need to make careful choices with the protocol design (e.g. nonrepudiability, whether/how to provide sender identity hiding, etc.), and there is likely to be confusion from having both a "seal" and a "box" API, especially if the seal API has multiple options.

**Comment by sarciszewski** [comment]
> there is likely to be confusion from having both a "seal" and a "box" API, especially if the seal API has multiple options

I don't believe we should have multiple options. This is the ideal usage (in PHP because of personal preferences):

```php
$ciphertext = Sodium::crypto_seal($credit_card_details, $recipient_publickey);
$db->insert('stored_payment_info', [
    'cc' => $ciphertext,
    'purchaser' => $_SESSION['userid'] 
]);
```

And then later, the ciphertext can be loaded onto an airgapped laptop and decrypted by the private key. This is better, IMO, than storing it with just symmetric crypto where the key is available to an attacker who gets root on the webserver.

**Comment by tarcieri** [comment]
I don't object to the way `seal` and `unseal` are being used here. This sort of usage has longstanding precedent as sealers/unsealers from capability systems:

http://wiki.erights.org/wiki/Walnut/Secure_Distributed_Computing/Capability_Patterns#Sealers_and_Unsealers

I think the only supported use should be D-H with an ephemeral sender key though.

It sounds like there's interest in colluding / slippery sloping this into some sort of forward-secret box, which isn't necessarily a bad idea in and of itself, but one I'd agree fits better into a protocol construct like Noise, and not in libsodium itself.

Being able to encrypt messages to a Curve25519 public key without having to make a corresponding private key for yourself sounds like a useful feature, however.

**Comment by sarciszewski** [comment]
> I think the only supported use should be D-H with an ephemeral sender key though.

Right, I would definitely agree with this. :)

**Comment by malthe** [comment]
Or simply ``crypto_encrypt`` and ``crypto_decrypt`` – is "seal" really helping here?

**Comment by sarciszewski** [comment]
Yes it is, because `encrypt` and `decrypt` traditionally refers to "encrypt with a symmetric key or passphrase" in openssl, etc.

**Comment by jedisct1** [comment]
`encrypt` and `decrypt` are way too generic, and are already used by `crypto_aead_chacha20poly1305_encrypt` and `crypto_aead_chacha20poly1305_decrypt`.

**Comment by jedisct1** [comment]
Back to this old issue.

Here's a proposal for it: https://github.com/jedisct1/libsodium/compare/seal

Introducing it as a new operation would be confusing. It's wrapping `crypto_box`, so let it be part of the `crypto_box` API. This makes it clear that the recipient can use key pairs generated with `crypto_box_keypair()` or `crypto_box_seed_keypair()`.

The IV is `H(ephemeral pk || recipient pk)`. If `DH(a, b)=DH(c, d)` with `a!=c | b!=d`, at least the IV is unlikely to be the same. A static IV would be fine given the key space, but deriving one from the PKs is free from a protocol perspective.

@sarciszewski The memory management functions being obvious exceptions, none of the functions in the library is doing dynamic memory allocations. As a result, given correct parameters, they can never fail.
`crypto_box_seal()` should not break this rule. So, using `sodium_malloc()` here is not an option.

**Comment by sarciszewski** [comment]
That makes sense to me. I also agree with `crypto_box_seal()` and `crypto_box_seal_open()` for the naming choices.

**Comment by sarciszewski** [comment]
Closed by https://github.com/jedisct1/libsodium/commit/575ce930585a0573b1d2fcde23bb168d87a60407 :)
