### ISSUE TITLE
AES 256 GCM

### ISSUE THREAD

**Issue by adamcaudill** [jedisct1/libsodium#234]
It seems at one point DJB planned on adding an `crypto_secretbox_aes256gcm` to NaCl (see [here](http://nacl.cr.yp.to/secretbox.html), bottom of the page), but alas, it's still listed as a TODO. I've not seen an implementation of it from DJB, but I could have missed it. (There was a brief mention of this a couple years ago in another ticket: https://github.com/jedisct1/libsodium/issues/25#issuecomment-15507977)

What are the thoughts on adding an implementation of it (assuming that a clean implementation can be found that's compatible with the license)?

(For my immediate needs, I have another implementation I can use, but having it here adds value, I think)

**Comment by tarcieri** [comment]
GCM is hard to implement in constant time. Specifically, on x86 it relies on having the (Westmere+) CLMUL set of instructions available (specifically PCLMULQDQ)

Personally I think I'd be more interested in libsodium incorporating a CAESAR winner than adding AES-GCM support :wink:

**Comment by jedisct1** [comment]
The plan is to definitely to add the CAESAR winner as default `crypto_aead` construction.

Adam, what is the main reason you need AES-GCM for? Having to use NIST-approved ciphers? Interoperability with other libraries? Speed?

**Comment by sarciszewski** [comment]
Aside: I wasn't aware that AES-256-GCM was even a thing. Every GCM implementation I've seen or read about was only defined for AES-128, and I thought GCM was only implemented for 128-bit fields.

**Comment by quantum1423** [comment]
GCM is implemented for ciphers with 128-bit *block sizes*.

**Comment by adamcaudill** [comment]
@jedisct1 NIST. In a number of corporate environments getting approval for anything that's not NIST approved is a major challenge. So, need AES, need 256 bit keys, and GCM seems to be the best option among what's being commonly implemented. (The 256 bit requirement is based on security requirements from a few financial institutions, I suspect many only think NIST == Good; Bigger == Better. Unfortunately they are the clients, so I have no input on their standards). 

Just to make it clear, I'm certainly not advocating for this to be a default or anything, just a very good "nice to have" for people working in certain, more conservative environments.

**Comment by sarciszewski** [comment]
Between January 15 and now, I had the unfortunate experience of trying to implement AES-GCM from PHP-land using the openssl extension. I now have a red spot on my forehead from the wall, but no working implementation.

So, count this as a :+1: from me for AES-256-GCM. Even though we already have ChaCha20+Poly1305.

**Comment by quantum1423** [comment]
I just came across this: 

http://www.chesworkshop.org/ches2009/presentations/01_Session_1/CHES2009_ekasper.pdf

Seems like AES GCM *can* be somewhat efficiently done in constant time.

**Comment by paragonie-scott** [comment]
I'm probably not good enough at C to be trusted to write this. Would anyone else like to take a crack at adding this support?

Specifically:

    * `crypto_aead_aes256gcm_encrypt()`
    * `crypto_aead_aes256gcm_decrypt()`

Support for AES256GCM was already going to be added to [NaCl eventually](http://nacl.cr.yp.to/secretbox.html).

**Comment by tarcieri** [comment]
Well, there's this:

https://boringssl.googlesource.com/boringssl/+/master/crypto/aes/aes.c
https://boringssl.googlesource.com/boringssl/+/master/crypto/aes/asm/

https://boringssl.googlesource.com/boringssl/+/master/crypto/modes/gcm.c
https://boringssl.googlesource.com/boringssl/+/master/crypto/modes/asm/

**Comment by jedisct1** [comment]
The Visual Studio solutions haven't been updated yet, but support for AES256-GCM has been added.

It requires a CPU with AESNI & PCLMUL, and while other implementations leveraging hardware crypto extensions (especially on ARM8+) may be added later, I'd rather avoid pure software implementations.
