### ISSUE TITLE
Feature request: Ed25519 scalar multiplication API

### ISSUE THREAD

**Issue by tarcieri** [jedisct1/libsodium#236]
libsodium contains multiple implementations of Ed25519 scalar multiplication, however the public APIs are all for EdDSA.

It would be nice if libsodium exposed an Ed25519 scalar multiplication API like the existing Curve25519 scalar multiplication API.

My intended use case for this is a different EdDSA key generation algorithm based on semiprivate keys:

https://gist.github.com/tarcieri/4760215

See also #77

**Comment by the-g-man** [comment]
As another potential use case for this, I'd like to be able to implement a 1-of-n signature with Ed25519.

**Comment by tarcieri** [comment]
It looks like this is part of TweetNaCl. The function is (confusingly) called `scalarmult` (as opposed to `crypto_scalarmult`, which is for Curve25519):

http://tweetnacl.cr.yp.to/tweetnacl-20140917.pdf

**Comment by paragonie-scott** [comment]
Would this also allow `crypto_sign_publickey_from_secretkey` to be exposed in the bindings for other languages?

**Comment by ilwaz** [comment]
I'd also like to see this implemented, to allow single-party asymmetric encryption (aka one public/private key pair, no key exchange between two key pairs).

**Comment by tarcieri** [comment]
@jedisct1 any advice how to proceed if I were to take a stab at implementing this? Should the current ed25519 ref10 scalar multiplication code in `src/libsodium/crypto_sign/ed25519` be relocated to e.g. `src/libsodium/crypto_scalarmult/ed25519`?

**Comment by jedisct1** [comment]
I'm not sure that relocating the current ed25519 ref10 scalar multiplication code is the way to go (don't assume that the ref10 implementation will be available/used), but yes, the end result should be in `crypto_scalarmult/ed25519`, exposed as `crypto_scalarmult_ed25519()`.

**Comment by cfcs** [comment]
This would also make it easy to implement more compact signatures (n private keys signing the same value, at the same time).

**Comment by tarcieri** [comment]
@cfcs yes, this could be used for threshold Schnorr, but a first-class API to that would probably be better

**Comment by sdgathman** [comment]
My use case is porting https://github.com/cjdelisle/cjdns to libsodium.  I was successful doing so through cjdns-19, but v20 uses ed25519 message signing with custom key conversion from curve25519.

**Comment by jedisct1** [comment]
Hi Stuart,

Unfortunately, a new API is not going to be added just for one very specific use case, sorry.
