### ISSUE TITLE
crypto_auth_verify contains undefined behavior

### ISSUE THREAD

**Issue by alex** [jedisct1/libsodium#237]
Specifically the code here: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_auth/hmacsha256/cp/verify_hmacsha256.c#L9-L10

`(-(h - correct == 0))`: `h` is a parameter, and `correct` is a stack allocated array, these can never point to the same memory. Subtracting pointers to arrays which do not point at memory allocated to the same array (or the edges thereof) is undefined behavior.

Further, it seems like this comparison is pointless. `h - correct` is always non-zero, since they point to different memory. `h - correct == 0` is therefore `false` (`0`), and `-0` goes to `0`, ultimately resulting in no change as the `0` is OR'd with the other values.

**Comment by alex** [comment]
I should note that this same pattern is repeated in a number of other locations.

**Comment by jedisct1** [comment]
This is to provide limited, but still better than nonexistent protection against fault injection.

Per C standard, the pointers subtraction is indeed undefined. But is there any modern environment (DJGPP on DOS doesn't count) where this can actually lead to an undefined behavior? Not sure that there is any, and that is likely to be detected when testing functions related to guarded memory no matter what.

And with LTO, a compiler is free to remove the pointer comparison check and to only keep one of the paths to check that the authenticator is correct. The only way to avoid this is not to use C. That said, none of the environments the library is being tested on seem to perform such an optimization

**Comment by jedisct1** [comment]
`(p1 - p2 == 0)` was changed to `p1 == p2`.
