### ISSUE TITLE
Is sodium_hex2bin cache-timing safe?

### ISSUE THREAD

**Issue by sarciszewski** [jedisct1/libsodium#241]
https://github.com/jedisct1/libsodium/blob/194a3c60480dde18150eff18b829b0c17c4dc19b/src/libsodium/sodium/utils.c#L123-L173

My understanding of cache-timing attacks may be flawed, but I was led to believe that two conditions lead to cache-timing vulnerabilities:

1. Indexing on secrets
2. Branching on secrets

Would there be any benefit in a branch-free hex2bin?
How could it be done without causing issues with invalid characters?

**Comment by jedisct1** [comment]
`sodium_hex2bin` is not constant-time, and it would be nice for it to be.

Table lookups or conditional branching to handle non-hex characters is acceptable; there is not much to learn from the format of the hex string.

**Comment by sarciszewski** [comment]
Would something like this work?

1. Set `variable` to `0`.
2. For each character in the hex string, increase `variable` if the character is not within [0-9a-f]
3. If the result is not equal to 0, abort because of invalid chars.
4. Apply the decoding without conditional lookups.

**Comment by jedisct1** [comment]
The input doesn't have to be `^[0-9a-fA-F]+$`. Some characters can be ignored; that's the purpose of the `ignore` parameter.
Having non-hex characters after the required length has been reached for the output is also fine.
`0a:e8:56:31:a0:4b // MAC address` should remain a valid input.

**Comment by jedisct1** [comment]
Done in f8af1790dd3777792be2c2a0419b9690f46dc246

**Comment by sarciszewski** [comment]
Wow :+1: I was at a complete loss for how to proceed with this.
