### ISSUE TITLE
Invalid arch armv7

### ISSUE THREAD

**Issue by mosin** [jedisct1/libsodium#242]
Running 
$ sh dist-build/android-armv7.sh
  Invalid --arch armv7
  Please use one of arm, x86, mips, arm64, x86_64 or mips64

Not sure why there is an armv7 script if it is not supported.

**Comment by jedisct1** [comment]
Hi,

armv7 is definitely supported, both by the NDK and by libsodium.

Oddly, I couldn't find the `Please use one of ` string anywhere in libsodium or in the current NDK.

Make sure that you are not using a very old version of the NDK and check that you are also using an up to date version of sodium.

**Comment by sbredahl** [comment]
I have this issue too using latest NDK (r10d) and libsodium 1.0.2

Setting TARGET_ARCH=arm in the android_armv7.sh build script solved the issue. (Probably this is caused by the move to GCC 4.8 in NDK r10d.)

**Comment by jedisct1** [comment]
This issue should be fixed in the current code in Git. So 1.0.3 should be fine :)
