### ISSUE TITLE
doesnt build under standard OS X Yosemite

### ISSUE THREAD

**Issue by andreasfink** [jedisct1/libsodium#245]
if you try to build under standard OS X Yosemite with developer tools installed you won't get anywhere.
Here's what I do:

[afink@flunderfinkorg.local git]$ https://github.com/jedisct1/libsodium.git
[afink@flunderfinkorg.local git]$ git clone https://github.com/jedisct1/libsodium.git
Cloning into 'libsodium'...
remote: Counting objects: 11060, done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 11060 (delta 31), reused 0 (delta 0)
Receiving objects: 100% (11060/11060), 3.23 MiB | 1.51 MiB/s, done.
Resolving deltas: 100% (5716/5716), done.
Checking connectivity... done.
[afink@flunderfinkorg.local git]$ cd libsodium
[afink@flunderfinkorg.local libsodium]$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/local/bin/autoconf --force
configure.ac:434: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/local/bin/autoconf failed with exit status: 1
[afink@flunderfinkorg.local libsodium]$ autoconf
[afink@flunderfinkorg.local libsodium]$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in build-aux "."/build-aux
[afink@flunderfinkorg.local libsodium]$ 

creating empty install.sh and copying config.guess and config.sub from another project into build-aux fixes the issue but the library should work out of the box including a prebuilt ./configure.

**Comment by jedisct1** [comment]
Hi,

What version of autoconf, libtool and automake do you have? They might be really outdated.

It should work out of the box with the current versions installed using Homebrew.

That said, unless you are willing to contribute code, you want to download releases instead of checking out the unstable development repository.

Releases include all the pregenerated files, and do not require autoconf or any other external dependency.

Releases can be downloaded here http://download.libsodium.org/libsodium/releases/

**Comment by andreasfink** [comment]
works after installing by hand the following packages and their dependencies. I was using the versions provided by Apple in Xcode 6.1.1 before.

autoconf-2.69
autogen-5.18
automake-1.15
