### ISSUE TITLE
Doesn't build with M/T runtime library option on vs2013

### ISSUE THREAD

**Issue by arzhna** [jedisct1/libsodium#246]
I tried to build with "M/T" runtime library option on vs2013, and I got follow build error.
But if I use "M/D" runtime library option, it's ok.
Please, check about using "M/T" runtime option on vs2013.

1>------ Build started: Project: libsodium, Configuration: ReleaseDLL Win32 ------
1>  ConfigurationType : DynamicLibrary
1>  Configuration     : ReleaseDLL
1>  PlatformToolset   : v120
1>  TargetPath        : D:\Download\libsodium\builds\msvc\vs2013\libsodium\..\..\..\..\bin\Win32\Release\v120\dynamic\libsodium.dll
1>  Will copy D:\Download\libsodium\builds\msvc\vs2013\libsodium\..\..\version.h -> D:\Download\libsodium\builds\msvc\vs2013\libsodium\..\..\..\..\src\libsodium\include\sodium\version.h
1>  Option-amd64asm   : 
1>          1 file was copied.
1>  aead_chacha20poly1305.c
1>  pwhash_scryptsalsa208sha256_nosse.c
1>  pwhash_scryptsalsa208sha256.c
1>  pwhash_scryptsalsa208sha256_sse.c
1>  base_curve25519_donna_c64.c
1>  smult_curve25519_donna_c64.c
1>  base_curve25519_ref10.c
1>  fe_0_curve25519_ref10.c
1>  fe_1_curve25519_ref10.c
1>  fe_add_curve25519_ref10.c
1>  fe_copy_curve25519_ref10.c
1>  fe_cswap_curve25519_ref10.c
1>  fe_frombytes_curve25519_ref10.c
1>  fe_invert_curve25519_ref10.c
1>  fe_mul121666_curve25519_ref10.c
1>  fe_mul_curve25519_ref10.c
1>  fe_sq_curve25519_ref10.c
1>  fe_sub_curve25519_ref10.c
1>  fe_tobytes_curve25519_ref10.c
1>  scalarmult_curve25519_ref10.c
1>  stream_chacha20_ref.c
1>  stream_chacha20_api.c
1>  stream_salsa20_ref.c
1>  xor_salsa20_ref.c
1>  crypto_auth.c
1>  auth_hmacsha256_api.c
1>  hmac_hmacsha256.c
1>  verify_hmacsha256.c
1>  auth_hmacsha512_api.c
1>  hmac_hmacsha512.c
1>  verify_hmacsha512.c
1>  auth_hmacsha512256_api.c
1>  hmac_hmacsha512256.c
1>  verify_hmacsha512256.c
1>  crypto_box.c
1>  crypto_box_easy.c
1>  box_curve25519xsalsa20poly1305_api.c
1>  after_curve25519xsalsa20poly1305.c
1>  before_curve25519xsalsa20poly1305.c
1>  box_curve25519xsalsa20poly1305.c
1>  keypair_curve25519xsalsa20poly1305.c
1>  core_hsalsa20.c
1>  core_hsalsa20_api.c
1>  core_salsa20.c
1>  core_salsa20_api.c
1>  core_salsa2012.c
1>  core_salsa2012_api.c
1>  core_salsa208.c
1>  core_salsa208_api.c
1>  crypto_generichash.c
1>  generichash_blake2_api.c
1>  blake2b-ref.c
1>  generichash_blake2b.c
1>  crypto_hash.c
1>  hash_sha256_api.c
1>  hash_sha256.c
1>  hash_sha512_api.c
1>  hash_sha512.c
1>  crypto_onetimeauth.c
1>  onetimeauth_poly1305.c
1>  onetimeauth_poly1305_api.c
1>  onetimeauth_poly1305_try.c
1>  auth_poly1305_donna.c
1>  verify_poly1305_donna.c
1>  crypto_scrypt-common.c
1>  scrypt_platform.c
1>  pbkdf2-sha256.c
1>  crypto_scalarmult.c
1>  scalarmult_curve25519_api.c
1>  crypto_secretbox.c
1>  crypto_secretbox_easy.c
1>  secretbox_xsalsa20poly1305_api.c
1>  box_xsalsa20poly1305.c
1>  crypto_shorthash.c
1>  shorthash_siphash24_api.c
1>  shorthash_siphash24.c
1>  crypto_sign.c
1>  sign_ed25519_api.c
1>  fe_0.c
1>  fe_1.c
1>  fe_add.c
1>  fe_cmov.c
1>  fe_copy.c
1>  fe_frombytes.c
1>  fe_invert.c
1>  fe_isnegative.c
1>  fe_isnonzero.c
1>  fe_mul.c
1>  fe_neg.c
1>  fe_pow22523.c
1>  fe_sq.c
1>  fe_sq2.c
1>  fe_sub.c
1>  fe_tobytes.c
1>  ge_add.c
1>  ge_double_scalarmult.c
1>  ge_frombytes.c
1>  ge_madd.c
1>  ge_msub.c
1>  ge_p1p1_to_p2.c
1>  ge_p1p1_to_p3.c
1>  ge_p2_0.c
1>  ge_p2_dbl.c
1>  ge_p3_0.c
1>  ge_p3_dbl.c
1>  ge_p3_to_cached.c
1>  ge_p3_to_p2.c
1>  ge_p3_tobytes.c
1>  ge_precomp_0.c
1>  ge_scalarmult_base.c
1>  ge_sub.c
1>  ge_tobytes.c
1>  keypair.c
1>  open.c
1>  sc_muladd.c
1>  sc_reduce.c
1>  sign.c
1>  sign_edwards25519sha512batch_api.c
1>  fe25519_edwards25519sha512batch.c
1>  ge25519_edwards25519sha512batch.c
1>  sc25519_edwards25519sha512batch.c
1>  sign_edwards25519sha512batch.c
1>  crypto_stream.c
1>  afternm_aes128ctr.c
1>  stream_aes128ctr_api.c
1>  beforenm_aes128ctr.c
1>  common_aes128ctr.c
1>  consts_aes128ctr.c
1>  int128_aes128ctr.c
1>  stream_aes128ctr.c
1>  xor_afternm_aes128ctr.c
1>  stream_salsa20_api.c
1>  stream_salsa2012_api.c
1>  stream_salsa2012.c
1>  xor_salsa2012.c
1>  stream_salsa208_api.c
1>  stream_salsa208.c
1>  xor_salsa208.c
1>  stream_xsalsa20_api.c
1>  stream_xsalsa20.c
1>  xor_xsalsa20.c
1>  verify_16_api.c
1>  verify_16.c
1>  verify_32_api.c
1>  verify_32.c
1>  verify_64_api.c
1>  verify_64.c
1>  randombytes.c
1>  randombytes_salsa20_random.c
1>  randombytes_sysrandom.c
1>  core.c
1>  runtime.c
1>  utils.c
1>  version.c
1>     Creating library D:\Download\libsodium\builds\msvc\vs2013\libsodium\..\..\..\..\bin\Win32\Release\v120\dynamic\libsodium.lib and object D:\Download\libsodium\builds\msvc\vs2013\libsodium\..\..\..\..\bin\Win32\Release\v120\dynamic\libsodium.exp
1>utils.obj : warning LNK4049: locally defined symbol __errno imported
1>pwhash_scryptsalsa208sha256_nosse.obj : warning LNK4217: locally defined symbol __errno imported in function _escrypt_kdf_nosse
1>pwhash_scryptsalsa208sha256.obj : warning LNK4049: locally defined symbol __errno imported
1>pwhash_scryptsalsa208sha256_sse.obj : warning LNK4049: locally defined symbol __errno imported
1>scrypt_platform.obj : warning LNK4049: locally defined symbol __errno imported
1>keypair.obj : warning LNK4049: locally defined symbol _memmove imported
1>open.obj : warning LNK4217: locally defined symbol _memmove imported in function _crypto_sign_ed25519_open
1>sign.obj : warning LNK4217: locally defined symbol _memmove imported in function _crypto_sign_ed25519
1>keypair_curve25519xsalsa20poly1305.obj : warning LNK4217: locally defined symbol _memmove imported in function _crypto_box_curve25519xsalsa20poly1305_seed_keypair
1>blake2b-ref.obj : warning LNK4049: locally defined symbol _memmove imported
1>crypto_secretbox_easy.obj : warning LNK4049: locally defined symbol _memmove imported
1>sign_ed25519_api.obj : warning LNK4049: locally defined symbol _memmove imported
1>crypto_scrypt-common.obj : warning LNK4217: locally defined symbol _strrchr imported in function _escrypt_r
1>scrypt_platform.obj : warning LNK4217: locally defined symbol _free imported in function _free_region
1>scrypt_platform.obj : warning LNK4217: locally defined symbol _malloc imported in function _alloc_region
1>randombytes_salsa20_random.obj : warning LNK4217: locally defined symbol _abort imported in function _randombytes_salsa20_random_stir
1>randombytes_sysrandom.obj : warning LNK4049: locally defined symbol _abort imported
1>utils.obj : warning LNK4049: locally defined symbol _abort imported
1>utils.obj : warning LNK4217: locally defined symbol _raise imported in function __out_of_bounds
1>pwhash_scryptsalsa208sha256.obj : error LNK2019: unresolved external symbol __imp__memchr referenced in function _crypto_pwhash_scryptsalsa208sha256_str_verify
1>crypto_scrypt-common.obj : error LNK2019: unresolved external symbol __imp__strchr referenced in function _decode64_one
1>utils.obj : error LNK2001: unresolved external symbol __imp__strchr
1>randombytes_salsa20_random.obj : error LNK2019: unresolved external symbol __imp___ftime64 referenced in function _sodium_hrtime
1>D:\Download\libsodium\builds\msvc\vs2013\libsodium\..\..\..\..\bin\Win32\Release\v120\dynamic\libsodium.dll : fatal error LNK1120: 3 unresolved externals
2>------ Build started: Project: test, Configuration: ReleaseDEXE Win32 ------
2>  ConfigurationType : Application
2>  Configuration     : ReleaseDEXE
2>  PlatformToolset   : v120
2>  TargetPath        : D:\Download\libsodium\builds\msvc\vs2013\test\..\..\..\..\bin\Win32\Release\v120\dynamic\test.exe
2>  Linkage-libsodium : dynamic
2>  aead_chacha20poly1305.c
2>  test.vcxproj -> D:\Download\libsodium\builds\msvc\vs2013\test\..\..\..\..\bin\Win32\Release\v120\dynamic\test.exe
2>  Copying libsodium.dll -> D:\Download\libsodium\bin\Win32\Release\v120\dynamic\libsodium.dll
2>D:\Download\libsodium\builds\msvc\vs2013\libsodium.import.props(39,5): error MSB3030: Could not copy the file "D:\Download\libsodium\builds\msvc\vs2013\test\..\..\..\..\..\libsodium\bin\Win32\Release\v120\dynamic\libsodium.dll" because it was not found.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

**Comment by jedisct1** [comment]
Thanks for reporting this. I'll take a look shortly.
So, `memchr`, `strchr` and `_ftime64` are not available when using this library. Quite unexpected, but there must be some workaround.

**Comment by jedisct1** [comment]
Looks like you are trying to build a dynamic library (your configuration is `ReleaseDLL`), but at the same time selecting the M/T runtime which is only for static libraries.

Just select a different configuration, such as `ReleaseLIB`. The output will be a static library (`.LIB`) using the M/T runtime.
