### ISSUE TITLE
linker error when using libsodium in Visual Studio 2013

### ISSUE THREAD

**Issue by mohamedkomalo** [jedisct1/libsodium#247]
I am trying to compile the following [code](https://github.com/notsecure/utox-update/blob/master/main.c) using Visual Studio 2013.
* using the libsodium binary release **libsodium-1.0.0-msvc.zip**
* added the include folder to the "Additional Include Directories" 
* added the lib folder to the "Additional Library Directories"
* added "libsodium.lib" to the "Additional Dependencies"

the code compiles but gives a linker error

    error LNK2019: unresolved external symbol __imp_crypto_sign_ed25519_open referenced in function checksignature

I tried calling other functions to check if it is only for crypto_sign_ed25519_open but turns out that this error happens with all the functions

am I missing something that should be done ??

Thanks

**Comment by mohamedkomalo** [comment]
just tried the dll instead of statically linking and it worked, still can't find the problem of static linking

**Comment by jedisct1** [comment]
Hi Mohamed,

For static linking, try defining a macro named `SODIUM_STATIC`. This will prevent symbol definitions from being referenced with `__dllexport`.

**Comment by mohamedkomalo** [comment]
thanks it worked now, can it be added to the [installation docs](http://doc.libsodium.org/installation/README.html) , maybe after "Cross-compiling" ?

**Comment by jedisct1** [comment]
Done!

Thanks for suggesting this!
