### ISSUE TITLE
Crates Integration

### ISSUE THREAD

**Issue by dirvine** [jedisct1/libsodium#248]
Is there any move to put this library on crates.io or would there be any resistance to another project forking and doing this? Of course if this project were on crates.io it would make it much simpler to use and in fact is a requirement I think for any crate on crates.io and the like to be able to use it. 

Thanks for your time.

**Comment by jedisct1** [comment]
crates.io is for Rust code. This is C code. Did I miss something?

**Comment by dirvine** [comment]
Ah no sorry my bad, pushed comment to wrong repo :-) please close and forget this one, sorry for the time.

**Comment by jedisct1** [comment]
Haha, np :)
