### ISSUE TITLE
crypto_stream_rot13_encode() not Cache-Timing Safe

### ISSUE THREAD

**Issue by sarciszewski** [jedisct1/libsodium#249]
https://github.com/jedisct1/libsodium/blob/a3b7fd8d0015adf275347c6fd79ef8f19c29618f/src/libsodium/crypto_stream/rot13/ref/stream_rot13_ref.c#L23

Happy April Fool's Day, Frank!

**Comment by jedisct1** [comment]
Happy April fool's day :)
