### ISSUE TITLE
Minor release with Android script updates?

### ISSUE THREAD

**Issue by JackWink** [jedisct1/libsodium#251]
Just looking for an ETA for 1.0.3, thanks Frank!

**Comment by jedisct1** [comment]
Soon, probably over the weekend.

I initially wanted to wait for the ARM optimized implementations to get merged first, but a few projects are waiting for a release tag, and since there are no blockers. let's do it.

**Comment by sarciszewski** [comment]
`\o/` :+1:

**Comment by JackWink** [comment]
Sweet, looking forward to the `crypto_box_seal` API too, thanks!

**Comment by jedisct1** [comment]
I have a dilemma regarding `crypto_box_seal` (/cc @sarciszewski ) ; help to solve it is welcome :)

The Swift bindings use `sodium.box.seal()` and `sodium.box.open()` for `crypto_box()` and `crypto_box_open()`. `sodium.box` can be seen as a namespace; a function called `sodium.box()` is not an option.

Bindings for another language (don't remember which project, sorry) do exactly the same thing and also use `seal` as a method name to create a box.

So, how to expose `crypto_box_seal()` in these bindings?

**Comment by sarciszewski** [comment]
I can think of three solutions:

* Rename the existing `sodium.box.seal()` to `sodium.box.close()` - BC breaks abound.
* Create a separate `sodium.seal.*` namespace for these circumstances.
* Find a synonym for seal to use in these contexts.

Not sure which one you would prefer.
