### ISSUE TITLE
How to use the command line to compile msvc?

### ISSUE THREAD

**Issue by KangLin** [jedisct1/libsodium#253]
How to use the command line to compile msvc?
suggest to use cmake manage this project.

**Comment by jedisct1** [comment]
Use `msbuild`. For example:

    msbuild /m /v:n /p:Configuration=LtcgRelease /p:Platform=x64 builds/msvc/vs2013/libsodium.sln

Or even easier, use the provided script [https://github.com/jedisct1/libsodium/blob/master/builds/msvc/build/buildbase.bat](buildbase.bat):

    buildbase.bat ..\vs2013\mysolution.sln 12

[https://github.com/jedisct1/libsodium/blob/master/builds/msvc/build/buildall.bat](buildall.bat) is the script that builds all the binaries for each release.

**Comment by jedisct1** [comment]
Please note that the current code in git is development code that has not been tested on Windows yet. It may not compile. It may not work. It may be totally insecure. It may wipe your hard disk.
Unless you want to contribute to the project, you should use a release instead. Which includes precompiled binaries for MSVC.
