### ISSUE TITLE
Thread local random number generator

### ISSUE THREAD

**Issue by netheril96** [jedisct1/libsodium#255]
By reading the documentation I have the impression that the rng in libsodium is shared by all threads. This may become a bottleneck when many random numbers are generated in all different threads. A better solution is to offer an option to make the rng thread-local so that no synchronization is needed for multi-threaded usage.

**Comment by sarciszewski** [comment]
I'm not an expert on threaded application development, so please pardon my ignorance.

> This may become a bottleneck when many random numbers are generated in all different threads.

So if I understand clearly, the problem looks like this:

```
                   randombytes_*
                  / / / / \ \ \ \
                 / / / |   | \ \ \
                / / |  |   |  | \ \ 
               / |  |  |   |  |  | \ 
              |  |  |  |   |  |  |  |
              t0 t1 t2 t3 t4 t5 t6 t7
```

You are saying this could become a performance bottleneck. 

My understanding of `randombytes*` is that, on systems without `getrandom` or similar syscalls available, it maintains exactly one file descriptor for `/dev/urandom` to prevent file descriptor exhaustion therefore weak entropy attacks.

I could be wrong on this, but I'm suspecting that the reason these aren't thread-local is to reduce the number of file descriptors in use by libsodium to a minimum.

**Comment by netheril96** [comment]
@sarciszewski 

I thought rng in libsodium was an userspace one. If it direct reads from `/dev/urandom`, then there is no need to be thread-local anymore. `/dev/urandom` is internally serialized in the kernel anyway.

**Comment by jedisct1** [comment]
That is correct. It uses `getrandom()` if available, or `/dev/urandom` if it's not. And yes, this is being serialized in the kernel no matter what.
