### ISSUE TITLE
Assembly version of ChaCha20

### ISSUE THREAD

**Issue by quantum1423** [jedisct1/libsodium#257]
It would be really nice if an assembly version of ChaCha20, for both i386 and amd64, could be integrated. Salsa20 seems to already have an amd64 version, so it wouldn't be too hard?

**Comment by tarcieri** [comment]
Perhaps integrate @floodyberry's https://github.com/floodyberry/chacha-opt ?

**Comment by quantum1423** [comment]
Yeah, it looks pretty good. Not sure whether it's fully constant-time though.

**Comment by jedisct1** [comment]
Ted Krovetz implementations are going to be merged. This will wait version 1.0.8, though.
