### ISSUE TITLE
Elligator transformation support

### ISSUE THREAD

**Issue by Scratch-net** [jedisct1/libsodium#261]
As you know, [Elligator](http://elligator.cr.yp.to) is a way to encode public keys in a way they are undistinguished from a random data. The price is that just 1 out of 2 keys are suitable for the transformation.

Will tox core (libsodium) support Elligator? I don't think that generating some extra Curve25519 keys is an issue.

Implementations now include [C](https://github.com/Yawning/libelligator), [Go](https://github.com/DeDiS/crypto/blob/master/edwards/ed25519/elligator.go) and [C# (my porting)](https://github.com/scratch-net/Chaos.NaCl)

**Comment by Yawning** [comment]
All of those implementations are/appear to be based off agl's Go version of the primitive.  I know the first one is.  They're all incorrect because the original code is wrong.  I should fix libelligator, but I haven't gotten around to it yet.

**Comment by Scratch-net** [comment]
@Yawning So, what's the issue is about?

**Comment by Yawning** [comment]
https://github.com/Yawning/libelligator/commit/eeefe989f9ced861cb6239eca0632b511aa498cb

There, I fixed libelligator.  There's a comment explaining the added code (referencing the paper), and new test vectors.

**Comment by Scratch-net** [comment]
@Yawning Thanks, nice! Will port to c# ASAP

**Comment by cfcs** [comment]
@Yawning it would be great to be able to package this with libsodium without having to add dependencies on a C++ compiler. Any chance you would be up for porting your code to C?

**Comment by jedisct1** [comment]
This might still be better kept as a separate library, along with an EKE or SPAKE2 implementation.

Elligator is nice, but the use cases are still very limited. It's probably a good idea to avoid the systemd syndrome; focus on what is actually required by many common applications, and let more specialized constructions be available as independent libraries.

**Comment by Yawning** [comment]
@cfcs I did a while ago on top of ed25519-donna.  I probably won't do C ref10, but it's straight forward and mechanical to do so.

https://gist.github.com/Yawning/0181098c1119f49b3eb2 

@jedisct1 re: packaging, I have no strong opinions on the matter, was just browsing bugs and saw people referencing something I wrote.
