### ISSUE TITLE
sodium_bin2hex() hex_maxlen checking bug

### ISSUE THREAD

**Issue by jpetso** [jedisct1/libsodium#262]
```
    if (bin_len >= SIZE_MAX / 2 || hex_maxlen < bin_len * 2U) {
        abort(); /* LCOV_EXCL_LINE */
    }
```
vs.
```
    hex[i * 2U] = 0U;
```
and here's the relevant excerpt from the documention:

> hex_maxlen is the maximum number of bytes that the function is allowed to write starting at hex. It should be at least bin_len * 2 + 1.

Stumbled upon this by using a destination char array with non-null-terminated strings at a size of `(bin_len * 2)`. Discovered by valgrind. valgrind is teh awesome.

**Comment by jedisct1** [comment]
Good catch.
Fixed, thanks!
