### ISSUE TITLE
Checks from PVS studio resulted in 4 level 1 and 2 warnings

### ISSUE THREAD

**Issue by scratch-net** [jedisct1/libsodium#263]
I've run [PVS](http://www.viva64.com/en/pvs-studio/) on libsodium (master) and got these level 1 and 2 warnings

V512 A call of the 'memcpy' function will lead to underflow of the buffer 'out0'. hmac_hmacsha512256.c 38
V512 A call of the 'memmove' function will lead to underflow of the buffer 'hash'. keypair_curve25519xsalsa20poly1305.c 16
V512 A call of the 'memset' function will lead to underflow of the buffer 'block0'. crypto_secretbox_easy.c 39
V512 A call of the 'memcpy' function will lead to underflow of the buffer 'h'. keypair.c 74

there are 54 level 3 warnings, I can also copy them here if you're interested. Or provide a license to PVS so that you could check it by yourself

**Comment by jedisct1** [comment]
All of these are intentional.

But a license for PVS would indeed be awesome!

**Comment by scratch-net** [comment]
@jedisct1 I think i saw one of them [here](http://pastebin.com/EBAQxd8E)

have a nice day )
