### ISSUE TITLE
Fork safety of random numbers

### ISSUE THREAD

**Issue by daurnimator** [jedisct1/libsodium#266]
See http://daurnimator.com/post/120415954844/linux-fork-detection-using-thread-specific

libsodium has the pid check mentioned at https://github.com/jedisct1/libsodium/blob/master/src/libsodium/randombytes/salsa20/randombytes_salsa20_random.c#L284

**Comment by jedisct1** [comment]
This is an example, which is not used by default. `sodium_stir()` is provided to rekey it after `fork()`ing.
The default RNG directly reads `/dev/urandom`.

**Comment by daurnimator** [comment]
> This is an example, which is not used by default.


Is that to say that the salsa20 random number generator is an example, and the 'sysrandom' random number generator is the default?

> sodium_stir() is provided to rekey it after fork()ing

What is the `stir_if_needed` function for then?

**Comment by jedisct1** [comment]
Yes, see the documentation: http://doc.libsodium.org/advanced/custom_rng.html

The purpose of `stir_if_needed()`, including in the default implementation, is to be able to generate numbers before/without calling `sodium_init()`.
