### ISSUE TITLE
Add bcrypt_pbkdf(3)

### ISSUE THREAD

**Issue by neuegram** [jedisct1/libsodium#267]
Given that reop is so strongly dependent upon libsodium already, for the sake of supporting ports it would make sense to possibly add bcrypt_pbkdf(3). Just a thought.

**Comment by jedisct1** [comment]
New algorithms are added if they solve a common problem that the current algorithms don't.

We have scrypt, we will have the PHC (which is almost over) winning scheme, there is absolutely no need for bcrypt.
