### ISSUE TITLE
Tag for 1.0.3

### ISSUE THREAD

**Issue by vstakhov** [jedisct1/libsodium#270]
As far as I see, there is a tarball available and I see `1.0.3` in GH tags. However, I don't see it in the main list of GH tags nor in the list of releases. It seems like this tag was done over some non-master branch. Could you please clarify that, as I'm going to apply update for FreeBSD ports and I'd like to ensure that I'm doing that for the correct tag?

**Comment by jedisct1** [comment]
Mmmm. There is a regular `1.0.3` tag. On the master branch https://github.com/jedisct1/libsodium/tree/1.0.3

I just tried over a fresh clone and it seems to work as expected:
```
$ git clone https://github.com/jedisct1/libsodium.git
Cloning into 'libsodium'...
remote: Counting objects: 11833, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 11833 (delta 8), reused 0 (delta 0), pack-reused 11800
Receiving objects: 100% (11833/11833), 3.40 MiB | 568.00 KiB/s, done.
Resolving deltas: 100% (6189/6189), done.
Checking connectivity... done.

$ git checkout 1.0.3 
Note: checking out '1.0.3'.

HEAD is now at 63dd054... crypto_box_keypair() cannot fail - Add lcov exclusion.
```

**Comment by vstakhov** [comment]
I see, thank you for clarifications!

**Comment by lancethepants** [comment]
There is some sort of weird behavior on github though.  I can see 1.0.3 tag in the repo when I clone it, but when navigating to the 'releases' area in github, it shows 1.0.2 as the last, but not designated as 'latest'. You can navigate to this url to see it though. Seems to be an issue with github?
https://github.com/jedisct1/libsodium/releases/tag/1.0.3

**Comment by jedisct1** [comment]
I forced the same tag, on the same commit id, and it seems to have refreshed github's cache.
