### ISSUE TITLE
Windows 10 (universal app support)

### ISSUE THREAD

**Issue by GregorSpagnolo** [jedisct1/libsodium#271]
When I call Libsodium from managed code (C#) through windows runtime component I receive exception:
An exception of type 'System.IO.FileNotFoundException' occurred in BiocodedUniversal.exe but was not handled in user code
Additional information: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
This exception is thrown only when I deploy my app in emulator or windows phone device if I run on local machine it works as expected.

**Comment by adamcaudill** [comment]
To keep the discussions connected, there is a related ticket here: https://github.com/adamcaudill/libsodium-net/issues/96

**Comment by jedisct1** [comment]
Hi Gregor,

Can you double check that it is actually related to Sodium?

On Windows, Sodium never attempts to access the filesystem, so I don't really see how it could trigger this exception.

**Comment by GregorSpagnolo** [comment]
In windows universal apps you have to build native code inside Windows Runtime Component. And then call this DLL from managed code (C#). This is the reason why I touch the disk. 
My main problem is that LibSodium Runtime Component Library builds normally and calls to library works when testing on local machine. The problem happens when you change to ARM. The Runtime Component builds normally but when code hits initialization of Runtime Component it crashes with reason no file not found exception (Runtime component DLL not found)

**Comment by Aurora12** [comment]
@GregorSpagnolo I have found out something new concerning this issue:
https://github.com/adamcaudill/libsodium-net/issues/96#issuecomment-118070949

**Comment by GregorSpagnolo** [comment]
@Aurora12 Yes indeed I narrowed down to same problem on W10 for phones... I suspect that must be something related to includes but do not know which as error tells nothing

**Comment by Aurora12** [comment]
@GregorSpagnolo Looks like it's cryptographical random function `RtlGenRandom` that is missing, that causes failure. See my last comments https://github.com/adamcaudill/libsodium-net/issues/96#issuecomment-118279389

But I'm still not sure how we are to solve the issue.

**Comment by GregorSpagnolo** [comment]
How to solve and address this issue can be found:
https://github.com/adamcaudill/libsodium-net/issues/96#issuecomment-118279389
For now, the only way to use LibSodium in Windows 10 environment is to create Windows Runtime component and expose C++ Random function to C code. 
I hope that Microsoft will address issue with random function in C.
