### ISSUE TITLE
Publish sha256 for the releases?

### ISSUE THREAD

**Issue by gabriel** [jedisct1/libsodium#272]
For the podspec (Cocoapods for iOS,OSX) we specify a sha256 for the tar.gz release. I'm generating it manually but would be nice to have it published with the release (and maybe in the ChangeLog).

**Comment by gabriel** [comment]
For example the most recent podspec is: 

https://github.com/CocoaPods/Specs/blob/master/Specs/libsodium/1.0.3/libsodium.podspec.json

using sha256: `cbcfc63cc90c05d18a20f229a62c7e7054a73731d0aa858c0517152c549b1288`

**Comment by jedisct1** [comment]
Signed SHA256 hashes for all the files available for download can be retrieved using a simple DNS query.

For example:

    $ drill -D TXT libsodium-1.0.3.tar.gz.download.libsodium.org
    ;; flags: qr rd ra ad ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0
    libsodium-1.0.3.tar.gz.download.libsodium.org.	600	IN	TXT "cbcfc63cc90c05d18a20f229a62c7e7054a73731d0aa858c0517152c549b1288"
