### ISSUE TITLE
Cross compiling for ARM

### ISSUE THREAD

**Issue by theWebalyst** [jedisct1/libsodium#274]
I'm building the maidsafe (Rust) code on an Intel Debian machine, and cross compiling for ARM (arm-unknown-linux-gnueabihf). I have the Rust code cross compiling fine, and "file" reports the output is ARM. I get all the way to linking the maidsafe code, but it fails at that point because I don't have an ARM build of libsodium.

I can build everything for the intel Debian machine.

I've tried several things but can't get libsodium to build for ARM. It happily compiles without error, but always the output is x86 (as reported by "file").

I've looked at the GNU autoconfigure code and in the libsodium scripts but don't understand what I'm doing wrong. Here's one example:

./configure --build=x86_64-unknown-linux-gnu --host=arm-unknown-linux-gnueabihf --target=arm-unknown-linux-gnueabihf

The Makefile has the host_triplet etc set correctly, but "make V=1" shows the compiler is not being told to build for ARM architecture. For example:

> /bin/bash ../../libtool  --tag=CC   --mode=compile gcc -std=gnu99 -DPACKAGE_NAME=\"libsodium\" -DPACKAGE_TARNAME=\"libsodium\" -DPACKAGE_VERSION=\"1.0.3\" -DPACKAGE_STRING=\"libsodium\ 1.0.3\" -DPACKAGE_BUGREPORT=\"https://github.com/jedisct1/libsodium/issues\" -DPACKAGE_URL=\"https://github.com/jedisct1/libsodium\" -DPACKAGE=\"libsodium\" -DVERSION=\"1.0.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_MMINTRIN_H=1 -DHAVE_EMMINTRIN_H=1 -DHAVE_PMMINTRIN_H=1 -DHAVE_TMMINTRIN_H=1 -DHAVE_SYS_MMAN_H=1 -DNATIVE_LITTLE_ENDIAN=1 -DHAVE_AMD64_ASM=1 -DHAVE_TI_MODE=1 -DHAVE_CPUID=1 -DHAVE_WEAK_SYMBOLS=1 -DCPU_ALIGNED_ACCESS_REQUIRED=1 -DHAVE_MMAP=1 -DHAVE_MLOCK=1 -DHAVE_MADVISE=1 -DHAVE_MPROTECT=1 -DHAVE_POSIX_MEMALIGN=1 -I. -I../../../../src/libsodium   -I../../../../src/libsodium/include/sodium -I./include/sodium -D_FORTIFY_SOURCE=2  -g -O2 -fvisibility=hidden -fPIC -fPIE -fno-strict-aliasing -fno-strict-overflow -fstack-protector -Winit-self -Wwrite-strings -Wdiv-by-zero -MT crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo -MD -MP -MF crypto_aead/chacha20poly1305/sodium/.deps/libsodium_la-aead_chacha20poly1305.Tpo -c -o crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo `test -f 'crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c' || echo '../../../../src/libsodium/'`crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c

The only clue I have is that configure reports the following warning (here I'm trying a different arm architecture, but the results are the same for arm-unknown-linux-gnueabihf, which is what I'm really trying to build.

$ ./configure --build=x86_64-unknown-linux-gnu --host=arm-none-eabi --target=arm-none-eabi

checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-none-eabi
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-none-eabi-strip... no
checking for strip... strip
configure: WARNING: using cross tools not prefixed with host triplet

It may well not be a libsodium issue, but I can't understand why it is accepting the architecture but ignoring it without error. Any clues?

**Comment by theWebalyst** [comment]
I've solved this. The problem seems to be that the --host and other configure flags don't do anything for the architecture. So maybe that is a bug?

Anyway, what worked is simply assigning CC to the cross compiler before invoking 'configure' as in:

'''
export CC=arm-linux-gnueabihf-gcc-4.9
../../configure --build=x86_64-unknown-linux-gnu --host=arm-unknown-linux-gnueabihf --target=arm-unknown-linux-gnueabihf
make v=1
sudo make install
sudo ln -s /home/mrh/src/libsodium-1.0.3/target/arm-unknown-linux-gnueabihf/src/libsodium/.libs/libsodium.so /usr/lib/arm-linux-gnueabihf/libsodium.so
sudo ln -s /home/mrh/src/libsodium-1.0.3/target/arm-unknown-linux-gnueabihf/src/libsodium/.libs/libsodium.so.13 /usr/lib/arm-linux-gnueabihf/libsodium.so.13
'''

I have included the "--host" etc flags here, but don't think they do anything.

**Comment by jedisct1** [comment]
You only need `--host`, but try to use a triplet that matches your installed toolchain.

    ./configure --host=arm-linux-gnueabihf

should work in your case.

**Comment by jedisct1** [comment]
You almost never need `--build` or `--target`. You don't need to set `CC` either (and if you do, you should set environment variables for the rest of the toolchain as well).

The autoconf script tries to use tools whose prefix is the host triplet before falling back to the regular toolchain of the build environment.

**Comment by jedisct1** [comment]
` x86_64-unknown-linux-gnu` is not a triplet, it's a quadruplet :)

Not sure where the `unknown` part comes from, but just look at the common prefix used the compiler toolchain you want to use: this is the host triplet you can give to the `configure` script.

**Comment by theWebalyst** [comment]
Thanks Frank, I'm really new to this. I did succeed in building
libsodium for ARM, and using it to link with Rust compiled for ARM, but
will try your instructions.

Mark
--
Secure Access For Everyone:
SAFE Network - launches soon!
Fully Decentralised Internet
http://MaidSafe.net

**Comment by theWebalyst** [comment]
Hi again Frank,

It seems libsodium is behind the times :-)

"All configuration names used to have three parts, and in some
documentation they are still called configuration triplets."

https://sourceware.org/autobook/autobook/autobook_17.html#Configuration-Names

I didn't know anything about this stuff and ended up with the
"quadruplet" by following instructions for cross compiling with Rust. So
I don't claim any credit, but thought you'd like to know.

Thanks again for your help. I'm now going to retry libsodium stuff with
your suggestion, and also try out static linking. In case you're
interested in what I'm up to, I've made a post on the SAFE forum about
it. Can I add a credit to it for your help? I'd like to acknowledge you
for maintaining libsodium and for helping me build it properly. Here's
the link:
https://forum.safenetwork.io/t/cross-compiling-maidsafe-rust-code-for-arm/4175

All the best,

Mark
--
Secure Access For Everyone:
SAFE Network - launches soon!
Fully Decentralised Internet
http://MaidSafe.net

**Comment by theWebalyst** [comment]
Frank,

I'm trying your suggestion and beginning to think there might be some issue here after all. I've done "make distclean" and created "target/arm-linux-gnueabihf" from where I run:

```
$ ../../configure --host=arm-linux-gnueabihf
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-unknown-linux-gnueabihf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-gnueabihf-strip... arm-linux-gnueabihf-strip
...
configure: WARNING: using cross tools not prefixed with host triplet
```

As you can see, configure seems to be picking up "quadruplets" from the OS and failing to match the --host triplet to the build tools.

I also tried this but it makes no difference. I'm not sure how this is possible and whether I've just missed something.
```
$ make distclean
$ ./../configure  --build=x86_64-unknown-linux-gnu --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
checking build system type... x86_64-unknown-linux-gnu
checking host system type... arm-unknown-linux-gnueabihf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-gnueabihf-strip... arm-linux-gnueabihf-strip
...
configure: WARNING: using cross tools not prefixed with host triplet
```

**Comment by jedisct1** [comment]
Make sure that you don't have environment variables lying around.

I tried with a vanilla Ubuntu 15.04 install, didn't add any extra packages except `gcc-arm-linux-gnueabihf` and it worked out of the box.
What is your build environment?

**Comment by theWebalyst** [comment]
I did search for the obvious in env variables (CC, arm etc.) so don't think it was that but think you must be right. I just can't think where it is picking this up. I'm on Debian Jesse. Things are working for me - so I'm trying to sort out static build and linking with Rust now. If I track it down I'll let you know.
