### ISSUE TITLE
sodium_hex2bin isn't fully constant time

### ISSUE THREAD

**Issue by marksteward** [jedisct1/libsodium#276]
See also #241.

I was pointed to sodium_hex2bin in a discussion and noticed that, unlike sodium_bin2hex, it's half constant time and half not. If the input data contains invalid or ignored characters, the function is not constant time, in a way that depends on the data passed in.

There are three ways to improve this:
 - switch to a constant-time strchr
 - filter out characters that are >= 0x80
 - move the validation to a separate initial loop, which tracks a `valid` variable
 - accept an ignore_count parameter which ensures that strchr is only called a fixed number of times
 - hope that we don't hit any caching issues on the `ignore` memory

or:
 - move all the `ignore` functionality to a separate function which strips out characters and leave it to the user to ensure this is called safely
 - track a "valid" variable and only throw an error at the end of the loop
 - comment that the function requires all characters to be < 0x80

or:
 - comment that the function is not constant time when non-hex data is passed in
 - update the documentation to say the same

I'm happy to do any of these, but I don't know much about the project, so I'm not sure which is most suitable. My preference would be the second option, because it's a lot easier to reason about constant-time functions when they don't have branches, and most of the branches come from the `ignore` functionality.

**Comment by jedisct1** [comment]
Hi Mark,

You are absolutely correct, parsing a hex character is constant-time, while parsing ignored characters is not.

The output of the function, which is the secret an adversary usually wants to learn about using timing attacks, only depends on hex characters. This is what really needs to be constant-time.

There is not much an attacker can learn from a timing attack about the format, which is very likely to be constant (and probably public), or controlled by the attacker performing the attack.

**Comment by marksteward** [comment]
Is it not worth saying this in the documentation?
