### ISSUE TITLE
crypto_generichash_{init,final} outlen mismatch possibility useful?

### ISSUE THREAD

**Issue by dsheets** [jedisct1/libsodium#277]
`crypto_generichash_init` accepts a parameter `outlen` for the length of the resultant hash.

`crypto_generichash_final` accepts a parameter `outlen` for the length of the resultant hash *buffer*.

The semantically meaningful value is `crypto_generichash_init`'s `outlen` which changes the behavior of the hash function. The value passed to `crypto_generichash_final` is purely for memory accounting.

Passing a larger value to `_final` will produce a hash comprised of that many bytes but computed with the `P->digest_length` passed to `_init`. Passing a smaller value to `_final` will produce a hash comprised of the prefix of the hash resulting from the algorithm with a larger `P->digest_length`.

Is this potential for mismatch necessary? Meaningful? Will any 'correct' code ever pass different `outlen` values for `_init` and `_final`?

I can see the rationale for being very explicit about buffer length in calls that write after addresses. Does this outweigh the chance for mismatch?

In my binding, I have created a record to track `outlen` along with the state pointer because my users do not have to manually manage memory and passing the same value is repetitive and pointless in a high-level language. Should a `P->digest_length` accessor be added to the `crypto_generichash` API?

**Comment by jedisct1** [comment]
Having a function explicitly require the buffer length when the buffer has a variable length supplied by the caller really helps avoid writing past the end of a buffer.

`sodium_bin2hex()` requires the length of the output buffer for the very same reason.

An extra check doesn't cost much and can help bugs that can be devastating in C.

I think the distinction is also required to implement the parallel version of blake2 where h(blocks processed by a given thread) is never truncated, while the final output can be truncated.

So, this is probably not going to change, especially since it would break the ABI.

**Comment by dsheets** [comment]
> An extra check doesn't cost much and can help bugs that can be devastating in C.

Is there a check on this length? As far as I can tell, a mismatched `_final` `outlen` is accepted and appears to 'work' when it actually returns an incorrect hash due to `digest_length` not matching.

I understand the motivation for the buffer length being passed with the pointer but it seems to me that an incorrect buffer length should result in an error to prevent users from changing `_final`'s `outlen` which will yield the expected number of bytes but not changing `_init`'s `outlen`.

> I think the distinction is also required to implement the parallel version of blake2 where h(blocks processed by a given thread) is never truncated, while the final output can be truncated.

Is this implementable on top of the current API? What's the shape of that construction?

**Comment by jedisct1** [comment]
The length given to `_init()` becomes part of the initial state, so that the same message hashed with the same key but two different output length is going to produce two very different results, and not one result being a truncated version of the other one.

The length given to `_final()` effectively truncates the output length to the size of the target buffer.

Returning an error if the length don't match in a language with exceptions or compound result types that must be destructured makes sense. But in C, the return value of `_final()` is likely to be ignored.

The check can cause the application to crash. But this will be a breaking change (changing the current behavior some applications can rely on) and adding the size to the state would also break the ABI. So making such a change now doesn't sound like a good idea.
I keep this in mind, though, to possibly slip it in a major release along with other breaking changes.
Meanwhile, enforcing that the length is the same in bindings for other languages is definitely not a bad idea.

**Comment by cfcs** [comment]
I agree that requiring the length of the output buffer as an argument to `_final()` can help verify `strcpy()`-like security disasters.

However, checking that the `outlen`s passed to `_init()` and `_final()`  to prevent 1) segmentation faults 2) potentially sensitive heap data spilling into digest results 3) incorrect results from `_final()`.
Especially if `_final()` already takes the time to modify the structure to sanitize it -- why not add detection of that to `_final()`?

> Returning an error if the length don't match in a language with exceptions or compound result types that must be destructured makes sense. But in C, the return value of _final() is likely to be ignored.

By incompetent C programmers?

It seems inconsistent that `libsodium` would fail silently in some cases, but use error messages in other cases. Examples where the programmer is assumed to be old enough to check the return value:
```c
int crypto_box_*(); 
int crypto_scalarmult_base();
int crypto_stream_chacha20_*();
int crypto_sign_ed25519_pk_to_curve25519(); // return value is not even documented for this, so I doubt anyone actually checks it, but it gets to be an int anyway!
```

That being said, breaking ABI would also be bad, so saving it for the next major release seems like the best approach. Perhaps that could be in August when the winner of the Password Hashing Competition is announced?

**Comment by jedisct1** [comment]
Thanks for your feedback.

> However, checking that the outlens passed to _init() and _final() to prevent 1) segmentation faults

The size passed to `_init()` is just a value that becomes part of the state.

The output buffer length given to `_final()` is the number of bytes put into the buffer also given to the function. And a length greater than the block size is rejected.

> 2) potentially sensitive heap data spilling into digest results

Can't happen. What is being put into the output buffer is the state after finalization, truncated to the requested length. It can't exceed that length.

> 3) incorrect results from _final()

Having different values for the length when initializing the state and when storing the result after finalization is not incorrect.
The initial length can be seen as a value added to the key. It doesn't affect the output size, which is always 512 bits. And `_final()` puts the requested amount of bits (up to 512) from this result into the output buffer.
This is not incorrect or insecure, and there are use cases for it. For example, and even if it is not using this function, the DNSCrypt protocol (server-side) uses the 8 first bytes of a public key as a header to identify the certificate chosen by the client. It requires the whole 256-bit key for one purpose, and a truncated version of it for a different purpose. Being able to compute the hash for a 256-bit output, as well as, in a different context, the 64 first bits of the same output is very simple with the current API, but would stop working if we add the check discussed above.

>  Perhaps that could be in August when the winner of the Password Hashing Competition is announced?

Hopefully this can be added without breaking the current ABI. There are intentionally no high-level `crypto_pwhash_*` function set, and the current API is the one proposed for this competition. But we'll see. Nobody's supposed to know that the winner is Yescrypt at this point.

**Comment by dsheets** [comment]
I agree that *truncation* is sometimes useful. The check under discussion wouldn't have to disallow truncation (though, abandoning truncation inside `_final` would save a copy). The primary error case I am concerned with is the ability to seed the algorithm with a small length and then extract from the algorithm a larger (say 512 bit) "hash" that was not computed using that digest size.

Is there a use for this case? It seems to me that this is always incorrect but perhaps there is a reason that this would be useful.

**Comment by jedisct1** [comment]
The length given when initializing the state doesn't change the block size. The actual output is always 512 bits, so unless this is the final output length, truncation always has to be done.

**Comment by dsheets** [comment]
Is there a use case for extracting a "hash" that is larger than the digest length passed to `_init`?

**Comment by jedisct1** [comment]
Maybe, but I can't think of any (using the length for personalization would be quite convoluted).

**Comment by cfcs** [comment]
I'm not familiar with the details of blake2b, but what is the reasoning for having the `_init(outlen)` modifier instead of just hashing with a fixed `outlen` and truncating the output?

**Comment by jedisct1** [comment]
A collision found for a specific key, personalization, salt and output length may not be applicable with a different output length. This assumes that collisions can be found efficiently, though.
