### ISSUE TITLE
crypto_generichash_final state mutation

### ISSUE THREAD

**Issue by dsheets** [jedisct1/libsodium#278]
The hash resulting from a second successive `crypto_generichash_final` call on the same state pointer is different to the hash from the first invocation.

Is this second hash value meaningful in some way? Should this be an error condition? Should updating an already finalized hash fail? Should finalizing an already finalized state return the same hash value?

Both this issue and #277 seem like potentially undesirable deviations from the user-protective philosophy of NaCl. Perhaps my understanding of the function is mistaken, though, and only documentation improvements are necessary.

**Comment by jedisct1** [comment]
`_final()` should only be called once, and this is also true for other functions (sha2, hmac-sha2, poly1305).

Sorry if that was not clear in the documentation. I am going to explicitly mention this. But the following scheme has to be used with all APIs processing multi-part messages:

- `_init()`
- `_update()` any number of times, including 0
- `_final()`

There are no memory allocations, but `_final()` intentionally overwrites sensitive parts of the state.

**Comment by dsheets** [comment]
> _final() should only be called once, and this is also true for other functions (sha2, hmac-sha2, poly1305).

I've not studied the state representation terribly deeply but it appears that knowing whether a state has already been finalized is discernible from something like `S-f[0] = -1` and the finalized digest is recoverable from `S->h[i]`. Why not check whether an invalid finalization is being attempted and either error or return the first finalized digest?

**Comment by jedisct1** [comment]
Honestly, I don't see why anybody would ever call `_final()` twice; even intuitively, it doesn't really make sense.

Calling `_update()` without initializing the state with `_init()` would be more concerning. Something else to really insist on in the documentation.

**Comment by dsheets** [comment]
Two successive calls to `_final` would be a bit silly but calling `_final` multiple times in a stream of updates might plausibly occur -- perhaps to compute the hash of headers and message/file body? This is currently possible by copying the state before the first finalization but it *looks like it works* by reusing the state.

I'd rather not track the finalization of a `generichash` state when the state structure already contains this information and I certainly don't want to give my users (who generally expect functional interfaces) an interface that lets them accidentally call `_final` more than once and get bogus digests for calls > 1.

**Comment by paragonie-scott** [comment]
> Honestly, I don't see why anybody would ever call `_final()` twice; even intuitively, it doesn't really make sense.

See:
* https://github.com/paragonie/php-encryption/blob/1fe5edf75a04eda6b4511ae3913234beef2f6536/src/File.php#L492-L501
* https://github.com/paragonie/php-encryption/blob/1fe5edf75a04eda6b4511ae3913234beef2f6536/src/File.php#L568-L585
