### ISSUE TITLE
libsodium-uninstalled.pc.in broken for out-of-directory builds

### ISSUE THREAD

**Issue by stanford-scs** [jedisct1/libsodium#282]
If you run an out-of-directory build (e.g., mkdir build; ../libsodium/configure; ...) the generated libsodium-uninstalled.pc file is placed in the build directory, not the source directory.  This means that `PKG_CONFIG_PATH=$PWD pkg-config --cflags` will return include paths under the build directory, when you actually need them to point to the source directory.  A trivial fix is:

diff --git a/libsodium-uninstalled.pc.in b/libsodium-uninstalled.pc.in
index 3f960e5..43eed60 100644
--- a/libsodium-uninstalled.pc.in
+++ b/libsodium-uninstalled.pc.in
@@ -3,4 +3,4 @@ Version: @PACKAGE_VERSION@
 Description: A portable, cross-compilable, installable, packageable fork of NaCl, with a compatible API.
 
 Libs: -L${pcfiledir}/src/libsodium -lsodium
-Cflags: -I${pcfiledir}/src/libsodium/include
+Cflags: -I@top_srcdir@/src/libsodium/include

**Comment by stanford-scs** [comment]
Actually, my patch above is not quite right, because you need the build directory in your path too, for sodium/version.h.

**Comment by jedisct1** [comment]
So I guess we need both.

Does 41bb37060380f05eb5192dd01aa01e996e46563a work for you?

**Comment by stanford-scs** [comment]
Yes, seems work.  Thank you!

**Comment by stanford-scs** [comment]
Sorry I spoke too soon.  Looks like you also need `-I@top_srcdir@/src/libsodium/include/sodium` in the CFLAGS, because when third-party software includes <sodium.h>, that file includes "sodium/version.h", which is auto-generated in the build directory but includes "export.h" (which is only in the source directory).  So to make this work in other packages, you either need three `-I` directives, or maybe you could change version.h.in to include "sodium/export.h" instead.  Thanks.

**Comment by jedisct1** [comment]
Should be good in 6d10bfffcae42a128ba1677054be9df79cae2fb0 !
