### ISSUE TITLE
Docs website is down (download.libsodium.org/doc)

### ISSUE THREAD

**Issue by snej** [jedisct1/libsodium#283]
https://download.libsodium.org/doc/ is returning a 500 Server Error response :(
This has been going on since at least yesterday afternoon.

**Comment by jedisct1** [comment]
Looks like an OpenBSD upgrade that didn't go well, and the local DNS resolver was borked.
Sorry and thanks for spotting this. It should be good now. Thanks again!

**Comment by boobiesinc** [comment]
Hey, uhm, looks like maybe the same cause(with DNS resolver?) because the DNS server 8.8.8.8 cannot resolve either of `download.libsodium.org` or `libsodium.org` BUT this DNS server can: 209.244.0.3

https://github.com/NixOS/nixpkgs/issues/15515#issuecomment-219683318

**Comment by jedisct1** [comment]
This should be fixed now, thanks! There was an issue with its DNSSEC signature.

Google did the right thing here. If 209.244.0.3 doesn't mind serving invalid records, I wouldn't trust it much.
