### ISSUE TITLE
Feature Request Placeholder - Argon v2 Password Hashing API

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/libsodium#286]
Since Argon2 was the winner of the Password Hashing Contest, when they announce the final tweaks to the algorithm, will it be accessible via `crypto_pwhash()` and `crypto_pwhash_verify()`?

**Comment by jedisct1** [comment]
http://doc.libsodium.org/password_hashing/index.html
Scroll down :)

**Comment by paragonie-scott** [comment]
:+1: Great news! (Also, not surprised you already made note of this. :))
