### ISSUE TITLE
armv7s

### ISSUE THREAD

**Issue by ghazel** [jedisct1/libsodium#288]
Does libsodium actually benefit from armv7s? https://github.com/jedisct1/libsodium/blob/34176344fe7a0da133a719eb83594790cf115ceb/dist-build/ios.sh#L58

Keeping armv7s adds to the size of the library, and armv7 code will run fine on CPUs which support armv7s. Unless there's any performance gain at all (which I suspect there isn't), it's probably better to drop it.

For what it's worth, Apple also dropped armv7s from ARCHS_STANDARD.

**Comment by jedisct1** [comment]
Removed.
