### ISSUE TITLE
Add output layout to the documentation.

### ISSUE THREAD

**Issue by FSMaxB** [jedisct1/libsodium#290]
It would be nice if the documentation would contain information on how the output of the functions looks like.

`crypto_secretbox` for example. Is it `MAC | MESSAGE` or is it `MESSAGE | MAC`? Or `crypto_aead_chacha20poly1305_encrypt`. Is it `AD | MESSAGE | MAC`, or is it `MESSAGE | AD | MAC` or something else?

Currently I'd have to read the source code to get that information.

In my particular case I need to access some of the additional data (like the message counter) to be able to derive the key to decrypt and authenticate the message. Another solution for this particular problem would be a new API function to get the additional data of the AEAD without verifying it's authenticity.

**Comment by jedisct1** [comment]
`crypto_secretbox for example. Is it MAC | MESSAGE or is it MESSAGE | MAC`

Actually, the idea behind a high-level API is that you shouldn't know or have to deal about the inner format.

For the `crypto_secretbox` example, if you need to separately access the MAC and the ciphertext, you should use `crypto_secretbox_detached` which is specifically made for this.

AEAD constructions don't include a copy of the additional data. The AD is included in the computation of the MAC, but it's not part of the output. Stateful protocols often use packet counters are AD, and both the client and the server know what the expected value for each packet is. Including the AD in the message would make the protocol vulnerable to replay attacks.

**Comment by FSMaxB** [comment]
Thanks for your quick answer.

Interesting, this means that my understanding of AEAD was incorrect because I thought that the additional data is unknown to the receiver. Thanks for pointing this out.

I'll have to go with using `crypto_onetimeauth` manually.

**Comment by jedisct1** [comment]
Thanks for pointing out that this is something to clarify in the documentation. I'll try to improve this shortly.

**Comment by FSMaxB** [comment]
Does this mean I can just transmit the additional data as plaintext and authenticate it in one step with decrypting the message by passing it to the AEAD?

**Comment by jedisct1** [comment]
Yes, absolutely.
