### ISSUE TITLE
static library contains non-PIC objects

### ISSUE THREAD

**Issue by ustulation** [jedisct1/libsodium#292]
Here is an issue similar to what i'm facing:
http://stackoverflow.com/questions/32165208/errors-when-linking-libsodium-a-into-a-shared-object

I am unable to link `libsodium.a` to a shared object of mine because of the problem above. Do you have a solution ?

**Comment by jedisct1** [comment]
Hi,

What environment are you trying this on?
How did you compile/install libsodium?
Can you clarify how to reproduce this?

I tried on OSX and Ubuntu 15.04, libsodium installed using the default package, and I had no issues linking `libsodium.a` to a shared object, even with `-Wl,--whole-archive` as in your link.

**Comment by ustulation** [comment]
hey, thanks for looking into it. So I am on ubuntu 14.04 (LTS) and this is what i do:
Download 1.0.3 from here:
https://download.libsodium.org/libsodium/releases/
and the usual:
`./configure`
`make`

It works for Windows (because the `.a` contains objects which are default -fPIC on windows ?) and it works on Mac. But for linux I cannot link any of the object files (after `ar x libsodium.a`) or the archive itself (`libsodium.a`) to my shared object .. says recompile with `-fPIC` .. but i do see that being present in the Makefile generated after `./configure`.
```
/usr/bin/ld: /home/spandan/deleteme/libsodium-1.0.3/src/libsodium/.libs/deleteme/libsodium_la-crypto_box_easy.o: relocation R_X86_64_PC32 against symbol `crypto_box_detached' can not be used when making a shared object; recompile with -fPIC
```

But when i do:
```
readelf --relocs /home/spandan/deleteme/libsodium-1.0.3/src/libsodium/.libs/deleteme/libsodium_la-crypto_box_easy.o | egrep '(GOT|PLT|JU?MP_SLOT)'
00000000004e  001400000004 R_X86_64_PLT32    0000000000000000 crypto_box_beforenm - 4
000000000067  001200000004 R_X86_64_PLT32    0000000000000000 crypto_secretbox_detac - 4
000000000076  001500000004 R_X86_64_PLT32    0000000000000000 sodium_memzero - 4
00000000009a  001600000004 R_X86_64_PLT32    0000000000000000 __stack_chk_fail - 4
00000000015e  001400000004 R_X86_64_PLT32    0000000000000000 crypto_box_beforenm - 4
000000000177  001a00000004 R_X86_64_PLT32    0000000000000000 crypto_secretbox_open_ - 4
000000000186  001500000004 R_X86_64_PLT32    0000000000000000 sodium_memzero - 4
0000000001aa  001600000004 R_X86_64_PLT32    0000000000000000 __stack_chk_fail - 4
000000000001  001200000004 R_X86_64_PLT32    0000000000000000 crypto_secretbox_detac - 4
0000000000bd  001200000004 R_X86_64_PLT32    0000000000000000 crypto_secretbox_detac - 4
000000000111  001a00000004 R_X86_64_PLT32    0000000000000000 crypto_secretbox_open_ - 4
0000000001ce  001a00000004 R_X86_64_PLT32    0000000000000000 crypto_secretbox_open_ - 4
```

**Comment by jedisct1** [comment]
So, the `libsodium.a` file is the one installed by `make install`?

What exact command did you use to create/link your shared object?

**Comment by ustulation** [comment]
I am not using `make install` .. just `make` and copy files around .. i don't think should make a difference as long as i can provide it in the correct place at correct time though.
So here is the command:
```
gcc -shared -std=c99 -Wall -Werror -O2 -s -fvisibility=hidden -fPIC -o libc_wrapper.so ./../../../c/c_wrapper.c -L./../../../rust/target/debug -lsafe_ffi /home/spandan/deleteme/libsodium-1.0.3/src/libsodium/.libs/deleteme/libsodium*.o
/usr/bin/ld: /home/spandan/deleteme/libsodium-1.0.3/src/libsodium/.libs/deleteme/libsodium_la-crypto_box_easy.o: relocation R_X86_64_PC32 against symbol `crypto_box_detached' can not be used when making a shared object; recompile with -fPIC
```

**Comment by ustulation** [comment]
and also with the whole archive ofcourse:
```
gcc -shared -std=c99 -Wall -Werror -O2 -s -fvisibility=hidden -fPIC -o libc_wrapper.so ./../../../c/c_wrapper.c -L./../../../rust/target/debug -lsafe_ffi /home/spandan/deleteme/libsodium-1.0.3/src/libsodium/.libs/deleteme/libsodium.a
/usr/bin/ld: /home/spandan/deleteme/libsodium-1.0.3/src/libsodium/.libs/deleteme/libsodium.a(libsodium_la-hmac_hmacsha256.o): relocation R_X86_64_PC32 against symbol `crypto_auth_hmacsha256_init' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

**Comment by jedisct1** [comment]
Disable PIE:

    ./configure --disable-pie

**Comment by jedisct1** [comment]
Also, this has been fixed since. Ubuntu 15.04 and 15.10 don't have this issue.

**Comment by ustulation** [comment]
brilliant, that worked .. thanks !

**Comment by pdefreitas** [comment]
I am having something related in Ubuntu 16.04 targeting x86_64 Android, example:
ld: error: libsodium.a(libsodium_la-keypair.o): requires dynamic R_X86_64_PC32 reloc against 'crypto_sign_ed25519_seed_keypair' which may overflow at runtime; recompile with -fPIC

**Comment by pdefreitas** [comment]
--disable-pie fixed my issue by changing android build scripts. Thanks!

**Comment by yudhisthira123** [comment]
I am trying to link sodium static library in my Android project on MacOS 10.13.2. I have 2 setup, in one setup its working but in another this is issue is coming. 
It is working with gradle experimental version but in gradle 3.0.1 this the issue.

Can anyone guide me?
