### ISSUE TITLE
function declare confusing

### ISSUE THREAD

**Issue by byronhe** [jedisct1/libsodium#294]
I think the function prototype in the header files is confusing.

for example : 
```
int crypto_box_seal(unsigned char *c, const unsigned char *m,
                    unsigned long long mlen, const unsigned char *pk);
```

if a do not read the documents , i do not know what does `c`, `m`,`mlen`, `pk` means ?
maybe it can be renamed to `ciphertext`, `message`,`message_length`,`private_key`, to make it more  easy to understand by newbies .

**Comment by jedisct1** [comment]
This is already on the [roadmap](http://doc.libsodium.org/internals/roadmap.html): http://doc.libsodium.org/internals/roadmap.html - It will be done at some point, that's an easy but boring and time-consuming task, so I'd rather open a ticket and spend my weekend with the kids than actually do it as well :)

That said, if one does not read the documentation of a crypto library, and try to use functions without understanding what they do and what the parameters are (by definition, `crypto_box_seal` cannot accept a private key!), it can be pretty dangerous. The documentation includes important information about when and how to use each operation, and even though the API tries to prevent foot-shooting, I would highly recommend reading its documentation before using it.

**Comment by paragonie-scott** [comment]
I could send a PR (but only for the public API bits, I'd not feel comfortable rewriting any of the code used in the primitives) to address this, since it *is* on the roadmap.
