### ISSUE TITLE
How to use the winphone branch?

### ISSUE THREAD

**Issue by luzianscherrer** [jedisct1/libsodium#295]
Is there any information available on how to use the winphone branch? I've cloned it but when I open the sln file in Visual Studio 2015 there are only Win32 and x64 targets defined. When I build one of those and try to reference it from my Windows Phone project, I get "A reference to a higher version or incompatible assembly cannot be added to the project".

**Comment by jedisct1** [comment]
Hi Luzian,

Don't :)

This is an old branch whose content was already merged into the main branch.

As you already saw in the libsodium-net threads, there is still work to be done in order to have it compile out of the box for Windows Phone, though.

**Comment by luzianscherrer** [comment]
Got it! Thanks for letting me know.
