### ISSUE TITLE
For 1.0.4, possibly add an arbitrary value sodium_increment API?

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/libsodium#299]
Offering `sodium_increment()` is a great idea, but if we wanted to call it on an arbitrary sized nonce increase, we'd currently have to throw it in a loop. This is probably sub-optimal.

Possible use case: Encrypting a stream in 1 MB chunks (e.g. for file encryption) using `crypto_stream_xor()`. After each chunk, we'd want to increase our nonce by 32768 (1024 * 1024 / 32).

Since 1.0.4 isn't out yet, could we add an extra parameter to `sodium_increment` that defaults to 1, which is the amount we are increasing?

If not, should an alternative helper be written for this?

**Comment by jedisct1** [comment]
Hi Scott,

salsa20 (`crypto_stream_xor()`) has an internal 64-bit counter (and the block size is 512 bits). Up to 2^70 bytes can be encrypted with a single nonce.

After each 1 Mb chunk, you don't need to increase the nonce by more than 1.

May I be missing something?

**Comment by paragonie-scott** [comment]
Oh. I stand corrected then.
