### ISSUE TITLE
Support for multi-part crypto_sign_detached

### ISSUE THREAD

**Issue by asherkin** [jedisct1/libsodium#301]
From #265:
> Adding support for multi-part messages to crypto_sign() is something I can quickly add to the library, but there's nothing wrong with pre-hashing using blake2 while sketching the certificate format.

This is something that would be reallllllllllly handy.

**Comment by jedisct1** [comment]
The ed25519 signature scheme requires hashing the message twice.

While that message can be provided as multiple chunks, having to do it twice still makes it impossible to do it on a stream, which in probably the most common use case.

So, using Blake2, with the full 512-bit output, and signing the final output, is actually not a bad idea.

**Comment by asherkin** [comment]
Cool, thanks for the info!

**Comment by tarcieri** [comment]
Note that the CFRG has mandated an IUF mode for their upcoming signature scheme, which will likely be EdDSA, and should provide a standard construction for what @jedisct1 is describing.
