### ISSUE TITLE
randombytes_sysrandom_random_dev_open fails on QNX

### ISSUE THREAD

**Issue by cicciotti-privatewave** [jedisct1/libsodium#302]
In QNX, `/dev/urandom` and `/dev/random` are not marked as character special files (`S_IFCHR`), but as  name special files (`S_IFNAM`), so this check fails:

            if (fstat(fd, &st) == 0 && S_ISCHR(st.st_mode)) {

I'm not sure what the right fix is. I think a special exception should be made for QNX and only QNX, to avoid weakening the check on other platforms

**Comment by jedisct1** [comment]
Thanks for pointing this out!

Maybe the best fix is to tolerate `S_IFNAM` in addition to `S_IFCHR` if `S_IFNAM` is defined.

**Comment by jedisct1** [comment]
Does d8e870cb43e51ef64e5bc0ab5ba2d25153fe2291 fix it for you?

**Comment by jedisct1** [comment]
Ping?

**Comment by cicciotti-privatewave** [comment]
It doesn't compile, you have a typo: `S_IFNAM(st.st_mode)` should be `S_ISNAM(st.st_mode)`

**Comment by jedisct1** [comment]
I just wanted to know if you actually tried it :)

More seriously, it should be fixed now. Thanks!

**Comment by cicciotti-privatewave** [comment]
Oh yes, it works! after I fixed the typo, it worked
