### ISSUE TITLE
Create signature using curve25519 key

### ISSUE THREAD

**Issue by jeroenooms** [jedisct1/libsodium#303]
In [public-key authenticated encryption](https://download.libsodium.org/doc/public-key_cryptography/authenticated_encryption.html) the `crypto_box_keypair` (curve25519) keypair is used for both encryption and signing. My application also needs an option to just create signatures, without encryption. 

However the [public-key signatures](https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html) section only describes using `crypto_sign_keypair ` (ed25519) keypairs for signatures. It is a little annoying that the user has need another keypair for creating signatures. 

Is it also possible to use the same `crypto_box_keypair` keypair that is used in authenticated encryption, to create a signature? There is a function to convert `ed25519` to `curve25519` but not the other way around.

**Comment by paragonie-scott** [comment]
See #77

**Comment by tarcieri** [comment]
Pretty much everyone I've talked to about this has said it's okay to combine Schnorr and ECDH this way, but it would still be safer to sign a static ECDH key with your Ed25519 key.

Another part of the problem is Ed25519 keys are derived by applying SHA-512 to a seed value. @trevp has suggested an alternate construction where the "RH" data used to derive nonces is derived by hashing the private scalar, I believe, but this is incompatible with how Ed25519 is otherwise used in libsodium.

And yes, see #77

**Comment by jeroenooms** [comment]
I guess this is more complex than I thought. So as I understand it, the current implementation does not provide a method to send an signed unencrypted message to somebody who knows my `curve25519` pubkey? But I can send them signed encrypted message with `crypto_box_easy`?

**Comment by cfcs** [comment]
@jeroenooms this is explain in the [documentation for crypto_box_easy](https://doc.libsodium.org/public-key_cryptography/authenticated_encryption.html).
Message authenticity is ensured using a poly1305 tag keyed with a secret symmetric key derived from the shared secret between your curve25519 secret key and the other party's curve25519 public key.
Thus, if the poly1305 tag on a message checks out, you can be sure that either
- 1) The other party sent the message to you
- 2) You sent the message to the other party

This differs from using a signatures in which case you can be sure that only 1) is the case.

**Comment by jeroenooms** [comment]
OK that makes sense, thank you.
