### ISSUE TITLE
Curve25519xsalsa20poly1305 key derivation

### ISSUE THREAD

**Issue by perfaram** [jedisct1/libsodium#305]
Hi !
I'm working on batch-encryption of files, for a small project of mine. The files are stored *encrypted* by the client, usually on a removable drive; each client has a keypair associated with, and while all keypairs are stored on a trustful server, a client only holds its public key. But, for enhanced safety, I'd like to use ONE keypair for ONE file.

Now, here's how I'd like things to happen :
1. Each time the client encrypts a file, it uses a key that is derived from the client's public key and a blob. This key is returned by `fun1(publicKey, blob)`. The `blob` is itself deterministically generated from a set of non-varying file attributes, and the `publicKey` is, well, the public part of the client's keypair.
2. Each time the client requests decryption for a file, the `blob` is generated again and sent to the server. The server then gathers the client's private key from the DB, and calls `fun2(privateKey, blob)` to get a private key. This key is the counterpart to step 1's public key, and it is sent to the client, which can now decrypt the file it wanted to, but NONE of the other files.

```
On the server (decryption): 
[master private key] \ 
                      \   / seed from client
                       \ /
                        \ fun2(privateKey, seed)
                         -> derived private key
```
```
On the client (encryption): 
[master public key] \ 
                     \   / getSeed(attributes)
                      \ /
                       \ fun1(publicKey, seed)
                        -> derived public key
```

If you're bitcoin-savvy, think BIP32 but for encryption.

How to achieve such a thing ? Is there even a way to do this ? What should the derivation function do ?

**Comment by chmike** [comment]
Hi, I'm just trying to understand your process. I'm not Bitcoin savvy. Why would you store the clients private key on the server ? This is counter intuitive. 

For clarification, could you explain what you try to achieve ? What is the purpose of your system ? An example would help us. Why is the client encrypting with it's public key ? Why decrypting on the server? 

I guess the output of fun1 and fun2 must be the same symmetric key. Right ?

--
Bien cordialement,
Ch.Meessen

**Comment by perfaram** [comment]
The purpose of the system is to be able to keep encrypted data safe, on a USB key, accessible to anyone who's allowed by the server, without having to create some kind of Dropbox (storage size issues). The server holds ONLY the keys, and give them to anyone who has the right permissions. 
BUT : having only 1 keeper for all the client's data is dangerous, because the client might try to intercept them and decrypt EVERYTHING it holds.

**Comment by perfaram** [comment]
Ahem... I see you're french too. So here's a french explanation : 
Le serveur garde les clés privées des clients et gère les autorisations. Les clients gardent seulement leurs données. 
Chaque fichier est crypté par le client avec une clé publique dérivée de la clé publique **globale** du client + un seed provenant d'attributs du fichier. 
Parfois, le client veut décrypter ses données. Il va recréer le seed à partir des attributs, puis l'envoyer au serveur. Après l'authentification, le serveur va aller chercher la clé privée du client dans sa BDD et l'utiliser avec le seed envoyé par le client pour en dériver une autre clé, une clé privée, qui correspondra à la clé publique créée auparavant par le client lors de l'encryption.

**Comment by perfaram** [comment]
test

Date: Fri, 16 Oct 2015 23:45:29 -0700

**Comment by perfaram** [comment]
<span class="email-hidden-toggle"><a href="#">…</a></span>

**Comment by perfaram** [comment]
<div class="comment-body markdown-body email-format js-comment-body">
          <div class="email-fragment">Hi, I'm just trying to understand your process. I'm not Bitcoin savvy. Why would you store the clients private key on the server ? This is counter intuitive.

For clarification, could you explain what you try to achieve ? What is the purpose of your system ? An example would help us. Why is the client encrypting with it's public key ? Why decrypting on the server?

I guess the output of fun1 and fun2 must be the same symmetric key. Right ?</div>
<span class="email-hidden-toggle"><a href="#">…</a></span><div class="email-hidden-reply" style="display: none;">
<div class="email-signature-reply">--
Bien cordialement,
Ch.Meessen</div>
<div class="email-quoted-reply"> Le 16 oct. 2015 à 20:00, Perceval Faramaz &lt;notifications@github.com&gt; a écrit :

 Hi !
 I'm working on batch-encryption of files, for a small project of mine. The files are stored encrypted on a removable drive, and the keys are stored on a trustful server. For enhanced safety, I'd like to use ONE key for ONE file.
 Each time the client adds a file to the drive, it is encrypted using a public key, generated with fun1(masterPublicKey, seed). The seed is itself deterministically generated from a set of non-varying file attributes, and the masterPublicKey is, well, a public key that belongs to the client and that's reused for all files belonging to this client.
 Each time the client requests decryption for a file, the seed is sent to the server. It then gathers the client's private key, and calls fun2(privateKey, seed) to get a derived private key. This key is sent to the client, which can now decrypt the file it wanted to, but NONE of the other files.

 On the server (decryption):
 [master private key] \
                       \   / seed from client
                        \ /
                         \ fun(privateKey, seed)
                          -&gt; derived private key
 On the client (encryption):
 [master public key] \
                      \   / getSeed(attributes)
                       \ /
                        \ fun(publicKey, seed)
                         -&gt; derived public key
 If you're bitcoin-savvy, think BIP32 but for encryption.

 How to achieve such a thing ? Is there even a way to do this ? What should the derivation function do ?

 —
 Reply to this email directly or view it on GitHub.
</div>
<div class="email-fragment"></div>
</div>
      </div>

**Comment by chmike** [comment]
It's Ok. You don't need to write in French. Note also that the replies 
to mails are published to the libsodium issue tracker. My private email 
is not disclosed, as yours.

I'm still trying to figure out what your system is doing.

So you want to implement a file server like dropbox where files are 
stored encrypted. You want that the owner, but also third party users 
with appropriate permission, may get back the files decrypted. Is this 
what you are trying to achieve ?

**Comment by perfaram** [comment]
Nah... The server only holds the *keys*. The client keeps only the data, which is encrypted using the libsodium's sealed boxes. A keypair is assigned to the client, and from these keys are derived file-specific keys.

NB : I deleted my translation to french.

**Comment by perfaram** [comment]
In the end, I'm just generating random keypairs, that aren't derived from any kind of file attributes. Anyway, that was a bit dangerous, as they could change.
