### ISSUE TITLE
Feature request: abort flag for pwhash

### ISSUE THREAD

**Issue by thijsvandien** [jedisct1/libsodium#306]
I'm doing key derivation using `crypto_pwhash_scryptsalsa208sha256` in some background service. Because it requires no interactivity, I could set the `opslimit` rather high. The problem is that I want to keep the ability to stop the service at any time. A long running blocking operation prevents that, even when it's running in a thread. Killing threads is a bad idea, especially since sodium might hold resources that need clean up.

What I'd like to be able to do is abort the call in a collaborative fashion when I'm no longer interested in the result. An implementation for this could be to have the function take a pointer to a boolean, the value of which could (atomically) be changed from a parent thread. The function should then regularly check the value of this abort flag and return -1 when it is set.

Unless there are other options to achieve the same, I think this would improve security, by not forcing the user to keep the `opslimit` low just to preserve usability. Chaining multiple calls with a lower `opslimit` did not work for me, because a low `opslimit` also lowers memory usage. Besides, it makes it easier to make a mistake; when one makes the intermediate output too short, it is easy to brute-force just the input to the final call that determines the end result.

**Comment by jedisct1** [comment]
Wouldn't spawning dedicated processes be an option?

You can safely kill it anytime, multiple key derivations can happen simultaneously on different cores without sharing the same address space, and since it is a compute-only job, it can run with very limited privileges compared to the main app.

**Comment by thijsvandien** [comment]
Having to introduce IPC and dealing with the edge cases of using multiple processes (killing the parent should also kill the child, which normally doesn't happen) doesn't make it very inviting either to set the `opslimit` fairly high. I suppose that is my main point; not necessarily that there is no way at all to make key derivation expensive and preserve usability, but that it is harder than it should be, and therefore implicitly encourages to make it less expensive.

For now I think I will stick with the idea of chaining, where `n-1` calls generate the salt for the next and the `n`th call produces the end result with the desired length. In this scheme I set the `opslimit` as low as possible to keep memory usage as desired and use `n` to control the total number of operations. With the `memlimit` set to `128MB` that makes the whole thing still reasonably responsive. I'd love to have a better way, but I'd be glad to hear if at least this is a sensible alternative for the time being.

**Comment by tarcieri** [comment]
> An implementation for this could be to have the function take a pointer to a boolean, the value of which could (atomically) be changed from a parent thread. The function should then regularly check the value of this abort flag and return -1 when it is set.

Or you could just use e.g. `pthread_kill`

**Comment by thijsvandien** [comment]
Perhaps it's different on Linux, but on Windows every discussion of `TerminateThread` mentions that it should *never* be used, for the mess it leaves behind.

**Comment by jedisct1** [comment]
scrypt performs memory allocations, so killing a thread may indeed leak memory.
On Unix-like systems, using processes is easy, safe, and automatically release memory no matter how the child process terminates.
On Windows, I'm not sure how to achieve the same thing. But introducing an "abort" pointer sounds like an ugly hack that I'd rather avoid.

**Comment by adamcaudill** [comment]
> Perhaps it's different on Linux, but on Windows every discussion of TerminateThread mentions that it should never be used, for the mess it leaves behind.

I would agree, killing the thread is messy - and should be avoided when possible.

> Wouldn't spawning dedicated processes be an option?

This is the route I'd go - it's not that complicated and is cleaner than trying to safely kill the thread or deal with hacking in an abort flag. I've built processes that work this way on Windows without issue - it takes a little more time, but it's the best way to solve the issue.

**Comment by thijsvandien** [comment]
Alright then; I consider myself out-voted. Could any of you still confirm that the chaining method isn't a terrible idea either?

**Comment by jedisct1** [comment]
The chaining method is not terrible, but it won't be memory-hard. Go for a dedicated process if possible.
