### ISSUE TITLE
segfault during test suite

### ISSUE THREAD

**Issue by remicollet** [jedisct1/libsodium#307]
Strangely, this only appears in RHEL-6 / i386 (fine in fedora, RHEL-5, RHEL-7, i386 and x86_64)

    make  check-TESTS
    make[3]: Entering directory `/builddir/build/BUILD/libsodium-1.0.4/test/default'
    make[4]: Entering directory `/builddir/build/BUILD/libsodium-1.0.4/test/default'
    ../../build-aux/test-driver: line 107: 20339 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
    FAIL: aead_aes256gcm

I will try to investigate later, to get an backtrace.

**Comment by jedisct1** [comment]
Can you reproduce this with the current git code?

**Comment by remicollet** [comment]
I confirm 1.0.4 + rev 63b9c02f0c093d496edd2ebeb40e04b87813fea7 is ok

Build + test suite run on Fedora 19 to 23 and RHEL 5 to 7, both i386 and x86_64

Thanks.

**Comment by jedisct1** [comment]
Thanks for the confirmation, Remi!
