### ISSUE TITLE
pbkdf2-sha256.c:56:5: warning: comparison is always false due to limited range of data type [-Wtype-limits] 

### ISSUE THREAD

**Issue by Gibbon1** [jedisct1/libsodium#312]
Hi I tried compiling libsodium for an ARM Cotrex M0+ and got warning in File pbkdf2-sha256.c line 56

The offender is this, where dkLen is size_t which is 32bits on the Cortex-M0

    if (dkLen > 0x1fffffffe0UL) {
        abort();
    }

Comment in the header: The value dkLen must be at most 32 * (2^32 - 1)
Not sure what this means for a 32 bit arch.

**Comment by jedisct1** [comment]
Hi Gibbon,

You can safely ignore this warning. The compiler will not emit any actual code for this test, which is totally fine as this error condition  cannot happen on your platform.
