### ISSUE TITLE
Problem: Possible broken test in some environments due to blacke2b changes

### ISSUE THREAD

**Issue by taotetek** [jedisct1/libsodium#314]
I noticed that libsodium is failing to build in my travis-ci environment as part of some integration tests due to an undefined reference to `blake2b_compress_sse41'.  It was working earlier this morning.

I suspect that this recent commit ( https://github.com/jedisct1/libsodium/commit/55a9a745e6af18d6637310e61dd63010f36b8fbb ) is the culprit.

My build script that I use for travis, which git clones libsodium from master as part of the process can be found here: https://github.com/taotetek/pressure/blob/master/ci_build.sh

The output from the build around the failure:
```
make  aead_aes256gcm aead_chacha20poly1305 auth auth2 auth3 auth5 auth6 auth7 box box2 box7 box8 box_easy box_easy2 box_seal box_seed chacha20 core1 core2 core3 core4 core5 core6 ed25519_convert generichash generichash2 generichash3 hash hash3 onetimeauth onetimeauth2 onetimeauth7 pwhash pwhash_scrypt_ll randombytes scalarmult scalarmult2 scalarmult5 scalarmult6 scalarmult7 secretbox secretbox2 secretbox7 secretbox8 secretbox_easy secretbox_easy2 shorthash sign sodium_core sodium_utils sodium_version stream stream2 stream3 stream4 verify1 sodium_utils2 sodium_utils3

make[3]: Entering directory `/home/travis/build/taotetek/pressure/libsodium/test/default'

  CC     aead_aes256gcm.o

  CCLD   aead_aes256gcm

../../src/libsodium/.libs/libsodium.so: undefined reference to `blake2b_compress_sse41'
```

The problem may very well be the way I'm building or a flag I need that I don't have due to the change.  I wanted to report it just in case it's an issue with libsodium itself in some environments.  Happy to answer any questions and run tests to help figure it out.

**Comment by taotetek** [comment]
Additional information: libsodium builds and passes tests from head with no issue locally on my laptop, so I am only seeing this issue on travis.  Perhaps something to do with how travis virtualizes build environments?

**Comment by jedisct1** [comment]
It's a development tree... You can expect it to not compile, to be broken or completely insecure.

Even more when code specific to Visual Studio is being worked on and changes haven't been tested on Linux at all :)

**Comment by jedisct1** [comment]
Do you have a link to the Travis log?

**Comment by taotetek** [comment]
@jedisct1 Thanks for the quick response!  I understand it's not a stable release (and I don't built against master for an actual release for anything, don't worry ;) ) - I just happened to run into it and wanted to report it in case the information was useful.

If you prefer to only have issues reported against stable releases I'll keep that in mind - I want to make sure to provide signal and not noise.  I can move my environment to build against stable for ci, and you can feel free to close this or handle it according to your own dev processes.

Link to travis log: https://travis-ci.org/taotetek/pressure/builds/88645511

**Comment by jedisct1** [comment]
Early reports are very useful and appreciated! That one might be fixed now, after af532e5dd169199fddb55016b67714fec4e533f7

I justed wanted to make sure that you didn't use the master branch for anything critical, as it's not guaranteed to work as expected.

**Comment by taotetek** [comment]
@jedisct1 Excellent - I'll kick off a rebuild and let you know!  No worries - not using master for anything critical, I just have my ci set up to build off of master while I'm developing - helps me spot changes faster when things fail.

**Comment by taotetek** [comment]
@jedisct1 
```
===================

All 58 tests passed

===================
```

Looking good!  Thanks!

**Comment by jedisct1** [comment]
Awesome, thanks!
