### ISSUE TITLE
Documentation describes non existant function crypto_auth_verify_detached

### ISSUE THREAD

**Issue by wsargent** [jedisct1/libsodium#315]
The documentation in http://doc.libsodium.org/advanced/hmac-sha2.html says:

> Only use these functions for interoperability with 3rd party services. For everything else, you should probably use crypto_auth_detached()/crypto_auth_verify_detached() or crypto_generichash_*() instead.

However, there are no `crypto_auth_detached` or `crypto_auth_verify_detached` methods available in the current code:

https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_auth/crypto_auth.c#L23

**Comment by jedisct1** [comment]
Good catch!

This has been fixed, thanks!
