### ISSUE TITLE
Pre-compiled Win32 packages are available for download at the same location?

### ISSUE THREAD

**Issue by LewisMcMahon** [jedisct1/libsodium#321]
In the docs it says "Pre-compiled Win32 packages are available for download at the same location." but i cant find could someone point me in the right direction?

My goal is to install so i can use pynacl

**Comment by jedisct1** [comment]
Hi,

Precompiled packages are available here:

https://download.libsodium.org/libsodium/releases/

**Comment by LewisMcMahon** [comment]
ive looked in their but i don't see anything vaguely recognise as a windows package

**Comment by jedisct1** [comment]
`libsodium-1.0.6-msvc.zip`  contains the precompiled libraries for Visual Studio, `libsodium-1.0.6-mingw.tar.gz` contains the precompiled libraries for MinGW.
