### ISSUE TITLE
Bob's anonymous public key

### ISSUE THREAD

**Issue by ambitslix** [jedisct1/libsodium#323]
Hello,

Why is it necessary that

crypto_box_easy(ciphertext, MESSAGE, MESSAGE_LEN, nonce, bob_publickey, alice_secretkey);

uses a private key of the sender?

**Comment by sbredahl** [comment]
Because Bob want to verify that Alice send the message (aka authentication). If the message should be anonymous, use crypto_box_seal instead (as of libsodium 1.0.3).
