### ISSUE TITLE
Feature request:  AES-256-GCM detached mode

### ISSUE THREAD

**Issue by portnoy** [jedisct1/libsodium#324]
AES is a requirement for me and I'm so glad you guys added AES-256-GCM implementation sparing me the horrors of openssl.

It would've been marvelous if the API supported detached signatures along the lines of crypto_secretbox_detached(). 

Thank you.

**Comment by jedisct1** [comment]
Hi Eugene,

That's a good idea, and it should also be added to the ChaCha20-Poly1305 implementation for consistency.

Do you need this urgently? It's pretty easy to add, but version 1.0.7 was planned to be released in the forthcoming days, so it would be great if it could wait version 1.0.8.

There is an API problem with introducing a detached version of `crypto_aead_*()`, though.
AEAD constructions can require padding. This is not the case with the current constructions, but the API was designed to cope with that.
`_ABYTES` represents the maximum number of bytes that will be added, after encryption (+ optional padding), and with the authentication tag.
Detached versions will require two new constants. One for the maximum padding length, and another one for the tag length. So, we will have `_ABYTES`, `_PADBYTES`, and `_MACBYTES`. That's a bit ugly.
Not a big deal. I was just thinking aloud :)

**Comment by portnoy** [comment]
Great, I'm glad you're planning to add detached signatures in 1.0.8. It would be nice to have them in by mid January, though, if it fits your release schedule.

And the meaning of _*BYTES constants is clear - not a big deal indeed.

Thank you again.

**Comment by ivmaykov** [comment]
Any update on this? I'd like to have it also.

**Comment by jedisct1** [comment]
Mostly done.

Missing: tests + same thing for chacha20poly1305 for consistency.

**Comment by jedisct1** [comment]
Tests done. Closing this ticket, but a detached API still has to be implemented for chacha20poly1305.

**Comment by portnoy** [comment]
Thank you so much!
