### ISSUE TITLE
Only high-level API now available in prebuilt MinGW binaries

### ISSUE THREAD

**Issue by Fraser999** [jedisct1/libsodium#327]
It would appear that https://github.com/jedisct1/libsodium/commit/cc29da17c39b0cd881de4fe5d154841057f75f91 changed the distribution builds for MinGW to use the new `--enable-minimal` option.

This has resulted in reduced functionality between versions 1.0.6 and 1.0.7 of the [prebuilt MinGW binaries](https://download.libsodium.org/libsodium/releases/).

I'm not sure if this is an intended effect, or if so, why that would be wanted.  If this is intended, perhaps two sets of prebuilt MinGW targets could be provided; minimal and full?

For reference, I hit this issue when building the tests in the Rust binding ([sodiumoxide](https://github.com/dnaq/sodiumoxide)) of libsodium.

**Comment by jedisct1** [comment]
The mingw build scripts were the only ones left that were not using `--enable-minimal` to skip undocumented and untested functions.

But indeed, some apps and bindings might still be using them, and previous pre-build binaries for MingGW still had these functions around, so it makes sense to keep them in these binaries, until they are completely removed.

The `--enable-minimal` addition was reverted and new binaries for MinGW have replaced the previous ones.

**Comment by Fraser999** [comment]
That's great - thanks very much.
