### ISSUE TITLE
crypto_sign_edwards25519sha512batch_open doesn't return original message

### ISSUE THREAD

**Issue by Fraser999** [jedisct1/libsodium#328]
This appears to be a trivial offset error in the function.

**Comment by jedisct1** [comment]
Do not use this. It is undocumented, it's untested, it is marked as deprecated, nothing is using it, and it is going to be removed.

**Comment by Fraser999** [comment]
Point taken :)  I'm not using it directly - it's used by the Rust bindings, but I'll probably create an issue there and link to your comment here.

Thanks.
