### ISSUE TITLE
Errors running "make check" on debian testing (gcc 5.2.1, Intel Xeon)

### ISSUE THREAD

**Issue by 0x64616E69656C** [jedisct1/libsodium#332]
Hi,

I was trying to create .deb packages for libsodium 1.0.7 on debian testing x86_64, but ran into a few errors during make check.

So I tried a clean build, with the same results:
```
./configure
make
make check
[...]
../../build-aux/test-driver: line 107: 14658 Illegal instruction     "$@" > $log_file 2>&1
FAIL: box
[...]
```
this happens with box\*, scalarmult\*, and ed25519_convert.

I took one of the failed tests, build a static binary, and run it with gdb:
```
$ ~/code/libsodium/clean/libsodium-1.0.7/test/default >  gcc -I ../../src/libsodium/include/ -I ../quirks/ -static -o test box8.c ../../src/libsodium/.libs/libsodium.a
$ gdb ./test
[...]
(gdb) run
Starting program: /home/daniel/code/libsodium/clean/libsodium-1.0.7/test/default/test

Program received signal SIGILL, Illegal instruction.
._ladder_base_loop () at crypto_scalarmult/curve25519/sandy2x/ladder_base.S:88
88      vbroadcastss 0(%rsi),%xmm10
```

Doing some research I was pointed at SSE instructions, but I'm not sure if this applies here.

Build-Box is a Xen-PV, CPU:
```
model name      : Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
fpu             : yes
fpu_exception   : yes
flags           : fpu de tsc msr pae cx8 sep cmov pat clflush mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc rep_good nopl pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes hypervisor lahf_lm ida arat pln pts dtherm
``` 

Some basic env info:
gcc: 5.2.1-23
autoconf: 2.69-9 (I tried autoreconf -i, autoconf, automake)
glibc: 2.19-22

Any idea what's going on?

Thanks!

**Comment by 0x64616E69656C** [comment]
On second thought, this looks AVX instruction related. So, I recompiled with CFLAGS="-msse", same issue, other gdb output:

```
Starting program: /home/daniel/code/libsodium/clean/libsodium-1.0.7/test/default/test

Program received signal SIGILL, Illegal instruction.
0x0000000000410133 in ._ladder_base_loop ()
```

So, basicly I've still no clue how to fix this ;-)

**Comment by jedisct1** [comment]
Hi,

and thanks for reporting this.

What does this print?

```c
#include <stdio.h>
#include <sodium.h>

int main(void)
{
    if (sodium_init() != 0) {
        return 1;
    }
    printf("%d\n", sodium_runtime_has_avx());

    return 0;
}
```

**Comment by jedisct1** [comment]
Can you also try this?
```c
#include <stdio.h>

int main(void)
{
    unsigned int eax, edx;
    __asm__ __volatile__ (".byte 0x0f, 0x01, 0xd0"
                          : "=a"(eax), "=d"(edx) : "c"(0UL));
    unsigned long long bv =
        (unsigned long long) eax | (((unsigned long long) edx) << 32);
    printf("%llx\n", bv);

    return 0;
}
```

**Comment by 0x64616E69656C** [comment]
Hi,

thanks for the quick response.

test 1 returns 1, so no avx. (staticly linked against libsodium build with -msse2)

test 2 returns SIGILL:

```
Program received signal SIGILL, Illegal instruction.
0x0000000000400516 in main ()
```

**Comment by jedisct1** [comment]
I'm confused. Does test 1 return `1` or `0`?

**Comment by jedisct1** [comment]
Please do not use `-msse2`, just the default options picked by the `configure` script.

**Comment by 0x64616E69656C** [comment]
sorry, 1.

**Comment by jedisct1** [comment]
`1`, so AVX is present?

**Comment by 0x64616E69656C** [comment]
Ok, to not mess things further up, I distclean'ed everything and rebuild with default options.

So, yes, test 1 returns literally ```1```, so ``` if (sodium_init() != 0)``` matches. printf is not reached.

the output of ```printf("%d\n", sodium_runtime_has_avx());``` itself is ```0```, when I comment the check for sodium_init() out.

test2 remains SIGILL, but that stands since it does not rely on sodium.

**Comment by 0x64616E69656C** [comment]
The SIGILL on test2 can be reproduced with gcc-4.8, gcc-4.9 and clang-3.5.2 too, so it's not an gcc-5.2 issue.

**Comment by jedisct1** [comment]
So, the library is not useable at all, if even `sodium_init()` fails.
Can you investigate where `sodium_init()` returns `-1`?

**Comment by 0x64616E69656C** [comment]
Ok, I'll dig deeper later this evening!

**Comment by 0x64616E69656C** [comment]
Ugh, SORRY. Now I got confused. sodium_init does *not* fail. **Literally** ```1``` means "yes, the library was initialized, and the value of sodium_runtime_has_avx() is 1".

**Comment by jedisct1** [comment]
Ok, now that makes sense :)

Can you check if ab4bade488a159fd653f6a5c31205164726bd77c fixes it on your CPU?

**Comment by 0x64616E69656C** [comment]
Confirmed, that fixes the issue! THANKS!
