### ISSUE TITLE
Cannot connect to https://doc.libsodium.org/ because of privacy error

### ISSUE THREAD

**Issue by VashaTS** [jedisct1/libsodium#342]
After hearing about this lib, I wanted to use it, so I went to
http://doc.libsodium.org/

It automatically switched to
https://doc.libsodium.org/
because of HSTS

It shows me this error:
http://i.imgur.com/ILD9whd.png

It seems to use certificate for *gitbook.com on the libsodium.org domain

System Windows 7 
Browser: Chrome

**Comment by jedisct1** [comment]
Hi,

Where did you find a link to doc.libsodium.org? This one is an alias for Gitbook and was unfortunately never designed to be accessible over https.

https://download.libsodium.org/doc/ is the correct link to documentation, and all instances of doc.libsodium.org should have been replaced with the new URL a long time ago, but maybe some were forgotten.

**Comment by VashaTS** [comment]
Steve Gibson's Security Now! poscast linked to it in its shownotes.

This pdf: https://www.grc.com/sn/sn-537-notes.pdf page 10

**Comment by jedisct1** [comment]
Unfortunately there's not much that can be done to links on web sites unrelated to the project.
But the redirect from doc.libsodium.org to the documentation should be good enough to take care of these links.
Thanks!
