### ISSUE TITLE
Linker error compiling on OSX

### ISSUE THREAD

**Issue by metsfan** [jedisct1/libsodium#343]
When trying to compile from source on OSX, I get a linker error which I cannot seem to figure out.  The error is as follows:

..
  CCLD     libsodium.la
Undefined symbols for architecture x86_64:
  "_randombytes_sysrandom_implementation", referenced from:
      _implementation in libsodium_la-randombytes.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libsodium.la] Error 1
make[2]: *** [check-recursive] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

I did nothing special, just ran autogen, configure, make.  Is this something I am doing wrong, or is this a bug with the project?  I am using the latest commit on the master branch, but I have also tried with the 1.0.8 release. I would like to build this without using homebrew or macports, if possible, as I would also like to cross compile the library for iOS.  I have tried using the dist-build scripts, but I get the same result (_randombytes_sysrandom_implementation symbol can't be found)  Thank you.

**Comment by jedisct1** [comment]
Hi,

What OSX and Xcode versions are you using?

I've never seen anything like that before. Could it be due to a mix of different versions of the same development tools installed on your system?

If you need precompiled binaries for OS and iOS, you can use the one from the [Swift Sodium](https://github.com/jedisct1/swift-sodium) project:
- https://github.com/jedisct1/swift-sodium/blob/master/Sodium/libsodium-ios.a
- https://github.com/jedisct1/swift-sodium/blob/master/Sodium/libsodium-osx.a

**Comment by metsfan** [comment]
XCode version 7.2, iOS SDK version 9.2, OSX Version 10.10 (Yosemite).  I will give the pre-compiled binaries a try.  Thank you.

**Comment by metsfan** [comment]
Some additional info: It appears to be a build configuration issue.  I was able to get the library compiling on OSX by setting --host and --build to "x86_64-unknown-linux-gnu" during configure, but this did not work for iOS.  Hope this helps narrow down the issue, or give you an idea of what the problem might be.  Thanks.

**Comment by jedisct1** [comment]
Can you download a 1.0.8 tarball, run `./configure` (do *not* run `autogen.sh`, keep the existing scripts), and post a gist of the `config.log` as well as the `src/libsodium/Makefile` files?

**Comment by metsfan** [comment]
Thank you for taking the time to look into this.  Here is my config.log

https://gist.github.com/metsfan/1c814820d47aac817956

This is building for OSX.  I can post for iOS as well if you wish, but I have a feeling its the same issue for both platforms

**Comment by jedisct1** [comment]
Looks like the build environment is not sane. It's mixing tools from Xcode with tools from Emscripten.

Try with a clean environment without an `$EMSCRIPTEN` environment variable, and without all these `/Users/adam/*` paths in your `$PATH`.

**Comment by metsfan** [comment]
Ok, I will give that a try, thank you

**Comment by metsfan** [comment]
Ok, I simplified my path and removed the EMSCRIPTEN environment variable and it built!  Thank you so much for your assistance and quick response (and of course for maintaining this awesome library!).  Going to close this now.
