### ISSUE TITLE
No #warning on MSVC

### ISSUE THREAD

**Issue by madebr** [jedisct1/libsodium#344]
Hey,

For the Windows CI of the zeromq and czmq project, the development version of libsodium is used.
Since some time, these builds are failing due to libsodium build failures.

The core of the problem is that the C preprocessor of Visual Studio does not support the
#warning directive. See http://goodliffe.blogspot.be/2009/07/c-how-to-say-warning-to-visual-studio-c.html

https://ci.appveyor.com/project/zeromq/czmq/build/build-291/job/u3au2wbuxjk2knst#L148

**Comment by jedisct1** [comment]
Hi,

This has been fixed, but I would still recommend using the `stable` branch instead.

Thanks!
