### ISSUE TITLE
crypto_stream_aes128ctr_xor not found on iOS

### ISSUE THREAD

**Issue by Gowzancha** [jedisct1/libsodium#345]
My project can't find "crypto_stream_aes128ctr_xor" method in the lib. I'm trying to build my project for iPhone 6 simulator, using xcode 7.2 on OS X EI Capitan 10.11.2. I'm using libsodium 1.0.8, compiled the lib using dist-build/ios.sh script.
I got the same error when I tried to use the precompiled binariy:
https://github.com/jedisct1/swift-sodium/blob/master/Sodium/libsodium-ios.a

undef: _crypto_stream_aes128ctr_xor
Undefined symbols for architecture x86_64:
  "_crypto_stream_aes128ctr_xor", referenced from:
      void Crypto::encrypt<20u>(Buffer<20u>&, Buffer<20u> const&, Vector<unsigned char> const&) const in castor_encrypt_ackauth.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by paragonie-scott** [comment]
* https://github.com/jedisct1/libsodium/blob/fd0c47025f4c07654af2eda053e53324bb07a584/src/libsodium/crypto_stream/aes128ctr/portable/stream_aes128ctr.c#L17
* https://github.com/jedisct1/swift-sodium/blob/master/Sodium/crypto_stream_aes128ctr.h#L39

That's odd. It *should* be available.

**Comment by jedisct1** [comment]
This is expected, as these binaries are compiled in `--enable-minimal` mode.

The minimal mode doesn't include undocumented, untested, rarely used low-level functions that are not used by any high-level API and that will eventually go away.

`crypto_stream_aes128ctr_xor` is:
- Dead slow.
- Undocumented, untested.
- Hard to use securely. It has a small nonce size, and no internal counter. So you need to carefully keep track of how many blocks each message requires.
- The reason to use a 128-bit stream cipher today would be speed + you don't care about your data still being confidential in a couple years. But all other available stream ciphers are faster and have a larger security margin.
- And of course, it doesn't include any authentication tag, so unless you are inventing your own constructions, this is probably not what you are looking for.

Like edwards25519sha512batch, aes128ctr is only present for to provide ABI compatibility with NaCl, and it is not compiled in by the dist-build scripts.
