### ISSUE TITLE
Visual Studio Projects in builds/msvc/vsXXXX

### ISSUE THREAD

**Issue by madebr** [jedisct1/libsodium#346]
Hello,

Thanks for fixing #344.
Are the Visual Studio projects in the builds/msvc/vsXXXX directories maintained?

At the moment, the linking phase fails due to unresolved symbols.

https://ci.appveyor.com/project/zeromq/czmq/build/build-298/job/7nk17n7rn2gjc3gv#L154

Thanks

**Comment by jedisct1** [comment]
The `master` branch contains development code. Windows is not my primary development platform and I can't access a Windows VM during the day.

So there is often a delay between changes being made to the code, that are mainly tested on OSX and OpenBSD, and these being tested on other platforms. The Visual Studio solutions, in particular, are not always updated for newly introduced code that is still a moving target.

These Visual Studio solutions are maintained. They are guaranteed to be up to date and tested in every release, as well as in the `stable` branch. Not in the development branch.
