### ISSUE TITLE
How to derive keys from high entropy input (other keys)

### ISSUE THREAD

**Issue by FSMaxB** [jedisct1/libsodium#347]
`crypto_pwhash_scryptsalsa208sha256` can be used for key derivation, but as I understand it, this is mainly for deriving keys from low entropy inputs like passwords that can potentially be brute forced, so this function is designed to require many CPU cycles and much memory to make brute forcing harder.

But I want to derive a key from another key with a length of `crypto_secretbox_KEYBYTES` that already has high entropy, other than a password. So it should be safe to derive keys without the enormous computational effort.

Can I use `crypto_pwhash_scryptsalsa208sha256` for that purpose? I would use a low `opslimit` (like 1), very few memory (don't know how much) and a constant salt (because the key derivation has to be deterministic). Is this safe to do, or maybe there's a better way to do this?

My current solution is [HKDF](https://tools.ietf.org/html/rfc5869) with `crypto_auth` as HMAC function.

**Comment by jedisct1** [comment]
Unless you need a subkey larger than 512 bits, just use Blake2b, namely `crypto_generichash_blake2b_salt_personal()` with the following parameters:
```
in=NULL
inlen=0
key=the master key
salt=a subkey counter
personal=a uid for your application
```

**Comment by FSMaxB** [comment]
Ok, great. This shouldn't be a problem because `crypto_secretbox_KEYBYTES` is 256 bit.

I have one case where I want to derive something longer, but that's only ever done once by a user, so in that case it isn't a problem that `crypto_pwhash_scryptsalsa208sha256` takes a bit longer.

**Comment by FSMaxB** [comment]
Oh, I just noticed that I **do** have a case where I frequently need more than 512 bits. Namely `2 * crypto_secretbox_KEYBYTES + crypto_aead_chacha20poly1305_KEYBYTES`, because I derive three keys from one.

**Comment by FSMaxB** [comment]
Ah, so that's what the subkey counter is for. Sorry, my bad.

**Comment by jedisct1** [comment]
Yes, that's what the counter is for. Use it to derive any number of subkeys.

**Comment by FSMaxB** [comment]
What do I do when I have multiple input keys? Concatenate them together and hash them with `crypto_generichash` before putting it into `crypto_generichash_blake2b_salt_personal`?

**Comment by jedisct1** [comment]
Yes, that's totally fine.

**Comment by vikram919** [comment]
Hello @FSMaxB , @jedisct1 
I am working to derive keys of 80 byte long from higher order entropy keys > 32byte, can I use `crypto_generichash_blake2b_salt_personal` ? 
Thank you

**Comment by enkore** [comment]
Not directly, no, because BLAKE2b outputs at most 64 bytes.

**Comment by jedisct1** [comment]
Use `randombytes_buf_deterministic()`.
