### ISSUE TITLE
the purpose of the *_easy variants isn't clear in the docs

### ISSUE THREAD

**Issue by oconnor663** [jedisct1/libsodium#349]
It looks like the goal of those is to avoid the need to pad the plaintext with zeroes. If that's right, could we explicitly call that out in the docs?

The docs also mention that it's safe to encrypt a message in-place. Is that an additional difference from the non-easy functions, or from the original NaCl implementation? Or is that just describing a property that all of them have?

**Comment by jedisct1** [comment]
Done, thanks!

The input and output buffers can overlap, even when using the legacy API.

**Comment by oconnor663** [comment]
Thank you!
