### ISSUE TITLE
Library compilation for BlackBerry 10 and/or BlackBerry 6/7

### ISSUE THREAD

**Issue by andreineacsu** [jedisct1/libsodium#352]
Hello,

I would like to compile your library for BlackBerry 10 and/or BlackBerry 6/7. 
Would you be so kind to let me know if this is possible and what would be required? 

Thank you,
Andrei

**Comment by jedisct1** [comment]
Unfortunately I'm not familiar with compiling code for BlackBerry.

But apparently, the native SDK includes `gcc`, which should be enough to build sodium with minor or no changes.

Maybe you should ask on BlackBerry-specific dev forums. There must be standard ways to build libraries initially designed for other systems. The libsodium build system is the Autotools, which is very common.
