### ISSUE TITLE
Missing implementations of crypto_sign_edwards25519sha512batch_{bytes,publickeybytes,secretkeybytes} functions

### ISSUE THREAD

**Issue by dne** [jedisct1/libsodium#356]
The `crypto_sign_edwards25519sha512batch_*` functions were marked deprecated in version 1.0.6, but later the implementations of the `*_{bytes,publickeybytes,secretkeybytes}` functions disappeared (version 1.0.7, commit 2ff0ec3aa1a5d0b6dc3a8d723f8f38fcf7fea82e) , while still being present in the header file.

**Comment by jedisct1** [comment]
These prototypes have been removed in e153debd0ddb40eb308e629dc6d3b22b83f86289 .

Thanks!
