### ISSUE TITLE
Provide SSE3, AVX, and AVX2-optimized ChaCha20 and Poly1305

### ISSUE THREAD

**Issue by DemiMarie** [jedisct1/libsodium#358]
`libsodium` currently only uses SSE2 in its fastest ChaCha20-Poly1305 implementation.  This is a feature request for faster implementations using SSE3, AVX, and AVX2.

**Comment by changloong** [comment]
+1

**Comment by ivmaykov** [comment]
+1

**Comment by enihcam** [comment]
+1
It seems like the Linux kernel has already used AVX2 to optimize ChaCha20.
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=3d1e93cdf16cfe6f315167c65dc504e467e4681a

**Comment by jedisct1** [comment]
Done.

**Comment by ivmaykov** [comment]
This is awesome. ChaCha20 is benchmarking 2x faster for me with this patch on a Haswell Xeon. Can't wait for the 1.0.12 release.

**Comment by jedisct1** [comment]
And Salsa has become just as fast :)

SHA-2 also got 20% faster, which gives a nice speed boost to signatures verification as well.
