### ISSUE TITLE
Document procedure for using Blake2b for key derivation

### ISSUE THREAD

**Issue by drbo** [jedisct1/libsodium#359]
The Blake2b functions in this library can be used to derive keys from high-entropy material, and such use is recommended (see #347).  However, such use is not in the documentation, so this is a request that this use be documented (in part so that users know such use is recommended, and in part so that users know how to do it correctly).

**Comment by paragonie-scott** [comment]
https://github.com/jedisct1/libsodium-doc/blob/master/hashing/generic_hashing.md would probably be the ideal place for this addition, I'd think.

**Comment by jedisct1** [comment]
Documented [here](https://download.libsodium.org/doc/key_derivation.html). Thank you!
