### ISSUE TITLE
ChaCha8 and ChaCha12

### ISSUE THREAD

**Issue by drbo** [jedisct1/libsodium#362]
This is a feature request for ChaCha20/8 and ChaCha20/12.

While ChaCha20/8 and ChaCha20/12 are somewhat redundant to Salsa20/8 and Salsa20/12, I believe that they are less redundant than full-round ChaCha20 is to full-round Salsa20.  The reason is that the best known cryptanalysis that is better than brute-force is on Salsa20/8 and ChaCha20/7.  This gives both ChaCha20 and Salsa20 massive security margins, but the margins for ChaCha20/12 and Salsa20/12 are smaller, and ChaCha20/8 has not been broken while Salsa20/8 has (although the attack is quite thoroughly impractical).  Additionally, ChaCha20 is slightly faster than Salsa20 for the same number of rounds, and any application that uses less than 20 rounds presumably is performance-critical.

**Comment by jedisct1** [comment]
Full-round ChaCha20 is still pretty fast. While reduced-rounds versions are still believed to have a decent security margin, it's probably better to stick to the full-round version only. 

Having different constructions to achieve the same thing, and different variants of the same constructions starts to smell like bloat, which is something this libraries tries to avoid.

Salsa20/8 and Salsa20/12 are not compiled at all in `--enable-minimal` mode, and may eventually go away for the same reason.
