### ISSUE TITLE
Support for AES and GCM instructions on ARM processors

### ISSUE THREAD

**Issue by DemiMarie** [jedisct1/libsodium#363]
Some new ARM processors have hardware support for AES-GCM.  This is a feature request to support AES-GCM on these processors.

**Comment by jedisct1** [comment]
This is in the roadmap, along with other ARM optimized implementations.

Unfortunately I don't have the hardware to work on this yet. The ODROID-C2 is not too expensive and has hardware support for AES. If I can find another need for it, I'll buy one.

**Comment by darakian** [comment]
If an ODroid C1+ has hardware AES I'll donate mine to get this working.

**Comment by darakian** [comment]
The C1+ also seems to have AES support according to this (See pdf page 9)
http://dn.odroid.com/S805/Datasheet/S805_Datasheet%20V0.8%2020150126.pdf

**Comment by jedisct1** [comment]
Hi @darakian ,

That would be fantastic, but it looks like the C1+ has a proprietary crypto engine. It doesn't include the more standard opcodes that were introduced in ARMv8.

**Comment by noloader** [comment]
@jedisct1,

> Unfortunately I don't have the hardware to work on this yet.

You gotta get a Compile Farm account. They have Aarch64 :)

You can find a portable, ARMv8, intrinsics based solution at [AES Intrinsics](https://github.com/noloader/AES-Intrinsics) and [SHA-Intrinsics](https://github.com/noloader/SHA-Intrinsics). The intrinsics work on iOS, Linux and Windows.

The sample code is public domain so there are no encumbrances.

**Comment by jedisct1** [comment]
AES is easy. GCM is more tricky.

**Comment by darakian** [comment]
I've got some AArch64 hardware I can test on if anyone has code for it.

**Comment by jedisct1** [comment]
Thanks a lot, John!

I'm now the proud owner of a Raspberry Pi3, so I can check code on AArch64 as well, but if AArch64 code lands, your help to make sure that it works well on your operating system/distro will still be very appreciated!

**Comment by darakian** [comment]
Sure thing. Tag me or PM me or something so I see a notification and I'll give it a spin.

**Comment by noloader** [comment]
Here is the [carryless multiply for Aarch64](https://github.com/noloader/SHA-Intrinsics/blob/master/clmul-arm.c). Your GMAC will run around 1 cpb.

```
MAYBE_INLINE uint8x16_t PMULL_LOW(const uint8x16_t a, const uint8x16_t b)
{
    uint8x16_t r;
    __asm __volatile("pmull    %0.1q, %1.1d, %2.1d \n\t"
        :"=w" (r) : "w" (a), "w" (b) );
    return r;
}

MAYBE_INLINE uint8x16_t PMULL_HIGH(const uint8x16_t a, const uint8x16_t b)
{
    uint8x16_t r;
    __asm __volatile("pmull2   %0.1q, %1.2d, %2.2d \n\t"
        :"=w" (r) : "w" (a), "w" (b) );
    return r;
}

void clmul_arm(uint8_t r[16], const uint8_t a[16], const uint8_t b[16])
{
    uint8x16_t a8, b8, c8;
    uint8x16_t z, p;
    uint8x16_t r0, r1;
    uint8x16_t t0, t1;

    a8 = vrbitq_u8(vld1q_u8(a));
    b8 = vrbitq_u8(vld1q_u8(b));

    /* polynomial multiply */
    z = vdupq_n_u8(0);
    r0 = PMULL_LOW(a8, b8);
    r1 = PMULL_HIGH(a8, b8);
    t0 = vextq_u8(b8, b8, 8);
    t1 = PMULL_LOW(a8, t0);
    t0 = PMULL_HIGH(a8, t0);
    t0 = veorq_u8(t0, t1);
    t1 = vextq_u8(z, t0, 8);
    r0 = veorq_u8(r0, t1);
    t1 = vextq_u8(t0, z, 8);
    r1 = veorq_u8(r1, t1);

    /* polynomial reduction */
    p = vreinterpretq_u8_u64(vdupq_n_u64(0x0000000000000087));
    t0 = PMULL_HIGH(r1, p);
    t1 = vextq_u8(t0, z, 8);
    r1 = veorq_u8(r1, t1);
    t1 = vextq_u8(z, t0, 8);
    r0 = veorq_u8(r0, t1);
    t0 = PMULL_LOW(r1, p);
    c8 = veorq_u8(r0, t0);

    vst1q_u8(r, vrbitq_u8(c8));
}
```

RPI-3's and ODROID-C2's don't have the optional CRC and Crypto extensions. RPI-3 is the runt of the liter because it runs an armv7hf image. (I have all four of the dev-boards).

You will need a Pine64 or LeMaker HiKey. Or better, sign up for a free account on the [GCC Compile Farm](https://gcc.gnu.org/wiki/CompileFarm). GCC117 and GCC118 are the machines to use because they are Aarch64 and the optional CRC and Crypto.

Here are the features you want to see from `/proc/cpuinfo`:

```
gcc118:~> cat /proc/cpuinfo
processor       : 0 [nid: 0]
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 1 [nid: 0]
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 2 [nid: 0]
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 3 [nid: 0]
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 4 [nid: 0]
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 5 [nid: 0]
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 6 [nid: 0]
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 7 [nid: 0]
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2
```

**Comment by jedisct1** [comment]
Looks like there are intrinsics for `pmull` and `pmull2` (`poly16x8_t vmull_p8` and `poly16x8_t vmull_high_p8`). Any reason to prefer inline assembly instead?

**Comment by jedisct1** [comment]
Rpi3 seems to have the crypto extensions as well. I'm running Pi64 and OpenBSD on it.

**Comment by noloader** [comment]
> Any reason to prefer inline assembly instead?

Early PMULL support was poor. It was easier to use the inline ASM rather than depend on missing intrinsics.

> Rpi3 seems to have the crypto extensions as well

Oh, nice. They must have revised the board.

**Comment by jedisct1** [comment]
timeout

**Comment by odkrys** [comment]
how bout this ?
https://github.com/nsacyber/simon-speck-supercop/blob/master/crypto_aead/aes256gcmv1/dolbeau/armv8crypto/armv8crypto.c
