### ISSUE TITLE
crypto_sign: can smlen be NULL?

### ISSUE THREAD

**Issue by FSMaxB** [jedisct1/libsodium#364]
For `crypto_sign_detached`, `siglen` can be NULL. Is the same true for `crypto_sign`'s `smlen`?

**Comment by jedisct1** [comment]
Yes, this pointer can also be set to `NULL`.

**Comment by FSMaxB** [comment]
And `sm` is also padded with zeroes up to `mlen + crypto_sign_BYTES`?

**Comment by jedisct1** [comment]
Nope. `sm` only contains the message. There is no padding. You don't need to allocate extra space and trim it right after, as in NaCl.

**Comment by FSMaxB** [comment]
So I actually do need `smlen` because I cant just use a buffer that is `mlen + crypto_sign_BYTES` long and expect it to work when trying to verify the signature again?

**Comment by jedisct1** [comment]
You are correct : you don't need `smlen`, and I think the documentation mentions this.

The purpose of `smlen` is to keep a consistent API in case another signature scheme requiring padding is ever implemented.

**Comment by FSMaxB** [comment]
The documentation mentions this for `crypto_sign_detached` but not for `crypto_sign`

**Comment by jedisct1** [comment]
Thanks for reporting this!

I'm going to update the documentation to mention that it also applies to `crypto_sign()`.

**Comment by jedisct1** [comment]
Finally documented. Thanks!
