### ISSUE TITLE
Feature request: implement HKDF per RFC 5869

### ISSUE THREAD

**Issue by ivmaykov** [jedisct1/libsodium#367]
Feature request: could you guys implement the HKDF key-derivation function (see RFC 5869: https://tools.ietf.org/html/rfc5869)?

My use case: I need to be able to derive encryption keys from a primary secret key + per-object secondary key. `derived_key = HKDF(primary_key + per_object_key)` would be an easy way to do this :)

**Comment by jedisct1** [comment]
Hi Ilya,

Blake2 can be used to achieve this.

See https://github.com/jedisct1/libsodium/issues/347

But thanks for the heads up: it really needs to be added to the documentation.

**Comment by ivmaykov** [comment]
@jedisct1 ok, thanks! yes, a documentation section on deriving secondary keys from existing keys would be great.

**Comment by paragonie-scott** [comment]
For example: https://github.com/paragonie/halite/blob/bf95337d07f05fe8b6539fa79a72245b619f766b/src/Util.php#L13-L80
