### ISSUE TITLE
Is RSA-OAEP encryption and RSA-PSS singing supported?

### ISSUE THREAD

**Issue by maiermic** [jedisct1/libsodium#368]

**Comment by jedisct1** [comment]
No. RSA is not supported at all.

**Comment by tarcieri** [comment]
:thumbsup: RSA has been an ongoing source of problems and I am glad libsodium doesn't support it. Just yesterday OpenSSL saw both Bleichenbacher attacks and cache timing attacks against an alleged "constant time" RSA implementation that wasn't.

https://twitter.com/tqbf/status/704709925901987840

> And because we’ll never get people to do that [i.e. use RSA securely], the simpler message is: abandon RSA altogether.

**Comment by paragonie-scott** [comment]
@maiermic Have you considered upgrading to `crypto_box()`? :)

**Comment by maiermic** [comment]
Unfortunately, I have no choice in my current work, but I will consider it next time.
