### ISSUE TITLE
Installing the libsodium.dll on Windows

### ISSUE THREAD

**Issue by RaviTezu** [jedisct1/libsodium#369]
Operating System: Windows 10 Pro 64 bit 
Version of libsodium: libsodium-1.0.8-mingw.tar.gz

Hi,

1. I have downloaded the latest libsodium-1.0.8-mingw.tar.gz from https://download.libsodium.org/libsodium/releases/ and extracted it.

2. I copied the libsodium-win64\bin\libsodium-18.dll into C:\Windows\System32 as libsodium.dll

3. There was a import error "OSError: Couldn't locate nacl lib, searched for libsodium" and this got resolved by following the above two steps. 

I am not sure, whether this is a proper way to install libsodium on Windows. Can someone please confirm this? I was able to install libsodium on mac and linux machines using homebrew and apt-get/yum package managers respectively.  

Thanks,
RaviTeja

**Comment by jedisct1** [comment]
I'm a bit confused here.

What application displayed `OSError: Couldn't locate nacl lib, searched for libsodium`?

**Comment by RaviTezu** [comment]
Hi @jedisct1,
Thanks for the reply. 
I am trying to write some script which needs libsodium and it was giving that error. When I did the above the two steps, it was resolved.

**Comment by jedisct1** [comment]
All good, then!

**Comment by RaviTezu** [comment]
@jedisct1 Thanks :)
