### ISSUE TITLE
make error on debian 7 64

### ISSUE THREAD

**Issue by kaneawk** [jedisct1/libsodium#375]
crypto_generichash/blake2/ref/blake2b-compress-avx2.c: In function ‘blake2b_compress_avx2’:
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: warning: implicit declaration of function ‘_mm256_broadcastsi128_si256’ [-Wimplicit-function-declaration]
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
crypto_generichash/blake2/ref/blake2b-compress-avx2.c:38:5: error: incompatible types when initializing type ‘__m256i’ using type ‘int’
make[3]: *** [crypto_generichash/blake2/ref/libavx2_la-blake2b-compress-avx2.lo] Error 1
make[3]: Leaving directory `/root/tmp/libsodium-1.0.9/src/libsodium'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/tmp/libsodium-1.0.9/src/libsodium'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/tmp/libsodium-1.0.9/src'
make: *** [all-recursive] Error 1

**Comment by kaneawk** [comment]
libsodium 1.0.8 work well.but 1.0.9 can not compiled.

**Comment by jedisct1** [comment]
Hi kaneawk,

Indeed, some ancient old of gcc did not properly define this symbol.

This has been fixed in the `stable` branch, but as a workaround, you can also compile like this:

```bash
env CPPFLAGS="-D_mm256_broadcastsi128_si256=_mm_broadcastsi128_si256" ./configure ...
```

**Comment by kaneawk** [comment]
thank you.
