### ISSUE TITLE
IETF variant of aead_chacha20poly1305 not exposed

### ISSUE THREAD

**Issue by ebfull** [jedisct1/libsodium#377]
The functions `crypto_aead_chacha20poly1305_ietf_encrypt` and `crypto_aead_chacha20poly1305_ietf_decrypt` are exposed by a `sodium.h` include.

The constants `crypto_aead_chacha20poly1305_ietf_ABYTES`, `crypto_aead_chacha20poly1305_ietf_NPUBBYTES` and so on... are not.

**Comment by jedisct1** [comment]
Maybe you installed an older version of the library.

The only difference between the IETF version and the original version is the nonce size.

And even on older versions, you should have `crypto_aead_chacha20poly1305_IETF_NPUBBYTES` and `crypto_aead_chacha20poly1305_NPUBBYTES`. Other constants are the same.

**Comment by ebfull** [comment]
We're using 1.0.8. You're right, `crypto_aead_chacha20poly1305_IETF_NPUBBYTES` is available.

Feel free to close if you think this is already fixed.

**Comment by jedisct1** [comment]
Extra `_IETF_` constants were added in 1.0.9, just for clarity.

You can safely use `crypto_aead_chacha20poly1305_KEYBYTES` and `crypto_aead_chacha20poly1305_ABYTES` with the IETF variant.

**Comment by ebfull** [comment]
Keep in mind, the documentation currently references the lowercase variants of these constants: https://download.libsodium.org/doc/secret-key_cryptography/ietf_chacha20-poly1305_construction.html

Which is why I thought libsodium didn't expose them.

**Comment by jedisct1** [comment]
I've updated the documentation to clarify this.

Thanks!
