### ISSUE TITLE
CMake build

### ISSUE THREAD

**Issue by jakirkham** [jedisct1/libsodium#378]
It would be nice if libsodium could be built using CMake. This would simplify Windows support as their wouldn't be multiple versions of Visual Studio project files required. Also, it could be used just as easily on UNIX platforms (Linux and Mac). There are several forks of libsodium that seem to have tried that, but haven't been updated for many years. Looking into what they have already done would likely provide a good starting point.

**Comment by jedisct1** [comment]
Sorry, there are no plans to replace the current build system.

The current build system has been tested on many environments, and there is no known problem with it, but there are many 3rd party packages and scripts that depend on it.

Some people like GYP, some prefer cmake, some prefer scons, some prefer some more recent ones, some prefer their own. But supporting all of them is complicated and makes testing painful, switching for no good reason to a new one doesn't seem like a good idea and can introduce regressions.

Eventually, what most people will actually use is pre-built packages for their favorite OS/distribution. So, it doesn't make a difference.

**Comment by jakirkham** [comment]
So, actually, I may have an issue with the current system. The problem I have is on Windows I must link to very particular versions of VC so that the library is compatible with my CPython install. CPython only supports a single version of VC for each major minor version. Using CMake would make this trivial. I have to check, but there may be some versions of VC that I need to support that are not included here.

**Comment by jedisct1** [comment]
What version of MSVC is it?

You can probably load one of the existing solutions with it.

**Comment by jakirkham** [comment]
Here's the [list]( https://wiki.python.org/moin/WindowsCompilers ):

* [ ] CPython 2.7 - VC9 - 2008
* [x] CPython 3.4 - VC10 - 2010
* [x] CPython 3.5 - VC14 - 2015

I checked everything I found [here]( https://github.com/jedisct1/libsodium/tree/master/builds/msvc ).

**Comment by jedisct1** [comment]
So, precompiled DLLs for these are already available :)

**Comment by jakirkham** [comment]
That actually doesn't work for me as I am trying to add it to a build system. So, I want to be able to build from source. Given that you have mentioned that there is a way to do this. Would you mind explaining to me how?

**Comment by jedisct1** [comment]
Sure.

Here are the scripts used to build the distributed DLLs: https://github.com/jedisct1/libsodium/tree/master/builds/msvc/build

**Comment by jakirkham** [comment]
That doesn't build with VC 2008 though. Is there a script for that too?

**Comment by jedisct1** [comment]
VC 2008 is completely unsupported, I'm sorry.
Loading the VC 2010 solution might work, but this is completely untested.

**Comment by jakirkham** [comment]
Understood. Thanks for your help.

**Comment by FSMaxB** [comment]
A gripe that I have about the current build system is that there are so many different ways to build for different platforms instead of one solution that works everywhere.

**Comment by jedisct1** [comment]
cmake: this is never going to happen.

I have a branch using Gyp to generate the MSVC solutions, but unlike the current solutions, it requires one configuration per platform. Ideally, they should work the same.

**Comment by FSMaxB** [comment]
Doesn't have to be CMake as far as I'm concerned. I'm glad you are putting in an effort to improve on whats currently there.

Also props for achieving the current state that libsodium provides build scripts for so many platforms.

**Comment by jedisct1** [comment]
Here's what the gyp file looks like: https://gist.github.com/b02b484b2802047e9ce49837c58cb513

The file list and the macros are not up-to-date with the latest code, though. But it was useful to test libsodium on Visual Studio 2008.

The current manually-updated Visual Studio solutions will probably be replaced by this in a future release, as soon as I find a better way than having one configuration per `(target, platform)` tuple.

**Comment by jakirkham** [comment]
Neat, was not familiar with GYP.

> The file list and the macros are not up-to-date with the latest code, though. But it was useful to test libsodium on Visual Studio 2008.

Does this mean VS 2008 is a possibility in the future?

**Comment by SylvainCorlay** [comment]
+1 on having a MSVC 2008 build, pretty much for the same reason: having a binary-compatible version for the windows + Python 2.7 combination.
