### ISSUE TITLE
high-level crypto_pwhash_* API missing in precompiled package

### ISSUE THREAD

**Issue by bwoester** [jedisct1/libsodium#379]
I downloaded v1.0.9 and v1.0.10 from https://download.libsodium.org/libsodium/releases/ and tried to follow the documentation on [Argon2 password storage](https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html#example-2-password-storage).

When I got linker errors (using VC11), I looked at the import libs, and it seems as if both releases did not export `crypto_pwhash_str` and `crypto_pwhash_str_verify`. `crypto_pwhash_argon2i_str` and `crypto_pwhash_argon2i_str_verify` are available though.

I'm not sure if it a mistake in the documentation or what else is going on. Just thought I let you know. :)

**Comment by bitbeans** [comment]
in libsodium-net i also used the argon2i* exports: https://github.com/bitbeans/libsodium-net/blob/3d00ad512c614357dc94f6cbcaeea8e36fa5e01f/libsodium-net/SodiumLibrary.cs#L112

**Comment by jedisct1** [comment]
Hi,

That was fixed in the stable branch, and the precompiled binaries for MSVC have been updated.

Sorry for that :(

**Comment by bwoester** [comment]
No need to be sorry. Thanks for your work. Much appreciated! :)
