### ISSUE TITLE
MSYS2, Windows 7 (64 bit), fails all tests

### ISSUE THREAD

**Issue by Bluebird45** [jedisct1/libsodium#380]
Hi,

I'm stuck on this after searching the past issues. Note that there are no spaces in the path to the files (a cause of this fault for some people). The steps are:

1. Fresh install of Windows 7 (64 bit), and nothing else on the computer.

2. Installed the 64 bit MSYS2 from https://msys2.github.io.

3. Installed the compiler and other tools: `pacman -S git gcc make wget pkg-config libtool autoconf automake`

4. Opened the "MinGW-w64 Win64" shell and cloned the sodium repository.

5. `cd libsodium`

6. `dist-build/msys2-win64.sh`
( both with and without first running `./autogen.sh`)

The compile phase of the script runs without error, but the tests all fail. The binaries produced cause another package to fail but the precompiled binaries work in that other package, indicating that the compile is failing to produce valid binaries. Below is the output. The test log is here: http://91.121.173.204/test-suite.log

Any ideas?

```bash
user@user-PC MINGW64 /c/Users/user/projects
$ cd libsodium

user@user-PC MINGW64 /c/Users/user/projects/libsodium
$ dist-build/msys2-win64.sh
make: *** No rule to make target 'distclean'.  Stop.
checking build system type... x86_64-pc-mingw64
checking host system type... x86_64-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-w64-mingw32-strip... no

[snip snip]

./.libs/lt-aead_aes256gcm.c: In function 'main':
./.libs/lt-aead_aes256gcm.c:318:16: warning: implicit declaration of function '_spawnv' [-Wimplicit-function-declaration]
   rval = (int) _spawnv (_P_WAIT, lt_argv_zero, (const char * const *) newargz);
                ^
./.libs/lt-aead_aes256gcm.c:318:25: error: '_P_WAIT' undeclared (first use in this function)
   rval = (int) _spawnv (_P_WAIT, lt_argv_zero, (const char * const *) newargz);

[snip snip]

Makefile:1692: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/c/Users/user/projects/libsodium/test/default'
Makefile:2171: recipe for target 'check-am' failed
```

**Comment by jedisct1** [comment]
I think the `gcc` package is only designed to develop tools for msys.

Use mingw to build native Windows libraries:

```bash
pacman -S mingw-w64-x86_64-gcc
```

**Comment by Bluebird45** [comment]
Thank you! It now compiles and tests OK, and the other package that has it as a dependency now compiles and tests OK.

The actual steps I now use for creating the compiler environment:

> pacman -S mingw-w64-x86_64-toolchain &nbsp;&nbsp;&nbsp;# install the compiler and some tools. 
> 
> pacman -S autoconf make libtool &nbsp;&nbsp;&nbsp;# install the other necessary tools.
> 

To compile:

> ./autogen.sh
> 
> dist-build/msys2-win64.sh
> 

I did get some warnings though (this is using the stable repo):

> 
>   CCLD     libaesni.la
> libtool: warning: '-version-info/-version-number' is ignored for convenience lib                                                                                                    raries
>   CC       crypto_pwhash/scryptsalsa208sha256/sse/libsse2_la-pwhash_scryptsalsa2                                                                                                    08sha256_sse.lo
>   CC       crypto_onetimeauth/poly1305/sse2/libsse2_la-poly1305_sse2.lo
>   CCLD     libsse2.la
> libtool: warning: '-version-info/-version-number' is ignored for convenience lib                                                                                                    raries
>   CC       crypto_generichash/blake2/ref/libssse3_la-blake2b-compress-ssse3.lo
>   CC       crypto_pwhash/argon2/libssse3_la-argon2-fill-block-ssse3.lo
>   CC       crypto_stream/chacha20/vec/libssse3_la-stream_chacha20_vec.lo
>   CCLD     libssse3.la
> libtool: warning: '-version-info/-version-number' is ignored for convenience lib                                                                                                    raries
>   CC       crypto_generichash/blake2/ref/libsse41_la-blake2b-compress-sse41.lo
>   CCLD     libsse41.la
> libtool: warning: '-version-info/-version-number' is ignored for convenience lib                                                                                                    raries
>   CC       crypto_generichash/blake2/ref/libavx2_la-blake2b-compress-avx2.lo
>   CCLD     libavx2.la
> libtool: warning: '-version-info/-version-number' is ignored for convenience lib                                                                                                    raries
>
