### ISSUE TITLE
crypto_sign_ed25519: Isn't this undefined behavior?

### ISSUE THREAD

**Issue by metadings** [jedisct1/libsodium#381]
We have there in [crypto_sign_ed25519](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_sign/ed25519/ref10/sign.c)

	unsigned char nonce[64];

and some lines later

	crypto_hash_sha512_final(&hs, nonce);

Now I'm not that hard in C, but isn't this undefined behavior, to declare a variable, not initializing it (or initializing it to NULs), and then going to use it?

**Comment by metadings** [comment]
Oh I see there is `unsigned char *out` in `crypto_hash_sha512_final`.

**Comment by jedisct1** [comment]
Hi,

You are correct, `crypto_hash_sha512_final()` puts the hash into the second function parameter.
