### ISSUE TITLE
1.0.10 build problem?

### ISSUE THREAD

**Issue by DannyThomas** [jedisct1/libsodium#382]
This is probably my error.

I had no problems with 1.0.8
With 1.0.10 I had to make a change in my build script to run `./autogen.sh`
(bootstrap scripts like this are not uncommon as auto-generated files
such as `Configure` should not be kept under version control).

    configure.ac:651: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
    If this token and others are legitimate, please use m4_pattern_allow.

Normally such errors happen when people don't have (current) versions of
`auto*` and `libtool`.

I build software outside the normal OS places to avoid any conflict, and make some
 effort to have the latest versions of the build tools visible to the build script. My approach
works with 70+ other software builds, but I can't see what's different in this case.

    0.1:   /bin/bash# cd /opt/uq.cis.work/build.libsodium/libsodium-1.0.10
    0.1:   /bin/bash# export CC=/opt/uq.cis.built/clang/bin/clang
    0.1:   /bin/bash# export CFLAGS=-O2 -m64 -mtune=generic -g -pipe -Wall -fexceptions --param=ssp-buffer-size=4 -fstack-protector-strong
    0.1:   /bin/bash# export CPPFLAGS=-O -D_FORTIFY_SOURCE=2
    0.1:   /bin/bash# /bin/rm /opt/bin/cc
    0.1:   /bin/bash# /bin/rm /opt/bin/gcc
    0.1:   /bin/bash# /bin/rm /opt/bin/c++
    0.1:   /bin/bash# /bin/rm /opt/bin/g++
    0.1:   /bin/bash# /bin/ln -s /opt/bin/bin/clang /opt/bin/cc
    0.1:   /bin/bash# /bin/ln -s /opt/bin/bin/clang /opt/bin/gcc
    0.1:   /bin/bash# /bin/ln -s /opt/bin/bin/clang /opt/bin/c++
    0.1:   /bin/bash# /bin/ln -s /opt/bin/bin/clang /opt/bin/g++
    0.1:   /bin/bash# export AUTOCONF=/opt/uq.cis.built/autoconf/bin/autoconf
    0.1:   /bin/bash# export AUTOHEADER=/opt/uq.cis.built/autoconf/bin/autoheader
    0.1:   /bin/bash# export AUTOM4TE=/opt/uq.cis.built/autoconf/bin/autom4te
    0.1:   /bin/bash# export AUTORECONF=/opt/uq.cis.built/autoconf/bin/autoreconf
    0.1:   /bin/bash# export AUTOSCAN=/opt/uq.cis.built/autoconf/bin/autoscan
    0.1:   /bin/bash# export AUTOUPDATE=/opt/uq.cis.built/autoconf/bin/autoupdate
    0.1:   /bin/bash# export ACLOCAL=/opt/uq.cis.built/automake/bin/aclocal
    0.1:   /bin/bash# export AUTOMAKE=/opt/uq.cis.built/automake/bin/automake
    0.1:   /bin/bash# export CMAKE=/opt/uq.cis.built/cmake/bin/cmake
    0.1:   /bin/bash# export LIBTOOL=/opt/uq.cis.built/libtool/bin/libtool
    0.1:   /bin/bash# export LIBTOOLIZE=/opt/uq.cis.built/libtool/bin/libtoolize
    0.1:   /bin/bash# export M4=/opt/uq.cis.built/m4/bin/m4
    0.1:   /bin/bash# export PATH=/opt/uq.cis.built/cmake/bin:/opt/uq.cis.built/m4/bin:/opt/uq.cis.built/automake/bin:/opt/uq.cis.built/libtool/bin:/opt/uq.cis.built/autoconf/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/uq.cis.pkg/go/bin
    0.1:   /bin/bash# ./autogen.sh
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: /opt/uq.cis.built/automake/bin/aclocal --force -I m4
    autoreconf: configure.ac: tracing
    autoreconf: configure.ac: creating directory build-aux
    autoreconf: configure.ac: not using Libtool
    autoreconf: running: /opt/uq.cis.built/autoconf/bin/autoconf --force
    configure.ac:651: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
    If this token and others are legitimate, please use m4_pattern_allow.
    See the Autoconf documentation.
    autoreconf: /opt/uq.cis.built/autoconf/bin/autoconf failed with exit status: 1

FYI

    /opt/uq.cis.built/autoconf/bin/autoconf  --version
    autoconf (GNU Autoconf) 2.69

Without knowing the real solution I first commented out
 `AC_LIBTOOL_WIN32_DLL` and indeed got further

    libtoolize: copying file 'm4/lt~obsolete.m4'
    autoreconf: running: /opt/uq.cis.built/autoconf/bin/autoconf --force
    autoreconf: configure.ac: not using Autoheader
    autoreconf: running: automake --add-missing --copy --force-missing
    Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /opt/bin/automake line 3936.
    configure.ac:10: error: version mismatch.  This is Automake 1.15,
    configure.ac:10: but the definition used by this AM_INIT_AUTOMAKE
    configure.ac:10: comes from Automake 1.13.4.  You should recreate
    configure.ac:10: aclocal.m4 with aclocal and run automake again.

As suggested I reran the script after making it run `/opt/uq.cis.built/automake/bin/aclocal`
before `autogen.sh`. Thence

    ...
    configure.ac:10: installing 'build-aux/missing'
    src/libsodium/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined
    src/libsodium/Makefile.am:1:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
    src/libsodium/Makefile.am:1:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
    src/libsodium/Makefile.am:1:   If 'LT_INIT' is in 'configure.ac', make sure
    src/libsodium/Makefile.am:1:   its definition is in aclocal's search path.
    src/libsodium/Makefile.am: installing 'build-aux/depcomp'

I'm not sure why `aclocal` was needed before `autogen.sh` as that ends with

    $LIBTOOLIZE && \
    aclocal && \
    automake --add-missing --force-missing --include-deps && \
    autoconf

Any ideas ?
FYI on OracleLinux 7 aka RHEL7
Not that it got as far as the compiler, but that is clang-3.8.0

cheers
Danny Thomas

**Comment by jedisct1** [comment]
Hi Danny,

Nothing has changed in the autoconf script.

It looks like `libtool` has not be installed, or cannot be found in `$PATH`:

    autoreconf: configure.ac: not using Libtool

Looks like you are also mixing different versions of the tools:

    configure.ac:10: error: version mismatch.  This is Automake 1.15,
    configure.ac:10: but the definition used by this AM_INIT_AUTOMAKE
    configure.ac:10: comes from Automake 1.13.4.

Maybe because you have one version in `/opt/uq.cis.built/`, and a different one in `/usr/local`.

I would get rid of all these variables (`AUTOCONF`, `LIBTOOL`, etc) and just set up `$PATH` so that the current versions come first, or uninstall the old versions.

```bash
# export CFLAGS=-O2
# export CPPFLAGS=-O
```

That combination doesn't make sense :)

**Comment by jedisct1** [comment]
Also, use `make distclean` to get rid of old files before trying to regenerate the scripts.

**Comment by DannyThomas** [comment]
On 16 Apr 2016, at 7:09 PM, Frank Denis <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, use make distclean to get rid of old files before trying to regenerate the scripts.

unfortunately I don’t get to the point of generating a Makefile.


I would get rid of all these variables (AUTOCONF, LIBTOOL, etc) and just set up $PATH

so that the current versions come first, or uninstall the old versions.

I think AUTOCONF etc are necessary for some things I build with a nearly identical build script.

Also ‘configure.ac’ does use ‘$LIBTOOLIZE’

The script already sets up $PATH so the versions of Cmake, m4, auto,* libtool I build will be found

PATH=/opt/uq.cis.built/cmake/bin:/opt/uq.cis.built/m4/bin:/opt/uq.cis.built/automake/bin:/opt/uq.cis.built/libtool/bin:/opt/uq.cis.built/autoconf/bin



It looks like libtool has not be installed, or cannot be found in $PATH:

autoreconf: configure.ac: not using Libtool


that went away when I commented out AC_LIBTOOL_WIN32_DLL


My testing yesterday did not always have $PATH set properly as happens

in the build script, so some of the things in the ticket are misleading.


After setting up $PATH, unpacking the tarball, commenting out AC_LIBTOOL_WIN32_DLL

./autogen.sh works up to the point when it tries building the first Makefile in src/

configure.ac:10: installing 'build-aux/missing'
src/libsodium/Makefile.am:1: error: Libtool library used but 'LIBTOOL' is undefined


the first warning from autogen.sh was

autoreconf: configure.ac: not using Gettext


but that didn’t go away after adding it to path

Mind you the OL7 gettext package is installed.

which libtool libtoolize autoreconf automake aclocal gettext
/opt/uq.cis.built/libtool/bin/libtool
/opt/uq.cis.built/libtool/bin/libtoolize
/opt/uq.cis.built/autoconf/bin/autoreconf
/opt/uq.cis.built/automake/bin/automake
/opt/uq.cis.built/automake/bin/aclocal
/opt/uq.cis.built/gettext/bin/gettext


‘configure’ is the one bundled with 07-Jan tarball

‘configure.new’ is the one generated by ‘autogen.sh'

ls -l configure*
-rwxr-xr-x 1 root root 542908 Apr 17 18:52 configure
-rwxr-xr-x 1 root root 291174 Apr 17 18:42 configure.new



Nothing has changed in the autoconf script.

You might not have changed anything (except version), but is github now generating
a different tarball?

I first wondered about this with maxmind/libmaxminddb. I’m not sure what the correct
term is, but that repo includes 2 directories imported from other repos. The unpacked
tarball had empty directories instead of the content from those other repos.

Previously my build script had to download those other 2 repos and move the appropriate
directories inside unpacked libmaxminddb.

However the last time I unpacked the libmaxminddb tarball, those 2 directories
had the correct content instead of being empty. The repo looks the same so I
guessed github itself was responsible.

And yes, the libsodium tarball I downloaded a few months ago is different from
that downloaded today (unless I somehow did the change).
NB previously with 1.0.8 my script started running ‘configure’ not ‘autogen.sh'

from 1.0.8 downloaded today
    libsodium-1.0.8/
    libsodium-1.0.8/.gitignore
    libsodium-1.0.8/.travis.yml
    libsodium-1.0.8/AUTHORS
    libsodium-1.0.8/autogen.sh
    libsodium-1.0.8/ChangeLog
    libsodium-1.0.8/configure.ac
    libsodium-1.0.8/libsodium-uninstalled.pc.in
    libsodium-1.0.8/libsodium.pc.in
    libsodium-1.0.8/libsodium.sln
    libsodium-1.0.8/libsodium.vcxproj
    libsodium-1.0.8/libsodium.vcxproj.filters
    libsodium-1.0.8/LICENSE
    libsodium-1.0.8/logo.png
    libsodium-1.0.8/Makefile.am
    libsodium-1.0.8/README
    libsodium-1.0.8/README.markdown
    libsodium-1.0.8/THANKS
    ...

but from tarball dowloaded on 7-Jan-2016
    libsodium-1.0.8/
    libsodium-1.0.8/aclocal.m4
    libsodium-1.0.8/AUTHORS
    libsodium-1.0.8/autogen.sh
    libsodium-1.0.8/ChangeLog
    libsodium-1.0.8/compile
    libsodium-1.0.8/config.guess
    libsodium-1.0.8/config.sub
    libsodium-1.0.8/configure
    libsodium-1.0.8/configure.ac
    libsodium-1.0.8/depcomp
    libsodium-1.0.8/install-sh
    libsodium-1.0.8/libsodium-uninstalled.pc.in
    libsodium-1.0.8/libsodium.pc.in
    libsodium-1.0.8/libsodium.sln
    libsodium-1.0.8/libsodium.vcxproj
    libsodium-1.0.8/libsodium.vcxproj.filters
    libsodium-1.0.8/LICENSE
    libsodium-1.0.8/ltmain.sh
    libsodium-1.0.8/Makefile.am
    libsodium-1.0.8/Makefile.in
    libsodium-1.0.8/missing
    libsodium-1.0.8/README
    libsodium-1.0.8/README.markdown
    libsodium-1.0.8/THANKS

    ...

**Comment by jedisct1** [comment]
Do not download ZIP files of the repository.

Use releases available from https://download.libsodium.org/libsodium/releases/ or if you check out the Git repository, use the `stable` branch:

```bash
$ git checkout stable
```

Your build environment looks very custom and difficult to reproduce, so it's pretty hard to help here.

**Comment by DannyThomas** [comment]
On 19 Apr 2016, at 12:21 AM, Frank Denis <notifications@github.com<mailto:notifications@github.com>> wrote:


Your build environment looks very custom and difficult to reproduce, so it's pretty hard to help here.

please close the issue
it was a local problem


sorry to waste your time
Danny
