### ISSUE TITLE
Cannot pass code validation when compile with native client newlib toolchain

### ISSUE THREAD

**Issue by meowlab** [jedisct1/libsodium#385]
Hi,
I'm working on a native client application which using libsodium. It works fine when compiling with PNaCl toolchain, but when I trying to compile it with `clang-newlib` toolchain, it cannot pass the compile anymore, the compiler says:
`Validating clang-newlib/Release/xx_unstripped_x86_32.nexe failed`.

So what's the validator?
> The NaCl validator statically analyzes code before running it to make sure it only uses code and data patterns that are permitted and safe.

By invoking the `ncval` under `pepper_xx/tools` to validate generated `nexe` file, it says:
```  
  14b7b1: unrecognized instruction
  14b7e2: unrecognized instruction
Invalid.
```

After many test, I found the validation could be passed only if remove the line `sodium_init();`, and I've searched an issue may related with my issue (https://bugs.chromium.org/p/nativeclient/issues/detail?id=4199).

I believe the issue is caused by inline assembly or something else in `sodium_init`, but I have no ability to investigate it, could you take a look? Thanks!

**Comment by jedisct1** [comment]
I wasn't able to duplicate this (on OSX with `gcc-newlib`, though).

Would you mind sharing the script you are using in order to build the library?

**Comment by jedisct1** [comment]
Can you check if the current code (after https://github.com/jedisct1/libsodium/commit/fbad64f6ef230c5f9b738dcf4559aae2d5d5eaaa) fixes your issue?

**Comment by meowlab** [comment]
Hi @jedisct1, thanks for your rapid respond

Actually `gcc-newlib` was deprecated in pepper_45 SDK ([see here](https://groups.google.com/forum/#!topic/native-client-discuss/J0-QDFZe3XE)), you may need use the latest stable SDK (current is pepper_49) to test it.

You can find my project [here](https://github.com/meowlab/shadowsocks-nacl), just change `VALID_TOOLCHAINS := pnacl` in Makefile to `VALID_TOOLCHAINS := clang-newlib` can reproduce this issue. (openssl and libsodium newlib version need to be installed via webports first).

Seems all version upper than 1.0.3 cannot be installed via naclports, compiler failed like this:
```
randombytes_nativeclient.c:(.text+0x3c): undefined reference to `nacl_secure_random'
collect2: ld returned 1 exit status
```

I will patch the change in commit fbad64f to 1.0.3 and compile it later today, I will let you know if I have any more information.

Thanks for your help~

**Comment by jedisct1** [comment]
Can you check again with the current git code?

`nacl_secure_random` is not available with the newlib toolchain, but the underlying function call `get_random_bytes` is. So https://github.com/jedisct1/libsodium/commit/7a667edbd08be576c77a3cbbc79d51d107776771 may fix your problem.

**Comment by meowlab** [comment]
Hi, I've compiled the code on `master` branch, it passed the validation on arch `i686`, but cannot pass the validation on arch `x86_64`.
Any ideas? Thanks

**Comment by meowlab** [comment]
The validation output is:
```
  194489: improper memory address - bad index
  194499: improper memory address - bad index
  1944a0: improper memory address - bad index
  1944a7: improper memory address - bad index
  1944ae: improper memory address - bad index
  1944f8: improper memory address - bad index
  194531: improper memory address - bad index
  1945b2: improper memory address - bad index
  1945c0: improper memory address - bad index
  1945d6: improper memory address - bad index
  195329: improper memory address - bad index
  19532f: improper memory address - bad index
Invalid.
```

**Comment by jedisct1** [comment]
Can you put the content of the config.log file somewhere?

**Comment by meowlab** [comment]
Sorry I don't know where `config.log` located.

The libsodium can be compiled successfully and installed into toolchain, and my project also can be compiled successfully, the only failed is the compiled ELF cannot pass the nexe validation.

If you want, you can install NaCl SDK and [webports](https://chromium.googlesource.com/webports/), run `./bin/webports extract libsodium`, then go to `src/out/build/libsodium/libsodium-1.0.3`, replace code with master branch code, and run `./bin/webports build libsodium --from-source -t clang-newlib -a x86_64`, you can see the issue happens.

**Comment by jedisct1** [comment]
The `config.log` file should be located in the same folder as the source code. It's generated by the `configure` script.

**Comment by meowlab** [comment]
Ok I found it at another place due to webports's directory design.
You can see it here: http://pastebin.com/hcWgGyt2

**Comment by jedisct1** [comment]
Can you try again with the current code? Don't forget to run `autogen.sh` again.

**Comment by jedisct1** [comment]
I suspect the problem was with SIMD instructions, that NativeClient either doesn't support, or that the validation tool rejects.

These have been disabled in `https://github.com/jedisct1/libsodium/commit/00e156198a6813028045dba03a4b4762be85998b`.

**Comment by meowlab** [comment]
Wow!!! It works!!!!!
Thanks for your hard work, it helps me a lot
