### ISSUE TITLE
Linker Error on OSX - Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by hibento** [jedisct1/libsodium#386]
Hello,

we're trying to use libsodium in a small project of ours (named "he2"). I build libsodium from source using your osx.sh Script in the dist-build folder. The building of our program works, but the linker fails:

    cc keys.o main.o -o he2 -arch x86_64 -mmacosx-version-min=10.8 -march=core2 -L/Users/hibento/Repositories/libsodium/libsodium-osx/lib -flto
    undef: _crypto_sign_verify_detached
    undef: _crypto_sign_detached
    Undefined symbols for architecture x86_64:
     "_crypto_sign_verify_detached", referenced from:
         _decode in main.o
         _verify in main.o
     "_crypto_sign_detached", referenced from:
         _encode in main.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [he2] Error 1

The build script of our program uses the following flags (i.e. the same like in your osx.sh script):

    export OSX_VERSION_MIN=${OSX_VERSION_MIN-"10.8"}
    export OSX_CPU_ARCH=${OSX_CPU_ARCH-"core2"}
    export CFLAGS="-arch x86_64 -mmacosx-version-min=${OSX_VERSION_MIN} -march=${OSX_CPU_ARCH} -I/Users/hibento/Repositories/libsodium/libsodium-osx/include -flto"
    export LFLAGS="-arch x86_64 -mmacosx-version-min=${OSX_VERSION_MIN} -march=${OSX_CPU_ARCH} -L/Users/hibento/Repositories/libsodium/libsodium-osx/lib -flto"

Are we missing something? Further notice: During the build of libsodium there was an error regarding a missing "endian.h" file, we use this file (https://gist.github.com/yinyin/2027912).

**Comment by jedisct1** [comment]
```bash
cc keys.o main.o -o he2 -arch x86_64 -mmacosx-version-min=10.8 -march=core2 -L/Users/hibento/Repositories/libsodium/libsodium-osx/lib -flto
```

Looks like you are not linking the library here! Isn't `-lsodium` missing?

Also don't forget to call `sodium_init()` before anything else.

**Comment by hibento** [comment]
@jedisct1 Okay, I forgot to mention that our program he2 uses a makefile, where the `-lsodium` is included. **But** there was another error, the make file overwrites the previously defined LFLAGS, fixing that everything works perfectly. Thanks a lot for the quick help.
