### ISSUE TITLE
crypto_scalarmult_BYTES or crypto_box_PUBLICKEYBYTES?

### ISSUE THREAD

**Issue by jamesruan** [jedisct1/libsodium#389]
I'm working on a wrapper of libsodium in Golang.
I use the static typing feature in Go to improve data size and data relationship check.

Instead of using generic `[]byte`, I use `BoxPublicKey` and `BoxSecretKey` for the API.
This will helps prevent accidentally miscoded use. It works fine so far, until...

I'm looking at the DH Key Exchanging functions which provides X25519. It has key length defined by constant `crypto_scalarmult_BYTES` and `crypto_scalarmult_SCALARBYTES`. However, the only possible key in used are box keys, which is also in X25519, but in different key length constants (`crypto_box_PUBLICKEYBYTES` and `crypto_box_SECRETKEYBYTES`). This inconsistency in naming impose the user to do a type casting between two type of data and responsible for possible inconsistency in the constant value. I don't see it good. It just a disorientation from the purpose that  abstracting the hard-coded number away from user by using named constants.

So why using two different name for a same X25519 key?

If there's a need for a uniform-named X25519 key, which one should be used?

**Comment by jedisct1** [comment]
This is merely for consistency. `crypto_box()` is expecting X25519 keys.

But `crypto_box_keypair()` and `crypto_box_seed_keypair()` is how they are usually computed. They avoid misuse by ensuring that the secret key is random, or, for the deterministic version, that the seed is hashed before use.

The output (`crypto_box_KEYBYTES`) should be seen as an opaque type.

Calling `scalarmult` is useful with AEAD constructions, not so much with `crypto_box` that already has dedicated functions for key generation.
