### ISSUE TITLE
Are the non-crypto_box_{after,before}nm just convenience APIs?

### ISSUE THREAD

**Issue by lvh** [jedisct1/libsodium#391]
I'm writing a Clojure binding for libsodium. I was wondering if there's any difference (other than the obvious "you go through libffi twice if you're binding") between using the `_beforenm`/`_afternm` box APIs to precompute (even in the non-precomputed API) case, or if they're supposed to be literally the same? 

I think my binding will probably just call the most direct libsodium API, but I was wondering if it actually mattered. Previously, I was binding to kalium, which apparently always calls the _beforenm/_afternm API when creating a "Box" object.

**Comment by jedisct1** [comment]
Hi,

The non-precomputed API is just sequentially calling `_beforenm` and `_afternm`.
This is indeed a convenience API.

**Comment by lvh** [comment]
Perfect, thanks!
