### ISSUE TITLE
crypto_scalarmult_base extremely slow?

### ISSUE THREAD

**Issue by theakman2** [jedisct1/libsodium#394]
Up until now I've been using floodyberry's library for curve25519 key exchange (https://github.com/floodyberry/curve25519-donna), but I decided to try out this library because the API looks beautifully simple.

For some reason though, the crypto_scalarmult_base function is exceptionally slow for me. I put together a little test program compiled against libsodium 1.0.10:

```
#include <stdio.h>
#include <time.h>

#include <sodium.h>

static double now(void) {
	struct timespec t;
	clock_gettime(CLOCK_MONOTONIC, &t);
	return (t.tv_sec*1000000000ULL + t.tv_nsec)/1000000000.0;
}

int main(void) {
	if (sodium_init() < 0) {
		puts("ERROR");
		return 1;
	}
	int iterations = 1500;

	unsigned char pri[32];
	randombytes_buf(pri, sizeof(pri));

	unsigned char pub[32];

	double t = now();
	for (int i = 0; i < iterations; ++i) {
		crypto_scalarmult_base(pub, pri);
	}
	t = now() - t;

	printf("Time taken for %d iterations: %f seconds (%f ns each)\n", iterations, t, 1000000000.0*(t/iterations));

	return 0;
}
```
I then compiled this with:

`gcc test.c -lsodium`

This is what I get when I run it:

`Time taken for 1500 iterations: 5.888849 seconds (3925899.086001 ns each)`

I'm running Xubuntu 16.04 on a machine with a Haswell E3-1231 v3 and 32GB memory so I was hoping for thousands of scalarmults per second, not hundreds.

Do you have any idea why this particular function might be so slow on my machine?

**Comment by theakman2** [comment]
In case it's helpful, I compiled and installed libsodium fairly standardly as follows:

```
make -j4
make -j4 check
sudo make install
```

I also tried compiling my benchmarking program with `gcc -O3 -flto -march=native -mtune=native test.c -lsodium`. This didn't help unfortunately.

**Comment by jedisct1** [comment]
Hi,

Is that on bare metal or going through an hypervisor?

**Comment by theakman2** [comment]
Bare metal. I should correct myself though - the CPU is a E3-1231 v3, not a 1270. I'll update the main post.

**Comment by theakman2** [comment]
I have access to a laptop running Lubuntu 16.04 with a Sandy Bridge i7-2630QM. I'll install libsodium on that and see if the benchmarking program reports anything different.

**Comment by jedisct1** [comment]
64 bit Ubuntu?

To be honest, I have no idea. I ran your test code on slower platforms and it completed orders of magnitude faster.

Do you get the same results when using the standard Ubuntu package?

**Comment by theakman2** [comment]
Yes, both machines are running 64 bit Ubuntu. Floodyberry's library is also orders of magnitude faster so I'm pretty surprised.

**Comment by theakman2** [comment]
I just ran it on the laptop with Lubuntu 16.04/Sandy Bridge i7-2630QM. I get:

`Time taken for 1500 iterations: 8.199102 seconds (5466067.874004 ns each)`

A little slower than I was hoping. I'll try it on the standard Ubuntu package.

**Comment by theakman2** [comment]
I'm still installing Ubuntu 16.04, but in the meantime I tried compiling the benchmark program with clang 3.8 on the E3-1231 machine and the i7-2630QM laptop. It made no difference - still extremely slow.

I also tried running it on a Linux Mint 14.04 machine with an Intel Q9300. On this machine I get:

`Time taken for 1500 iterations: 0.215768 seconds (143845.415335 ns each)`

That's more like it. It could be something in 16.04 that's causing the problem? Let's see what happens when standard Ubuntu 16.04 is installed.

**Comment by theakman2** [comment]
I just installed standard Ubuntu 16.04 (64 bit) on the E3-1231 machine. Still very slow:

```
ubuntu@ubuntu:/tmp$ uname -a
Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ubuntu:/tmp$ uname -i
x86_64
ubuntu@ubuntu:/tmp$ ./a.out 
Time taken for 1500 iterations: 5.945523 seconds (3963682.071333 ns each)
ubuntu@ubuntu:/tmp$ gcc --version
gcc (Ubuntu 5.3.1-14ubuntu2) 5.3.1 20160413
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I'm going to try updating to GCC 6 and also running it on a Ubuntu 14.04 machine. Do you have any thoughts about what's going on? I'd really like to use libsodium but I can't with this level of performance.

**Comment by theakman2** [comment]
Updating to GCC 6 made no difference:

```
ubuntu@ubuntu:/tmp$ gcc-6 --version
gcc-6 (Ubuntu 6.1.1-2ubuntu12~16.04) 6.1.1 20160510
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ubuntu@ubuntu:/tmp$ gcc-6 test.c /usr/local/lib/libsodium.a 
ubuntu@ubuntu:/tmp$ ./a.out 
Time taken for 1500 iterations: 5.920696 seconds (3947130.590667 ns each)
ubuntu@ubuntu:/tmp$ gcc-6 -O3 -march=native -mtune=native test.c /usr/local/lib/libsodium.a 
ubuntu@ubuntu:/tmp$ ./a.out 
Time taken for 1500 iterations: 5.975159 seconds (3983439.501333 ns each)
```

**Comment by jedisct1** [comment]
Can you post the config.log file somewhere?

**Comment by theakman2** [comment]
I just ran Xubuntu 15.10 on the E3-1231 machine:

```
xubuntu@xubuntu:/tmp$ ./a.out 
Time taken for 1500 iterations: 0.087748 seconds (58498.614667 ns each)
```
So this is working as expected. The config.log for this install is attached. I'll attach the config.log from a problematic install shortly.
[config.xubuntu1504working.log.txt](https://github.com/jedisct1/libsodium/files/264980/config.xubuntu1504working.log.txt)

**Comment by theakman2** [comment]
I just ran a fresh Xubuntu 16.04 install on the E3-1231 machine:

```
xubuntu@xubuntu:/tmp$ ./a.out 
Time taken for 1500 iterations: 5.797794 seconds (3865195.727333 ns each)
```
The config.log for this install is attached.
[config.xubuntu1604failing.log.txt](https://github.com/jedisct1/libsodium/files/264993/config.xubuntu1604failing.log.txt)

**Comment by theakman2** [comment]
This is interesting:

```
xubuntu@xubuntu:/tmp$ gcc test.c /usr/local/lib/libsodium.a
xubuntu@xubuntu:/tmp$ ./a.out 
Time taken for 1500 iterations: 5.743738 seconds (3829158.876667 ns each)
xubuntu@xubuntu:/tmp$ gcc test.c /usr/local/lib/libsodium.a -static
xubuntu@xubuntu:/tmp$ ./a.out 
Time taken for 1500 iterations: 0.059995 seconds (39996.997333 ns each)
xubuntu@xubuntu:/tmp$ 
```

**Comment by jedisct1** [comment]
Glad to see that `-static` fixed your issue.

Does dynamic linking give the same performance figures?

**Comment by jedisct1** [comment]
Still, mixing static and shared libraries should work, at least on Linux.
But directly adding `/usr/local/lib/libsodium.a` to the command line looks clunky. Maybe try:
```bash
$ gcc test.c -Wl,-Bstatic -lsodium -Wl,-Bdynamic
```

**Comment by theakman2** [comment]
On the i7-2630QM laptop:
```
a@axn:/tmp$ gcc test.c -lsodium
a@axn:/tmp$ ./a.out 
Time taken for 1500 iterations: 8.019348 seconds (5346232.186673 ns each)
a@axn:/tmp$ gcc test.c -lsodium -static
a@axn:/tmp$ ./a.out 
Time taken for 1500 iterations: 0.162026 seconds (108017.218668 ns each)
a@axn:/tmp$ gcc test.c -Wl,-Bstatic -lsodium -Wl,-Bdynamic
a@axn:/tmp$ ./a.out 
Time taken for 1500 iterations: 8.000094 seconds (5333395.750669 ns each)
a@axn:/tmp$ 
```
Maybe there's something problematic about the shared libc library on 16.04? Dynamically linking works on the Linux Mint 14.04 and Xubuntu 15.10 machines.

**Comment by jedisct1** [comment]
I spent the time to download and install Xubuntu 16.04, and I was unable to reproduce this, both with the standard Ubuntu package and with a hand-compiled one :(

**Comment by jedisct1** [comment]
Maybe try with `--disable-pie` and `--disable-ssp`. Or even with `--disable-asm`. But there must be something peculiar about your system.

**Comment by theakman2** [comment]
It does look to be something strange about the Linux 16.04 installs on the E3-1231 and i7-2630QM systems. I just compiled it on the E3-1231 machine on a Windows 7 install and it runs at the right speed. I also ran it on the Q9300 machine on Xubuntu 16.04 and it also runs at the right speed.

**Comment by theakman2** [comment]
Compiling with --disable-asm makes it run much faster, but now the library isn't using optimised routines.

**Comment by jedisct1** [comment]
Sorry, I give up. I don't know what's going on, I can't reproduce this, I don't have this hardware, and the difference between static and dynamic linking doesn't make any sense to me.

The speed difference between the assembly version and the one using intrinsics is fairly small, so if `--disable-asm` works for you, you can use that as a workaround.

If you ever find more clues about what is possibly going on, it would be wonderful if you could share them. Meanwhile, I give up, there's nothing I can do.

**Comment by jedisct1** [comment]
Still, can you check that the results are correct in spite of the slowdown?

I'm currently checking the initialization of all registers being used in a loop.

**Comment by theakman2** [comment]
How would I check the results are correct? I always ran `make -j4 check` when I compiled libsodium and it always passed.

Although it does look to be an issue with my machine, it's curious that I've not experienced any slowdowns with other libraries, and floodyberry's library executes at the expected speed.

**Comment by theakman2** [comment]
In case it's helpful, here is an `oprofile` summary on the i7-2630QM machine (Lubuntu 16.04). It does look to be `ladder_base_loop` that's causing the problem.

```
a@axn:/tmp$ gcc test.c -lsodium
a@axn:/tmp$ readelf -d ./a.out 

Dynamic section at offset 0xe18 contains 25 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libsodium.so.18]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x4006e0
 0x000000000000000d (FINI)               0x400a84
 0x0000000000000019 (INIT_ARRAY)         0x600e00
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x600e08
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x400298
 0x0000000000000005 (STRTAB)             0x400480
 0x0000000000000006 (SYMTAB)             0x4002d0
 0x000000000000000a (STRSZ)              291 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x601000
 0x0000000000000002 (PLTRELSZ)           192 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x400620
 0x0000000000000007 (RELA)               0x400608
 0x0000000000000008 (RELASZ)             24 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x4005c8
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x4005a4
 0x0000000000000000 (NULL)               0x0
a@axn:/tmp$ operf ./a.out 
Kernel profiling is not possible with current system config.
Set /proc/sys/kernel/kptr_restrict to 0 to collect kernel samples.
operf: Profiler started
Time taken for 1500 iterations: 8.441261 seconds (5627507.428000 ns each)

Profiling done.
a@axn:/tmp$ opreport --demangle=smart --symbols ./a.out 
Using /tmp/oprofile_data/samples/ for samples directory.
CPU: Intel Sandy Bridge microarchitecture, speed 2900 MHz (estimated)
Counted CPU_CLK_UNHALTED events (Clock cycles when not halted) with a unit mask of 0x00 (No unit mask) count 100000
samples  %        image name               symbol name
233543   99.8358  libsodium.so.18.0.1      ._ladder_base_loop
214       0.0915  libsodium.so.18.0.1      ._loop
130       0.0556  no-vmlinux               /no-vmlinux
19        0.0081  libsodium.so.18.0.1      crypto_scalarmult_curve25519_sandy2x_fe51_mul
5         0.0021  libsodium.so.18.0.1      crypto_scalarmult_curve25519_sandy2x_base
5         0.0021  libsodium.so.18.0.1      crypto_scalarmult_curve25519_sandy2x_fe51_nsquare
3         0.0013  libsodium.so.18.0.1      ._ladder_base_small_loop
3         0.0013  libsodium.so.18.0.1      ._reduceloop
2        8.5e-04  libsodium.so.18.0.1      crypto_scalarmult_curve25519_sandy2x_ladder_base
1        4.3e-04  ld-2.23.so               _dl_allocate_tls_init
1        4.3e-04  ld-2.23.so               strlen
1        4.3e-04  libsodium.so.18.0.1      crypto_scalarmult_curve25519_sandy2x_fe51_invert
a@axn:/tmp$ gcc test.c -lsodium -static
a@axn:/tmp$ readelf -d ./a.out 

There is no dynamic section in this file.
a@axn:/tmp$ operf ./a.out 
Kernel profiling is not possible with current system config.
Set /proc/sys/kernel/kptr_restrict to 0 to collect kernel samples.
operf: Profiler started
Time taken for 1500 iterations: 0.123226 seconds (82150.884667 ns each)

Profiling done.
a@axn:/tmp$ opreport --demangle=smart --symbols ./a.out 
Using /tmp/oprofile_data/samples/ for samples directory.
CPU: Intel Sandy Bridge microarchitecture, speed 2900 MHz (estimated)
Counted CPU_CLK_UNHALTED events (Clock cycles when not halted) with a unit mask of 0x00 (No unit mask) count 100000
samples  %        image name               symbol name
2029     89.4227  a.out                    ._ladder_base_loop
206       9.0789  a.out                    ._loop
11        0.4848  a.out                    crypto_scalarmult_curve25519_sandy2x_fe51_mul
10        0.4407  no-vmlinux               /no-vmlinux
7         0.3085  a.out                    ._ladder_base_small_loop
2         0.0881  a.out                    crypto_scalarmult_curve25519_sandy2x_fe51_nsquare
1         0.0441  a.out                    ___printf_fp
1         0.0441  a.out                    crypto_scalarmult_curve25519_sandy2x_fe51_invert
1         0.0441  a.out                    main
1         0.0441  a.out                    ptmalloc_init.part.7
```

**Comment by jedisct1** [comment]
Ah, it might be these CPUs with slow CLMUL.

**Comment by theakman2** [comment]
If it was an issue with a slow instruction though, surely it wouldn't be ~80x slower than it should be? And it should be just as slow on any OS on that hardware regardless of how it's compiled. However the benchmark completes very quickly on a fresh Xubuntu 15.04 install, on Windows 7 and when compiled statically. I'm genuinely stumped.

**Comment by jedisct1** [comment]
Asm code is not used on Windows, and ancient Ubuntu kernels have `OSXSAVE` support, so the assembly implementation is not used either.

**Comment by jedisct1** [comment]
Can you confirm that f361d1ccecce3330cbb4f534f6b91dc7d0eb8d67 fixes this?

**Comment by jedisct1** [comment]
Or rather https://github.com/jedisct1/libsodium/commit/263101cfaf8c33f47c4ab806a1d95e5c1b39408b

**Comment by theakman2** [comment]
I just checked out the master branch. The problem seems to have been fixed:

```
a@axn:/tmp$ gcc test.c -Wl,-Bstatic -lsodium -Wl,-Bdynamic
a@axn:/tmp$ readelf -d ./a.out 

Dynamic section at offset 0x17e28 contains 24 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x4009b0
 0x000000000000000d (FINI)               0x415254
 0x0000000000000019 (INIT_ARRAY)         0x617e10
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x617e18
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x400298
 0x0000000000000005 (STRTAB)             0x400558
 0x0000000000000006 (SYMTAB)             0x4002b8
 0x000000000000000a (STRSZ)              310 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x618000
 0x0000000000000002 (PLTRELSZ)           624 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x400740
 0x0000000000000007 (RELA)               0x400728
 0x0000000000000008 (RELASZ)             24 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x4006c8
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x40068e
 0x0000000000000000 (NULL)               0x0
a@axn:/tmp$ ./a.out 
Time taken for 1500 iterations: 8.007415 seconds (5338276.412000 ns each)
a@axn:/tmp$ gcc test.c ./libsodium/src/libsodium/.libs/libsodium.a
a@axn:/tmp$ readelf -d ./a.out 

Dynamic section at offset 0x1ce28 contains 24 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x400b20
 0x000000000000000d (FINI)               0x41a504
 0x0000000000000019 (INIT_ARRAY)         0x61ce10
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x61ce18
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x400298
 0x0000000000000005 (STRTAB)             0x4005e8
 0x0000000000000006 (SYMTAB)             0x4002b8
 0x000000000000000a (STRSZ)              374 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000003 (PLTGOT)             0x61d000
 0x0000000000000002 (PLTRELSZ)           768 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x400820
 0x0000000000000007 (RELA)               0x400808
 0x0000000000000008 (RELASZ)             24 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x4007a8
 0x000000006fffffff (VERNEEDNUM)         1
 0x000000006ffffff0 (VERSYM)             0x40075e
 0x0000000000000000 (NULL)               0x0
a@axn:/tmp$ ./a.out 
Time taken for 1500 iterations: 0.152968 seconds (101978.798000 ns each)
```
Thanks a lot for this! I'm looking forward to the next release.
