### ISSUE TITLE
cpuid avx2 detection broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [jedisct1/libsodium#395]
Using pysodium, I am seeing less than expected speed:
```
speedup sha256 -> sha512: 1.4616587679833115
speedup sha256 -> blake2b: 1.5823430737200959
speedup sha512 -> blake2b: 1.0825666758755845  <-- should be ~3
```
The numbers come from just hashing a big amount of data with python3.5 stdlib sha256/512 and pysodium crypto_generichash - cpu is a i5-4200u, linux 64bit, source code:

[hash_speed.py.txt](https://github.com/jedisct1/libsodium/files/266605/hash_speed.py.txt)

I first thought this is maybe caused by a slow blake2b in libsodium 1.0.8 in ubuntu and I manually compiled / installed libsodium 1.0.10 - but it doesn't get faster.

```
$ ldconfig -p|grep sodium
	libsodium.so.18 (libc6,x86-64) => /usr/local/lib/libsodium.so.18
	libsodium.so.18 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libsodium.so.18
	libsodium.so (libc6,x86-64) => /usr/local/lib/libsodium.so
```

https://blake2.net/ says blake2b should be about 3x faster than sha512 (and I read about the "record setting blake2b" in libsodium >= 1.0.9), so what's going wrong here?

**Comment by ThomasWaldmann** [comment]
Absolute speed value: speed blake2b cgh: 525.720984 MB/s - Haswell i5 CPU running at 2.6GHz.

So, not bad, but also not quite as high as expected.

Also: did get sha512 faster since the comparison graphics on blake2.net was made?

**Comment by jedisct1** [comment]
Maybe the Python bindings have some overhead, and it also depends on the message size, and obviously on the SHA2 implementation.

Quick benchmark of the library itself (Macbook 2013, 2.8 Ghz i7):

* [sha512 benchmark](https://gist.github.com/aac6e6219549a0ee9eca540326286146) ([source code](https://gist.github.com/87e6fbd2755192aa1711bb3dd8d1cea8))
* [blake2 benchmark](https://gist.github.com/6ec3cff15e6ca68aef263b254237459e) ([source code](https://gist.github.com/8a04226d3285f445eb95b2f64a53a708))

So it's about 2.45 times faster here. 

That said, BLAKE2 has major advantages over SHA2 beyond speed.

It is not vulnerable to length extension attacks. So it doesn't require extra care, or double hashing.

It is keyed, so you don't need to use the HMAC construction. So only one pass is required, unlike HMAC-SHA2 that requires hashing twice.

BLAKE2 personalization can be used to derive keys without using the HKDF construction. Whereas HKDF-SHA2 also requires hashing twice.

**Comment by ThomasWaldmann** [comment]
Didn't look into pysodium yet about the overhead, but I am not aware of my cython binding having significant overhead (esp. there is no memcpy or something for the whole input data) - both gave same speed.

About your benchmark code: as you always use the same 64KB input, that will comfortably sit in some CPU cache (while my huge 500MB data in my benchmark needs to be read from memory).

So, I guess the numbers from blake2.net might be meant without memory overhead, with all the data already sitting in some cpu cache.

Still strange that the advantage of blake2b over sha512 shrinks to only 8% - is memory that slow?

**Comment by ThomasWaldmann** [comment]
I used your benchmark code, seems to run against a wall at 520MB/s (above 8 block size) - so it is not a CPU cache effect because I also got that speed with bigger amounts of data.

Are you sure that the super fast blake2b in 1.09+ is actually active? I am asking because 1.0.8 vs. 1.0.10 did not make a difference here (with your benchmark code). Or does it need any special code to activate?

**Comment by jedisct1** [comment]
You obviously need to call `sodium_init()`, but the Python library probably already does this for you.
And your CPU has to support the AVX2 instruction set (that some hypervisors disable).

**Comment by ThomasWaldmann** [comment]
I is a haswell i5, cpuflags have avx2 and I am not running inside a VM.

**Comment by ThomasWaldmann** [comment]
Hmm, ldd on the binary says it always uses the lib from /usr/local (which is 1.0.10), no matter what I give with -I and -L.

**Comment by ThomasWaldmann** [comment]
```
sodium_runtime_has_avx2: 0   <- WAT!? (I added the resp. call to your code).
```

```
(env)tw@tux:~/w/borg$ cat /proc/cpuinfo | head -n 20
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 69
model name	: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
stepping	: 1
microcode	: 0x1d
cpu MHz		: 1102.203
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
# avx2 is close to EOL ^^^
```

**Comment by jedisct1** [comment]
What does this print? https://gist.github.com/c9a36d0a6bff51f5f28d37763f9840ba

**Comment by ThomasWaldmann** [comment]
```
7fdafbbf
10000000
8000000
```

**Comment by jedisct1** [comment]
What distro / kernel are you running?

**Comment by ThomasWaldmann** [comment]
Ubuntu 16.04 64bit, currently a self-made 4.5.4 kernel.

**Comment by ThomasWaldmann** [comment]
found it! update coming...
