### ISSUE TITLE
Unable to compile aead_aes256gcm_aesni.c: immintrin.h missing

### ISSUE THREAD

**Issue by Toxe** [jedisct1/libsodium#401]
I am unable to compile libsodium 1.0.10 because my compiler seems to be too old (GCC 4.3.4) and I am missing immintrin.h.

I get an error when compiling aead_aes256gcm_aesni.c:

> crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c:23:23: error: immintrin.h: No such file or directory
> crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c:48: error: expected specifier-qualifier-list before ‘__m128i’
> crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c:52: error: expected declaration specifiers or ‘...’ before ‘__m128’
> crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c: In function ‘aesni_key256_expand’:
> crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c:54: error: ‘__m128’ undeclared (first use in this function)
> [snip 500+ lines]
> crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c:796: error: expected expression before ‘)’ token
> crypto_aead/aes256gcm/aesni/aead_aes256gcm_aesni.c:796: error: expected expression before ‘)’ token
> make[3]: *** [crypto_aead/aes256gcm/aesni/libaesni_la-aead_aes256gcm_aesni.lo] Error 1
> make[2]: *** [all-recursive] Error 1
> make[1]: *** [all-recursive] Error 1
> make: *** [all-recursive] Error 1

Is there any way to skip compiling this file? Any configure options?

You can find the whole configure config.log file here:
[config-log.txt](https://github.com/jedisct1/libsodium/files/283954/config-log.txt)

**Comment by jedisct1** [comment]
Hi Toxe,

Does https://github.com/jedisct1/libsodium/commit/9c12da0362d3c03a34a77586704d17a9a7ece672 fix your compilation issue?

**Comment by Toxe** [comment]
It worked, thanks a lot! That was pretty fast. :-)

**Comment by jedisct1** [comment]
Out of curiosity, what Linux distro is that?

**Comment by Toxe** [comment]
According to /etc/SuSE-release:

> SUSE Linux Enterprise Server 11 (x86_64)
> VERSION = 11
> PATCHLEVEL = 3
