### ISSUE TITLE
incremental AEAD API

### ISSUE THREAD

**Issue by DemiMarie** [jedisct1/libsodium#402]
This is a feature request for an incremental AEAD API.

Specific features of the API:

- No decrypted but unauthenticated plaintext is revealed.
- The amount of data that must fit in memory is bounded.
- Each chunk authenticates not only itself, but also all previous chunks.
- Truncation is detected and a return code distinct from that of forgery is given.
- Forged chunks are rejected.  This may or may not cause all future data to be rejected.
- Both public and secret key versions should be provided.

I am thinking of something based on incremental hashing of authentication tags.

The reason for this feature request is that this is often what application developers actually need: a way to send streams of encrypted and authenticated data.  Good examples are:

- encrypting and authenticating a 1TB backup (much larger than available RAM) to an untrusted cloud service, along with some metadata, in such a way that &ndash; if an error occurs &ndash; the portion that was successfully transmitted can be recovered.
- a long-running computation sending intermediate results to an untrusted remote disc.

In both cases, TLS is not applicable, because TLS requires that two parties agree to a single key.  Here the objective is sending data to an untrusted storage platform in a streaming fashion, such that the data that has been sent so far can be recovered even if the transfer is interrupted mid-stream, and with all data sent successfully guaranteed authentic.  Storing all data in temporary storage is not an option either: the data can be larger than available free trusted storage.

While no existing library that I know of provides this, this is something that application developers have no choice but to create themselves as a result.  Since there are probably many pitfalls, this is something that would be useful for libsodium to provide.

**Comment by jedisct1** [comment]
[Blobcrypt](https://github.com/jedisct1/blobcrypt) may be close to what you describe.

[StreamCryptor](https://github.com/bitbeans/StreamCryptor) is also an excellent option if you are using .NET.

**Comment by tarcieri** [comment]
> I am thinking of something based on incremental hashing of authentication tags.

Please don't invent your own scheme for this. Phil Rogaway has already done that for us:

https://eprint.iacr.org/2015/189

The STREAM construction leverages the AD portion of AEAD to provide a safe primitive for building streaming AEAD.

**Comment by jedisct1** [comment]
blobcrypt was made to solve a specific problem (seekable file encryption), and to prototype a platform-independent API for online encryption. It is a distinct project, and will remain so.

There is a real need for online encryption, and several good proposals, such as STREAM. But as of today, there are no standards (either IETF documents, drafts, or de-facto standards). This is likely to change soon, but until then, OE schemes built on sodium primitives shall remain external projects.
