### ISSUE TITLE
.gitignore is ignoring too much

### ISSUE THREAD

**Issue by paixaop** [jedisct1/libsodium#403]
Hi 

I'm the developed of node-sodium and I have an issue when packaging the node-sodium for distribution. 
The .gitignore file in the master is ignoring `libsodium-*` which excludes `libsodium-uninstalled.pc.in` and `libsoidum.pc`. 
The node npm tool looks at the `.gitignore` files and automatically excludes all files ignore by git. Therefore these files are not included in the package and make libsodium fails, since these files are needed by `autogen.sh`.
Any chance you can remove them from the .gitignore? They are in the repository anyway so it seems that they got put in the ignore file by mistake

Thanks!

**Comment by jedisct1** [comment]
Hi!

9ecde0c45653df96c8b58995468a25a08f69e439 makes the ignore list more specific.

Thanks!

**Comment by jedisct1** [comment]
The change has been made to the `stable` branch as well.
