### ISSUE TITLE
Support for AES-OCB with AESNI backing

### ISSUE THREAD

**Issue by azet** [jedisct1/libsodium#406]
Hi,

I realise may not be in scope for this project. Recent ASM optimized OCB implementations in OpenSSL outperform GCM on certain Intel processors. I really like OCB and was wondering if there's any interest in supporting it within `libsodium` as an AEAD?

As this project is FOSS patents do not apply here either.

**Comment by jedisct1** [comment]
AES-OCB wouldn't solve any problems that AES-GCM doesn't already solve. If a new AEAD construction is introduced, it has to have a property that existing constructions don't have, such as being nonce-misuse resistant.

**Comment by FSMaxB** [comment]
Another problem: Patents do apply because libsodium is only used in proprietary software. Also a software being FOSS doesn't mean it can't be used for commercial purposes.

**Comment by azet** [comment]
> AES-OCB wouldn't solve any problems that AES-GCM doesn't already solve. If a new AEAD construction is introduced, it has to have a property that existing constructions don't have, such as being nonce-misuse resistant.

This was a feature request not something that's required for a secure AEAD.

> Another problem: Patents do apply because libsodium is also used in proprietary software. Also a software being FOSS doesn't mean it can't be used for commercial purposes.

1) Rogaway's patents recently expired.
2) He granted verbatim exemptions for all software released under any OSI approved license (i.e. not limited to GPLvX).
