### ISSUE TITLE
Threadsafe `sodium_init()`

### ISSUE THREAD

**Issue by Fraser999** [jedisct1/libsodium#407]
Apologies for creating this as an issue, but your [commit making `sodium_init()` threadsafe](https://github.com/jedisct1/libsodium/commit/f8ff8ebf669f8a07fa53c427dbdc6bbc9d21ad1d) would be very useful to us.

When do you plan to release a new version which will allow us to make use of this?

**Comment by jedisct1** [comment]
Soon!

Probably next week.

**Comment by Fraser999** [comment]
Brilliant - thanks :)
