### ISSUE TITLE
use_frameworks! issue

### ISSUE THREAD

**Issue by gioenn** [jedisct1/libsodium#408]
I'm using libsodium through cocoapods. I started mixing obj-c and swift code. To use Swift frameworks such as Alamofire I had to add the _use_frameworks!_ tag  to my Podfile. After that I can't compile libsodium anymore because I'm getting error: 'Include of non-modular header inside framework module 'libsodium'' inside the libsodium-umbrella.h file. 

<img width="780" alt="schermata 2016-06-23 alle 18 57 29" src="https://cloud.githubusercontent.com/assets/1504957/16312281/40677570-3974-11e6-9ff3-994906fe41e5.png">

Can you help me?

**Comment by chrisballinger** [comment]
This is likely related to a bug/change in CocoaPods 1.0

https://github.com/CocoaPods/CocoaPods/issues/5409

There are some workarounds that involve modifying the podspec

**Comment by jedisct1** [comment]
Hi Giovanni,

You may want to take a look at https://github.com/jedisct1/swift-sodium and https://github.com/drewcrawford/NaOH
