### ISSUE TITLE
Shouldn't crypto_auth_hmacsha512_keybytes be 64 bytes?

### ISSUE THREAD

**Issue by paixaop** [jedisct1/libsodium#409]
Is 32 the correct size for `crypto_auth_hmacsha512_keybytes`?
In `src/libsodium/include/sodium/crypto_auth_hmacsha512.h` 

    #define crypto_auth_hmacsha512_KEYBYTES 32U

When using the streaming API we can specify a key with length bigger that `crypto_auth_hmacsha512_keybytes`, said key will be converted by 

    key = SHA512(key)

This is 64 byte length key not 32. Shouldn't the correct value be 64?

    int crypto_auth_hmacsha512_verify(const unsigned char *h, const unsigned char *in,
                                      unsigned long long inlen, const unsigned char *k)
    {
      unsigned char correct[64];
      crypto_auth_hmacsha512(correct,in,inlen,k);
      return crypto_verify_64(h,correct) | (-(h == correct)) |
             sodium_memcmp(correct,h,64);
    }

again tests for 64 bytes

**Comment by paragonie-scott** [comment]
The other two are hmacsha512256 and hmacsha256, so it could be a pasto.

**Comment by jedisct1** [comment]
The output size is 512 bits (`crypto_auth_hmacsha512_BYTES`), but the key size can be anything.

`crypto_auth_hmacsha512_KEYBYTES` is the recommended key size. It doesn't have to match the output size. A 256-bit key for HMAC is more than enough for all use cases.

**Comment by paixaop** [comment]
@jedisct1 I still have some doubts regarding this issue. I understand that 256-bit is enough but when we call `crypto_auth_hmacsha512_init` with a key bigger than 128 we reduce said key to the `key = SHA512(key)`. This is a 64 byte length.

But when we use the `crypto_auth_hmacsha512` it will in turn call `crypto_auth_hmacsha512_init` but this time with `crypto_auth_hmacsha512_KEYBYTES` which is defined as 32U.

So when using the Streaming API the key is 64 bytes, but when using the regular API the key is reduced to 32 bytes. This produces different results when calling init, update, final vs regular API

   crypto_auth_hmacsha512_init(&state, bigLenghtyKey, sizeof(bigLenghtyKey));
   crypto_auth_hmacsha512_update(&state, in, inlen);
   crypto_auth_hmacsha512_final(&state, out);
  
vs

   crypto_auth_hmacsha512(out, in, inlen, bigLenghtyKey);

produces different `out` values.

Is this what we want?

**Comment by jedisct1** [comment]
```c
    crypto_auth_hmacsha512_init(&state, key, 32);
    crypto_auth_hmacsha512_update(&state, in, sizeof in);
    crypto_auth_hmacsha512_final(&state, out);
```
and
```c
    crypto_auth_hmacsha512(out, in, sizeof in, key);
```

produce exactly the same output.

**Comment by paixaop** [comment]
Thanks for the fast reply!
If we do that then the code in the top of `crypto_auth_hmacsha512_init` will never get called. as length will never be bigger than 128.

    if (keylen > 128) {
        crypto_hash_sha512_init(&state->ictx);
        crypto_hash_sha512_update(&state->ictx, key, keylen);
        crypto_hash_sha512_final(&state->ictx, khash);
        key = khash;
        keylen = 64;
    }

Wouldn't it be better to update `crypto_auth_hmacsha512_KEYBYTES` to 64 and then the functions would all return the same values automatically, as long as the user calls verify with `key=SHA512(bigLenghtyKey)`?

**Comment by jedisct1** [comment]
What are you trying to do?

**Comment by paixaop** [comment]
In the node-sodium port I allow the caller to pass any size key to _init, internally libsodium calculates the SHA512 of the big key and all is ok. When verifying the token I cannot pass the same key as the value is truncated to 32. 

That is all. If this scenario is not to be used I will just do as you say and call _init with 32 all the time and avoid the problem

**Comment by jedisct1** [comment]
It would be probably better to only expose `crypto_auth()` and `crypto_auth_verify()` as all other bindings do.

Letting users choose the key size can lead to insecure key sizes, or to making people believe that using absurdly large keys improves security.

If you really want to allow this, compute the HMAC with the streaming API and then use `sodium_memcmp()` to verify that it matches the expected value. This is exactly what `crypto_auth_verify()` does.

Support for arbitrary key length in the streaming interface was only added for interoperability with 3rd party services, such as computing AWS session tokens. It can also be useful to build KDFs. But none of these scenarios require verifying a tag.

**Comment by paixaop** [comment]
will do. Thanks!
