### ISSUE TITLE
can't pass the test compelling with native client mac-x86_glibc

### ISSUE THREAD

**Issue by zzyheart** [jedisct1/libsodium#412]
hi, 
    I'm trying to compile native client version on my MacOs.  
    I changed the `$NACL_SDK_ROOT` in the script to the real path on my Mac: 

        export NACL_SDK_ROOT=${NACL_SDK_ROOT-"/Users/zzy/Documents/nacl_sdk/pepper_49"}

It works fine with `nativeclient-x86_64.sh`

But, when I try to build the 32 bit version,using `nativeclient-x86.sh`, it failed all the test. 
`test-suite.log` says all the test failed like this: 
```
FAIL: aead_aes256gcm

./aead_aes256gcm: error while loading shared libraries: ./aead_aes256gcm: failed to load code from shared object: Invalid argument
FAIL aead_aes256gcm (exit status: 127)
```

Is there any change I should make to the script? Thanks

**Comment by jedisct1** [comment]
Hi,

What source code are you trying to compile? Is it a release (1.0.10?), the `stable` branch or the development code in git?

**Comment by zzyheart** [comment]
I use the the development code in git, because release 1.0.10 has no nativeclient-x86_64.sh, and the nativeclient-x86.sh use only pnacl in release 1.0.10?

**Comment by jedisct1** [comment]
Can you try again with the latest development code?

**Comment by zzyheart** [comment]
Thanks! It works fine on your commit  351ae49!
