### ISSUE TITLE
Debug symbols included by default

### ISSUE THREAD

**Issue by Cyberunner23** [jedisct1/libsodium#414]
Debug symbols seem to be included by default when building with autotools. I'm wondering if this is as intended and if so is there an option to do a release build? (I am using 1.0.10)

**Comment by jedisct1** [comment]
This is intentional. These symbols can be extremely useful, and don't change anything to the code itself.

If you really don't want them, you can always compile with `env CFLAGS=-O2 ./configure ...`

**Comment by Cyberunner23** [comment]
Some symbols still seem to be present though
