### ISSUE TITLE
Sealed boxes that don't use a nonce?

### ISSUE THREAD

**Issue by BobWall23** [jedisct1/libsodium#415]
I am attempting to use libsodium to encrypt data in a way that is compatible with GPG - specifically, to write encrypted files that GPG can read. I was happy to find crypto_box_seal, because that's pretty much how the new version of GPG / libgcrypt does curve25519 as well - it always uses an ephemeral key instead of the sender's key.

Things turned bad when I discovered that crypto_box_seal always generates a nonce. Seems like this is not required if you are using an ephemeral key, and I'm guessing it is just doing that because the underlying crypto_box_easy function requires a nonce.

Would the idea of introducing an alternative sealed box that didn't use a nonce be entertained? I expect that making crypto_box_easy so it could take a NULL for the nonce would be a terrible idea - looks like the API is designed to try to make people do the right thing. But under the covers, would there be support for refactoring so it is possible to encrypt without a nonce, but just not expose those functions?

**Comment by jedisct1** [comment]
The nonce is used by the stream cipher (XSalsa20 here). X25519 doesn't use a nonce.

Does GPG actually support XSalsa20? I doubt it, but if it does, a nonce is required to build the initial state no matter what, even if it's just zeros.

**Comment by BobWall23** [comment]
My apologies - you are right. I would have more problems than just the immediate one. GPG doesn't support XSalsa20 - it's using AES. Sorry for the silly question.
