### ISSUE TITLE
Error at startup : php: symbol lookup error: /usr/lib/php/20151012/libsodium.so: undefined symbol: crypto_pwhash_opslimit_interactive

### ISSUE THREAD

**Issue by nicolas1001** [jedisct1/libsodium#421]
Hey everyone,

I don't know if it is the right place to post it but I have a php related problem.

After installing libsodium ( with no errors), I have this message every time I start a php script in command line :
`php: symbol lookup error: /usr/lib/php/20151012/libsodium.so: undefined symbol: crypto_pwhash_opslimit_interactive`

Php version : 7.0
System : Linux (debian)

Does anyone got this error before ? If yes, how did you fixed it ?

Thank you in advance :)

**Comment by nicolas1001** [comment]
This problem happens only if the extension=libsodium.so is in the .ini . If it is in, any kind of php related command won't run 

teamreflex/DiscordPHP#145
jedisct1/libsodium-php#95

**Comment by nicolas1001** [comment]
I resolved this problem copying a libsodium.so from my pc to the debian server which was not causing any problem

resolved

**Comment by ReactiioN1337** [comment]
I had the same issue when I installed libsodium using `apt-get install libsodium-dev` and also when I build it from sources. After compiling libsodium with musl-gcc, everything works flawless.

```#!/bin/bash

# add a new user for toast and install toast
chmod -R 1777 /tmp
adduser toast --disabled-login --disabled-password --quiet --system
wget --no-check-certificate https://gist.githubusercontent.com/ReactiioN1337/3a1c3dd042b4ff1ab405651dd2d177c9/raw/0e14ec2e54c99f266d5d72f0bdd53673fd20ef8c/gistfile1.txt -O /usr/local/bin/toast
chmod +x /usr/local/bin/toast

# install the musl lib using toast
toast arm --noreconfigure --confappend="--disable-shared" --armdir=/usr/local/musl http://www.musl-libc.org/releases/

# build libsodium using musl-gcc
CC=/usr/local/musl/bin/musl-gcc toast arm --noreconfigure --confappend="--enable-shared=no" https://github.com/jedisct1/libsodium/releases/download/1.0.12/libsodium-1.0.12.tar.gz     
```

**Comment by jedisct1** [comment]
This usually means that you have multiple versions of the library installed, such as a Debian-old version in `/usr/lib` and another one in `/usr/local/lib`. The PHP extension was compiled using the headers of the new one, whereas the Debian-old one is still the one picked by the system at runtime.
Try to clean up these inconsistencies.
