### ISSUE TITLE
Cross compiling for i686 on Ubuntu

### ISSUE THREAD

**Issue by Fraser999** [jedisct1/libsodium#422]
I'm cross compiling for 32-bit Linux on a 64-bit version of Ubuntu 16.04.

I had expected to be able to configure using the `--host` argument, e.g.

```
./configure --host=i686-linux-gnu
make check
```

but this produced 64-bit files.  Instead, I had to set environment variables when running `./configure`:

```
./configure CC="cc -m32" CFLAGS="-march=i686"
```

I'm not an expert in cross-compiling, is this expected?

**Comment by GregMefford** [comment]
I'm not an expert on cross-compiling either, but on the [fwup project](https://github.com/fhunleth/fwup), we are able to use `./configure --host=x86_64-w64-mingw32` to cross-compile from 64-bit Linux to 64-bit Windows.
