### ISSUE TITLE
crypto_pwhash removed from Emscripten standard build, breaking existing users

### ISSUE THREAD

**Issue by johndoughnut** [jedisct1/libsodium#425]
This just broke my build. Why was it removed?

**Comment by jedisct1** [comment]
Hi John,

libsodium.js has [its own repository](https://github.com/jedisct1/libsodium.js) and is a better fit for questions specific to libsodium.js .

`crypto_pwhash` is still available, but there are now [two distributions of libsodium.js](https://github.com/jedisct1/libsodium.js#standard-vs-sumo-version).
