### ISSUE TITLE
What do beforenm and afternm stand for?

### ISSUE THREAD

**Issue by thebigb** [jedisct1/libsodium#426]
I know what the functions are for, but can't figure out the abbreviation.

**Comment by paragonie-scott** [comment]
From [this document](https://cryptojedi.org/papers/coolnacl-20111201.pdf):

> Bob's operation is just as easy, with the keys and packets reversed:
>     m = crypto_box_open(c,n,pk,sk)
> Each side begins with
>     pk = crypto_box_keypair(&sk)
> to generate a secret key and a public key in the rst place.

...

> C NaCl allows crypto_box to be split into two steps, crypto_box_beforenm
and crypto_box_afternm, slightly compromising simplicity but gaining extra
speed as discussed in Section 4. The beforenm step preprocesses pk and sk,
preparing to handle any number of messages; the afternm step handles n and
m. Most applications actually use this two-step procedure.

**Comment by cfcs** [comment]
So ... "number of messages"? Was the question answered?

**Comment by paragonie-scott** [comment]
It literally means, "After processing n and m".

**Comment by tarcieri** [comment]
More specifically it's "before nonce/message"
