### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [jedisct1/libsodium#428]
Just a reminder for you. :smiley: 

Same as in https://github.com/jedisct1/libsodium-php/issues/96

**Comment by rugk** [comment]
Okay, so you sign releases, so why not sign commits too?

Also you do not need to attach your own tarball. See [this instruction](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) for now to use the automatically generated sources.

**Comment by jedisct1** [comment]
Hi Rugk,

I commit from a bunch of different hosts, and all of them do not have gpg, and even if gpg is installed, I cannot always store my key there (even encrypted). Quite a few commits have also been done from my phone.

I'm also not convinced that signing every single commit is worth it.

**Comment by rugk** [comment]
But you can always work in a PR and later - when you get to one trusted computer - you can merge and sign the PR there. That's how it is proposed in https://is.gd/7vU4oK.
