### ISSUE TITLE
Documentation for crypto_secretbox

### ISSUE THREAD

**Issue by thebigb** [jedisct1/libsodium#431]
The documentation for crypto_secretbox says that the algorithm used is XSalsa20, however looking at [crypto_secretbox_easy.c](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretbox/crypto_secretbox_easy.c) it appears that Salsa20 is being used.

This could be a typo in the documentation, but looking closer I'm also curious why libsodium uses Salsa20, and NaCl XSalsa20?

**Comment by tarcieri** [comment]
That looks like XSalsa20 to me. From the [XSalsa20 paper](https://cr.yp.to/snuffle/xsalsa-20081128.pdf):

> XSalsa20/r is a two-level generalized cascade, using the output of HSalsa20/r as a key for Salsa20/r.

Here's where the "HSalsa20" step is happening: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretbox/crypto_secretbox_easy.c#L26

**Comment by thebigb** [comment]
Ah, I missed that. Thanks.
