### ISSUE TITLE
Add a cmake find script.

### ISSUE THREAD

**Issue by BurningEnlightenment** [jedisct1/libsodium#432]
__TLDR__; I propose that a `Findsodium.cmake` script gets added to the repository.

## problem
A cmake find file is a portable script which locates an external library (like libsodium) and imports it into a cmake project. Usually those scripts are easily written, but in case of libsodium it is cumbersome to find the matching msvc library in the official binary distribution package.

## proposed solution
Add a (semi-)official `Findsodium.cmake` to the repository (in a `contrib` or `cmake` subfolder). This allows for centralized collaboration and will make it much easier to use libsodium in a cmake backed project by providing a ready to use high quality find script.

My current [`Findsodium.cmake`](https://gist.github.com/BurningEnlightenment/cf795d789e87ec8e5b88402b44810267) could be used as a starting point. On windows It works with the official libsodium packages (msvc and mingw). On unix pkg-config is used to find the library if pkg-config is available, otherwise it tries to find the library in the system default include and library paths. This should satisfy the common use cases.

**Comment by jedisct1** [comment]
Hi Henrik!

That can indeed be a useful addition.

You script was added to a new `contrib` directory.

Thanks!
