### ISSUE TITLE
Need a benchmark tool like 'openssl speed'

### ISSUE THREAD

**Issue by enihcam** [jedisct1/libsodium#433]
I didn't find any tool to do the perf test on ciphers with libsodium, but I thought it would be very helpful if we had this for benchmarking hardware performance.

**Comment by enihcam** [comment]
First scenario I have here is:
I would like to know, between AES-* and ChaCha20 which is faster on an AES accelerated processor?

**Comment by jedisct1** [comment]
You can use something like https://gist.github.com/jedisct1/63a4df48c7b367b45664ea0a9f5c1d4e to measure the speed of specific ciphers.

`crypto_box()`/`crypto_seal()` are more than fast enough for most applications, and I would recommend using them before considering alternatives. The large nonce size of XSalsa20 makes it easier to use these functions securely.

ChaCha20 performs well on pretty much all architectures, but on modern Intel CPUs, AES is faster. But once again, speed shouldn't be your first criteria.
