### ISSUE TITLE
clarification on the platform independence of sodium_memcmp

### ISSUE THREAD

**Issue by cjdelisle** [jedisct1/libsodium#435]
I have a question on the platform compatibility of sodium_memcmp() as per:
https://github.com/jedisct1/libsodium/blob/aff4aaeabf406044e90954593b3d378fc088020a/src/libsodium/sodium/utils.c#L131

I observe `d` is an `unsigned char` which is guaranteed in C99 to have 8 bits, then I see in the comparison `return (1 & ((d - 1) >> 8)) - 1;` that we shift `d-1` by 8 bits.

It appears that the `d-1` computation is being done on a 32 bit ALU and so when it is shifted, "bit 9" does exist. However, I am wondering if this could compile on a machine with a true 8 bit ALU wherein (d - 1) becomes 0xff and shifting by 8 reliably produces zero.

I observe that in djb's constant time comparison, he uses "int" which should always be at least 16 bits on any sane machine. https://github.com/cjdelisle/cjdns/blob/master/node_build/dependencies/cnacl/crypto_verify/32/ref/verify.c

Sorry to be the C standard rules-lawyer but I would like some background as to why this decision was taken and how it is defended.

**Comment by jedisct1** [comment]
The `-` operation on a `char` value promotes it to an `int`.

**Comment by cjdelisle** [comment]
thanks
