### ISSUE TITLE
Update function for crypto_secretbox_easy / crypto_secretbox

### ISSUE THREAD

**Issue by udf2457** [jedisct1/libsodium#437]
Hi,

Maybe I'm being dumb but ....

As far as I can make out from your documentation and source code, the crypto_secretbox appear to rely on the fact that "m" contains the entire plaintext to be encrypted.

What happens if I've got a large file to encrypt that's far too big to sensibly stuff into a variable in one go ?

So consider this an enhancement request for an "update" on crypto_sandbox.

**Comment by jedisct1** [comment]
Then you need to split it into smaller chunks.

Or use something like https://github.com/jedisct1/blobcrypt
