### ISSUE TITLE
avx2 optimized blake2

### ISSUE THREAD

**Issue by lfarkas** [jedisct1/libsodium#439]
it'd be nice to adopt Tromp's avx2 optimized blake2 implementation: https://github.com/tromp/equihash/tree/master/blake2-avx2

**Comment by FSMaxB** [comment]
In the README it says that it is still experimental.

**Comment by jedisct1** [comment]
libsodium has AVX2 optimized implementation since version 1.0.9.

**Comment by lfarkas** [comment]
would be nice to measure the performance of both.
