### ISSUE TITLE
SHA1 and MD5

### ISSUE THREAD

**Issue by amitmurthy** [jedisct1/libsodium#44]
Some of Amazon's APIs, S3 for example, only supports HMAC-SHA1 signatures. 

Will libsodium ever include support for creation of HMAC-SHA1 digests? 
Also MD5 hashing. Again, it used with AWS S3 to verify correctness of uploaded data.

**Comment by kkimdev** [comment]
Random passing by comment:  Even algorithms that's considered secure today can be broken over time.  I think it will be good to establish "supported" -> "obsolete/insecure" -> "removed" process.  If we once have that, then I guess it's OK to put MD5 / SHA in "obsolete/insecure" category.
