### ISSUE TITLE
`Sodium.h` file not found with <angled> include, use "quotes" instead

### ISSUE THREAD

**Issue by amir-sabbaghi** [jedisct1/libsodium#441]
I'm using libsodium with cocoapods version `1.1.1`. But I cannot update libsodium to version `1.0.11` because one of the libraries that I use is including `libsodium.h` with angled brackets and Xcode give the above error message.
But everything works correctly if I revert back to libsodium `1.0.3`.
I think you are specifying  public header files incorrectly.

**Comment by jedisct1** [comment]
Looks like a problem with the cocoapods package. I don't use Cocoapods, and that package is maintained independently. So you should probably report this to its maintainer, who probably knows way more about Cocoapods that I do :)

**Comment by amir-sabbaghi** [comment]
I saw another [issue](https://github.com/jedisct1/libsodium/issues/423) about cocoapods here, and this seems to a problem about libsodium's podspec not cocoapods itself.
