### ISSUE TITLE
Padding length in crypto_aead_chacha20poly1305_ietf

### ISSUE THREAD

**Issue by djarek** [jedisct1/libsodium#444]
Hi, I've noticed an issue with the ietf version of the chacha20 aead algorithm which makes it incompatible with other implementations (verification fails) due to the padding length being different from the one specified [here](https://tools.ietf.org/html/rfc7539#section-2.8.1) when the additional data length is divisible by 16. The code in sodium that calculates padding is [here](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c#L267-L271):
```
(0x10 - adlen) & 0xf
```

According to RFC7539 it should instead be:
```
0x10 - (adlen % 0x10)
```

I've checked  [OpenSSL](https://github.com/openssl/openssl/blob/6a69e8694af23dae1d1927813932f4296d133416/crypto/evp/e_chacha20_poly1305.c#L223-L225) for comparison and it seems they use the same method for calculating the pad length as specified in RFC7539.

Is this incompatibility intentional or just a bug?

**Comment by jedisct1** [comment]
[Section 2.8](https://tools.ietf.org/html/rfc7539#section-2.8) mentions:

`padding1 -- the padding is up to 15 zero bytes`
`padding2 -- the padding is up to 15 zero bytes`

`0x10 - (adlen % 0x10)` breaks this definition and would add 16 bytes of padding to additional data whose length is already a multiple of 16.

Looking at the actual pseudo-code of the RFC, reformatted for clarity:
```
 pad16(x):
         if (len(x) % 16)==0 then:
                 return NULL
         else:
                 return copies(0, 16-(len(x)%16))
         end
```
This seems to match what the previous definition does: it doesn't add any padding if the length is already a multiple of 16.

**Comment by djarek** [comment]
@jedisct1 
Oh, I got confused by the weird formatting of the pseudo-code in the RFC. Just wondering - what is the reason for sodium not using modulo here as in the spec? Is it an optimization - modulo is quite expensive, right?

**Comment by FSMaxB** [comment]
`number & 0xf` is the same as `number % 16` and bitwise and is probably much faster than modulo, so yes, it is an optimization.

But for better readability it would make sense to still use `% 16`, normal compilers produce the same code for both anyways (doing the bitwise and for a modulo with a power of 2).
