### ISSUE TITLE
Cannot build on termux

### ISSUE THREAD

**Issue by Exaeta** [jedisct1/libsodium#445]
This library can't be built using termux because ```/bin/sh``` does not exist. 

Oddly, it breaks at ```./configure``` but ```autogen.sh``` works.
 ```autogen.sh``` correctly identifies ```sh``` at ```/data/data/com.termux/files/usr/bin/sh``` but ```./configure``` is looking for ```/bin/sh```.

```
$ ./configure
configure: error: cannot run /bin/sh build-aux/config.sub
$
```

**Comment by jedisct1** [comment]
Unless you are willing to use development code, you should never have to run `autogen.sh`.

Actually you should not run it, so that in bug reports, we can assume that the `autoconf`-generated files are identical to the one from releases (or from the `stable` branch).

A `CONFIG_SHELL` environment variable can be used in order to use a specific shell for the configuration.

For example:

```sh
env CONFIG_SHELL=/data/data/com.termux/files/usr/bin/sh ./configure --enable-minimal
```

**Comment by Exaeta** [comment]
There is no ```./configure``` when I download the repository though.

**Comment by thebigb** [comment]
Archives from the releases tab or from https://libsodium.org will have it.

**Comment by Exaeta** [comment]
Doesn't work. I've been trying to fiddle around with it, but this configure script is horribly broken. How do I compile it manually?

**Comment by jedisct1** [comment]
Termux is not a supported platform.

Still, can you post the content of the `config.log` file somewhere in order to see what doesn't get properly detected?

**Comment by jedisct1** [comment]
Using an unmodified release tarball, or the `stable` branch:

* Create a directory for temporary files:
```sh
mkdir tmp
export TMPDIR=$(pwd)/tmp
```
* Define what shell has to be used and how to run the `mkdir` command:
```sh
export CONFIG_SHELL=$SHELL
export MKDIR_P="mkdir -p"
```
* Run the `configure` script:
```sh
$SHELL ./configure --disable-shared --enable-minimal --prefix=$TMPDIR
```
* Compile, test and install:
```sh
make check
make install
```

You may also have to install the standard Unix tools `sed` and `grep`.

**Comment by fornwall** [comment]
For reference, note that libsodium is available as a pre-built Termux package, so it doesn't need to be built but can be installed with:

    apt install libsodium-dev

**Comment by jedisct1** [comment]
@fornwall Thanks! That's even way easier!
