### ISSUE TITLE
Difference between this repo and libsodium/libsodium?

### ISSUE THREAD

**Issue by spacekitteh** [jedisct1/libsodium#450]

**Comment by jedisct1** [comment]
The `libsodium` account (hence `libsodium/libsodium`) has nothing to do with the maintainers of the library.

Github was notified, but didn't do anything.

**Comment by spacekitteh** [comment]
Well that's pretty awful.

**Comment by jedisct1** [comment]
It is :(

In doubt, only download releases from libsodium.org and check the signatures.
