### ISSUE TITLE
Add more platform-specific optimised sources

### ISSUE THREAD

**Issue by spacekitteh** [jedisct1/libsodium#451]
This involves several things.

1. Grabbing new implementations from SUPERCOP. ARM and ARM-NEON implementations are especially needed.
2. Refactor the configure script to allow a finer-grained selection of target platform; similar to specifying a board support package
3. Improve the platform-specific source selection abilities in the configure script. An good example of this for an older version of NaCL is here: https://github.com/cjdelisle/cjdns/tree/master/node_build/dependencies/cnacl 

I'm (slowly) working on this in a fork. 

TODO:
- [ ] Port SUPERCOP crypto_core/salsa20/armneon
- [ ] Replace crypto_core/salsa20/ref with crypto_core/salsa20/armneon in makefile when on ARM

**Comment by spacekitteh** [comment]
A good start for ARM-NEON would be from [here](https://github.com/cjdelisle/cjdns/blob/master/node_build/dependencies/cnacl/node_build/plans/armeabi_neon_plan.json), namely:

* Salsa20: armneon6
* Ed25519: ref10
* Poly1305: [floodyberry's implementation](https://github.com/floodyberry/poly1305-opt/tree/master/app/extensions/poly1305)
* ChaCha20: moon/neon/32
* scalarmult: neon2
* aes128ctr: neon

**Comment by jedisct1** [comment]
ARM-optmized implementations are already on the TODO list.

The first step would be to extend the CPU features detection code to detect NEON presence beyond Android.

**Comment by spacekitteh** [comment]
I've been putting off learning autoconf forever; I guess now's the time to learn!

**Comment by jedisct1** [comment]
Some autoconf changes might be necessary to check that the toolchain can compile the required opcodes, but the detection is actually done at runtime in `sodium/runtime.c`.

**Comment by spacekitteh** [comment]
Ahh, I see.

**Comment by jedisct1** [comment]
Unlike NaCl and many implementations, libsodium is not compiled for a specific architecture.

The same binary must work on a wide range of similar CPUs. CPU features are detected at run-time, and enable specific implementations (or some specific code paths, for example in the BLAKE2 case) depending on the result.

If only for that reason, and also for portability concerns, implementations from SUPERCOP and other freestanding implementations can almost never be used as-is.

**Comment by spacekitteh** [comment]
That certainly makes things a lot easier, if a bit more bloated :D

**Comment by spacekitteh** [comment]
I am working on it here: https://github.com/spacekitteh/libsodium/tree/arm-neon

Figuring out the process of creating an implementation struct when the implementations don't offer optimised versions of every function. For example, the core_stream/salsa20 armneon6 implementation doesn't have a xor_ic, only a xor. So, until xor_ic is implemented, it will be set to a default.

Effectively, trying to figure out a good way emulate an object-oriented implementation system with virtual methods in C, with the ref implementation as the tree root. For example, ARM-NEON is an extension of ARM, so if an ARM-NEON implementation doesn't exist for a certain function, but an ARM implementation does, it should fall back to the ARM implementation. Thus, an implementation struct instance should only need to assign methods that differ from its parent implementation.

**Comment by jedisct1** [comment]
The NEON instructions set has been around for a while, and the number of ARM CPUs without NEON is soon going to be statistically insignificant. So, it's probably not worth having both NEON + ARM without NEON implementations. Keep things simple, introducing object-oriented concepts is certainly not required here.

What is far more important is to perfectly understand the algorithm and the code, and to validate it on a wide range of actual hardware and compilers. 
salsa20_xor_ic` is not present in the implementation you mentioned, so you need write it based on the reference code, and rewrite `salsa20_xor` based on it.
The ed25519 code cannot be used without implementing conversions and the extra verifications to avoid small subgroups and prevent malleability. The scalar multiplication code cannot be merged without also checking that you don't end up with the point at infinity. ChaCha20 will require the ability to set the block counter. Poly1305 implementations have to support a streaming API. For BLAKE2, you will have to make sure that the code can be shared with the Argon2 implementation, but you will also have to implement and maintain future constructions based on the same round function such as BLAKE2X.
Unless the performance gains of a pure assembly implementation are significant, libsodium also tends to favor intrinsic-based code over assembly code. In addition to being more readable, this makes it easier to reuse the code across different platforms (Visual Studio). 

The first steps before adding ARM code are probably to add extra autoconf rules to check that the toolchain can compile the required NEON opcodes, define whatever is required if this is not the case, improve the runtime NEON detection code and check it on a wide range of real hardware. Emulators can unfortunately have very different behaviors that real hardware, especially when it comes to feature detection and alignment constraints.

**Comment by spacekitteh** [comment]
>The NEON instructions set has been around for a while, and the number of ARM CPUs without NEON is soon going to be statistically insignificant. So, it's probably not worth having both NEON + ARM without NEON implementations. Keep things simple, introducing object-oriented concepts is certainly not required here.

Fair enough. It was more of a "rolling release" type thing than anything else - the default implementation would have simply been the reference implementation, and then as each function is implemented it can be merged, rather than waiting for the entire set all at once. If you think that's too complicated, then that's perfectly reasonable!

>validate it on a wide range of actual hardware and compilers

Is there a specific C spec to target? And a list of compilers which must be able to compile it? Or is it more of a "we must keep the C-style API for v1" thing?

>Unless the performance gains of a pure assembly implementation are significant, libsodium also tends to favor intrinsic-based code over assembly code. In addition to being more readable, this makes it easier to reuse the code across different platforms (Visual Studio).

Aye, I was going to convert it to intrinsics. I certainly don't want to have to deal with pure assembly :D

**Comment by jedisct1** [comment]
https://download.libsodium.org/doc/internals/ has a list of compilers and tools used to check every release. If ARM implementations are added, it would make sense to add the ARM compiler to the list.

**Comment by spacekitteh** [comment]
Ah, I must have missed the dynamic analysis section for some reason!

**Comment by spacekitteh** [comment]
So I understand correctly:

* Autoconf rules for broad architecture decisions (x86 vs arm vs mips etc)
* Runtime testing for instruction set extensions/specific architectures in the broad architecture

Yeah?

**Comment by jedisct1** [comment]
Predefined macros are usually enough for broad architecture decisions, but autoconf is indeed the tool to be used for compiler capabilities, whereas specific CPU types are detected at runtime.
