### ISSUE TITLE
aead_aes256gcm_decrypt zeroes output buffer on MAC verification failure

### ISSUE THREAD

**Issue by uberjay** [jedisct1/libsodium#454]
From `crypto_aead_aes256gcm_decrypt_detached_afternm` (in `aead_aes256gcm_aesni.c`):
```c
    {
        unsigned char d = 0;

        for (i = 0; i < 16; i++) {
            d |= (mac[i] ^ (T[i] ^ accum[15 - i]));
        }
        if (d != 0) {
            if (m != NULL) {
                memset(m, 0, mlen);
            }
            return -1;
        }
        if (m == NULL) {
            return 0;
        }
    }
```

If the output buffer (m) is supplied, and the tag verification fails, the output buffer is zeroed. This is getting in the way of decrypting in place. It's entirely likely that this is being done for a security-related reason that I haven't reasoned out yet. :)

Since the buffer is only cleared if supplied, I can work around this by calling decrypt twice, but that seems a little ridiculous. If clearing the output buffer for safety is important in the general case, maybe it could at least be skipped if the input and output buffer pointers match?

Thoughts? Am I missing something?

**Comment by FSMaxB** [comment]
Filling the output with 0 ensures that you don't accidentally use uninitialized values in case the return value was not checked for errors properly. (although I am not 100% sure that this is the reasoning behind this, but it seems likely). Things like this make the library more misuse resistant.

**Comment by uberjay** [comment]
Yeah, I hear you on that, but doesn't it completely screw up in-place decryption? Because of this, I have to make a copy of the data, in the (unlikely, unless I'm writing a unit test... which I am right now :) event the mac doesn't verify.

As a counter example, `crypto_secretbox_open_detached` doesn't do this.

**Comment by jedisct1** [comment]
Your guess is absolutely correct :)

The intent is to prevent the decrypted data from being used if it was tampered with, but the return value of the function was not being checked.

If the computed MAC doesn't match the provided one, the decrypted data should not be used, but neither should the ciphertext. The only way to "fix" it would be to recompute a correct authentication code, that would completely defeat its purpose.

`aead_chacha20poly1305_*()` has the same behavior.

`secretbox_*()` doesn't, but it certainly should as well.

**Comment by FSMaxB** [comment]
For completeness: There are cases where you would want to try different keys until you find one that matches (the double ratchet by OpenWhisperSystems does that for example). In these cases it would be impossible to use these functions inplace (which is fine in my opinion, because the benefits of inplace decryption don't outweigh the misuse resistance).

**Comment by tarcieri** [comment]
Perform a Poly1305 verification first, and only decrypt if it succeeds?

**Comment by uberjay** [comment]
I get it... and still am finding this to be overly heavy handed. (Especially given the complier-enforced return-value checking. Especially when performing in-place decryption.)

At the very least I think this needs to be explicitly documented.

**Comment by FSMaxB** [comment]
@tarcieri makes sense.

**Comment by jedisct1** [comment]
Or just use `NULL` for the target pointer. This will check the MAC without performing the decryption.
