### ISSUE TITLE
Cross-compiling for the ESP8266

### ISSUE THREAD

**Issue by kitmonisit** [jedisct1/libsodium#455]
Can this be cross-compiled for the ESP8266? I have managed to build [pfalcon/esp-open-sdk](https://github.com/pfalcon/esp-open-sdk) and I'm wondering what other settings I need to specify other than the path to `gcc`.

From the chapter [Installation](https://jedisct1.gitbooks.io/libsodium/content/installation/), there is a guide for cross-compiling to ARM:

```
$ export PATH=/path/to/gcc-arm-none-eabi/bin:$PATH
$ export LDFLAGS='--specs=nosys.specs'
$ export CFLAGS='-Os'
$ ./configure --host=arm-none-eabi --prefix=/install/path
$ make install
```

What settings (such as `--host`, `LDFLAGS` and `CFLAGS`) should I use to compile libsodium for the ESP8266?

**Comment by jedisct1** [comment]
Looks like we don't have a lot of people using the ESP8266 here.

libsodium uses the standard autotools suite as a build system, so the procedure should be exactly the same as any other piece of software using it. But I have no idea what it is either.

Maybe you will have more success on a forum dedicated to microcontrollers.

**Comment by kitmonisit** [comment]
Thank you Frank. I actually got it to work on the ESP8266 about a week
after I posted the issue. But it was done during a project at work. I would
like to open-source it but first I need to ask if it's okay with my
employer.

**Comment by jedisct1** [comment]
Awesome, thanks!

**Comment by codebudo** [comment]
Sorry to zombie this thread, but @kitmonisit I would be very interested in your work on ESP8266 cross-comp. Any chance you can post your changes?

**Comment by jedisct1** [comment]
You'd rather consider [libhydrogen](https://github.com/jedisct1/libhydrogen) on such a platform.
