### ISSUE TITLE
Expose ARGON* constants for `crypto_pwhash`

### ISSUE THREAD

**Issue by emilbayes** [jedisct1/libsodium#457]
Is there a reason the `ARGON*` constants are not exposed for `crypto_pwhash`?

I'm specifically thinking of the input restrictions, which you might want to check for when taking user input. Especially if the password hash function might be changed in the future, it'd be nice for completeness to have [min, max] password length, [min, max] hash output length etc. officially exposed instead of hardcoded by the application developer.

**Comment by jedisct1** [comment]
Hi Emil,

Indeed, these would be nice to have. I'm gonna add these as soon as possible.

Thanks!
