### ISSUE TITLE
Where `HAVE_MEMSET_S` is defined?

### ISSUE THREAD

**Issue by Diadlo** [jedisct1/libsodium#463]
Hello. I want to copy your implementation of [`sodium_memzero`](https://github.com/jedisct1/libsodium/blob/9cae7b6b7c6f527df807157602ba48821281048b/src/libsodium/sodium/utils.c#L75). And found using of `HAVE_EXPLICIT_BZERO` and `HAVE_MEMSET_S`. I found only definition of [`HAVE_EXPLICIT_BZERO`](https://github.com/jedisct1/libsodium/blob/master/configure.ac#L678). Where `HAVE_MEMSET_S` is defined?

Thanks for attention.

**Comment by jedisct1** [comment]
It is not :) Actually, it used to, but was removed, because some OSX version had the symbol defined although it didn't work.

That was quite some time ago, around OSX Leopard or so. It's very likely to be safe to reintroduce it now.
