### ISSUE TITLE
sodium_FOUND not defined

### ISSUE THREAD

**Issue by LongShao007** [jedisct1/libsodium#466]
I use FindSodium.cmake to determine whether the installation of libsodium, but sodium_FOUND not defined, sodium_INCLUDE_DIR and sodium_LIBRARY_RELEASE are defined.
I tried libsodium verison 1.0.11 and master.
cmake version 3.7.1
ubuntu 14.04 64
`set(sodium_FOUND TRUE)`

**Comment by jedisct1** [comment]
Any idea, @BurningEnlightenment ?

**Comment by BurningEnlightenment** [comment]
I'll look into this when I'm back from my ski holidays (you can assign me if you want :wink:)

**Comment by jedisct1** [comment]
Enjoy your skip trip!

**Comment by BurningEnlightenment** [comment]
@LongShao007 `sodium_FOUND` is always defined by [FindPackageHandleStandardArgs](https://cmake.org/cmake/help/v3.7/module/FindPackageHandleStandardArgs.html). But AFAIK it's not a cached variable, i.e. you can't inspect its value via `cmake gui` or `ccmake`. However you should still be able to use it from your script. Have you tried checking whether `sodium_FOUND` has been defined with something like the following?
```cmake
if (NOT DEFINED sodium_FOUND)
    message(FATAL_ERROR "sodium_FOUND wasn't defined")
endif()
```

**Comment by LongShao007** [comment]
i use FindSodium.cmake
`find_package(Sodium)
if(NOT sodium_FOUND)
  message(FATAL_ERROR "Sodium not found!")
endif(NOT sodium_FOUND)`
cmake report error. "Sodium not found!"

**Comment by BurningEnlightenment** [comment]
I'm not sure, whether I understood your problem correctly. 
Do you have problems detecting the sodium libraries, i.e. the three cached variables `sodium_INCLUDE_DIR`, `sodium_LIBRARY_DEBUG` and `sodium_LIBRARY_RELEASE` are not set appropriately? Or are those variables set to _valid_ values, but `sodium_FOUND` is set to "FALSE"?

**Comment by LongShao007** [comment]
my code:

> find_package(Sodium)
message("sodium_FOUND = " "${sodium_FOUND}")
message("sodium_INCLUDE_DIR = " "${sodium_INCLUDE_DIR}")
message("sodium_LIBRARY_RELEASE = " "${sodium_LIBRARY_RELEASE}")
if(NOT DEFINED sodium_FOUND)
    message(FATAL_ERROR "sodium_FOUND wasn't defined")
endif()

the result:

> sodium_FOUND =
sodium_INCLUDE_DIR = /usr/local/include
sodium_LIBRARY_RELEASE = /usr/local/lib/libsodium.so
CMake Error at CMakeLists.txt:79 (message):
  sodium_FOUND wasn't defined

/usr/local/include/sodium.h and /usr/local/lib/libsodium.so are exist.

**Comment by BurningEnlightenment** [comment]
This is very likely a file naming issue 😖. As already stated above `find_package_handle_standard_args` defines the `_FOUND` variable. The documentation clearly states that `<PackageName>_FOUND` and `<PACKAGENAME>_FOUND` will be defined. You looked for `Sodium`, hence `Sodium_FOUND` and `SODIUM_FOUND` should be defined, but `sodium_FOUND` obviously isn't defined.
Therefore renaming `FindSodium.cmake` to `Findsodium.cmake` and using `find_package(sodium)` should fix your problem.
***
@jedisct1 Do you want to rename the file in this repository yourself or do you want me to file a pr?

**Comment by LongShao007** [comment]
I tried.
SODIUM_FOUND is ok.
Sodium_FOUND is not defined.
I rename FindSodium.cmake to Findsodium.cmake, then try again, sodium_FOUND is not defined, SODIUM_FOUND is defined. 
so i use SODIUM_FOUND.
