### ISSUE TITLE
Issues on apt-get update

### ISSUE THREAD

**Issue by ImthePeach** [jedisct1/libsodium#468]
I keep getting the following errors at the end of updating libraries for ubuntu 14.04

```
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/chris-lea/libsodium/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: http://ppa.launchpad.net/chris-lea/libsodium/ubuntu/dists/trusty/Release.gpg: Signature by key 136221EE520DDFAF0A905689B9316A7BC   7917B12 uses weak digest algorithm (SHA1)
E: Failed to fetch http://ppa.launchpad.net/chris-lea/libsodium/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Everything that I use that uses libsodium does still seem to work properly with no issues. But after trying to research these such as the `release file` I haven't found much info. If anyone can direct me in the right direction for any of this it would be appreciated.

**Comment by jedisct1** [comment]
This PPA looks abandoned. That libsodium version is very old.

I'm not sure what Ubuntu version you are running since there are references to `xenial` is what you pasted.

If you are actually running Xenial or Yakkety, you'd better remove that PPA and use the official package from Ubuntu.

**Comment by ImthePeach** [comment]
Weird it was a fresh installation Ubuntu through Digital Ocean a few weeks ago and I swore I used the official package. Not sure what happened though

**Comment by ImthePeach** [comment]
Shoot I forgot I upgraded it to Ubuntu 16.04.01

**Comment by ImthePeach** [comment]
Ok, I removed all of libsodium and reinstalled using apt-get to pull directly from Ubuntu, the following URL has the installation portion and update and the same stuff on the end. Am I doing something wrong because if so I don't see it.
https://hastebin.com/zewopatiri.rb

**Comment by jedisct1** [comment]
The upgrade was not clean and there are still leftovers from the old version.

Inspect the `/etc/apt/sources.list.d/` directory and remove any files with references to `http://ppa.launchpad.net/chris-lea`. These repositories are neither official libsodium nor ubuntu repositories.

**Comment by ImthePeach** [comment]
I have done a ppa-purge on the ppa that was there. Reinstalled libsodium-dev, updating seemed to be successful. 
```
root@Peach:~/gngBot# apt-get update
Ign:1 http://download.rethinkdb.com/apt xenial InRelease
Hit:2 http://ppa.launchpad.net/mc3man/xerus-media/ubuntu xenial InRelease
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:4 http://download.rethinkdb.com/apt xenial Release
Hit:5 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
Hit:6 http://nyc3.clouds.archive.ubuntu.com/ubuntu xenial InRelease
Get:7 http://nyc3.clouds.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:8 http://nyc3.clouds.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Fetched 306 kB in 2s (122 kB/s)
Reading package lists... Done
```

**Comment by jedisct1** [comment]
Great! 👍

**Comment by ImthePeach** [comment]
Thanks for the assistance
