### ISSUE TITLE
Passing crypto_aead_chacha20poly1305_encrypt_detached an external ic?

### ISSUE THREAD

**Issue by ayende** [jedisct1/libsodium#469]
I have the need to independently encrypt pages in a file. Pages are accessed randomly for both reads & writes.
The idea is that we'll have a single master key for the entire file, and each page will be encrypted independently, using a different nonce (and each time we modify a page we increment the nonce).

The problem is that because we increment the nonce on each page modification, and we start with random nonce, it is possible that we'll encrypt (different) pages with the same nonce & key, which the docs call our to be a _bad_ thing.

For reference, here is what the page is supposed to look like. 
```
+-------------------------------------------------------------------------+
|Page # 64 bits|Page metadata up to 288 bits  |mac 128 bits| nonce 96 bits|
+-------------------------------------------------------------------------+
|                                                                         |
|  Encrypted page information                                             |
|                                                                         |
|       8,128 bytes                                                       |
|                                                                         |
|                                                                         |
+-------------------------------------------------------------------------+
```

My thinking is that we can modify `crypto_aead_chacha20poly1305_encrypt_detached` and `crypto_aead_chacha20poly1305_decrypt_detached` so they will take a page number, which will they then pass to `crypto_stream_chacha20_xor_ic`.

As a sample of this change:
https://gist.github.com/ayende/81e7c3915051fa769646f812ef89a778/revisions

My question is whatever this kind of behavior is safe? Am I opening myself up to issues in this manner?

The page number is going to be constant always, and the nonce will be different between each page encryption. But we still might have same key/nonce (with different block number).

**Comment by jedisct1** [comment]
Do you have additional data? If you don't, you may just use `crypto_box`, with its 192-bit nonce. Use a few bits of the nonce as a counter, and keep the rest random.

**Comment by ayende** [comment]
@jedisct1 isn't `crypto_box` public key encryption? I thought it was significantly slower than using symmetric encryption.

The idea was that we'll use the rest of the page header (the first 44 bytes) as the additional data, which the mac will also auth.

It it also important to note that I'm encrypting pages in a file and not sending it around. It is all there on the same machine, so I don't think that public key encryption would be appropriate.

**Comment by jedisct1** [comment]
`crypto_secretbox`, then :)

**Comment by ayende** [comment]
That give me a nonce of 24 bytes (192 bits), so I can safely generate it randomly, which prevents the nonce reuse, I assume.
This is workable, I guess, but I'm not seeing how I can pass  additional data to `crypto_secretbox_detached`, and the size of nonce + mac is a bit big.

Since I would like to add additional data (the page header), I thought using the `AEAD` would be preferable, but that bring me back to the block number.

**Comment by jedisct1** [comment]
1.0.12 will provide `crypto_aead_xchacha20poly1305_*()` which may solve your issue; it supports both additional data and a 192-bit nonce.
