### ISSUE TITLE
Why does crypto_box_seal() generate keys?

### ISSUE THREAD

**Issue by goblin** [jedisct1/libsodium#470]
Hi,

I'm not 100% sure how it's done internally, but it seems that the ephemeral key generation and signing of the message in crypto_box_seal() may be unnecessary.

My main point is that the generated ephemeral key is only used for signing the MAC, but this MAC cannot really be verified by the recipient. So it can only be used for ensuring message integrity, for which a simple hash function could be better.

I've ran a small test and generating an ephemeral key pair seems to take about as long as crypto_box()ing a 1kB message, which is a significant overhead.

So my main question is: can the underlying crypto algorithm encrypt a message without signing it, like PGP/GnuPG?

If I understand it correctly, crypto_box_seal() will first generate an ephemeral keypair `epk`/`esk`, then compute some hash of the message, `H(m)`, then sign that hash with `esk`. It probably stores `epk` somewhere in the seal tag (within `crypto_box_SEALBYTES`), and then finally it encrypts the message using recipient's public key `rpk`.

So recipient can decrypt using his secret key `rsk`, get the sender's public key `epk` from the message, and check integrity by ensuring the signature matches.

Please correct me if I'm wrong, but just including `H(m)` with the plaintext before encrypting it should achieve the same purpose, without the overhead of generating a separate keypair, shouldn't it?

Many thanks

**Comment by ivmaykov** [comment]
crypto_box_seal() is built on top of crypto_box(). crypto_box() derives a shared secret by multiplying the sender's secret key and the receiver's public key using crypto_scalarmult(). crypto_box_open() derives the same shared secret by multiplying the sender's public key and the receiver's secret key. This is elliptic curve diffie-hellman. It doesn't work if you only have one key pair.

**Comment by goblin** [comment]
Gotcha, yeah, I suspected it might be the case. I'll read up about it some more.

Thanks for the answer!
