### ISSUE TITLE
crypto_aead_aes256gcm_is_available() returning 0 on Macbook Pro Mid 2015

### ISSUE THREAD

**Issue by alias1** [jedisct1/libsodium#472]
So I was implementing a wrapper around libsodium for Scala, and then hit this issue.

It seems that `crypto_aead_aes256gcm_is_available()` is returning `0` for me, even though my CPU should have hardware support.

`MacBook Pro (Retina, 15-inch, Mid 2015)` on `macOS Sierra v10.12.2 (16C67)`
* [This](http://www.everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i7-2.8-15-dual-graphics-mid-2015-retina-display-specs.html) seems to say it has a `Core i7 (I7-4980HQ)`, which according to [Intel](http://ark.intel.com/products/83503/Intel-Core-i7-4980HQ-Processor-6M-Cache-up-to-4_00-GHz) supports the AES instructions.

```
⇒  brew info libsodium
libsodium: stable 1.0.11 (bottled), HEAD
NaCl networking and cryptography library
https://github.com/jedisct1/libsodium/
/usr/local/Cellar/libsodium/1.0.11 (66 files, 1.1M) *
  Poured from bottle on 2017-01-02 at 11:30:37
```

I haven't dug too deeply, as low-level crypto libraries are definitely not my forte.. Would appreciate some guidance.

**Comment by paragonie-scott** [comment]
If I recall, it's not just AES-NI that's needed. https://github.com/jedisct1/libsodium/issues/234#issuecomment-70028523

**Comment by alias1** [comment]
Interesting.. I had a quick look at the source, and there seem to be like 3 parts that are used to calculate that response. Maybe I can dig a little deeper and see which of those are supposedly missing.

I know this is a bit of a subjective thing, but I was going to use AES256-GCM because my reading seemed to imply it was he best/fastest (if your hardware supports it), but given the issues I've had..I wonder, is the PolyChaCha type thing "just as good"?

My other alternative is to turn to BouncyCastle or maybe even bind myself into AWS KMS.

**Comment by jedisct1** [comment]
Hi!

Can you check what `sodium_runtime_has_aesni()` and `sodium_runtime_has_pclmul()` return on this laptop?

If you don't specifically need AES256-GCM, definitely use `crypto_secretbox` instead. It's likely to be fast enough for your application, and its nonce size makes it easier to use correctly.

**Comment by ivmaykov** [comment]
Just to take care of the obvious, did you call sodium_init() first? I had a bug in some code that was calling crypto_aead_aes256gcm_is_available() in a static variable initializer, so it was being called before sodium_init() and was returning false.

**Comment by alias1** [comment]
..oh dear.. perhaps I should take more breaks/code later into the night.. Most of my code calls init first, but this particular hacky test looks like it may not have been..

Just tested again, and adding init back in seems to pass that check (get a different unrelated error now, but that's almost certainly on me)

Thanks for the help!
