### ISSUE TITLE
ETA for releasing 1.0.12?

### ISSUE THREAD

**Issue by ivmaykov** [jedisct1/libsodium#474]
Do you have any ETA on when 1.0.12 will be released? It's been half a year since the last release and some new primitives (i.e. xchacha20) have been added since then. Thanks!

**Comment by jedisct1** [comment]
1.0.11 is fine, with no critical bugs calling for a new version to be released, so 1.0.12 will essentially be released when it will be ready!

Among the missing things are tests for the new constructions, make the new version work on Windows and other platforms and update the documentation with the new APIs.
