### ISSUE TITLE
Compiling to WebAssembly

### ISSUE THREAD

**Issue by facekapow** [jedisct1/libsodium#475]
Hi, I just wanted to say that I've been able to compile libsodium to WebAssembly via Binaryen and was wondering if you would accept a pull request with a new `dist-build` script for WebAssembly (pretty much just a modified `emscripten.sh`). It would be great for speedy libsodium in browsers and Node.js! 😉

**Comment by jedisct1** [comment]
Of course, that would be great!

I tried to do it a while back, but didn't manage to run the test suite.

**Comment by jedisct1** [comment]
Any updates on this? This is pretty exciting since Chrome is going to enable wasm soon.

**Comment by facekapow** [comment]
Yeah, I'm working on getting browser tests working, but so far, Node.js tests are passing with flying colors.

**Comment by facekapow** [comment]
I've got it working except for 2 catches:

1) With an older version of Emscripten, Node.js tests work fine, however, the current incoming branch uses properties of the WebAssembly object (like Memory) which are implemented in the latest V8 (including Chrome Canary v57.0.2987.4 with V8 v5.7.492), but not the version of V8 the current Node.js uses (Node v7.4.0 with V8 v5.4.500.45). So, it throws because it's performing `instanceof` on an undefined property.

2) In the browser, generichash2 and 3 are failing, I'm guessing because they're not matching the expected test results. Has their code been updated and the expected test results haven't been updated, or is this a WebAssembly build problem?

Also, on a minor note, I based the work off the `stable` branch because master isn't compiling. If I open the PR, would you prefer to me to open it on the `stable` branch or cherrypick my commit(s) onto master in my fork and merge that?

**Comment by jedisct1** [comment]
Thanks for the exciting progress you made!

We can stick to an older Emscripten for now, and update once both Node and Chrome-stable get a V8 update.

The generichash tests failing is something a bit more concerning. There have been no changes that should make them fail. They are also passing in the asm.js tests, so you might have found a WebAssembly problem.

The master branch is broken on Windows, but shouldn't be on Emscripten. I just compiled it fine as asm.js. Where exactly is the build failing?
Could you possibly share your build scripts so I can possibly help?

**Comment by jedisct1** [comment]
Tried with emcc 1.37.1 and whatever binaryen version it automatically retrieved: compilation works fine, and generichash tests are passing, but I only tested with the interpreter, due to the limitations you mentioned.

**Comment by facekapow** [comment]
@jedisct1 Ok, so the problem I was getting before on master was with native WebAssembly was at runtime (I said compiling because the first time I tried it, I didn't realize I was missing some stuff), it complains that `__syscall221` cannot be found (and inspecting the JavaScript module loader file generated by Emscripten reveals it's telling the truth). Weird, since it works with `interpret-binary`. Also, with interpret-binary, the generichash tests are passing. I'm going to open an issue on binaryen for the problem and see what I can get.

Btw, I've uploaded my progress so far to [master on my fork](https://github.com/facekapow/libsodium/).

**Comment by bufke** [comment]
Any progress on this? I'd be happy to support this feature financially if that helps get it done.

**Comment by arashbm** [comment]
@bufke I believe you can pay for this or any other feature requests/commercial support [here](https://www.primulinus.com/).

**Comment by bufke** [comment]
@facekapow do you do any contracting work? Otherwise I can reach out to that company.

**Comment by facekapow** [comment]
My computer broke about a week ago, and I ordered a new one which should be arriving between the 14th and 19th. When I get it, I'll see if I can make any further progress on this.

(P.S. I do all open source contributions free. I haven't done anything on it because I had forgotten about this. @bufke no, I don't do contracting)

**Comment by jedisct1** [comment]
No problem, @facekapow .

Very sorry to hear that your computer broke :(

**Comment by bufke** [comment]
Thanks @facekapow I'm happy to test things out or help in any way I can.

**Comment by facekapow** [comment]
I've gotten the tests all passing (including all the generichashes) with the latest master, but once again, except for 2 tests: `misuse` and `sodium_core` (the problem with the latter is probably that it includes `misuse` code) :cry: They just stop and don't do anything. The memory usage is perfectly normal and they just don't error or do anything at all.

@jedisct1 First of all, I'd like to make sure this is a problem with the WebAssembly build and not just something that isn't implemented or working. Are these tests working in C++?

By the way, if anyone would like to test it out on their computer, I've pushed my current WIP to my fork (https://github.com/facekapow/libsodium) and my current tools in case anyone wants to rebuild for themselves are:
   - sdk-nightly-1.37.9-2017_03_30_19_17-64bit
   - binaryen-master-64bit

You can install with emsdk and the build command is `./dist-build/emscripten-wasm.sh --browser-tests`.

To open `full-browser-suite.html` for a nice browser test UI, you have to make a server in the libsodium root directory (with something like [`http-server`](https://www.npmjs.com/package/http-server)) and then go to `localhost:<whatever-port-your-server-is-on>/test/full-browser-suite.html`

**Comment by pepyakin** [comment]
@facekapow did you tried to compile and run tests via asm.js? If yes, do these tests also behave same as wasm builds?

**Comment by facekapow** [comment]
@pepyakin No, not yet, thanks for the idea though, I'm actually going to try that right now.

**Comment by jedisct1** [comment]
Did you manage to run the tests using node?

`--tests` still complains about `__syscall146` (latest Emscripten-incoming, latest Binaryen)

```
TypeError: Right-hand side of 'instanceof' is not an object
    at ___syscall146 (/Users/j/src/libsodium/test/default/xchacha20.js:3:180931)
    at cb (/Users/j/src/libsodium/test/default/xchacha20.js:7:84229)
    at Array.Ob (/Users/j/src/libsodium/test/default/xchacha20.js:7:98756)
    at sb (/Users/j/src/libsodium/test/default/xchacha20.js:7:92966)
    at Fb (/Users/j/src/libsodium/test/default/xchacha20.js:7:96847)
    at eb (/Users/j/src/libsodium/test/default/xchacha20.js:7:86173)
    at be (/Users/j/src/libsodium/test/default/xchacha20.js:7:112500)
    at Object.Vd [as _main] (/Users/j/src/libsodium/test/default/xchacha20.js:7:111977)
    at Object.callMain (/Users/j/src/libsodium/test/default/xchacha20.js:14:3017)
    at doRun (/Users/j/src/libsodium/test/default/xchacha20.js:14:3760)
```

**Comment by aykevl** [comment]
(following this discussion with interest)
@facekapow does it just allocate memory, or also fill the memory?
Note that by default, at least Linux does optimistic allocation meaning that programs can easily allocate large amounts of memory without actually increasing their memory usage. Only the moment it is actually written to is the memory truly allocated in RAM. Go does this for example: it allocates large amounts of memory but (initially) uses very little of it.
So maybe not setting `TOTAL_MEMORY` doesn't really matter for actual (non-virtual) memory usage.

Then again, maybe wasm works very different or maybe this is a real issue on different kernels.

**Comment by pepyakin** [comment]
Indeed, WebAssembly works same way. Citing http://webassembly.org/docs/modules/#linear-memory-section:

> When declared [maximum memory size], implementations should (non-normative) attempt to reserve virtual memory up to the maximum size. While failure to allocate the initial memory size is a runtime error, failure to reserve up to the maximum is not. When a maximum memory size is not declared, on architectures with limited virtual address space, engines should allocate only the initial size and reallocate on demand.

**Comment by jedisct1** [comment]
As far as I know, `TOTAL_MEMORY` is still required for asmjs, that we will want to support for browsers that can't handle wasm yet.

Not setting it would reserve too little memory for the asmjs version.

Or maybe we can compile the code without setting `TOTAL_MEMORY`, but still set it later at runtime if we detect that the asmjs backend should be used?

**Comment by jedisct1** [comment]
@facekapow How do you run the test suite using Node?

I could never get `emscripten-wasm.sh --tests` to work :/

**Comment by jedisct1** [comment]
@facekapow Nevermind. Looks like current Node versions don't need `--expose-wasm` any more, and run the test suite just fine without it. Great!

The last thing before we can way WebAssembly is good to go is proper support in libsodium.js.

Right now, it should work fine in Node, but won't work in web browsers.

**Comment by jedisct1** [comment]
Another complication (on Brave Browser):
```
failed to compile wasm module: RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
```

The js code from Emscriptencalls `WebAssembly.compile()`, so we can't do it ourselves in a worker.

**Comment by pepyakin** [comment]
@jedisct1 This should be also be the case for Chrome. I believe that I had encountered something like this.

**Comment by jedisct1** [comment]
Patch Emscripten's code
```js
instance=new WebAssembly.Instance(new WebAssembly.Module(getBinary()),info)}
```

To use a precompiled module instead?

Things are becoming really hackish and complicated :/

**Comment by jedisct1** [comment]
At this point, we can enable WebAssembly for Node.

But I don't see any simple ways to make it work in a browser.

Current blockers:
- `libsodium.wasm` has to be `fetch()`ed and stored into `Module.wasmBinary` prior to anything else. Easy to do, even though it means that we cannot support a synchronous load API any more. This is probably acceptable.
- Creating a new `WebAssembly` instance cannot be done in the main thread on Brave/Chrome. We can hack the Emscripten-generated code to avoid creating this instance, but we won't be able to prepare this instance with the correct environment (with `DYNAMICTOP_PTR` and friends being properly defined).

So what are our options here? Keep everything in a worker from begin to end, and build a proxy API to calls the functions from the main thread? It wouldn't be too bad for some operations (`crypto_pwhash`), but it would be really lousy for everything else.

WebAssembly instances can be `postMessage()`'d to other threads. So maybe the `libsodium` Module could be built in a worker, and then re-built in the main thread using the already existing wasm instance?

Or presumably there is a super simple way to achieve that, but I don't see it.

**Comment by facekapow** [comment]
For the testing I had to do all the tests in a worker, but the performance hit is very small, and actually, possibly better or on par with doing it in the main thread. IMO, doing everything in a web worker and just proxying everything (even if you're then forced to use the functions  asynchronously) sounds just fine.

**Comment by jedisct1** [comment]
I like the idea of using workers, but that completely breaks the current API and applications relying on it :(

**Comment by jedisct1** [comment]
Another thing...

When `BINARYEN_METHOD` is set to `native-wasm,asmjs` (which seems to be the default), neither the wasm code nor the asmjs code are optimal.

So, we need to set `BINARYEN_METHOD` to `native-wasm`.

Easy, right? Add `export CFLAGS="${CFLAGS} -s BINARYEN_METHOD='native-wasm'"` and call it a day?

Unfortunately not, due to the quotes. It compiles, but then the linker fails:

```
  CC       crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo
Traceback (most recent call last):
  File "/usr/local/Cellar/emscripten/HEAD-3bfcf9c/libexec/emcc", line 13, in <module>
    emcc.run()
  File "/usr/local/Cellar/emscripten/HEAD-3bfcf9c/libexec/emcc.py", line 881, in run
    exec 'shared.Settings.' + key + ' = ' + value in globals(), locals()
  File "<string>", line 1, in <module>
NameError: name 'native' is not defined
make[3]: *** [crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

Yay :(

**Comment by jedisct1** [comment]
Actually, [this](https://github.com/WebAssembly/binaryen/issues/822#issuecomment-261404611) seems to say that `native-wasm` is the default.

But eventually, we still get an asmjs version along with the wasm version, and the asmjs version gets the `"almost-asm"` annotation which is typical of wasm+asmjs builds.

**Comment by jedisct1** [comment]
The [settings.js file](https://github.com/kripken/emscripten/blob/incoming/src/settings.js#L696) seems to confirm it.

How come an (almost)asmjs version still gets built then?

**Comment by pepyakin** [comment]
Hm, isn't this is the way emscripten works? AFAIK, emscripten compiles C code to the asm.js and then processes it with `asm2wasm` (from binaryen) tool to get actual WebAssembly binary.

**Comment by jedisct1** [comment]
Is that still the case? Doesn't it use `s2wasm` these days?

**Comment by jedisct1** [comment]
And maybe not, `s2wasm` is used by Rust and possibly other compilers, but still not by Emscripten.
Ok, that would explain it, then.
No need to find a way to work around these `BINARYEN_METHOD` quotes. Phew!

**Comment by pepyakin** [comment]
(Nope, Rust using [asm2wasm](https://github.com/WebAssembly/binaryen/issues/1105) [too](https://github.com/WebAssembly/binaryen/issues/1109))

**Comment by jedisct1** [comment]
Cool, so we should just ignore these .asm.js files, and create the actual asmjs code by recompiling without `-s wasm`.

What would be a way to check that the browser can compile code that is > 4 KB? Build an array of NOPs and try to compile it?

**Comment by pepyakin** [comment]
As an option. But why do you want to check it?

**Comment by jedisct1** [comment]
If the wasm code is too large be loaded in the main thread, we can then fallback to the asmjs implementation.

**Comment by pepyakin** [comment]
> What would be a way to check that the browser can compile code that is > 4 KB?

Can we just try to `compile` and in exception handler fallback to asmjs version?

**Comment by BurningEnlightenment** [comment]
Is it planned to provide a llvm/emscripten bitcode release of the library? This would ease the porting process of existing native solutions which rely on libsodium.
Ref https://kripken.github.io/emscripten-site/docs/compiling/Building-Projects.html#using-libraries

**Comment by jedisct1** [comment]
So, libsodium.js now supports WebAssembly.

This is ugly and hacky. Hope this is something that can be improved later. But it's there.

Thanks to everybody who helped!
