### ISSUE TITLE
Warning building on Solaris 10 with gcc 4.8.2

### ISSUE THREAD

**Issue by selsky** [jedisct1/libsodium#476]
```
../../libsodium/randombytes/sysrandom/randombytes_sysrandom.c: In function 'randombytes_sysrandom_buf':
../../libsodium/randombytes/sysrandom/randombytes_sysrandom.c:310:5: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     assert(size <= ULONG_LONG_MAX);
     ^
```
size is of type size_t so I think we want to compare to SIZE_MAX instead (assuming C99) since C99 ensures that SIZE_MAX is the proper size for the current platform.  And likely the ifdef should check for SIZE_MAX as well, if we can't assume a C99 compiler.

Thanks!

**Comment by jedisct1** [comment]
Checking that a `type` value is less than or equal to `type_MAX` is true by definition and would not be very useful even from a semantic perspective.

Here, the code that follows assumes that the value fits in the `unsigned long long` type, which may not be the case if the value is 128-bit. This is what we are explicitly checking.
On many platforms, this can't be the case, the compiler can figure it out at compile time and will not emit any code for that check. This is what this message suggests, and this is perfectly fine.

**Comment by zoulasc** [comment]
I don't see the point to compare with ULONG_LONG_MAX; I think you meant to compare with SSIZE_MAX since this is what you are casting to in the code. Can you please explain why you are comparing with ULONG_LONG_MAX?

**Comment by FSMaxB** [comment]
Also doesn't [this code](https://github.com/jedisct1/libsodium/blob/de3c0ff85ee0016805d570bb797064957bda9da8/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c#L334-L339) assume that `ULONG` is not smaller than 64 bit, is that assumption valid?

```c
if (size > (size_t) 0xffffffff) { //<-- maximum 8 bit integer
    abort(); /* LCOV_EXCL_LINE */
}
if (! RtlGenRandom((PVOID) buf, (ULONG) size)) {
    abort(); /* LCOV_EXCL_LINE */
}
```

**Comment by jedisct1** [comment]
The whole API assumes that sizes are `unsigned long long` values. This convention was required to be ABI compatible with NaCl.

The `randombytes` functions are the exception, since they follow their OpenBSD counterpart. 

I would not feel comfortable receiving a value whose size would not be compatible with the rest of the API here. Granted, with the current code, it cannot currently happen from internal calls. But considering the fact that the corresponding compiled code doesn't even exist in the context of the compiled warning being discussed here, it doesn't hurt having it around.

**Comment by jedisct1** [comment]
@FSMaxB This is the WIndows-specific code path. It assumes that the length is not larger than what that specific Windows function can handle.

**Comment by FSMaxB** [comment]
Ok, at least currently it might make sense to assume that Windows is not ported to platforms where that assumption is not valid. But are you sure? What happens on Window-RT or Windows-Phone for example?

**Comment by jedisct1** [comment]
Nothing different. `0xffffffff` is 32 bits long, not 64.

**Comment by FSMaxB** [comment]
Oh, ... my bad.

**Comment by zoulasc** [comment]
What I was saying is that read(2) will not work anyway if size > SSIZE_MAX according to http://pubs.opengroup.org/onlinepubs/7908799/xsh/read.html, so you might as well change the assert to that so that the compiler does not warn :-)

**Comment by jedisct1** [comment]
There is already such as check before the actual `read()` call. The purpose of these checks is to potentially prevent security issues, not to make the compiler silent about the fact that it performed an expected optimisation.

**Comment by zoulasc** [comment]
Yes, I see that now. Thanks for clarifying; would be nice to silence the warning though.
