### ISSUE TITLE
android-build.sh do not work

### ISSUE THREAD

**Issue by ppmag** [jedisct1/libsodium#481]
Hi,
at least for 'stable' branch 
I just discovered script
libsodium/dist-build/android-build.sh
is failing due to unknown option "--force".

After removing it (two places)  I was able to build *.so for all ABIs.
My platform is Ubuntu Linux x86_64.

Pls let me know if some additional details required for reproduction.

**Comment by jedisct1** [comment]
Mmm what version of the NDK do you have?

**Comment by ppmag** [comment]
android-ndk-r12b-linux-x86_64

**Comment by jedisct1** [comment]
Can you try with the current stable version (`r13b`)?

**Comment by jedisct1** [comment]
Ping?

**Comment by ppmag** [comment]
r13b  has NO this issue.

I was using r13b because it set by default in 
https://github.com/joshjdevl/libsodium-jni

But just changed there to use r13b and this issue is not reproducing.
Closing this.
