### ISSUE TITLE
Installation on windows

### ISSUE THREAD

**Issue by monicaphalswal** [jedisct1/libsodium#484]
Can anyone please explain the proper method of installing libsodium in windows to be used with MinGW.

**Comment by jedisct1** [comment]
Hi Monica,

If you are using msys2, the easiest way is to just install the package:

```sh
pacman -S 
```

The library and the headers will be ready for use with mingw.

**Comment by monicaphalswal** [comment]
So what's the name of the package?

**Comment by jedisct1** [comment]
The package is named `libsodium`.

**Comment by monicaphalswal** [comment]
I got `error: target not found: libsodium`
when I did `pacman -S libsodium` in msys2 console.

**Comment by niXman** [comment]
i686-libsodium/x86_64-libsodium

**Comment by monicaphalswal** [comment]
i'm still getting` target not found`

**Comment by niXman** [comment]
`pacman -S mingw-w64-x86_64-libsodium`

**Comment by monicaphalswal** [comment]
@niXman Thanks, it is installed now but, I am  still getting 
 ```
fatal error: sodium.h: No such file or directory
compilation terminated.
```

**Comment by niXman** [comment]
`#include <sodium/sodium.h>`

**Comment by monicaphalswal** [comment]
Still getting same error.

**Comment by niXman** [comment]
please show the result of `gcc -v` and `cat /mingw64/include/sodium/sodium.h` commands.

**Comment by monicaphalswal** [comment]
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/5.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-5.3.0/configure --build=x86_64-pc-linux-gnu --host=m
ingw32 --prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i58
6 --enable-languages=c,c++,objc,obj-c++,fortran,ada --enable-static --enable-sha
red --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-sp
ecific-runtime-libs --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with
-tune=generic --enable-libgomp --disable-libvtv --enable-nls : (reconfigured) ..
/src/gcc-5.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --prefix=/mi
ngw --disable-win32-registry --target=mingw32 --with-arch=i586 --enable-language
s=c,c++,objc,obj-c++,fortran,ada --enable-static --enable-shared --enable-thread
s --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs
 --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-d
ebug --with-tune=generic --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 5.3.0 (GCC)

**Comment by monicaphalswal** [comment]
This is location of sodium.h in my PC `C:\msys64\mingw64\include\sodium.h`

**Comment by niXman** [comment]
Oh...
\
You use 32bit mingw, but sodium for 64bit =)

Try `pacman -S mingw-w64-i686-libsodium`

**Comment by niXman** [comment]
And simple `#include <sodium.h>` not `#include <sodium/sodium.h>`

**Comment by monicaphalswal** [comment]
Ok so now I have sodium.h in C:\msys64\mingw32\include\sodium.h also. And have done #include <sodium.h> but I am still getting the same error.

**Comment by monicaphalswal** [comment]
I am compiling it as `g++ test.cpp -o test.exe`

**Comment by niXman** [comment]
show error.

**Comment by monicaphalswal** [comment]
C:\Users\mp\Desktop\nacl>g++ test.cpp -o test.exe
test.cpp:1:20: fatal error: sodium.h: No such file or directory
compilation terminated.

**Comment by niXman** [comment]
you shoud use mingw installed into msys2 using pacman: `pacman -S mingw-w64-i686-toolchain`

**Comment by niXman** [comment]
```
printf "#include <sodium.h>\n\nint main() {return sodium_init();}" > test.cpp
g++ test.cpp -otest -lsodium
```

**Comment by monicaphalswal** [comment]
I am installing mingw into msys2.  I have above code only in test.cpp

**Comment by monicaphalswal** [comment]
Working now. Thanks a lot :) But I think installation for windows should be documented properly.
