### ISSUE TITLE
Use libsodium in IAR for ARM cortex M3

### ISSUE THREAD

**Issue by monicaphalswal** [jedisct1/libsodium#485]
How do I compile **libsodium** in IAR for **ARM cortex M3**?
 I only want to use just 2 functions,
`crypto_secretbox_easy()` and `crypto_secretbox_open_easy()`, so is it feasible to just use source of these two functions and their dependencies.

**Comment by jedisct1** [comment]
Hi,

I'm really sorry but I don't know what IAR is.
