### ISSUE TITLE
Install doc error

### ISSUE THREAD

**Issue by n7ekg** [jedisct1/libsodium#486]
I used git clone to pull down the library source, then tried to follow the directions in the install section of the documentation. First, there's no section for using git to pull the source, and second, there's no "configure" file in the cloned source. So, how do I build the library?

**Comment by jedisct1** [comment]
The recommended and documented ways are to:
- Either use release tarballs, available for download here: https://download.libsodium.org/libsodium/releases/
- Or if you want to use git, use the `stable` branch:  `git clone https://github.com/jedisct1/libsodium --branch stable`

These include everything you need to build them.
