### ISSUE TITLE
Unable to find Argon2 functions during runtime

### ISSUE THREAD

**Issue by t206** [jedisct1/libsodium#487]

**Comment by t206** [comment]
Crypto_pw_hash and it's string variant compile correctly and with no warnings but the symbols for these functions are undefined at runtime. All I can assume is that they don't exist in the installed C library yet all the make check tests pass. The library was compiled and installed on a Raspberry Pi 2 system running Ubuntu 16.04 LTS using the standard configure and make scripts. Is there a special switch that must be invoked to include the Argon2 functionality? I also tried the _argon2_ functions and they're missing as well. Library version is 1.0.11 stable branch.

**Comment by jedisct1** [comment]
Double check that you haven't multiple versions installed on the same system.

Such as one in `/usr/local` and one in `/usr`.
