### ISSUE TITLE
lbSodium.dll for .net Server 2008 R2 Deployment Issue

### ISSUE THREAD

**Issue by Shuvodeep1** [jedisct1/libsodium#492]
Hi,
We have two version of libsodium library (32 bit & 64 bit) which we have downloaded from GitHub.

We are trying to build a simple interface for the user that will be hosted on IIS Server 7 and would provide the user with a functionality of setting a hashed PIN that will be saved against the Active Directory attribute of the user.

However, since we have encountered some issues with the deployment of the same web application on the server box, we now have created a stand-alone application. The web application works with IIS Express on the developers Windows 7 box though.
We have been encountering the issue of invoking the libSodium exposed apis from our wrapper class.

We are using the call to this libraries from our project using a wrapper class which is build by .net C#.
There is method implemented in the wrapper class that actually  decides which version of library  should be loaded based on the OS environment.
We were keeping this two dll files in project bin folder and the path of bin folder also has been set in environment variable.
Build the wrapper class and got a sodium.dll file which has  been  taken as reference in project solution and finally build this project solution and run on my local workstation(Windows 7) and it was working.

1st Scenario:

While we have tried to deploy this project to our test server(Windows server 2008 R2) and run it has been thrown some exception mention below.

Error For 32 bit:
```
Inner Exception: Unable to load DLL 'libsodium.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
2nd Scenario:

We thought the windows server 2008 has not recognized this 32 bit dll and we have changed the configuration file and build the wrapper class dll into 64 bit env and the project solution also.
In this case we are unable to run this project on both env In our  local work station as well as windows server env and the error is:

Error For 64bit :
```
Unable to load DLL 'libsodium-64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E).
```
We have been trying to go through multiple threads in the web space on the discussions on the same topic. But, could not reach to a conclusive solution over a period of almost a month now.

So, trying to reach out and explore all possible ways to get this resolved. Maybe, someone has some ready solution to this and you  might help us in trying to find out the same.

-Best Regards,
Shuvodeep Ghosh
+919830240849

**Comment by jedisct1** [comment]
That looks like an issue with IIS or with your code.

Is your wrapper available somewhere? Is it an opensource project?

**Comment by Shuvodeep1** [comment]
Although I see this as closed. But this is still an open issue. 

This seems not to be working as a stand-alone application. So, not a issue with IIS.

The wrapper is an open source project and is available in Github.

**Comment by jedisct1** [comment]
Googling for [libsodium-64.dll](https://www.google.com/?gfe_rd=cr&ei=ow-9WKSdI8eGuwTjur2oAw&gws_rd=cr#q=libsodium-64.dll&*) gives quite a lot of pointers to similar issue.

This file is not part of the libsodium distribution, so as the number of answers confirm, this repository is not the best place to get an answer for it.
