### ISSUE TITLE
possible macro typo for Visual Studio

### ISSUE THREAD

**Issue by wongsyrone** [jedisct1/libsodium#496]
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/runtime.c#L152

`# ifdef MSC_VER` should be `# ifdef _MSC_VER`

**Comment by jedisct1** [comment]
Good catch for the `_MSC_VER` typo, thanks!

Including redundant headers is fine, I don't this this is an issue for Visual Studio.

Thanks!

**Comment by wongsyrone** [comment]
Okay. Let me make it clear. When compiling with VS, optimized code is protected by macros like:

```
HAVE_MMINTRIN_H
HAVE_EMMINTRIN_H
HAVE_PMMINTRIN_H
HAVE_TMMINTRIN_H
HAVE_SMMINTRIN_H
HAVE_AVXINTRIN_H
HAVE_AVX2INTRIN_H
HAVE_WMMINTRIN_H
```

Can I just add them to pre-defined macros to enable instruction set detection?

One example:

We can only use the ref variant of chacha20 without these macros for VS compiled DLL, https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_stream/chacha20/stream_chacha20.c#L101-L113

**Comment by wongsyrone** [comment]
@jedisct1 Any thought?

**Comment by jedisct1** [comment]
You missed something: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/private/common.h#L195

**Comment by wongsyrone** [comment]
Sorry. I didn't check master branch, just based on v1.0.11.
