### ISSUE TITLE
stream_chacha20.c missing intrin macro definitions

### ISSUE THREAD

**Issue by wongsyrone** [jedisct1/libsodium#500]
After adding `#include "private/common.h"` to `src/libsodium/crypto_stream/chacha20/stream_chacha20.c`, avx2 and ssse3 detection works.

**Comment by wongsyrone** [comment]
Other modules may also be affected. The above one is an example.

**Comment by jedisct1** [comment]
I know :) Windows support is still not done yet.

**Comment by jedisct1** [comment]
Added! Thanks!

**Comment by wongsyrone** [comment]
Okay. I commented my testing result after trying AVX2 on x86: https://github.com/jedisct1/libsodium/commit/4fea4d917b8e6e2534feded33a78eb67e16b0d7a.

I'm looking forward to the new release.
