### ISSUE TITLE
fails to build on msys

### ISSUE THREAD

**Issue by zhou0** [jedisct1/libsodium#502]
CC       sodium/libsodium_la-utils.lo
```
sodium/utils.c:14:23: fatal error: sys/mman.h: No such file or directory
 # include <sys/mman.h>
                       ^
```
compilation terminated.

**Comment by jedisct1** [comment]
What version is that? 1.0.11? Stable?

**Comment by jedisct1** [comment]
That's a bit surprising since this include is protected by a conditional macro.

Can you post a copy of the `config.log` file somewhere?

**Comment by zhou0** [comment]
building it with MSYS is a bad idea,  I have successfully build it with mingw (w/o msys ).  If you build it on MSYS it will treat it like building on Linux and ask for sys/mman.h which is only available on Linux.
