### ISSUE TITLE
Pre-release for .NET Core

### ISSUE THREAD

**Issue by ektrah** [jedisct1/libsodium#504]
This issue is intended to track the progress towards a pre-release of a libsodium package for .NET Core.

The purpose of the package is to provide pre-compiled binaries for a number of platforms for the implementation of .NET Core language bindings such as [nsec](https://github.com/ektrah/nsec). The package does not provide a .NET API itself.

**Issues**

- [x] Tooling

  Add the scripts and files needed to build a libsodium package for .NET Core to the libsodium repository.

- [ ] Package metadata

  Metadata includes the package name, description and URLs. See the [libsodium.props](https://github.com/jedisct1/libsodium/blob/master/packaging/dotnet-core/libsodium.props) file. To avoid confusion, the description should IMO indicate that the package is intended for use with .NET Core only and not usable stand-alone.

- [x] Versioning

  ~~.NET Core uses [semver](http://semver.org/) for versioning: `major.minor.patch`. This means libsodium version numbers can be used as-is, but each new package release (e.g., when adding support for a new platform or if a package contains a broken binary) would always require a new libsodium version. This could be avoided, for example, by using different version numbers for the packages or switching libsodium to `major.minor` version numbers.~~

  Although .NET Core uses [semver](http://semver.org/) for versioning, it is possible to use version numbers with four parts for packages: `major.minor.patch.build`. This means that `major.minor.patch` can be used for the libsodium version, and `build` to number the packages released for a libsodium version.

- [ ] Logo

  Optional, but nice to have. Should be 128x128 and should look good when resized to 64x64 and 48x48.

- [ ] Building the package

  See the [README.md](https://github.com/jedisct1/libsodium/blob/master/packaging/dotnet-core/README.md) file.

- [ ] Publishing the package

  This requires an account at [nuget.org](https://www.nuget.org/). It's possible to grant other people uploading rights for a package once created, so if you like, I could take over the building and publishing steps.

**Comment by BurningEnlightenment** [comment]
I would like to drive this effort further forward. I'm currently augmenting the package files to also support the AnyCPU .net framework target which will (eventually) enable [libsodium-net](https://github.com/adamcaudill/libsodium-net) to also use this package instead of distributing their own binaries.
I also recommend choosing a package name which matches the .NET naming scheme, e.g. `Sodium.Raw.Library`. This would have the benefit that we could provide an xplat assembly just DllImporting the raw apis under `Sodium.Raw.Api` serving as a starting point/bundling efforts for the different abstraction layers like nsec and libsodium-net. @ektrah what are your thoughts on this?

**Comment by ektrah** [comment]
Yes, I hope this package is useful for libsodium-net as well and I believe it should be quite easy for libsodium-net to support .NET Core (https://github.com/adamcaudill/libsodium-net/issues/148) once this package is released.

Supporting .NET Framework would be nice, but it seems to have a much more complicated story for distributing native binaries than .NET Core, in particular if you want to support ASP.NET (shadow copying), 32-bit and 64-bit platforms, Mono, etc.

I have an MSBuild snippet for .NET Framework that copies the right Windows DLL to the `bin` directory depending on the bitness, but I haven't tried to make it work for the other cases yet. I would like to start with .NET Core and try to add support for .NET Framework later. But maybe you could put your augmentations in a gist or branch so it's ready when we decide to do it?

There are a bunch of different naming conventions for packages with native binaries, e.g., [runtime.native.System.IO.Compression](https://www.nuget.org/packages/runtime.native.System.IO.Compression/), [Microsoft.Xaml.Behaviors.Uwp.Native](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Uwp.Native/), or [Libuv](https://www.nuget.org/packages/Libuv/). I don't have a strong opinion which one would be best for the libsodium package, but I think we should pick one of those and not invent a new naming convention.

I don't think we should provide a package that exposes the DllImport methods. These are implementation details and should be hidden behind by the high(er)-level APIs. Also, I'm not sure if it's possible to make DllImport signatures that make everyone happy. For example, nsec needs signatures that accept `Span<byte>`, while libsodium-net needs `byte[]`.

**Comment by BurningEnlightenment** [comment]
> There are a bunch of different naming conventions for packages with native binaries, e.g., `runtime.native.System.IO.Compression`, `Microsoft.Xaml.Behaviors.Uwp.Native`, or `Libuv`. I don't have a strong opinion which one would be best for the libsodium package, but I think we should pick one of those and not invent a new naming convention.

yeah, I know 😓. I personally vote for `Sodium.Native`, because it's *different* from `libsodium_vc120`.

> Supporting .NET Framework would be nice, but it seems to have a much more complicated story for distributing native binaries than .NET Core, in particular if you want to support ASP.NET (shadow copying), 32-bit and 64-bit platforms, Mono, etc.

Yes, it's more complicated, but I think it's sufficient to start with a solution that covers what is already covered by `libsodium-net`, i.e. full framework >= 4.6 and handling the bitness issue. If someone needs Mono/shadow copying support they still can provide the necessary patches.

> I have an MSBuild snippet for .NET Framework that copies the right Windows DLL to the bin directory depending on the bitness, but I haven't tried to make it work for the other cases yet. I would like to start with .NET Core and try to add support for .NET Framework later. But maybe you could put your augmentations in a gist or branch so it's ready when we decide to do it?

I opted for the approach taken by `SQLitePCL.raw`: #547 
This of course needs to be supported by the higher layers which leads to:

> I don't think we should provide a package that exposes the DllImport methods. These are implementation details and should be hidden behind by the high(er)-level APIs. Also, I'm not sure if it's possible to make DllImport signatures that make everyone happy. For example, nsec needs signatures that accept `Span<byte>`, while libsodium-net needs `byte[]`.

The thing I was mainly concerned with was that the library initialization process is somewhat more complicated on net46 and higher. I have to admit that I just took a brief look at your Interop layer and it looked very similiar which is why I suggested trying to deduplicate the DllImport maintenance work. However, I still think that it will be beneficial to share the native library loading code (which I'm currently developing) for net46 and higher.

**Comment by BurningEnlightenment** [comment]
From https://github.com/jedisct1/libsodium/pull/547#issuecomment-302729106
> it works only in a very narrow set of cases for .NET Framework and requires nasty, platform-specific hacks such as LoadLibraryEx to get it even barely working.

You won't get around those platform specific hacks. Furthermore this is exactly what major Microsoft projects like `EntityFrameworkCore` (through `SQLitePCL.raw`) do rely on. Which major use cases apart from `shadow copying`<=>`asp.net` don't work?

**Comment by ektrah** [comment]
For comparison, here is my MSBuild snippet: [gist](https://gist.github.com/ektrah/0e9c4f988bb8fa870b8d77dbc051f2d6). It copies only one DLL to the output directory so that the normal DllImport mechanism can be used and LoadLibraryEx is not needed.

I don't know what cases don't work because I haven't done any testing yet. My focus is on shipping a stable, well-tested package for .NET Core.

**Comment by BurningEnlightenment** [comment]
> I don't know what cases don't work because I haven't done any testing yet. My focus is on shipping a stable, well-tested package for .NET Core.

That's absolutely fine; my patch didn't change anything regarding the .net core configuration and it will continue to work for the core platform as it did before.

> For comparison, here is my MSBuild snippet: gist. It copies only one DLL to the output directory so that the normal DllImport mechanism can be used and `LoadLibraryEx` is not needed.

My problem with your script is the `'$(Platform)|$(Prefer32Bit)' == 'AnyCPU|false'"` part; it will work as long as the consuming application stays on a x64 machine. This somewhat defeats the purpose of building AnyCPU and sadly isn't a solution for the shadow copying issue either. Which is why I want to distribute both binaries (only on net46!). The consequence is that you have to provide a little hint to the runtime through `LoadLibraryEx` before calling any DllImported function which makes this the least intrusive option in my opinion.

**Comment by BurningEnlightenment** [comment]
@jedisct1 would it be possible for you to sign the windows dlls with a code signing certificate? I know that you sign the current binary distribution for windows with minisign, but that signature is neither available nor applicable for a repacked nuget package.

**Comment by jedisct1** [comment]
Mmmmm, but code signing certificates aren't exactly free, are they? Or is there a way to get free certificates for open-source projects?

**Comment by BurningEnlightenment** [comment]
Yes, usually you have to pay for code signing certificates, but for example [certum.eu](https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml) is kind enough to provide code signing certificates for open source projects for free. I know that @adamcaudill uses "certum" certificates for the lobsodium binaries provided with libsodium-net. HTH

**Comment by BurningEnlightenment** [comment]
Seems like no one is giving away free certificates for open source projects anymore 😞; from what I've seen certum still seems to be the cheapest option for open source projects with a yearly 28€ price tag (if you have a crypto card and a reader). Seems like a very unfortunate situation 😒

**Comment by evoskuil** [comment]
Hi @jedisct1, I just noticed you copied me a while back. Glad to help if I can but not sure what if anything is needed on my end.

**Comment by adamcaudill** [comment]
> Seems like no one is giving away free certificates for open source projects anymore

Indeed, as far as I can tell, there's no free options anymore. Certum seems to still be the best value; I've tried to convince contacts at other CAs to offer something for OSS, but to no avail. Handling OSS projects doesn't fit well in the requirements standard, so it makes it a bit difficult for CAs to offer something that makes sense. Certum has been quite kind to offer a low-cost option tied to an individual developer's name, which is about as good as it gets right now.

**Comment by BurningEnlightenment** [comment]
@ektrah what's still missing/needs to be decided in terms of package metadata? I think we hit a point where it makes sense to release at least a prerelease package on nuget or did I miss something important?

@jedisct1 are you willing to publish the package to nuget yourself when it's ready?

**Comment by jedisct1** [comment]
I'd be glad to publish it on Nuget but I have no idea how to do that :)

**Comment by ektrah** [comment]
Yes, let's make a pre-release!

The package currently generates some warnings when used with the .NET Core 2.0 preview. It's mis-detected as a .NET Framework package because of the net46 files in it, but otherwise it seems to work. We should watch the development here before making a stable release.

The package metadata just needs an OK from @jedisct1. It can be changed at any later time, though. A logo isn't important right now as well.

@jedisct1:
* `python3 prepare.py 1.0.12-preview-01`
* `make`
* `make test`
* Create an account at nuget.org
* Sign in
* Select [Upload package](https://www.nuget.org/packages/manage/upload)
* Upload `build/libsodium.1.0.12-preview-01.nupkg`

**Comment by LammyL** [comment]
You also need to make sure the version number in https://github.com/jedisct1/libsodium/blob/master/builds/msvc/resource.rc matches the one specified on the command line.  The exes right now are set to compile by embedding version number 1.0.13.0 based on the resource file.

**Comment by ektrah** [comment]
@LammyL: The packaging script downloads the released tarball/zip for the specified version. It does not compile the binaries from the GitHub repository. If the resource.rc was correct at the time of the release, nothing needs to be done.

**Comment by LammyL** [comment]
@ektrah wonderful.  that makes things super easy.  i forgot it did that.

**Comment by jedisct1** [comment]
Boom!

https://www.nuget.org/packages/libsodium/1.0.12-preview-01

**Comment by danielcrenna** [comment]
At this point we have libsodium 1.0.15 which works great in .NET Standard 2.0, but it's still the internal package, requiring a wrapper assembly. `libsodium-net` version on Nuget still uses .NET 4.6.1, and @tabrath's `Sodium.Core` package is out of date (and I had trouble using it with .NET Core 2.0 apps, compiler warnings et al.).

I'm resorting to shipping custom source that binds to 1.0.15. It works fine, but it would be nice to get a proper multi-targeted NuGet package at `libsodium-net`.
