### ISSUE TITLE
Feature request: support unified headers starting from NDK r14

### ISSUE THREAD

**Issue by wongsyrone** [jedisct1/libsodium#505]
https://github.com/android-ndk/ndk/wiki/Changelog-r14

https://android.googlesource.com/platform/ndk/+/master/docs/UnifiedHeaders.md

**Comment by jedisct1** [comment]
Done in 79fe40cfe848dea6482051f79dca1f23002c3536

Thanks!

**Comment by wongsyrone** [comment]
Thanks.
As long as I know, `make_standalone_toolchain.py` shipped by NDK only works on Python 2, for some cutting-edge distros like Archlinux, we have to use `python2 make_standalone_toolchain.py`

**Comment by jedisct1** [comment]
And mips32 doesn't compile any more, and the same change breaks dnscrypt-proxy since `stdout` and `stderr` are not defined any more.

Do you know how to possible fix these?

**Comment by wongsyrone** [comment]
> The legacy headers will be removed in a future release. It is likely that r15 will default to using these while still being optional. If all goes well, the legacy headers will be removed in r16, so please test them now.

Then we may revert it and report bugs to Google?

**Comment by jedisct1** [comment]
Looks like it was broken prior to that change.

Not sure what's causing it. Maybe the update to r14. The generated toolchain seems to want to use gcc-mips64 to compile for mips32.

**Comment by wongsyrone** [comment]
For new toolchain, Google says GCC will not be removed and will no longer receive backports. How about switch to clang and test again?

**Comment by wongsyrone** [comment]
> GCC is no longer supported. It will not be removed from the NDK just yet, but is no longer receiving backports. It cannot be removed until after libc++ has become stable enough to be the default, as some parts of gnustl are still incompatible with Clang. It will likely be removed after that point.

**Comment by jedisct1** [comment]
The build scripts do not specifically try to use gcc. The environment is setup by `make_standalone_toolchain.py`.

**Comment by wongsyrone** [comment]
Okay. I will try the script and see what is going on when have free time.

**Comment by jedisct1** [comment]
Thanks a lot for your help!

**Comment by wongsyrone** [comment]
I just checked NDK r14's make_standalone_toolchain.py; it works well on Python 3.6.
But the script is broken, here goes the result:

```
ls arm64-unifi

aarch64-linux-android/  bin/     COPYING3      COPYING.LIB      include/  lib64/    manifest_3362437.xml     MODULE_LICENSE_GPL  NOTICE     share/    test/
AndroidVersion.txt      COPYING  COPYING3.LIB  COPYING.RUNTIME  lib/      libexec/  MODULE_LICENSE_BSD_LIKE  MODULE_LICENSE_MIT  repo.prop  sysroot/  tools/

ls mips64-unifi

AndroidVersion.txt  COPYING   COPYING3.LIB  COPYING.RUNTIME  lib/    libexec/              mips64el-linux-android/  MODULE_LICENSE_GPL  NOTICE     share/    test/
bin/                COPYING3  COPYING.LIB   include/         lib64/  manifest_3362437.xml  MODULE_LICENSE_BSD_LIKE  MODULE_LICENSE_MIT  repo.prop  sysroot/  tools/

ls mips-unifi

AndroidVersion.txt  COPYING   COPYING3.LIB  COPYING.RUNTIME  lib/    libexec/              mips64el-linux-android/  MODULE_LICENSE_GPL  NOTICE     share/    test/
bin/                COPYING3  COPYING.LIB   include/         lib64/  manifest_3362437.xml  MODULE_LICENSE_BSD_LIKE  MODULE_LICENSE_MIT  repo.prop  sysroot/  tools/

ls arm-unifi

AndroidVersion.txt      bin/     COPYING3      COPYING.LIB      include/  lib64/    manifest_3362437.xml     MODULE_LICENSE_GPL  NOTICE     share/    test/
arm-linux-androideabi/  COPYING  COPYING3.LIB  COPYING.RUNTIME  lib/      libexec/  MODULE_LICENSE_BSD_LIKE  MODULE_LICENSE_MIT  repo.prop  sysroot/  tools/

ls x86-unifi

AndroidVersion.txt  COPYING   COPYING3.LIB  COPYING.RUNTIME      include/  lib64/    manifest_3362437.xml     MODULE_LICENSE_GPL  NOTICE     share/    test/
bin/                COPYING3  COPYING.LIB   i686-linux-android/  lib/      libexec/  MODULE_LICENSE_BSD_LIKE  MODULE_LICENSE_MIT  repo.prop  sysroot/  tools/

ls x86_64-unifi

AndroidVersion.txt  COPYING   COPYING3.LIB  COPYING.RUNTIME  lib/    libexec/              MODULE_LICENSE_BSD_LIKE  MODULE_LICENSE_MIT  repo.prop  sysroot/  tools/
bin/                COPYING3  COPYING.LIB   include/         lib64/  manifest_3362437.xml  MODULE_LICENSE_GPL       NOTICE              share/     test/     x86_64-linux-android/
```
