### ISSUE TITLE
documentation site error

### ISSUE THREAD

**Issue by chantra** [jedisct1/libsodium#511]
https://download.libsodium.org/doc has broken css (same SPDY error fetching the resource) and some pages are totally broken like with

https://download.libsodium.org/doc/advanced/xsalsa20.html
<img width="839" alt="screen shot 2017-03-13 at 10 12 18 pm" src="https://cloud.githubusercontent.com/assets/24572/23886712/4e99bbea-083a-11e7-8b52-dc9630afcc38.png">

**Comment by jedisct1** [comment]
Interesting things happen when you run out of disk space :)

Fixed, thanks!
