### ISSUE TITLE
Why do releases lack osx build script?

### ISSUE THREAD

**Issue by pdefreitas** [jedisct1/libsodium#512]
Why do releases on https://download.libsodium.org/libsodium/releases/ lack the osx build script in dist-build?

**Comment by jedisct1** [comment]
Because pretty much everybody uses Homebrew on MacOS these days.

**Comment by pdefreitas** [comment]
That should be documented. I found myself searching for the script and building it manually.

**Comment by jedisct1** [comment]
If you don't use Homebrew, there is nothing special about MacOS. The generic installation instructions are fine.
For the same reason, there are no build scripts for Linux or BSD systems. They are not needed. Just use `./configure && make check && make install`.
