### ISSUE TITLE
Not enough entropy at startup on a Scaleway ARM instance

### ISSUE THREAD

**Issue by khumarahn** [jedisct1/libsodium#513]
Hi, I am trying to make libsodium work on my arm box running gentoo.

I clone the repo, compile it with
```
./autogen.sh
./configure --prefix=/home/user/.usr
make
make install
```

Then I take a test program
```
$ cat test.c
#include <sodium.h>
#include <stdio.h>

int main(void)
{
    printf("result: %d", sodium_init());

    return 0;
}
```

I compile it with
```
$ gcc test.c -o test.x -I/home/user/.usr/include/ -L/home/user/.usr/lib -lsodium -Wl,-rpath=/home/user/.usr/lib
```

And run
```
./test.x
```

And it never terminates. Am I doing something wrong?

**Comment by jedisct1** [comment]
```sh
 emerge -av haveged
```

**Comment by jedisct1** [comment]
Is that on a Scaleway host?

**Comment by khumarahn** [comment]
It is a Scaleway host, right. Setting up haveged helped, now things work!

Thanks a lot!

**Comment by khumarahn** [comment]
I wonder if there could be an error message, or an explanation in the manual.

**Comment by jedisct1** [comment]
There is some information about this in the dnscrypt-proxy manual: https://github.com/jedisct1/dnscrypt-proxy/wiki/Running-dnscrypt-proxy-on-a-Linux-with-an-unseeded-RNG

And the server also emits a warning using this code:

https://github.com/jedisct1/dnscrypt-proxy/blob/a255d2908305739b54dafb01ae0285f6016869ab/src/proxy/app.c#L342

Maybe the same code can be used in ShadowSocks.

But I don't trust haveged. I don't trust it at all on virtualized environments. If waiting a little bit until enough entropy has been collected is fine, this should be preferred.

Scaleway is aware of this issue, and they are working on fixing it.

**Comment by jedisct1** [comment]
This has been added to the documentation: https://download.libsodium.org/doc/usage/

Thanks!
