### ISSUE TITLE
[libsodium-php] undefined symbol: crypto_pwhash_opslimit_interactive

### ISSUE THREAD

**Issue by mjmunger** [jedisct1/libsodium#514]
When installing PHP 7.1.2 OR PHP 5.6.30 on Debian 8 (PHP compiled from source) with libsodium 1.0.12, (compiled from source) and then running `pecl install libsodium`, we get the error "_undefined symbol: crypto_pwhash_opslimit_interactive_" when running `php -i` from the command line.

After looking at the release notes, change logs, and code, I discovered this belongs to Argon2, which was added in 1.0.9.

So, I re-compiled v 1.0.8 of libsodium (make, make check, make install) then ran `pecl uninstall libsodium` followed by `pecl install libsodium`

After reverting to a version _without_ Argon2 support (1.0.8), php -i works fine with no other changes.

**Comment by jedisct1** [comment]
You've been probably mixing and matching multiple versions of the library.

The php extension was compiled and linked against version 1.0.12 of libsodium, but then you installed version 1.0.8.

Or you have both installed simultaneously, maybe one in /usr/ and another one in /usr/local.

So, try to remove all versions of the library, and all versions of the PHP extension. The ones you installed from precompiled packages, and the one you manually installed.

Then reinstall version 1.0.12 and the PHP extension.

**Comment by mjmunger** [comment]
OK, here's what I did to clean up:

1. from `/usr/src/libsodium-1.0.12/` ran `make clean`
2. `pecl uninstall libsodium`
3. updateb, then locate sodium.so, and removed all instances I could find.
4. Recompile libsodium-1.0.12
5. Ran `ldconfig`
6. `pecl install libsodium`

Compilation now fails for 1.0.12

running: make
/bin/bash /tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/libtool --mode=compile cc  -I. -I/tmp/pear/temp/libsodium -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/include -I/tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/main -I/tmp/pear/temp/libsodium -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /tmp/pear/temp/libsodium/libsodium.c -o libsodium.lo
mkdir .libs
 cc -I. -I/tmp/pear/temp/libsodium -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/include -I/tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/main -I/tmp/pear/temp/libsodium -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /tmp/pear/temp/libsodium/libsodium.c  -fPIC -DPIC -o .libs/libsodium.o
/bin/bash /tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/libtool --mode=link cc -DPHP_ATOM_INC -I/tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/include -I/tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/main -I/tmp/pear/temp/libsodium -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -o libsodium.la -export-dynamic -avoid-version -prefer-pic -module -rpath /tmp/pear/temp/pear-build-rooth29Eip/libsodium-1.0.6/modules  libsodium.lo -lsodium
cc -shared  .libs/libsodium.o  -lsodium  -Wl,-soname -Wl,libsodium.so -o .libs/libsodium.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libsodium.a(libsodium_la-hmac_hmacsha512256.o): relocation R_X86_64_PC32 against symbol `crypto_auth_hmacsha512256_final' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:199: recipe for target 'libsodium.la' failed
make: *** [libsodium.la] Error 1
ERROR: `make' failed

**Comment by mjmunger** [comment]
Fix that with this:

1. `ln -s /usr/local/lib/libsodium.la /usr/lib/x86_64-linux-gnu/libsodium.la`
2. `ldconfig`
3. pecl install libsodium
