### ISSUE TITLE
Wrong value for crypto_pwhash_argon2i_MEMLIMIT_MIN

### ISSUE THREAD

**Issue by lmctv** [jedisct1/libsodium#516]
Since the stated minimum size for argon2i memory is 2 * 4 * 1KiB I think the
```
#define crypto_pwhash_argon2i_MEMLIMIT_MIN 1U
```
line should read
```
#define crypto_pwhash_argon2i_MEMLIMIT_MIN 8192U
```

**Comment by jedisct1** [comment]
Sure!

The change has been pushed to the `stable` branch. Thanks!
