### ISSUE TITLE
crypto_pwhash_argon2i_MEMLIMIT_MAX too small in 32 bit environments

### ISSUE THREAD

**Issue by lmctv** [jedisct1/libsodium#522]
At least under windows_x86 and linux_i386, `SIZE_MAX == 1ULL << 32 - 1`; therefore, 
```
#define crypto_pwhash_argon2i_MEMLIMIT_MAX ((SIZE_MAX >= 1ULL << 48) ? 4398046510080U : \
                                            (SIZE_MAX >= 1ULL << 32) ? 2147483648U : \
                                            32768U)
```
sets `crypto_pwhash_argon2i_MEMLIMIT_MAX = 32768 `.

I think the macro should be checking for either `SIZE_MAX >= 1ULL << 32 - 1` or `SIZE_MAX >= 1ULL << 31`.

By the way, I don't understand the reason why, in the case of SIZE_MAX >= 2^48, `crypto_pwhash_argon2i_MEMLIMIT_MAX` is being set to `4398046510080U == 1ULL << 42 - 1ULL << 10` instead of just `4398046511104U == 1ULL << 42`

**Comment by jedisct1** [comment]
Fixed in `stable`, thanks!
