### ISSUE TITLE
Impossible to use HMAC-SHA-512 with keys > 32 bytes

### ISSUE THREAD

**Issue by esaulpaugh** [jedisct1/libsodium#523]
Tested via crypto_auth_hmacsha512.

This causes incompatibility with other implementations. For HMAC-SHA-256, it is possible to work around by padding or hashing keys beforehand. But this is not possible for HMAC-SHA-512, because crypto_auth_hmacsha512 does not accept 64-byte keys (crypto_auth_hmacsha512_KEYBYTES is hardcoded to 32).

Short keys should be first padded and long keys should be first hashed with the underlying hash function.

RFC: https://tools.ietf.org/html/rfc2104#section-3
Test Vectors: https://tools.ietf.org/html/rfc4231#section-4.3

HMAC-SHA-512 should certainly allow 64-byte keys because "the minimal recommended length for K is L bytes" where L is the output length. -- https://tools.ietf.org/html/rfc2104#section-2

See also https://github.com/jedisct1/libsodium/issues/43

**Comment by paragonie-scott** [comment]
Correct me if I'm wrong, but this really isn't meant to be a generic drop in SHA512-truncated-to-256-bits HMAC interface. Its purpose was to be compatible with itself and only with itself.

**Comment by jedisct1** [comment]
Any key size can already be used:

```c
int crypto_auth_hmacsha512_init(crypto_auth_hmacsha512_state *state,
                                const unsigned char *key,
                                size_t keylen);
```

**Comment by esaulpaugh** [comment]
hmacsha256 requires a state array of length 176 or longer and hmacsha512 requires a state array of length 384 or longer to avoid a SIGSEGV on OSX using Java JNI.

This is strange

**Comment by paragonie-scott** [comment]
> This are strange numbers

https://github.com/jedisct1/libsodium/blob/d9e3adda6870d5fb76f3bda333ee1caec4892c97/src/libsodium/include/sodium/crypto_auth_hmacsha512.h#L38-L41

https://github.com/jedisct1/libsodium/blob/d9e3adda6870d5fb76f3bda333ee1caec4892c97/src/libsodium/include/sodium/crypto_hash_sha512.h#L24-L28

**Comment by jedisct1** [comment]
Just use the _statebytes() macros.
