### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by pdefreitas** [jedisct1/libsodium#526]
Would iOS compile script with included bitcode `-fembed-bitcode` work in tvOS? Do I need to provide the specific SDK of this platform? I am having trouble targeting this platform.

**Comment by pdefreitas** [comment]
Ok looks like the issue with my script was the double quotes in the MIN version. The compiler won't compile without this flags btw.

Here is the script that sorted it out, based on ios.sh script:
`#! /bin/sh
#
#  Step 1.
#  Configure for base system so simulator is covered
#  
#  Step 2.
#  Make for tvOS and tvOS simulator
#
#  Step 3.
#  Merge libs into final version for xcode import

export PREFIX="$(pwd)/libsodium-tvos"
export IOS64_PREFIX="$PREFIX/tmp/tvos64"
export SIMULATOR64_PREFIX="$PREFIX/tmp/simulator64"
export XCODEDIR=$(xcode-select -p)

export IOS_SIMULATOR_VERSION_MIN=${IOS_SIMULATOR_VERSION_MIN-9.0}
export IOS_VERSION_MIN=${IOS_VERSION_MIN-9.0}

mkdir -p $SIMULATOR64_PREFIX $IOS64_PREFIX || exit 1

# Build for tvOS
export BASEDIR="${XCODEDIR}/Platforms/AppleTVOS.platform/Developer"
export PATH="${BASEDIR}/usr/bin:$BASEDIR/usr/sbin:$PATH"
export SDK="${BASEDIR}/SDKs/AppleTVOS.sdk"

## 64-bit tvOS
export CFLAGS="-O2 -arch arm64 -isysroot ${SDK} -mtvos-version-min=${IOS_VERSION_MIN} -flto -fembed-bitcode"
export LDFLAGS="-arch arm64 -isysroot ${SDK} -mtvos-version-min=${IOS_VERSION_MIN} -flto"

make distclean > /dev/null

./configure --host=arm-apple-darwin10 \
            --disable-shared \
            --enable-minimal \
            --prefix="$IOS64_PREFIX" || exit 1

make -j3 install || exit 1

# Build for the simulator
export BASEDIR="${XCODEDIR}/Platforms/AppleTVSimulator.platform/Developer"
export PATH="${BASEDIR}/usr/bin:$BASEDIR/usr/sbin:$PATH"
export SDK="${BASEDIR}/SDKs/AppleTVSimulator.sdk"

## x86_64 simulator
export CFLAGS="-O2 -arch x86_64 -isysroot ${SDK} -mtvos-simulator-version-min=${IOS_SIMULATOR_VERSION_MIN} -flto"
export LDFLAGS="-arch x86_64 -isysroot ${SDK} -mtvos-simulator-version-min=${IOS_SIMULATOR_VERSION_MIN} -flto"

make distclean > /dev/null

./configure --host=x86_64-apple-darwin10 \
--disable-shared \
--enable-minimal \
--prefix="$SIMULATOR64_PREFIX"

make -j3 install || exit 1

# Create universal binary and include folder
rm -fr -- "$PREFIX/include" "$PREFIX/libsodium.a" 2> /dev/null
mkdir -p -- "$PREFIX/lib"
lipo -create \
  "$SIMULATOR64_PREFIX/lib/libsodium.a" \
  "$IOS64_PREFIX/lib/libsodium.a" \
  -output "$PREFIX/lib/libsodium.a"

mv -f -- "$IOS64_PREFIX/include" "$PREFIX/"

echo
echo "libsodium has been installed into $PREFIX"
echo
file -- "$PREFIX/lib/libsodium.a"

# Cleanup
rm -rf -- "$PREFIX/tmp"
make distclean > /dev/null`

**Comment by jedisct1** [comment]
Added... but I don't know if it works (:scared:) ...
