### ISSUE TITLE
Extra headers in 64-bit MinGW tarball

### ISSUE THREAD

**Issue by Fraser999** [jedisct1/libsodium#527]
The 64-bit [MinGW tarball for version 1.0.12](https://download.libsodium.org/libsodium/releases/libsodium-1.0.12-mingw.tar.gz) contains the headers removed in https://github.com/jedisct1/libsodium/commit/fd797db30afdcfdc39b6acf7e631e1b4bef8c3a5.  They aren't present in the 32-bit version, nor in the other two 1.0.12 tarballs.

**Comment by jedisct1** [comment]
Oh, good catch, thanks!

This will be fixed in the forthcoming 1.0.13 version. Thanks!
