### ISSUE TITLE
Chacha20 incompatable with wolfssl

### ISSUE THREAD

**Issue by zhou0** [jedisct1/libsodium#529]
Chacha20 of wolfssl use 96 bits nonce, so is libsodium. But when i use wolfssl to decrypt stream encrypted by crypto_stream_chacha20_ietf_xor_ic, i only get the correct plain text with stream that are very shot. with long stream, i get most of the stream chunks decrypted wrong and only a few chunks correct.

to demo the problem:

    pull the mysocks project ( which use wolfssl for chacha20 )from https://github.com/zhou0/mysocks.git , it a cmake based project, build the project and run the following command

./ssclient-wolfssl -k fuckgfw -m chacha20-ietf -p 2194 -s localhost -l 1895

    pull the shadowsocks (which uses libsodium for chacha20 )from https://github.com/shadowsocks/shadowsocks-libev.git or download a release later than v2.5.0 https://github.com/shadowsocks/shadowsocks-libev/archive/v2.5.0.tar.gz , build the project and run the following command in a second terminal

./ss-server -k fuckgfw -m chacha20-ietf -p 2194 -s localhost -l 1895 -v

    now in a 3rd terminal run the following command , you will observe the problem.

curl -v -x socks5h://localhost:1895 cn.bing.com

if you change the url to bing.com, such as

curl -v -x socks5h://localhost:1895 bing.com

which is correct because the HTTP reply is just a short HTTP redirection message.

**Comment by jedisct1** [comment]
Could you submit a very short test case that encrypts the same long message with both systems and reproduces the problem?

**Comment by jedisct1** [comment]
From a quick glance at these projects' code, mysocks seems to also be using libsodium for chacha20-poly1305. And it's always using the AEAD, not the unauthenticated cipher like shadowsocks-libev.

**Comment by zhou0** [comment]
I have fixed this in mysocks and proved that libsodium chacha20 is compatible with wolfssl. It is not compatible with openssl howerver.
