### ISSUE TITLE
Implicit function declaration warning

### ISSUE THREAD

**Issue by endoffile78** [jedisct1/libsodium#530]
```
sodium/runtime.c: In function ‘_sodium_runtime_intel_cpu_features’:
sodium/runtime.c:150:9: warning: implicit declaration of function ‘_xgetbv’ [-Wimplicit-function-declaration]
         xcr0 = (uint32_t) _xgetbv(0);
         ^
```

This causes the build to fail: 

```
CCLD     libsodium.la
sodium/.libs/libsodium_la-runtime.o:runtime.c:(.text+0x156): undefined reference to `_xgetbv'
collect2: error: ld returned 1 exit status
```

Compiling with: x86_64-w64-mingw32-gcc
Compilig on Travis: https://travis-ci.org/uTox/uTox/jobs/219909515
Using the stable branch.

**Comment by jedisct1** [comment]
This version of mingw is very old (2013). Current stable versions should be fine.

You can also just use the precompiled binaries from https://download.libsodium.org/libsodium/releases/

**Comment by jedisct1** [comment]
This is still quite surprising since `_xgetbv()` availability is checked (9eea164007af29bcb00e79a756a1854e5e61f566).

Can you post the content of your `config.log` file somewhere?

**Comment by endoffile78** [comment]
Is this what you are wanting: https://gist.github.com/endoffile78/3902c242a3fcd58ed833bbb643352d65

**Comment by jedisct1** [comment]
c9139f8db36837f73164a4bf4d67925d21889d76 should fix it.

**Comment by endoffile78** [comment]
Thank you! That fixed it.
