### ISSUE TITLE
FAIL: sodium_utils3 on aarch64 (Qemu)

### ISSUE THREAD

**Issue by oberstet** [jedisct1/libsodium#532]
Any idea why this single test is failing me? This is while building a Docker image for aarch64 that includes libsodium https://gist.github.com/oberstet/47ece8347cc235b0749b89ebc12d742b

**Comment by jedisct1** [comment]
Can you post the content of the `sodium_utils3.log` and `sodium_utils3.res` files?

**Comment by oberstet** [comment]
`sodium_utils3.res` is empty:

```console
/ # ls -la /tmp/pip-build-aoFoIb/pynacl/build/temp.linux-aarch64-2.7/test/default/sodium_utils3*
-rwxr-xr-x    1 root     root        447968 Apr 21 06:06 /tmp/pip-build-aoFoIb/pynacl/build/temp.linux-aarch64-2.7/test/default/sodium_utils3
-rw-r--r--    1 root     root           169 Apr 21 06:07 /tmp/pip-build-aoFoIb/pynacl/build/temp.linux-aarch64-2.7/test/default/sodium_utils3.log
-rw-r--r--    1 root     root         14128 Apr 21 06:06 /tmp/pip-build-aoFoIb/pynacl/build/temp.linux-aarch64-2.7/test/default/sodium_utils3.o
-rw-r--r--    1 root     root             0 Apr 21 06:07 /tmp/pip-build-aoFoIb/pynacl/build/temp.linux-aarch64-2.7/test/default/sodium_utils3.res
-rw-r--r--    1 root     root            84 Apr 21 06:07 /tmp/pip-build-aoFoIb/pynacl/build/temp.linux-aarch64-2.7/test/default/sodium_utils3.trs
```

Here is `sodium_utils3.log`:

```console
/ # cat /tmp/pip-build-aoFoIb/pynacl/build/temp.linux-aarch64-2.7/test/default/sodium_utils3.log 
qemu: Unsupported syscall: 278
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
FAIL sodium_utils3 (exit status: 139)
/ # 
``` 

[Here](https://gist.github.com/oberstet/c24ae8887a4dc753db30b729b2fc7cfe) is a complete log of what I tried. Essentially:

```console
sudo docker run --rm -it -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static aarch64/python:2.7-alpine sh
```

and then within the container:

```console
apk add --update build-base libffi-dev openssl-dev python-dev py-pip \
    && rm -rf /var/cache/apk/*

pip install -U pip \
    && pip install trollius \
    && pip install --no-clean autobahn[twisted,asyncio,accelerate,serialization,encryption]=='0.18.2'
```

The above is part of cross build tooling [here](https://github.com/crossbario/crossbar-docker/tree/master/autobahn-python/aarch64)

**Comment by jedisct1** [comment]
```
qemu: Unsupported syscall: 278
```

This is an issue specific to Travis, whose host kernel is very old compared to the containers (`278` is `vmsplice()`), which affects a couple other projects.

Not really a libsodium issue, and on actual hardware (tried on a Rpi 3 as well as on a Scaleway node) all the tests are passing.

You can remove that test from the `am__append_1` definition in `tests/default/Makefile` in order to skip it on this specific case until Travis updates their environment.

**Comment by oberstet** [comment]
I am not using Travis, but Qemu on notebook:

```console
oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-docker/autobahn-cpp/x86_64$ uname -a
Linux thinkpad-t430s 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-docker/autobahn-cpp/x86_64$ cat /proc/cpuinfo | grep "model name" | uniq
model name	: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-docker/autobahn-cpp/x86_64$ cat /proc/cpuinfo | grep flags | uniq
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts
oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-docker/autobahn-cpp/x86_64$ qemu-arm-static --version
qemu-arm version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.11), Copyright (c) 2003-2008 Fabrice Bellard
```

**Comment by oberstet** [comment]
@jedisct1 also, the Pi 3 isn't `aarch64`, but `armhf` userland, and the latter works for me, but the former not.

**Comment by jedisct1** [comment]
The Pi3 is aarch64. I'm running [Pi64](https://github.com/bamarni/pi64) and OpenBSD/aarch64 without any problems on it.

**Comment by jedisct1** [comment]
Scaleway: yes https://www.scaleway.com/virtual-cloud-servers/

**Comment by oberstet** [comment]
Right, too sloppy: _Raspbian_/Pi is armhf (userland), not aarch64, which is probably what most people run on the Pi.

I do have the issue on **Qemu/aarch64**, and I would like to continue using Qemu because no real hardware is needed to build binaries in CI.

> qemu: Unsupported syscall: 278

This seems not to be the problem: I get this warning during most builds in that container with no harm.

However the **segfault** in the specific sodium_utils3 unit test is a problem.
