### ISSUE TITLE
crypto_pwhash_str_verify does not distinguish errors

### ISSUE THREAD

**Issue by emilbayes** [jedisct1/libsodium#533]
`crypto_pwhash_str_verify` does not distinguish between hash mismatch and the OS refusing to allocate memory. The underlying `argon2_verify` however does. It should be fairly simple to expose.

I will do a PR in one of the coming days to fix this :)

**Comment by emilbayes** [comment]
@jedisct1 Would the best method here be a `errno` set for mismatch or a new return code?

**Comment by jedisct1** [comment]
Hi Emil,

And thanks a lot for reporting this.

`errno` would be best!
