### ISSUE TITLE
How to link statically in a project using cmake?

### ISSUE THREAD

**Issue by absalomedia** [jedisct1/libsodium#534]
I'm looking to utilise LibSodium as a shared static library in something I'm building & can't seem to find where the build sequence to generate it is inside the Git repo as there's no Makefile listed.

Platform: Ubuntu Trusty (Local Vagrant build tests) & Ubuntu Xenial (Docker based Travis QA packaging)

Here's part of my cmake file I'm working off:
`set(LIBSODIUM_LIBRARY ${CMAKE_CURRENT_SOURCE_DIR}/lib/libsodium/lib/libsodium.a)
add_custom_target(build_libsodium ALL 
                   COMMAND ${CMAKE_MAKE_PROGRAM}
                   WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/lib/libsodium
                   COMMENT "Original libsodium makefile target")`

Does anyone have a walkthrough on how to create LibSodium as a shared static library?

**Comment by jedisct1** [comment]
Did you try the supplied [`Findsodium.cmake`](https://raw.githubusercontent.com/jedisct1/libsodium/master/contrib/Findsodium.cmake) script?
