### ISSUE TITLE
possible undefined behaviour in hash_sha256_cp

### ISSUE THREAD

**Issue by mvduin** [jedisct1/libsodium#537]
When compiling master branch (ea2273540ab5) with -O3 -flto, I'm getting the following warning reported by arm-linux-gnueabihf-gcc 6.3.0 while linking the tests "core3", "stream", and "stream2":

`crypto_hash/sha256/cp/hash_sha256_cp.c: In function 'crypto_hash_sha256.constprop':`
`crypto_hash/sha256/cp/hash_sha256_cp.c:205:31: warning: iteration 64 invokes undefined behavior [-Waggressive-loop-optimizations]`
`crypto_hash/sha256/cp/hash_sha256_cp.c:204:9: note: within this loop`

The tests do still pass, and curiously I don't get the same warning when building natively on x86_64 instead of cross-compiling to arm, but it may be worth checking whether gcc is right about there being undefined behaviour in that function.

Steps to reproduce on debian with gcc-arm-linux-gnueabihf 4:6.3.0-4 installed:
`./configure --host=arm-linux-gnueabihf --without-pthreads --disable-shared --enable-minimal --disable-asm CFLAGS="-O3 -flto" LDFLAGS="-O3 -flto" AR=arm-linux-gnueabihf-gcc-ar RANLIB=arm-linux-gnueabihf-gcc-ranlib && make && cd test/default && make stream`

**Comment by jedisct1** [comment]
This doesn't make any sense, since there can't be more than 63 iterations.

**Comment by mvduin** [comment]
Hmm, indeed, and the compiler should have no trouble seeing that that is true with some basic range analysis...

It gets weirder. I wondered why _those_ three tests emit the warning but the "hash" test does not. Based on some testing, it seems that the reason is that they use sha256 _exactly once_, and functions used once get unconditionally inlined. But that means the compiler should know perfectly well that inlen is a large value, hence the loop it warns about is unreachable code!

It seems I should report a gcc bug instead. :-)
