### ISSUE TITLE
Scrypt output format (seemingly) not standard, no documentation given to explain anything.

### ISSUE THREAD

**Issue by iWnn** [jedisct1/libsodium#538]
So as the title says, i've been using libsodium and for the sake of my own sanity later i've been trying to find the specification/documentation in regards to the output format of crypto_pwhash_scryptsalsa208sha256_str and so far i haven't found it. Other major libraries (for instance python's Passlib) document their output format very [plainly](https://passlib.readthedocs.io/en/stable/lib/passlib.hash.scrypt.html#format-algorithm).

Does this documentation exist, and if so where can i find it ?

**Comment by jedisct1** [comment]
It is using the standard scrypt string format: https://gitlab.com/jas/scrypt-unix-crypt/blob/master/unix-scrypt.txt

**Comment by iWnn** [comment]
Although i think it's a rather contrived/fragile format (specially the identifier being a single digit) and IMO the [PHC format](https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md) is better, that answers my question...so i'm going to go ahead and close this. 

Thanks!

**Comment by jedisct1** [comment]
Depends on your requirements. A huge advantage of the scrypt format is that its length is constant.
