### ISSUE TITLE
Switch build system to Meson

### ISSUE THREAD

**Issue by FSMaxB** [jedisct1/libsodium#539]
I know that you are not a complete stranger to the idea of switching away from GNU Autotools as a build system and have been doing experiments with GYP, but I think that [Meson](http://mesonbuild.com/) might be a good build system to switch to.

It is gaining more and more traction in the free software world with more and more projects switching to it, and it might even be able to replace all the custom build files for Visual Studio and Android etc.

Just a suggestion.

**Comment by jedisct1** [comment]
Meson looks promising, but there are no problems with the current build scripts that requires changing to a new build system.

This can only introduce regressions, confusion, and break other software depending on the current system.

**Comment by FSMaxB** [comment]
Ok, get it.

**Comment by FSMaxB** [comment]
Maybe for a new major version.
