### ISSUE TITLE
Inconsistency: sodium_bin2hex needs the buffer length parameter to include the space for the null byte, nothing else seems to

### ISSUE THREAD

**Issue by fredemmott** [jedisct1/libsodium#540]
Seeing this with my own usage, and it's also the only `+ 1` in https://github.com/jedisct1/libsodium-php/blob/master/libsodium.c#L2415

**Comment by fredemmott** [comment]
There seems to be a similar quirk with pwhash/pwhash_str (or a bug in the PHP extension):
 - pwhash hash_len does not include the trailing null
 - pwhash_str subtracts 1 from crypto_pwhash_STRBYTES to calculate the length

**Comment by fredemmott** [comment]
same for the scrypt pwhash_str

**Comment by jedisct1** [comment]
That's intentional. These functions are the only ones that store strings. Strings are zero-terminated in C. Everything else is binary data, that doesn't need a leading `\0` in any language except PHP.

In all cases, the length is the actual minimum number of bytes required to store the result.

**Comment by jedisct1** [comment]
s/leading/trailing/ :)
