### ISSUE TITLE
Move CRYPTO_ALIGN to after struct keyword in typedef structs

### ISSUE THREAD

**Issue by fredemmott** [jedisct1/libsodium#543]
Caused facebook/hhvm#7827

This is required for GCC 5 LTO builds in some circumstances when we have both C and C++ users of libsodium linked in to the same library - though a trivial attempt at reproducing it outside of FB's internal HHVM build didn't work.

This is the correct placement per https://gcc.gnu.org/onlinedocs/gcc/Type-Attributes.html

**Comment by fredemmott** [comment]
(sorry, still waiting for legal approval on pull requests :( )

**Comment by jedisct1** [comment]
Backported to `stable`. Thanks!
