### ISSUE TITLE
How do I build for Android and a specific API level?

### ISSUE THREAD

**Issue by chris-doclily** [jedisct1/libsodium#545]
I need to build the library for Android and API level 21, and I need to do it for all of the architectures that Android presently supports, including x86 for testing. I first tried to do it by just running the scripts in the dist-build/ folder, and that worked fine except for the fact that I had to change my app's API level to 23 in order to define __poll_chk. I looked at some of the build scripts but didn't see a great way to change the API level, and I couldn't figure out how to use the "configure" file to build for Android.

**Comment by jedisct1** [comment]
Defining `NDK_PLATFORM` should do the trick:

```sh
env NDK_PLATFORM=android-21 ./dist-build/android-mips64.sh
```
