### ISSUE TITLE
Undocumented return values for crypto_sign_keypair /  crypto_scalarmult_base

### ISSUE THREAD

**Issue by jadamcrain** [jedisct1/libsodium#549]
These functions return int, but the examples always ignore the return value. Is this safe behavior? What are the conditions under which these functions fail?

**Comment by jedisct1** [comment]
These functions cannot fail, and the reason they return an `int` is for compatibility with the legacy NaCl ABI.

**Comment by jadamcrain** [comment]
Thanks for that info!

How best would it be to document this?

**Comment by jedisct1** [comment]
We may add a line mentioning that these functions cannot fail. But testing if the result is `!= 0` wouldn't hurt either.
