### ISSUE TITLE
Windows dll's don't contain version resources

### ISSUE THREAD

**Issue by LammyL** [jedisct1/libsodium#550]
The windows dll's don't have any version resources so it is difficult to look at a libsodium.dll and know the version and architecture it was compiled for. 

I am looking to be able to right-click the dll in windows explorer, go to properties and click on the tab with the file information.

This is fairly easy to add into the visual c++ project as a resource.  I am just not fully sure of the best practices to implement this.  If anyone has some guidance, I don't mind making a pull request.

**Comment by jedisct1** [comment]
@BurningEnlightenment @evoskuil @ektrah Any idea on how to add that?

**Comment by BurningEnlightenment** [comment]
It has been a while since I used that thing...
Just add a `.rc` resource file and reference it from the vs project like so:
```xml
  <ItemGroup>
    <ResourceCompile Include="version.rc" />
  </ItemGroup>
```
The last version resource file I created, might serve you as a template:
```c++
/////////////////////////////////////////////////////////////////////////////
// version.rc
//				  
#include "version.inl"

1 VERSIONINFO
FILEVERSION VERSION_BIN
PRODUCTVERSION VERSION_BIN
FILEFLAGSMASK 0x3fL
#ifdef _DEBUG
FILEFLAGS 0x1L
#else
FILEFLAGS 0x0L
#endif
FILEOS 0x40004L
FILETYPE 0x2L
FILESUBTYPE 0x0L
BEGIN
	BLOCK "StringFileInfo"
	BEGIN
		BLOCK "000004b0"
		BEGIN
			VALUE "CompanyName", "BurningEnlightenment"
			VALUE "FileDescription", "CrysisWars BurningClientExtension"
			VALUE "FileVersion", VERSION_STR
			VALUE "ProductVersion", VERSION_STR
			VALUE "InternalName", "cwbce.dll"
			VALUE "OriginalFilename", "cwbce.dll"
			VALUE "ProductName", "CryServ Client"
			VALUE "LegalCopyright", "Copyright © 2014 Henrik S. Gaßmann"
		END
	END
	BLOCK "VarFileInfo" { VALUE "Translation", 0x0, 1200 }
END
```
note that the actual version values are defined in `version.inl`, but IIRC I did that because i generated the version.inl using some tool; you can merge the `version.inl` into the file above or keep them seperated for clarity:
```c++
// version.inl
#define VERSION_BIN  1,1,0,0
#define VERSION_STR "1.1.0.0"
```
HTH

**Comment by evoskuil** [comment]
@jedisct1, I would add `libsodium\builds\msvc\resource.h` and `libsodium\builds\msvc\resource.rc` with add references to the `.vcxproj` files of each library that emits a versioned DLL, eg:
```xml
    <ClInclude Include="..\..\resource.h" />
    <ResourceCompile Include="..\..\resource.rc" />
```
with corresponding entries in the `.filters` files. This allows all MSVC versions to share the same resource definitions. This is the approach I've used in other libraries (such as zeromq) that are based on the same [MSVC template](https://github.com/evoskuil/visual-studio-template).

The IDE will perform the proper organization for both if the files are just dropped into the root for the project (it likes to organize the resource file into its own group and the header into the existing headers group).

**Comment by LammyL** [comment]
I implemented something that works.  The pull request is here.  https://github.com/jedisct1/libsodium/pull/551

I'm not sure how to link the pull request to the issue.

**Comment by jedisct1** [comment]
Thanks!
