### ISSUE TITLE
MSVC advapi32.lib dependency should not be in vcxproj.

### ISSUE THREAD

**Issue by evoskuil** [jedisct1/libsodium#552]
These [lines](https://github.com/jedisct1/libsodium/blob/master/builds/msvc/vs2013/libsodium/libsodium.vcxproj#L313-L333) in the MSVC files should be removed and replaced with a single entry that looks more like this:
```xml
  <ItemDefinitionGroup>
    <Link>
      <AdditionalDependencies>advapi32.lib</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
```
...in the [project properties](https://github.com/jedisct1/libsodium/blob/master/builds/msvc/vs2013/libsodium/libsodium.props) file. 

Note that the [import properties](https://github.com/jedisct1/libsodium/blob/master/builds/msvc/vs2013/libsodium.import.props#L22) (for use by external projects) already has this dependency included.

**Comment by jedisct1** [comment]
How does https://github.com/jedisct1/libsodium/commit/87473fdd3f80e3e5b108dd00b50cf900ace22f5e look?

**Comment by LammyL** [comment]
I think this line below was accidentally removed from the project file and it caused the build to fail because the build batch file couldn't find the 'build' target.  I send a pull request to fix that.

`<Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />`

**Comment by evoskuil** [comment]
@jedisct1, that should work, but it would be clearer to nest the Link element into the existing ItemDefinitionGroup (under the Configuration comment).
