### ISSUE TITLE
sodium_malloc(1) abort()s

### ISSUE THREAD

**Issue by goblin** [jedisct1/libsodium#555]
Hello,

Trying to allocate any amount of memory with `sodium_malloc()` results in "Aborted (core dumped)" for me... The documentation doesn't specify what should happen when `sodium_malloc()` fails, but normal `malloc()` tends to return `NULL` instead of crashing.

Here's how to reproduce (at least on my machine):

```
$ pkg-config --modversion libsodium
1.0.11
$ cat t.c
#include <sodium.h>

int main()
{
        sodium_malloc(1);

        return 0;
}
$ gcc -o t t.c -lsodium
$ ./t
Aborted (core dumped)
$
```

What could be causing this?

**Comment by goblin** [comment]
BTW this is on Arch Linux, so nothing exotic IMO. I can provide more info if needed.

**Comment by jedisct1** [comment]
The library must be initialized with `sodium_init()` before any other function is called.
