### ISSUE TITLE
when I build the project,I get the problem, that the file, libsodium.a, is missing.

### ISSUE THREAD

**Issue by AimeeChen** [jedisct1/libsodium#556]
I build the project on the Ubuntu, I get this problem:
Android NDK:ERROR:opus/Android.mk:sodium: LOCAL_SRC_FILES points ti a missing file
Android NDK:Check that ./libsodium/libsodium-android-armv6/lib/libsodium.a exists or path is correct
make: Entering directory 'batphone/app/src/main/jni'
ndk/android-ndk-r14b/build/core/prebuilt-library.mk:45:*** Android NDK. Stop.
make: Leaving directory 'batphone/app/src/main/jni'
:app:buildDebugNdk FAILED

**Comment by jedisct1** [comment]
What project are you talking about?
