### ISSUE TITLE
Argon2 docs: it's bad to use constants for password verification but it's fine to use them for the reproducible key derivation

### ISSUE THREAD

**Issue by nurupo** [jedisct1/libsodium#557]
The documentation for Argon2 says

>Do not use constants (including crypto_pwhash_OPSLIMIT_* and crypto_pwhash_MEMLIMIT_*) in order to verify a password. Save the parameters along with the hash instead, and use these saved parameters for the verification.

Ok, "Don't use constants for password verification". Password verification is only one half of the Argon2 API though. What about the key derivation? It's fine to always use the constants?

For example, a user uses application using libsodium 1.0.12, the user enters a password in the application, a key is generated from the password using argon2 with `crypto_pwhash_OPSLIMIT_*` and `crypto_pwhash_MEMLIMIT_*` constants, and that key is used to encrypt some user information. In some distant future, in year 2060, the application updates to use libsodium 59.0.3. The user enters the very same password, the application derives the key out of it using Argon2 with `crypto_pwhash_OPSLIMIT_*` and `crypto_pwhash_MEMLIMIT_*` constants of and decrypts the previously encrypted with libsodium 1.0.12 user data. User expects the decrypted data to match the encrypted data, which is, given that the user provided the very same password, would require using the very same Argon2 arguments, so that the very same symmetric key would be derived.

Anyway, I find it very confusing that the documentation mentions password verification specifically, omitting the key derivation, giving the false impression that it's bad to use constants for password verification but it's fine to use them for the reproducible key derivation. I think it's better to explicitly document the very reason why it's not recommended to use constants for the key verification, instead of having it being implied and the API users guessing if this is really what was implied there -- the fact that the values of the constants might be changed in the future versions of the library.

**Comment by jedisct1** [comment]
This has been clarified, thanks!

The documentation resides in its own repository: https://github.com/jedisct1/libsodium-doc

It's better to file issues (or even better: pull requests) in that repository so that changes can reference them.

Thanks!

**Comment by BurningEnlightenment** [comment]
@jedisct1 you may want to link to the docs repository somewhere more prominent, because currently its somewhat obscure that it exists at all and not that easy to find 😖

**Comment by nurupo** [comment]
Sorry, didn't know that there is a separate repository for documentation.

A bit dissatisfied with the commit, was expecting an explicit "Constants might change value between different libsodium versions, so don't rely on them to always being the same for the determistic output".

Btw, does this also mean that `_[OPSLIMIT|MEMLIMIT]_[MIN|MAX]` might be changed in the future?

**Comment by jedisct1** [comment]
`_[OPSLIMIT|MEMLIMIT]_[MIN|MAX]` might change, the algorithm itself might change (in fact, it will soon change to Argon2id) and even without any changes in the library, you may want to update these parameters in your applications according to the platform they run on.

So, always store all the required parameters.

**Comment by nurupo** [comment]
Hm, interesting, even the algorithm might change. Sounds like anyone using argon/scrypt in their project should have a regression test to make sure that the parameters used in argon/scrypt result in the expected CPU and RAM consumption, in case the updated libsodium changes anything. Good to know.

**Comment by jedisct1** [comment]
That's why the algorithm is also a parameter.
