### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by Fraser999** [jedisct1/libsodium#558]
Looks like https://download.libsodium.org is down.

**Comment by jedisct1** [comment]
I know. Along with all the other websites I am running, and my email, and a lot of other things :(

There's a recent regression in the OpenBSD-current kernel (at least when running kvm). Been chasing it for the past few days. Still on it :)

**Comment by Fraser999** [comment]
Ah - good luck!

**Comment by jedisct1** [comment]
Thanks!
