### ISSUE TITLE
sodium_utils2 fails ec2 CentOS 7

### ISSUE THREAD

**Issue by mmapixio** [jedisct1/libsodium#559]
Seems that sodium_utils2 does not like ec2 in general:

    PASS: verify1
    /tmp/pip-build-i_tNiN/pynacl/src/libsodium/build-aux/test-driver: line 107: 22894 Segmentation fault      "$@" > $log_file 2>&1
    FAIL: sodium_utils2
    PASS: sodium_utils3

Unfortunately, this is reached when I attempt to install pynacl's latest update (pulled in from recent paramiko), and even attempting to install libsodium itself did not fix the issue.  Don't know if there is something that can be done in regards to ec2 and sodium_utils2, but want to post this here either way.

**Comment by jedisct1** [comment]
Can you put the content of the `config.log` file somewhere?

Are you using ASAN? Didn't the `configure` script explicitly say something about the fact that this specific test will fail?

**Comment by jedisct1** [comment]
Incompatibility of this test with ASAN has been documented for a long time, but in addition to that, a compile-time check has been added to the stable branch. If segv handlers cannot be used due to ASAN or other sanitizers, the tests depending on it are now automatically ignored.
