### ISSUE TITLE
Feature request: crypto_box_curve25519xchacha20poly1305_seal

### ISSUE THREAD

**Issue by buu700** [jedisct1/libsodium#561]
Would it be possible to provide a "sealed box" variant of the `crypto_box_curve25519xchacha20poly1305` API?

**Comment by jedisct1** [comment]
Just curious: why?

**Comment by buu700** [comment]
@cyph was recently updated from ChaCha20 to XChaCha20 as part of an upcoming version which introduces features that non-random nonces would've been a pain to work with, and it'd be nice to also have our existing `crypto_box_seal` code migrated to XChaCha20 for consistency.

It isn't a *huge* deal since XSalsa20 is fine too, but we'll be committed to whatever goes out with this next release long-term, so now would be the best time to standardize on XChaCha20 across the board if possible.

**Comment by jedisct1** [comment]
Done in ccb842f4884aa8917dcbba79509a349f8c475b3c

**Comment by buu700** [comment]
Awesome, thanks a lot!
