### ISSUE TITLE
Continued compliance with the HSTS preload requirements.

### ISSUE THREAD

**Issue by bardiharborow** [jedisct1/libsodium#563]
Hey! `libsodium.org` is currently HSTS preloaded, but has not continued to remain compliant with the [preload requirements](https://hstspreload.org/). If you are able to remedy this, it would be highly appreciated. This will ensure that if Chrome begins delisting non-compliant domains that yours will not be affected. Over at [EFForg/https-everywhere](https://github.com/EFForg/https-everywhere), we can't remove rewrite rules for domains that are non-compliant because that would present a security risk if Chrome then also removes them. Your domain is one of hundreds of non-compliant domains which add unnecessary maintenance and file size to our rulesets. Any assistance you can provide is appreciated.

**Comment by jedisct1** [comment]
Hi,

And thanks for the heads up.

Can you clarify what doesn't comply with the HSTS preload requirements any more?

I didn't see anything obvious.

Thanks!

**Comment by bardiharborow** [comment]
`http://libsodium.org` needs to redirect to `https://libsodium.org/` not `https://www.libsodium.org/` in order to ensure that browsers without preload support still log the `includeSubDomains` directive for `*.libsodium.org` rather than `*.www.libsodium.org` and `*.download.libsodium.org` (noting that `Strict-Transport-Security` headers on HTTP endpoints do not take effect, so even having headers on `http://libsodium.org` like you currently do does not solve this issue).

**Comment by jedisct1** [comment]
Oh, I see.

This should now be fixed.

Thanks!

(for the record: `s/\$server_name/\$host/g` in the Nginx configuration file)

**Comment by bardiharborow** [comment]
Confirmed fixed. Thanks for the very quick responce.
