### ISSUE TITLE
Memory allocation limitation

### ISSUE THREAD

**Issue by nicwhitts** [jedisct1/libsodium#564]
Hi,
Im using lib sodium within a third party repo.
Im having trouble due to memory limitations of the project I'm working on.
(im also new to memory management on the whole)
If I'm correct:
libsodium allocates in memory the total bytes needed for the crypto action. (alloc_region)
Is there a way to allocate the memory in chunks in a 'lazy' fashion? Instead of allocating the whole chunk at once? Lets say i can 'cap' the alloc at 10mb. compute, release and the allocate another chunk until completion?

I don't know the terminology or if this is possible but a response would be greatly appreciated

**Comment by jedisct1** [comment]
Hi Nic,

libsodium never allocates anything on the heap, with the exception of password hashing functions (`crypto_pwhash()`).

Password hashing functions *have* to the configured amount of maximum memory, and pages *have* to be accessed in (pseudo)random order. There would be zero benefits in configuring a large amount of memory if the same computation could be done using smaller chunks.

In a memory constrained environment, you can reduce the maximum amount of memory used by the function as much as needed, but you then need to crank the number of operations up in order to counter balance this, and still make the function require a significant time to perform the computation.

**Comment by nicwhitts** [comment]
Hey thanks for the response.
How much difference would the computation time be?
Im trying to use a library inside an iOS extension and I'm locked to a maximum of 30mb memory, would there be a workaround to this?
If i understand correctly the Heap is the virtual memory but everything is allocated on the stack which is causing my problems?

**Comment by jedisct1** [comment]
You can even use just 1 Mb if you need to.

Keep raising the `opslimit` parameter until the computation takes about 1 second to complete (actually, it depends on your use case; you didn't explain what you are trying to do).

**Comment by nicwhitts** [comment]
This is new to me so I'm trying my best to explain.
I'm just trying to keep the memory usage under 30mb, my iOS extension terminates when allocating 32mb for the call as I'm only allowed a max of 30mb.

Called from:
`crypto_pwhash_scryptsalsa208sha256_ll((uint8_t *)password.bytes, password.length, (uint8_t *)salt.bytes, salt.length, N, r, p, [outData mutableBytes], outData.length);`

`  NSData *keyMaterial = [NAScrypt scrypt:key salt:salt N:32768U r:8 p:1 length:totalKeysBytes error:error];
`

> N:32768U
This is 32mb in bytes so i should be able to just change this number?

**Comment by jedisct1** [comment]
Don't use that function. Use `crypto_pwhash()` (or `crypto_pwhash_str()` as you still didn't describe what you want to do).

https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html

There are 2 parameters: `opslimit` and `memlimit`.

Do what this documentation page explains.

Set `memlimit` to `30*1024*1024` if you want the function to use up to 30 Mb.
Set it to `1*1024*1024` if you want it to not use more than 1 Mb.  Anything is fine, but if you can use 30 Mb, set it to 30 Mb.

Then, find a value for `opslimit` that makes the function take about 1 second to return. Start with `1`. It's probably going to be way too low, and the function will be too fast. So increase it until the function is slow enough.

**Comment by nicwhitts** [comment]
Thanks il give it a try.

And I'm using a third party cocoa pod called kbpgp.
It uses this library (line 38):
https://github.com/gabriel/TSTripleSec/blob/master/TSTripleSec/TRSTripleSec.m

And 

Line 39
https://github.com/gabriel/NAChloride/blob/master/NAChloride/NAScrypt.m

Which is what i was referring to.

**Comment by jedisct1** [comment]
You can't use scrypt with less than 32 Gb.

**Comment by nicwhitts** [comment]
Cool thanks a lot for the help anyway, appreciated
