### ISSUE TITLE
Add CodeBlocks project (.cbp) file.

### ISSUE THREAD

**Issue by sahil56** [jedisct1/libsodium#565]
It would be easy for those who don't have Visual Studio installed and there is no _CMakeLists.txt_ file.
I would like to contribute by providing a _CMakeLists.txt_ file or a _CodeBlocks project_ file.

**Comment by jedisct1** [comment]
You don’t need to have Visual Studio installed! Just use the precompiled binaries.

**Comment by sahil56** [comment]
I mean to build the solution, one needs Visual Studio. right?

**Comment by jedisct1** [comment]
We're not going to add configurations for all IDEs and code editors.

Codeblocks is just an IDE. The compiler in MingW, and it is fully supported, but requires features detection.

Precompiled binaries for MingW are available for download: https://download.libsodium.org/libsodium/releases/ so these are the only files you need to add to you project.
