### ISSUE TITLE
Support opting out of AVX implementations

### ISSUE THREAD

**Issue by ivmaykov** [jedisct1/libsodium#567]
Using AVX instructions on Intel chips can cause the chips to reduce the core frequency, per Intel documentation (i.e. see https://computing.llnl.gov/tutorials/linux_clusters/intelAVXperformanceWhitePaper.pdf). It can also increase the power consumption of the CPU and increase CPU temperature.

In some cases this may be undesirable, so it would be great if libsodium supported opting out of AVX functionality at library initialization time, even on chips that have the AVX support and are running a version of the library compiled with AVX support. I suggest adding a new version of sodium_init() that allows users to explicitly disable AVX support (and maybe other features too?). Something like:

  // Disables AVX implementations, even if the CPU and library support it
  #define SODIUM_AVX_DISABLE 0x1
  // .. add more flags here
  int sodium_init_flags(unsigned long long flags);

Then if the user of the library is ok with auto-detecting AVX support and using it if available, (s)he can call `sodium_init()`. To explicitly disable AVX and use non-AVX implementations of crypto functions, (s)he can instead call `sodium_init_flags(SODIUM_AVX_DISABLE)`.

It would also be great if we had an API that returned the features that libsodium is using after sodium_init() runs, i.e. user could call some function and see what implementations of crypto functions are being used (AVX / SSE / etc).

**Comment by jedisct1** [comment]
I'm not a fan of this, as it would introduce something very architecture-specific.

What optimized implementations are being used is also something that applications shouldn't really rely on, as this this is bound to change a lot, even between minor versions.

The `sodium_runtime_*()` functions can be used to check that features are being used. These functions do not only detect CPU features, but also depend on what the compiler was able to support, and thus what implementations will be used.

I totally understand the use case, but adding a function specifically to disable AVX would be a bit of a ugly hack.

Would a compile-time option work?

**Comment by ivmaykov** [comment]
Compile-time option exists now, but it is pretty annoying to support in our build environment, as we currently enforce a single version of each dependency for everything in our repo. So, we would need to have two different dependencies, "libsodium" and "libsodium-no-avx", and have projects depend on one or the other. And if I want "libsodium-no-avx" in my service, but it already depends on internal library "foo" which depends on "libsodium", I am out of luck. I understand that's not really your problem though.

Is there any way to make the runtime opt-out option acceptable? My thinking was, if you call `sodium_init_flags(SODIUM_AVX_DISABLE)` on a system that doesn't have AVX (maybe an older Intel chip or a non-Intel chip), it is simply ignored and the effect is the same as just calling `sodium_init()`.

**Comment by ivmaykov** [comment]
@jedisct1 Re: "What optimized implementations are being used is also something that applications shouldn't really rely on, as this this is bound to change a lot, even between minor versions."

This is clearly a performance tuning issue. Application's correctness is not affected by which implementations are selected by libsodium. But performance is, and when running at very large scale things like power consumption and heat can matter a lot. And if our application is using relatively few AVX-enabled crypto functions, the increased perf on those functions might not be worth the performance cost on everything else, caused by Intel's clock speed throttling when AVX unit on the CPU is turned on.

Again, this can be very workload-specific, so AVX-enabled may be the right decision for one service while AVX-disabled is the right decision for another. Easiest way for us to control this is to have a single library dependency and make the decision at runtime within each application, but if that's not possible we'll explore other options.

**Comment by jedisct1** [comment]
An alternative might be to tag the `sodium_runtime_*()` function as weak symbols, so they can be overridden?

**Comment by ivmaykov** [comment]
@jedisct1 You mean the client would manually set the implementations they want after calling sodium_init()? That would probably work, but seems more fragile from the user's perspective:

- user now has to be aware of capabilities of the CPU and detect the best non-AVX implementation, essentially duplicating the libsodium logic that already does this
- when more AVX implementations of crypto primitives are added in later versions, user has to modify their initialization code and override those too

I am not familiar with the internals of the code that performs the selection of implementations. I guess if we had something like this, it wouldn't be too bad:

int cpuFlags = some_sodium_function_that_detects_cpu_capabilities();
cpuFlags &= ~CPU_AVX_FLAG; // zero out the AVX feature flag
sodium_set_runtime_implementations(cpuFlags);

**Comment by ivmaykov** [comment]
I would also be fine with an additional function like `sodium_avx_disable()` that must be called after `sodium_init()` and works like this:
- if CPU and/or library does not have AVX support, does nothing
- otherwise, changes runtime implementations of crypto functions to the fastest non-AVX implementation

Maybe also have a `sodium_avx_enable()` that does the opposite (enable AVX implementations if both CPU and library have support, otherwise does nothing).

**Comment by jedisct1** [comment]
No what I meant.

If your app doesn't want to use AVX, it can define a `sodium_runtime_has_avx()` function that always return `0`.

If this is a weak symbol in the library, the one from your application will replace it.

**Comment by ivmaykov** [comment]
I see ... and if we don't define it, the default function in libsodium will be used instead?

**Comment by jedisct1** [comment]
Exactly.

**Comment by jedisct1** [comment]
I think this can even offer more flexibility, such as the ability to use a set of features even if they were not detected (maybe because you're performing tests within an emulator).

**Comment by ivmaykov** [comment]
Yeah, I think that would work. We can define a tiny internal library ("libsodium-avx-disable") that provides a single function:

`int sodium_runtime_has_avx() { return 0; }`

Then, any binary that wants to disable AVX depends on both "libsodium" and "libsodium-avx-disable". And a binary that wants AVX support depends on just "libsodium". Works for me.

**Comment by jedisct1** [comment]
Hi Ilya,

That was done in cc51916072f645e0ff6528f515d9de17655929de

Thanks!
