### ISSUE TITLE
Premake for Windows

### ISSUE THREAD

**Issue by hectorllanosSBM** [jedisct1/libsodium#568]
I wanted to use the build guildlines outlined in BUILDING.md, but I am unable to create the .sln file from premake. (I maybe doing it wrong)

I installed premake and pulled the latest release (0.6).
Opened up CMD and cd to yojimbo.
Then I typed 'premake5 solution'.

When it runs, I get an error that states: "Windows cannot find 'Yojimbo.sln'. Make sure you typed the name correctly, and then try again."

Am I suppose to make a .sln first? I am using VS 2015 and/or 2017

**Comment by jedisct1** [comment]
There's no `BUILDING.md` file in this project, and it doesn't use premake (and never will).

Since you mentioned Yojimbo, I think you should ask on the issues tracker of the Yojimbo project, not here :)

**Comment by hectorllanosSBM** [comment]
Oh sorry wrong project
