### ISSUE TITLE
Libsodium 1.0.13 fails to build on Visual Studio 2013

### ISSUE THREAD

**Issue by DevCybran** [jedisct1/libsodium#569]
The libsodium 1.0.13 package, downloaded from https://github.com/jedisct1/libsodium/releases/download/1.0.13/libsodium-1.0.13.tar.gz , fails to build on Visual Studio with the following error message:

`RC : fatal error RC1110: could not open builds\msvc\resource.rc`

All previous versions of libsodium (1.0.12 and earlier) can be built without any problems.

The error might be related to the following new elements which were added to `libsodium.vcxproj` in 1.0.13:

```
  <ItemGroup>
    <ResourceCompile Include="builds\msvc\resource.rc">
    </ResourceCompile>
  </ItemGroup>
```

`builds\msvc\resource.rc` does indeed not exist in the package.

Additional information:
* I attempted to run release- and debug-DLL and -non-DLL x64 builds using the batch build system
* Platform: Visual Studio 2013 Update 5 on Windows 7 x64

**Comment by jedisct1** [comment]
I'm a bit confused here. The build scripts for Visual Studio were never part of the tarballs, and I just verified that 1.0.13 doesn't have the builds directory either.

Adding them wouldn't be a bad idea, even if this means we need to make sure that we don't forget to update the list of distributed files whenever these Visual Studio files get updated.

But in the meantime, if you want to rebuild the DLLs, you need to check out the code from Git (use the `stable` branch).

**Comment by jedisct1** [comment]
The files were added. I'm not sure that it is a good idea, though, as the Visual Studio files represent no less than 660 K of additional data that most people don't need.

**Comment by BurningEnlightenment** [comment]
My thoughts in random order:
* 660KiB aren't really significant these days
* the VS build files could ~~live~~ rot in their own tarball
* people not capable of typing `git clone -b stable --depth 1 https://github.com/jedisct1/libsodium.git` are doomed anyway :wink:

**Comment by jedisct1** [comment]
My thoughts in random order:
- 660 KB isn't small, but since it's all very redundant XML data, it compresses down to about 12 KB, so this is acceptable.
- `git` returns `command not found` on Windows. That said, Visual Studio now has really nice Git integration.
- Having build files in one tarball, and the source code in another would be a mess.
- It's raining cats and dogs outside, and it really plenty sucks since I was planning to hit the gym.
