### ISSUE TITLE
Argon2i is too slow.

### ISSUE THREAD

**Issue by LoupVaillant** [jedisct1/libsodium#571]
Libsodium's Argon2i implementation seems to be significantly slower than it should be. Monocypher beats it by 27% on my machine. Given the nature of password derivation, this would affect security.

Observed on version 1.0.12 and 1.0.13, on a Skylake i5 laptop running GNU/Linux.

Steps to reproduce
--------------------------

Download version [1.0.13](https://github.com/jedisct1/libsodium/releases/download/1.0.13/libsodium-1.0.13.tar.gz), then install it thus:

    $ tar -xzf  tar -xzf libsodium-1.0.13.tar.gz 
    $ cd libsodium-1.0.13
    $ CFLAGS="-O3 -march=native"
    $ echo $CFLAGS  #Just to make sure
    $ ./configure
    $ make
    $ sudo make install

Download [Monocypher](https://github.com/LoupVaillant/Monocypher)

    $ git clone git@github.com:LoupVaillant/Monocypher.git
    $ cd Monocypher
    $ make speed
    $ ./speed

Look at the results.

Notes
-----

Monocypher is compiled with GCC, using `-O3 march=native` by default. Argon2 is very sensitive to optimisation options, both on Monocypher's and Libsodium's end. Using `-O2` just makes everyone slower, but Monocypher is still 15% faster than Libsodium.

The source code of the benchmark can be found in `Monocypher/tests/speed.c`. The approach was to take the best timing of 20 runs (performed in a row, which should minimise cache misses). This is relatively stable, results rarely varying by more than 1 or 2%.

The benchmark currently works with 1024 blocks (1Mib) in a single lane (Monocypher doesn't support multiple lanes). Running it with 16Mib instead (modify the macro `SIZE` at the beginning of `speed.c`) yields similar results.

Are SSE or AVX instructions enabled by default for Libsodium's Argon2? I haven't found any reliable way to enable or disable those (even generally). Right now I'm not sure what my benchmark measures exactly.

Speculations about the cause
------

I have personally looked at the reference implementation to correct my own. They seem they use heap allocations liberally —which is surprising, considering Argon2 was designed specifically to avoid those. More specifically, they seem to use such allocations to generate the stream of secret-independent reference indices needed by Argon2i. I believe they do this once per segment. (Monocypher instead uses a pseudo-stream cypher with a context on the stack, inspired by its own Chacha20 implementation.)

Overall, the reference implementation is pretty complex, and may hide other inefficiencies. (Threads maybe? Monocypher's choice of using only one lane makes its life much easier.)

If Libsodium inherited from this reference implementation, even indirectly, it may share those inefficiencies.

**Comment by jedisct1** [comment]
Pull requests welcome!

**Comment by jedisct1** [comment]
It's the reference implementation, so submitting your patches there would be even better for all users!

**Comment by LoupVaillant** [comment]
Crap, this is going to require some work: my implementation is very different, and incomplete (no threads, Argon2i only.)

(I noticed you closed the issue, do you mean to suggest I open it upstream? Also, if someone could actually reproduce my observations…)

**Comment by technion** [comment]
@LoupVaillant I've fixed several upstream issues and they've landed here soon after, so yes, I'd expect getting it dealt with there is exactly what they mean.
