### ISSUE TITLE
Macro that contains the size of the sodium_malloc canary and wrapper around getpagesize

### ISSUE THREAD

**Issue by FSMaxB** [jedisct1/libsodium#572]
It would be  really useful to have a macro that contains the size of the canary that `sodium_malloc` uses and a wrapper around the `getpagesize` call that the current platform provides.

This would allow to exactly allocate a desired amount of pages with `sodium_malloc` like this.

```c
size_t pages = 3;
size_t allocation_size = pages * sodium_pagesize() - SODIUM_CANARY_SIZE;
void *three_pages = sodium_malloc(allocation_size);
```

Use case: For implementing an arena allocator for temporary storage of sensitive data.

**Comment by jedisct1** [comment]
That's a good idea, but how about platforms that don't have a page size (e.g. wasm, js)?
What should we return in that case?

**Comment by jedisct1** [comment]
Also, on platforms that don't have protected memory, we use *two* canaries.
It's a bit tricky to expose this in a generic way.

**Comment by FSMaxB** [comment]
If there is no pagesize I think there are two options:
1. return 0 (bad, because it might be quite unexpected and many people won't check for that)
2. Just return some common value, like 4K for example

About the canaries: If the macro would be something like `SODIUM_MALLOC_OVERHEAD` then it wouldn't matter if there are two canaries, the value would just be 2 times the canary size.

**Comment by FSMaxB** [comment]
Another possibility for the page size:
```c
int sodium_pagesize(size_t *size);
```

If there is no pagesize available this returns nonzero, otherwise zero.

**Comment by jedisct1** [comment]
That's another possibility!

But as the page size is essentially an alignment, just returning `1` would also work.

Gonna add this shortly. Thanks for suggesting this!

**Comment by FSMaxB** [comment]
In my use case the use of `getpagesize` is less for alignment and more for not wasting space when using `sodium_malloc` since it allocates at least 3 pages anyway even for small allocations.

Returning `1` when there is no concept of a pagesize would mean that I have to manually detect `1` and fall back to some other chunk size.

**Comment by jedisct1** [comment]
The overhead is not constant; it depends on the allocation size, since the base address has to be aligned to a page size even if the requested size is not.

So instead of returning the page size, maybe something like this?

```c
size_t sodium_alloc_overhead(size_t unprotected_size)
```

**Comment by FSMaxB** [comment]
Ok, this is turning into the XY problem. Let me explain exactly what I want to do:

For a given number of pages that `sodium_malloc` allocates, I want to get the maximum amount of usable memory out of it.

How can I achieve this with `sodium_alloc_overhead`?

Looking at the source code, `sodium_malloc` allocates 3 pages + `page_round(size + canary_size)`. Meaning that I get the most out of it when requesting `n * pagesize - canary_size`.

There only seem to be two cases:
1. HAVE_ALIGNED_MALLOC
   * as described above
   * Need to allocate `n * pagesize - canary_size` to not waste memory.
2. !HAVE_ALIGNED_MALLOC
   * I can allocate whatever I want.
   * Just uses `malloc` except for size 0, where it allocates one byte.
   * Either I'm reading the code wrong, or no canary is used at all in this case.

**Comment by FSMaxB** [comment]
My understanding of the memory layout after reading the code:

```
          page 1               page 2               page 3                     page n - 1     page n
+-------------------------+------------+----------------------------+-- ... --+-----------+------------+
| allocation_size | empty | guard page | empty | canary | user_data |   ...   | user_data | guard page |
+-------------------------+------------+----------------------------+-- ... --+-----------+------------+
^                                      ^       ^        ^
|                                      | ------|--------| unprotected size ---------------|
base_ptr                 unprotected_ptr       |        user_ptr
                                               canary_ptr
```

The idea is to make use of the empty space in page 3.

**Comment by FSMaxB** [comment]
Or rather: not having any empty space there.

**Comment by jedisct1** [comment]
Very nice ASCII drawing, and this is exactly how it works :)

So, maybe a function that returns the maximum user data size given a number of pages?

Even then, I'm not a big fan of such an API, as it exposes too much of the internals.

**Comment by FSMaxB** [comment]
Maybe I'll just have to rely on the internal layout then by just using a number for the canary size.

But in that case it would still be useful to have an abstraction over `getpagesize`.
