### ISSUE TITLE
Compiling with VS2017

### ISSUE THREAD

**Issue by tsky1971** [jedisct1/libsodium#573]
Hi,
Compiling with VS 2017 Enterprise seems to be broken.
The batch files where hardcoded to "community" version. 

> SET solution=%1
SET version=%2
SET log=build_%version%.log
SET tools=Microsoft Visual Studio %version%.0\VC\vcvarsall.bat
IF %version% == 15 SET tools=Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
SET environment="%programfiles(x86)%\%tools%"
IF NOT EXIST %environment% SET environment="%programfiles%\%tools%"
IF NOT EXIST %environment% GOTO no_tools

And the Solution for 2017gives for DynRelease x64
>1>   Bibliothek "D:\AUT_WH\ThirdParty\libsodium\builds\msvc\vs2017\libsodium\..\..\..\..\bin\x64\Release\v141\dynamic\libsodium.lib" und Objekt "D:\AUT_WH\ThirdParty\libsodium\builds\msvc\vs2017\libsodium\..\..\..\..\bin\x64\Release\v141\dynamic\libsodium.exp" werden erstellt.
1>randombytes_sysrandom.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "COMPILER_ASSERT" in Funktion "randombytes_sysrandom_buf".
1>D:\AUT_WH\ThirdParty\libsodium\builds\msvc\vs2017\libsodium\..\..\..\..\bin\x64\Release\v141\dynamic\libsodium.dll : fatal error LNK1120: 1 nicht aufgelöste Externe
1>Die Erstellung des Projekts "libsodium.vcxproj" ist abgeschlossen -- FEHLER.

This is a linker error... can anyone give a hint?

tom

**Comment by jedisct1** [comment]
Use a release or the `stable` branch.

**Comment by tsky1971** [comment]
ok. branch stable fix link error.
and:

```
IF EXIST Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat (
	IF %version% == 15 SET tools=Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat	
)

IF EXIST Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat (
	IF %version% == 15 SET tools=Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
)
```

fix VS2017 Enterprise problem.
