### ISSUE TITLE
libtool error msg on dietpi eg debain 8

### ISSUE THREAD

**Issue by blub4747** [jedisct1/libsodium#577]
Hi guys,

I am trying to compile libsodium from the tar archive on my Rasperry Pi2 eg Dietpi eg Debian 8 variant.

When trying to built I do get the following error msg

checking whether to enable maintainer-specific portions of Makefiles... no
configure: error: The build directory contains whitespaces - This can cause tests/installation to fail due to limitations of some libtool versions

Can someone please tell me how to resolve this problem?

Thx, blub4747

**Comment by jedisct1** [comment]
As the error message says, you are trying to compile it in a directory that contains whitespaces, and libtool has issues with this.

Compile in a different directory.
