### ISSUE TITLE
ed25519_ref10.h to the public API

### ISSUE THREAD

**Issue by rozmansi** [jedisct1/libsodium#587]
Hi,

I am writing a C# wrapper for libsodium trying to implement a class for Ed25519 signing.

Are there any drawbacks, functions in _ed25519_ref10.h_ are not publically available?

I require signing/verifying a SHA-512 hash I receive from an external source. The data is not available to me, only the hash. Therefore, I cannot use the official `crypto_sign_ed25519ph_init()`, `crypto_sign_ed25519ph_update()`, `crypto_sign_ed25519ph_final_create()`/`crypto_sign_ed25519ph_final_verify()` pattern.

Therefore, I use `_crypto_sign_ed25519_detached()`/`_crypto_sign_ed25519_verify_detached()` directly. But those are not part of the public API raising security and future compatibility concerns.

**Comment by jedisct1** [comment]
Hi,

These functions are really only supposed to be used internally, by a specific implementation of a specific signature scheme.

However, as long as the hash function is collision-resistant, it's perfectly acceptable to use the regular `crypto_sign()` function for signing hashes.

The only difference between `Ed25519ph(m)` and `Ed25519(h(m))` is a constant to provide domain separation; if the same key is used for both, the output will be intentionally not the same.
So, unless you specifically need Ed25519ph, just use the regular `crypto_sign()` API with your hashes.

**Comment by rozmansi** [comment]
The issue is exposed when trying to create derived classes implementing [`AsymmetricSignatureFormatter.CreateSignature()`](https://msdn.microsoft.com/en-us/library/0ceswc8x.aspx) and [`AsymmetricSignatureDeformatter.VerifySignature()`](https://msdn.microsoft.com/en-us/library/ms147963.aspx) methods.
.NET Framework stream signing helper classes do the hashing and when EOS is reached they call these methods with `h(m)` as the input.
Deriving signer/verifier from those classes enables one to seamlessly integrate Ed25519 signing into .NET Framework readily available stream signers/verifiers.

Workarounds are:
1. Calling `_crypto_sign_ed25519_detached()`/`_crypto_sign_ed25519_verify_detached()` directly:
   This option provides Ed25519ph compatibility with best .NET integration, at a cost of couple of internal libsodium calls.
2. Switching from `Ed25519ph(m)` to `Ed25519(h(m))` as suggested by @jedisct1:
   This breaks Ed25519ph compatibility (the signing sides needs amends), but still offers best .NET integration.
3. Invent parallel .NET classes for stream signing and verifying:
   You get Ed25519ph compatibility, but you can't use standard .NET helper classes to sign/verify data streams.

Reviewing the libsodium code, the public [`crypto_sign_ed25519ph_final_create()`](https://github.com/jedisct1/libsodium/blob/1a3b474f7f6e6c01c56f2b3f53c1d30ed74e54ef/src/libsodium/crypto_sign/ed25519/sign_ed25519.c#L74) and [`crypto_sign_ed25519ph_final_verify()`](https://github.com/jedisct1/libsodium/blob/1a3b474f7f6e6c01c56f2b3f53c1d30ed74e54ef/src/libsodium/crypto_sign/ed25519/sign_ed25519.c#L87) which are intended for Ed25519ph signing/verifying are actually just a simple wrappers to the internal `_crypto_sign_ed25519_detached()` and `_crypto_sign_ed25519_verify_detached()`.

My original intent to ask you was:
Given the `crypto_sign_ed25519ph_final_create()` and `crypto_sign_ed25519ph_final_verify()` simplicity, is it cryptographically safe to bypass them and call `_crypto_sign_ed25519_detached()` and `_crypto_sign_ed25519_verify_detached()` directly?

**Comment by jedisct1** [comment]
These internal functions may change or disappear.

To be safe, opt for 2).

**Comment by rozmansi** [comment]
... perhaps a `crypto_sign_*hash*_ed25519ph_final_create()` and a `crypto_sign_*hash*_ed25519ph_final_verify()` would then be introduced. ;)
