### ISSUE TITLE
Question about Integer Multiplication (Ref10 Curve25519)

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/libsodium#588]
There are a few places in the ref10 code where an integer is multiplied by `1 << n` instead of being bitshifted by `n`. Is there a reason for this? Bonus: Would replacing these operations with a left shift make the code faster?

https://github.com/jedisct1/libsodium/blob/6b43c1ddb6bb7d7f2528bdac8433520603150345/src/libsodium/crypto_core/curve25519/ref10/curve25519_ref10.c#L240-L270

https://github.com/jedisct1/libsodium/blob/6b43c1ddb6bb7d7f2528bdac8433520603150345/src/libsodium/crypto_core/curve25519/ref10/curve25519_ref10.c#L351-L421

Related to my inquiry, but not any specific security issues:

* https://research.kudelskisecurity.com/2017/01/16/when-constant-time-source-may-not-save-you/
* https://bearssl.org/ctmul.html

**Comment by paragonie-scott** [comment]
(Sending a pull request, mostly to see if Travis CI pukes if I make this change.)

**Comment by jedisct1** [comment]
These are signed integers.

When negative, shifting a signed integer has an undefined behavior in C.

**Comment by paragonie-scott** [comment]
Ah. This is why I don't do C development. :)

Thanks, @jedisct1 :)

**Comment by jedisct1** [comment]
Carries could be unsigned. But everything else has to be signed.
