### ISSUE TITLE
Building for iOS fails

### ISSUE THREAD

**Issue by peret** [jedisct1/libsodium#591]
For me running `./dist-build/ios.sh` configures fine but the make-run fails. My Xcode version is 8.3.3.
This is the log output:

> checking build system type... x86_64-apple-darwin16.7.0
checking host system type... i686-apple-darwin10
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-apple-darwin10-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '501' is supported by ustar format... yes
checking whether GID '20' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for i686-apple-darwin10-gcc... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc is Clang... yes
checking whether Clang needs flag to prevent "argument unused" warning when linking with -pthread... -Qunused-arguments
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for gcc option to accept ISO C99... none needed
checking dependency style of gcc... gcc3
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for __native_client__ defined... no
checking for _FORTIFY_SOURCE defined... no
checking whether C compiler accepts -D_FORTIFY_SOURCE=2... yes
checking whether C compiler accepts -fvisibility=hidden... yes
checking whether C compiler accepts -fPIC... yes
checking whether C compiler accepts -fPIE... yes
checking whether the linker accepts -pie... yes
checking whether C compiler accepts -fno-strict-aliasing... yes
checking whether C compiler accepts -fno-strict-overflow... yes
checking whether C compiler accepts -fstack-protector... yes
checking whether the linker accepts -fstack-protector... yes
checking whether C compiler accepts -Wwrite-strings... yes
checking whether C compiler accepts -Wdiv-by-zero... yes
checking whether C compiler accepts -Wsometimes-uninitialized... yes
checking whether C compiler accepts  -Wall... yes
checking whether C compiler accepts  -Wall -Wextra... yes
checking for clang... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wpointer-arith... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wpointer-arith -Wredundant-decls... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wshorten-64-to-32... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wshorten-64-to-32 -Wstrict-prototypes... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wshorten-64-to-32 -Wstrict-prototypes -Wswitch-enum... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wshorten-64-to-32 -Wstrict-prototypes -Wswitch-enum -Wvariable-decl... yes
checking whether C compiler accepts  -Wall -Wextra -Wno-unknown-warning-option -Wbad-function-cast -Wcast-align -Wcast-qual -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-unknown-pragmas -Wnormalized=id -Wnull-dereference -Wpointer-arith -Wredundant-decls -Wshorten-64-to-32 -Wstrict-prototypes -Wswitch-enum -Wvariable-decl -Wno-type-limits... yes
checking whether the linker accepts -Wl,-z,relro... no
checking whether the linker accepts -Wl,-z,now... no
checking whether the linker accepts -Wl,-z,noexecstack... no
checking whether segmentation violations can be caught when using the C compiler... unknown
configure: WARNING: On this platform, segmentation violations cannot be caught using signal handlers. This is expected if you enabled a tool such as Address Sanitizer (-fsanitize=address), but be aware that using Address Sanitizer may also significantly reduce performance.
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... no
checking for i686-apple-darwin10-dumpbin... no
checking for i686-apple-darwin10-link... no
checking for dumpbin... no
checking for link... link -dump
configure: WARNING: using cross tools not prefixed with host triplet
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin16.7.0 file names to i686-apple-darwin10 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin16.7.0 file names to toolchain format... func_convert_file_noop
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for i686-apple-darwin10-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for i686-apple-darwin10-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for i686-apple-darwin10-ar... no
checking for ar... ar
checking for archiver @FILE support... no
checking for i686-apple-darwin10-strip... strip
checking for i686-apple-darwin10-ranlib... no
checking for ranlib... ranlib
checking command to parse nm output from gcc object... failed
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for i686-apple-darwin10-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking for i686-apple-darwin10-dsymutil... no
checking for dsymutil... dsymutil
checking for i686-apple-darwin10-nmedit... no
checking for nmedit... nmedit
checking for i686-apple-darwin10-lipo... no
checking for lipo... lipo
checking for i686-apple-darwin10-otool... no
checking for otool... otool
checking for i686-apple-darwin10-otool64... no
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... ./configure: line 10867: 53374 Abort trap: 6           $RANLIB libconftest.a 2>&5
no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fno-common -DPIC
checking if gcc PIC flag -fno-common -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin10 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for i686-apple-darwin10-ar... ar
checking whether C compiler accepts -mmmx... yes
checking for MMX instructions set... yes
checking whether C compiler accepts -mmmx... (cached) yes
checking whether C compiler accepts -msse2... yes
checking for SSE2 instructions set... yes
checking whether C compiler accepts -msse2... (cached) yes
checking whether C compiler accepts -msse3... yes
checking for SSE3 instructions set... yes
checking whether C compiler accepts -msse3... (cached) yes
checking whether C compiler accepts -mssse3... yes
checking for SSSE3 instructions set... yes
checking whether C compiler accepts -mssse3... (cached) yes
checking whether C compiler accepts -msse4.1... yes
checking for SSE4.1 instructions set... yes
checking whether C compiler accepts -msse4.1... (cached) yes
checking whether C compiler accepts -mavx... yes
checking for AVX instructions set... yes
checking whether C compiler accepts -mavx... (cached) yes
checking whether C compiler accepts -mavx2... yes
checking for AVX2 instructions set... yes
checking whether C compiler accepts -mavx2... (cached) yes
checking if _mm256_broadcastsi128_si256 is correctly defined... yes
checking whether C compiler accepts -maes... yes
checking whether C compiler accepts -mpclmul... yes
checking for AESNI instructions set and PCLMULQDQ... yes
checking whether C compiler accepts -maes... (cached) yes
checking whether C compiler accepts -mpclmul... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking intrin.h usability... no
checking intrin.h presence... no
checking for intrin.h... no
checking if _xgetbv() is available... no
checking for inline... inline
checking whether byte ordering is bigendian... (cached) no
checking whether __STDC_LIMIT_MACROS is required... no
checking whether we can use x86_64 asm code... no
checking whether we can assemble AVX opcodes... no
checking for 128-bit arithmetic... no
checking for cpuid instruction... yes
checking if the .private_extern asm directive is supported... yes
checking if the .hidden asm directive is supported... no
checking if weak symbols are supported... yes
checking if data alignment is required... no
checking if atomic operations are supported... yes
checking for arc4random... yes
checking for arc4random_buf... yes
checking for mmap... yes
checking for mlock... yes
checking for madvise... yes
checking for mprotect... yes
checking for explicit_bzero... no
checking for nanosleep... yes
checking for posix_memalign... yes
checking for getpid... yes
checking if gcc/ld supports -Wl,--output-def... not needed, shared libraries are disabled
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating contrib/Makefile
config.status: creating dist-build/Makefile
config.status: creating libsodium.pc
config.status: creating libsodium-uninstalled.pc
config.status: creating msvc-scripts/Makefile
config.status: creating src/Makefile
config.status: creating src/libsodium/Makefile
config.status: creating src/libsodium/include/Makefile
config.status: creating src/libsodium/include/sodium/version.h
config.status: creating test/default/Makefile
config.status: creating test/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
Making install in contrib
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in dist-build
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in msvc-scripts
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in src
Making install in libsodium
Making install in include
make[4]: Nothing to be done for `install-exec-am'.
 /usr/local/bin/gmkdir -p '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include'
 /usr/local/bin/gmkdir -p '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include'
 /usr/local/bin/gmkdir -p '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include/sodium'
 /usr/local/bin/gmkdir -p '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include/sodium'
 /usr/bin/install -c -m 644  sodium/version.h '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include/sodium'
 /usr/bin/install -c -m 644  sodium/core.h sodium/crypto_aead_aes256gcm.h sodium/crypto_aead_chacha20poly1305.h sodium/crypto_aead_xchacha20poly1305.h sodium/crypto_auth.h sodium/crypto_auth_hmacsha256.h sodium/crypto_auth_hmacsha512.h sodium/crypto_auth_hmacsha512256.h sodium/crypto_box.h sodium/crypto_box_curve25519xchacha20poly1305.h sodium/crypto_box_curve25519xsalsa20poly1305.h sodium/crypto_core_hchacha20.h sodium/crypto_core_hsalsa20.h sodium/crypto_core_salsa20.h sodium/crypto_core_salsa2012.h sodium/crypto_core_salsa208.h sodium/crypto_generichash.h sodium/crypto_generichash_blake2b.h sodium/crypto_hash.h sodium/crypto_hash_sha256.h sodium/crypto_hash_sha512.h sodium/crypto_kdf.h sodium/crypto_kdf_blake2b.h sodium/crypto_kx.h sodium/crypto_onetimeauth.h sodium/crypto_onetimeauth_poly1305.h sodium/crypto_pwhash.h sodium/crypto_pwhash_argon2i.h sodium/crypto_pwhash_argon2id.h sodium/crypto_pwhash_scryptsalsa208sha256.h sodium/crypto_scalarmult.h sodium/crypto_scalarmult_curve25519.h sodium/crypto_secretbox.h sodium/crypto_secretbox_xchacha20poly1305.h sodium/crypto_secretbox_xsalsa20poly1305.h sodium/crypto_shorthash.h sodium/crypto_shorthash_siphash24.h sodium/crypto_sign.h sodium/crypto_sign_ed25519.h sodium/crypto_sign_edwards25519sha512batch.h '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include/sodium'
 /usr/local/bin/gmkdir -p '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include/sodium'
 /usr/bin/install -c -m 644  sodium/crypto_stream.h sodium/crypto_stream_aes128ctr.h sodium/crypto_stream_chacha20.h sodium/crypto_stream_salsa20.h sodium/crypto_stream_salsa2012.h sodium/crypto_stream_salsa208.h sodium/crypto_stream_xchacha20.h sodium/crypto_stream_xsalsa20.h sodium/crypto_verify_16.h sodium/crypto_verify_32.h sodium/crypto_verify_64.h sodium/export.h sodium/randombytes.h sodium/randombytes_salsa20_random.h sodium/randombytes_sysrandom.h sodium/runtime.h sodium/utils.h '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include/sodium'
 /usr/bin/install -c -m 644  sodium.h '/Users/peter/Downloads/libsodium-1.0.13/libsodium-ios/tmp/simulator32/include/.'
  CC       crypto_generichash/blake2b/ref/libssse3_la-blake2b-compress-ssse3.lo
  CC       crypto_pwhash/argon2/libssse3_la-argon2-fill-block-ssse3.lo
  CC       crypto_generichash/blake2b/ref/libsse41_la-blake2b-compress-sse41.lo
  CC       crypto_generichash/blake2b/ref/libavx2_la-blake2b-compress-avx2.lo
  CC       crypto_pwhash/argon2/libavx2_la-argon2-fill-block-avx2.lo
  CC       crypto_stream/chacha20/dolbeau/libavx2_la-chacha20_dolbeau-avx2.lo
  CC       crypto_stream/salsa20/xmm6int/libavx2_la-salsa20_xmm6int-avx2.lo
  CC       crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo
  CC       crypto_aead/xchacha20poly1305/sodium/libsodium_la-aead_xchacha20poly1305.lo
  CC       crypto_auth/libsodium_la-crypto_auth.lo
  CC       crypto_auth/hmacsha256/libsodium_la-auth_hmacsha256.lo
  CC       crypto_auth/hmacsha512/libsodium_la-auth_hmacsha512.lo
  CC       crypto_auth/hmacsha512256/libsodium_la-auth_hmacsha512256.lo
  CC       crypto_box/libsodium_la-crypto_box.lo
  CC       crypto_box/libsodium_la-crypto_box_easy.lo
  CC       crypto_box/libsodium_la-crypto_box_seal.lo
  CC       crypto_box/curve25519xsalsa20poly1305/libsodium_la-box_curve25519xsalsa20poly1305.lo
  CC       crypto_core/curve25519/ref10/libsodium_la-curve25519_ref10.lo
  CC       crypto_core/hchacha20/libsodium_la-core_hchacha20.lo
  CC       crypto_core/hsalsa20/ref2/libsodium_la-core_hsalsa20_ref2.lo
  CC       crypto_core/hsalsa20/libsodium_la-core_hsalsa20.lo
  CC       crypto_core/salsa/ref/libsodium_la-core_salsa_ref.lo
  CC       crypto_generichash/libsodium_la-crypto_generichash.lo
  CC       crypto_generichash/blake2b/libsodium_la-generichash_blake2.lo
  CC       crypto_generichash/blake2b/ref/libsodium_la-blake2b-compress-ref.lo
  CC       crypto_generichash/blake2b/ref/libsodium_la-blake2b-ref.lo
  CC       crypto_generichash/blake2b/ref/libsodium_la-generichash_blake2b.lo
  CC       crypto_hash/libsodium_la-crypto_hash.lo
  CC       crypto_hash/sha256/libsodium_la-hash_sha256.lo
  CC       crypto_hash/sha256/cp/libsodium_la-hash_sha256_cp.lo
  CC       crypto_hash/sha512/libsodium_la-hash_sha512.lo
  CC       crypto_hash/sha512/cp/libsodium_la-hash_sha512_cp.lo
  CC       crypto_kdf/blake2b/libsodium_la-kdf_blake2b.lo
  CC       crypto_kdf/libsodium_la-crypto_kdf.lo
  CC       crypto_kx/libsodium_la-crypto_kx.lo
  CC       crypto_onetimeauth/libsodium_la-crypto_onetimeauth.lo
  CC       crypto_onetimeauth/poly1305/libsodium_la-onetimeauth_poly1305.lo
  CC       crypto_onetimeauth/poly1305/donna/libsodium_la-poly1305_donna.lo
  CC       crypto_pwhash/argon2/libsodium_la-argon2-core.lo
  CC       crypto_pwhash/argon2/libsodium_la-argon2-encoding.lo
  CC       crypto_pwhash/argon2/libsodium_la-argon2-fill-block-ref.lo
  CC       crypto_pwhash/argon2/libsodium_la-argon2.lo
  CC       crypto_pwhash/argon2/libsodium_la-blake2b-long.lo
  CC       crypto_pwhash/argon2/libsodium_la-pwhash_argon2i.lo
  CC       crypto_pwhash/argon2/libsodium_la-pwhash_argon2id.lo
  CC       crypto_pwhash/libsodium_la-crypto_pwhash.lo
  CC       crypto_scalarmult/libsodium_la-crypto_scalarmult.lo
  CC       crypto_scalarmult/curve25519/libsodium_la-scalarmult_curve25519.lo
  CC       crypto_secretbox/libsodium_la-crypto_secretbox.lo
  CC       crypto_secretbox/libsodium_la-crypto_secretbox_easy.lo
  CC       crypto_secretbox/xsalsa20poly1305/libsodium_la-secretbox_xsalsa20poly1305.lo
  CC       crypto_shorthash/libsodium_la-crypto_shorthash.lo
  CC       crypto_shorthash/siphash24/libsodium_la-shorthash_siphash24.lo
  CC       crypto_shorthash/siphash24/ref/libsodium_la-shorthash_siphash24_ref.lo
  CC       crypto_sign/libsodium_la-crypto_sign.lo
  CC       crypto_sign/ed25519/libsodium_la-sign_ed25519.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-keypair.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-open.lo
  CC       crypto_sign/ed25519/ref10/libsodium_la-sign.lo
  CC       crypto_stream/chacha20/libsodium_la-stream_chacha20.lo
  CC       crypto_stream/chacha20/ref/libsodium_la-chacha20_ref.lo
  CC       crypto_stream/libsodium_la-crypto_stream.lo
  CC       crypto_stream/salsa20/libsodium_la-stream_salsa20.lo
  CC       crypto_stream/xsalsa20/libsodium_la-stream_xsalsa20.lo
  CC       crypto_verify/sodium/libsodium_la-verify.lo
  CC       randombytes/libsodium_la-randombytes.lo
  CC       sodium/libsodium_la-core.lo
  CC       sodium/libsodium_la-runtime.lo
  CC       sodium/libsodium_la-utils.lo
  CC       sodium/libsodium_la-version.lo
  CC       randombytes/salsa20/libsodium_la-randombytes_salsa20_random.lo
  CC       randombytes/sysrandom/libsodium_la-randombytes_sysrandom.lo
  CC       crypto_scalarmult/curve25519/ref10/libsodium_la-x25519_ref10.lo
  CC       crypto_stream/salsa20/ref/libsodium_la-salsa20_ref.lo
  CC       crypto_aead/aes256gcm/aesni/libaesni_la-aead_aes256gcm_aesni.lo
  CC       crypto_onetimeauth/poly1305/sse2/libsse2_la-poly1305_sse2.lo
  CC       crypto_stream/salsa20/xmm6int/libsse2_la-salsa20_xmm6int-sse2.lo
  CC       crypto_stream/chacha20/dolbeau/libssse3_la-chacha20_dolbeau-ssse3.lo
  CCLD     libsse41.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
  CCLD     libavx2.la
ranlib: warning for library: .libs/libsse41.a the table of contents is empty (no object file members in the library define global symbols)
  CCLD     libaesni.la
  CCLD     libsse2.la
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
Assertion failed: ((unsigned)Val < Attribute::EndAttrKinds && "Attribute out of range!"), function addAttribute, file Attributes.cpp, line 948.
ar: fatal error in /opt/local/bin/ranlib
make[3]: *** [libavx2.la] Error 1
make[3]: *** Waiting for unfinished jobs....
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
Assertion failed: ((unsigned)Val < Attribute::EndAttrKinds && "Attribute out of range!"), function addAttribute, file Attributes.cpp, line 948.
ar: fatal error in /opt/local/bin/ranlib
make[3]: *** [libaesni.la] Error 1
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
Assertion failed: ((unsigned)Val < Attribute::EndAttrKinds && "Attribute out of range!"), function addAttribute, file Attributes.cpp, line 948.
ar: fatal error in /opt/local/bin/ranlib
make[3]: *** [libsse2.la] Error 1
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

**Comment by jedisct1** [comment]
`ar: fatal error in /opt/local/bin/ranlib`

`/opt/local/bin/ranlib` and `/opt/local/bin/ar` are not part of Xcode.

Xcode includes its own version of these tools, and has only been designed to work with them. You seem to have built a Frankenstein environment, mixing the compiler from Xcode and unexpected version of the other required tools.

Delete that `/opt/local/bin` thing, or make sure that it comes at the very end of your `PATH` environment variable instead of overriding what Xcode provides and expects.
