### ISSUE TITLE
Are certain functions guaranteed to be successful, and clarity on AES-GCM limitations?

### ISSUE THREAD

**Issue by theakman2** [jedisct1/libsodium#593]
Hi there,

Will the following functions continue to always either return 0 (i.e. be successful) or abort?

* `crypto_scalarmult_base`
* `crypto_generichash_blake2b`, assuming that `outlen` is not 0 and doesn't exceed 64kb, that `keylen` doesn't exceed `BLAKE2B_KEYBYTES` and `inlen` doesn't exceed 64kb?
* `crypto_sign_ed25519_detached`

When I say 'continue', I mean for future 1.X releases. The current source indicates that they're always successful, but I don't know whether I can rely on that behaviour.

Thanks in advance!

**Comment by jedisct1** [comment]
Hi!

To be safe, don't assume anything. If they return a value, that value should be checked.

**Comment by theakman2** [comment]
Okay, thanks for clarifying. All the error checking makes following our overall algorithms more difficult so I was hoping we could cut down on some of it.

Am I correct in assuming though that `crypto_aead_aes256gcm_encrypt` and `crypto_aead_aes256gcm_encrypt_afternm` will continue to always return 0 for 1.X releases, as described in the documentation?

**Comment by jedisct1** [comment]
To be honest, `crypto_scalarmult_base()` cannot possibly fail unless the curve changes, so it's safe to assume that it will always return `0` in version 1.x.

Ditto for `crypto_generichash()` with correct parameters.

`crypto_sign_ed25519_detached()` should be checked, though.

`crypto_aead_aes256gcm_encrypt()` cannot fail, but they can `abort()` if used with messages that are too large.

**Comment by theakman2** [comment]
Great, that's helpful. We won't be encrypting messages larger than ~64kb so we shouldn't fall into the `abort()` clauses.

On an unrelated note, could you clarify what you mean when you say the following about AES-GCM?

> No more than ~ 350 GB of input data should be encrypted with a given key. This is for ~ 16 KB messages -- Actual figures vary according to message sizes.

Where does this recommendation come from, and how could we calculate the maximum recommended input data for message sizes other than 16kb?

In an ideal world we'd be using ChaCha/Poly, but we need the performance of hardware-accelerated AES.

**Comment by jedisct1** [comment]
See http://www.isg.rhul.ac.uk/~kp/TLS-AEbounds.pdf regarding these limits.

Is ChaCha/Poly actually too slow for your needs? On a recent CPU with AVX2, ChaCha is really fast, and you could just leverage the newly introduced `crypto_secretstream()` API instead of having to deal with key rotations yourself.

**Comment by theakman2** [comment]
I see. Our message sizes range from 8 bytes to ~64kb, but we're regenerating keys every 16GB or once a day (whichever comes first), so it doesn't look like we'd be vulnerable to these attacks.

We're developing a reliable, semi-ordered, secured protocol on top of UDP. Our initial quick-and-dirty benchmarks showed that AES was noticeably faster than ChaCha so we decided to go with the former. AES-GCM, but not ChaCha/Poly, was also supported by OpenSSL at the time, which gave us the flexibility of switching crypto libraries if AES was used.

Now that our protocol implementation is largely complete though and we have a solid performance testing system in place, it looks like it's memory-bound rather than computation-bound. We may therefore be able to switch to ChaCha/Poly without a significant performance hit. OpenSSL also now seems to support ChaCha/Poly.

Experimenting with ChaCha/Poly is definitely on our list for a future refactoring project, as is the `crypto_secretstream` API.
