### ISSUE TITLE
Why is sodium_{bin2hex,bin2base64} returning a char pointer instead of status code?

### ISSUE THREAD

**Issue by blochberger** [jedisct1/libsodium#595]
https://github.com/jedisct1/libsodium/blob/6dcba550c2c86b730657bd55db82eb8c3748618d/src/libsodium/include/sodium/utils.h#L55-L56

https://github.com/jedisct1/libsodium/blob/6dcba550c2c86b730657bd55db82eb8c3748618d/src/libsodium/include/sodium/utils.h#L70-L72

I wonder why the above two functions return a `char` pointer instead of an `int` status code. The pointer should already be known by the caller, as it is passed as an argument anyway.

Unless there is a specific reason I can't think of right now, I would vote for returning an `int` in favour of API consistency.

**Comment by jedisct1** [comment]
For the same reason most `str*` functions of the C library return the target pointer. It makes it easier to use directly as an argument of another function.
```c
fprintf(fp, "result: %s\n", sodium_bin2hex(hex, sizeof hex, bin, sizeof bin));
```

**Comment by blochberger** [comment]
That is a convenience, I agree.

It is a limitation of the underlaying programming language, but I find it confusing when reading code like:

```c
bool a = sodium_bin2hex(hex, sizeof hex, bin, sizeof bin) == 0
bool b = sodium_init() == 0
```

There I cannot quickly see that `a` and `b` are semantically inverted.

**Comment by jedisct1** [comment]
These functions will never fail.

If the output buffer is too small, `sodium_misuse()` will be triggered. But they will never return `NULL`.

**Comment by blochberger** [comment]
I like that, but then the documentation should probably be updated, as this states:

> The function returns `hex` on success, or `NULL` on overflow. It evaluates in constant time for a given size.

**Comment by jedisct1** [comment]
The documentation has been updated. Thanks a lot for spotting this!

**Comment by blochberger** [comment]
For reference: jedisct1/libsodium-doc@ff8895000fae05e8f8a6cf9fa52871c4f64f9217.
