### ISSUE TITLE
Installing Nullarbor dependencies- Emboss

### ISSUE THREAD

**Issue by Anuravi123** [jedisct1/libsodium#596]
I am trying to install all the dependencies for Nullarbor such as snippy, roary, spades and many more. Most of these programs could be installed using brew. But I keep getting errors when installing emboss-

 Installing emboss from homebrew/science
==> Installing dependencies for homebrew/science/emboss: gawk, check, linuxbrew/xorg/libxcb, linuxbrew/xorg/libx11, linuxbrew/xorg/libxext, linuxbrew/xorg/libfs, linuxbrew/xorg/libice, linuxbrew/xorg/libsm, linuxbrew/xorg/libxscrnsaver, linuxbrew/xorg/libxt, linuxbrew/xorg/libxmu, linuxbrew/xorg/libxpm, linuxbrew/xorg/libxaw, linuxbrew/xorg/libxfixes, linuxbrew/xorg/libxcomposite, linuxbrew/xorg/libxrender, linuxbrew/xorg/libxcursor, linuxbrew/xorg/libxdamage, linuxbrew/xorg/font-util, linuxbrew/xorg/libfontenc, linuxbrew/xorg/libxfont, libbsd, expat, gperf, fontconfig, linuxbrew/xorg/libxft, linuxbrew/xorg/libxi, linuxbrew/xorg/libxinerama, linuxbrew/xorg/libxrandr, linuxbrew/xorg/libxres, linuxbrew/xorg/libxtst, linuxbrew/xorg/libxv, linuxbrew/xorg/libxvmc, linuxbrew/xorg/libxxf86dga, linuxbrew/xorg/libxxf86vm, linuxbrew/xorg/libdmx, linuxbrew/xorg/libpciaccess, linuxbrew/xorg/libxkbfile, linuxbrew/xorg/libxshmfence, linuxbrew/xorg/xorg
==> Installing homebrew/science/emboss dependency: gawk
==> Downloading https://ftp.gnu.org/gnu/gawk/gawk-4.1.4.tar.xz
Already downloaded: /home/ubuntu/.cache/Homebrew/gawk-4.1.4.tar.xz
==> ./configure --prefix=/home/ubuntu/.linuxbrew/Cellar/gawk/4.1.4_1 --without-l
==> make
make check
Last 15 lines from /home/ubuntu/.cache/Homebrew/Logs/gawk/03.make:
make[2]: *** [mpfrsort] Error 132
/bin/bash: line 1:  4550 Illegal instruction     (core dumped) LC_ALL=${GAWKLOCALE:-C} LANG=${GAWKLOCALE:-C} AWKLIBPATH=../extension/.libs ../gawk -M -vPREC=double -f "."/mpfrieee.awk > _mpfrieee 2>&1
Makefile:2317: recipe for target 'mpfrieee' failed
make[2]: *** [mpfrieee] Error 132
/bin/bash: line 1:  4530 Illegal instruction     (core dumped) LC_ALL=${GAWKLOCALE:-C} LANG=${GAWKLOCALE:-C} AWKLIBPATH=../extension/.libs ../gawk -M -f "."/mpfrnegzero.awk > _mpfrnegzero 2>&1
Makefile:2332: recipe for target 'mpfrnegzero' failed
make[2]: *** [mpfrnegzero] Error 132
make[2]: Leaving directory '/tmp/gawk-20170913-27471-1l1v87p/gawk-4.1.4/test'
Makefile:1683: recipe for target 'mpfr-tests' failed
make[1]: *** [mpfr-tests] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/gawk-20170913-27471-1l1v87p/gawk-4.1.4/test'
make[1]: Leaving directory '/tmp/gawk-20170913-27471-1l1v87p/gawk-4.1.4/test'
Makefile:742: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

I am not sure what the problem is or I dont understand the error. Due to this, I am unable to install Abricate since it requires emboss. Could someone help me out with this please.

Thanks!

**Comment by jedisct1** [comment]
I don't think that has anything to do with the libsodium project.
