### ISSUE TITLE
crypto_pwhash scryptsalsa208sha256 incompatible with scryptsalsa208sha256_str

### ISSUE THREAD

**Issue by the-djmaze** [jedisct1/libsodium#599]
crypto_pwhash_scryptsalsa208sha256() runs escrypt_kdf() with 'salt' as SALTBYTES (32).
crypto_pwhash_scryptsalsa208sha256_str() runs escrypt_kdf() with 'salt' as STRHASHBYTES_ENCODED (43).

Is it on purpose that these functions are not compatible?

**Comment by jedisct1** [comment]
`_str()` encodes the salt using Base64.

**Comment by the-djmaze** [comment]
Yes i've noticed that. But this way i can't feed crypto_pwhash_scryptsalsa208sha256() with the salt using a Base64 variant or any other salt that is not 32 bytes.
The function expects that salt is always 32 characters which makes it odd.

Did i miss a function where i can provide the salt length to prevent overflows or feed it with salt that is generated by crypto_pwhash_scryptsalsa208sha256_str()?

**Comment by jedisct1** [comment]
This is not exactly base64, but the traditional encoding used by the libc `crypt(3)` function.

What problem are you trying to solve?

**Comment by jedisct1** [comment]
What are you trying to do?

**Comment by jedisct1** [comment]
`scryptsalsa208sha256()` expects a 256 bits, not a string with an encoded representation of that salt. Other parameters are a memory cost and a computational cost factor.

`scryptsalsa208sha256_str()` produces a string. The only guarantee you have about that string is that `scryptsalsa208sha256_str_verify()` can be used to verify that it's valid for a given password.

Internally, and this may change at any time (or be removed), it encodes the algorithm ID, a salt, its length, as well as the `N`, `r` and `p` parameters. Not the memory and CPU cost factors. The former can be computed from the later, but not the other way round.

These functions serve different purposes. You shouldn't mix and match them.

**Comment by the-djmaze** [comment]
Thanks for the explanation. Now i understand i just have to use crypto_pwhash_scryptsalsa208sha256_ll

**Comment by jedisct1** [comment]
It would have helped if you had explained what you wanted to do.
