### ISSUE TITLE
./configure failing for 2017-09-22 version of LATEST.tar.gz

### ISSUE THREAD

**Issue by lmctv** [jedisct1/libsodium#600]
With a just downloaded
   https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
configure fails with a

```
config.status: error: cannot find input file: `builds/Makefile.in'
```
as you can see in 
https://travis-ci.org/lmctv/pynacl/jobs/271340570

**Comment by lmctv** [comment]
While the problem can be worked around by executing
```
automake --add-missing
```
in the top directory of the extracted sources, I'd rather prefer being able to just follow the instructions in 
https://download.libsodium.org/doc/installation/index.html#compilation-on-unix-like-systems

**Comment by jedisct1** [comment]
Good catch, thanks!

That file was added. Thanks again!
