### ISSUE TITLE
scrypt parameters: ‘p = 1’ to disable parallelism, ‘N = 512’ and ‘r = 256’ to set memory requirements

### ISSUE THREAD

**Issue by Jaaap** [jedisct1/libsodium#601]
According to https://download.libsodium.org/doc/password_hashing/scrypt.html
the crypto_pwhash_scryptsalsa208sha256 function (assuming this is THE scrypt function) accepts these parameters:

```
key, sizeof key,
password, sizeof password,
salt,
opslimit,
memlimit
```

most scrypt implementations work with parameters p, N and r, see for instance
http://www.tarsnap.com/scrypt.html

> /**
>  * crypto_scrypt(passwd, passwdlen, salt, saltlen, N, r, p, buf, buflen):
>  * Compute scrypt(passwd[0 .. passwdlen - 1], salt[0 .. saltlen - 1], N, r,
>  * p, buflen) and write the result into buf.  The parameters r, p, and buflen
>  * must satisfy r * p < 2^30 and buflen <= (2^32 - 1) * 32.  The parameter N
>  * must be a power of 2 greater than 1.
>  *
>  * Return 0 on success; or -1 on error.
>  */
> int crypto_scrypt(const uint8_t *, size_t, const uint8_t *, size_t, uint64_t,
>     uint32_t, uint32_t, uint8_t *, size_t);

Any idea how i can map sodium's parameters to scrypt's N, r and p?

**Comment by jedisct1** [comment]
```c
static int
pickparams(unsigned long long opslimit, const size_t memlimit,
           uint32_t *const N_log2, uint32_t *const p, uint32_t *const r)
{
    unsigned long long maxN;
    unsigned long long maxrp;

    if (opslimit < 32768) {
        opslimit = 32768;
    }
    *r = 8;
    if (opslimit < memlimit / 32) {
        *p   = 1;
        maxN = opslimit / (*r * 4);
        for (*N_log2 = 1; *N_log2 < 63; *N_log2 += 1) {
            if ((uint64_t)(1) << *N_log2 > maxN / 2) {
                break;
            }
        }
    } else {
        maxN = memlimit / ((size_t) *r * 128);
        for (*N_log2 = 1; *N_log2 < 63; *N_log2 += 1) {
            if ((uint64_t)(1) << *N_log2 > maxN / 2) {
                break;
            }
        }
        maxrp = (opslimit / 4) / ((uint64_t)(1) << *N_log2);
        /* LCOV_EXCL_START */
        if (maxrp > 0x3fffffff) {
            maxrp = 0x3fffffff;
        }
        /* LCOV_EXCL_STOP */
        *p = (uint32_t)(maxrp) / *r;
    }
    return 0;
}
```
