### ISSUE TITLE
"libsodium leaks secret key material to the stack"

### ISSUE THREAD

**Issue by snej** [jedisct1/libsodium#602]
Alleged by @resilar [here](https://github.com/resilar/sqleet/issues/4#issuecomment-332297204). I have no idea if this is actually true, but it doesn't seem to have been reported to the issue tracker yet and I felt it should be.

Quoting @resilar:

> ... libsodium leaks secret key material to the stack:
>
> https://github.com/jedisct1/libsodium/blob/d338ae951209aa85018cdd1d07fcc21c037f743c/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h#L32-L36 key material moved to heap @ st->r[0..4]
>
> https://github.com/jedisct1/libsodium/blob/d338ae951209aa85018cdd1d07fcc21c037f743c/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h#L66-L75 and then copied to stack variables r0..r4 and s1..s4. The stack variables are never cleared. I have confirmed this experimentally and found out that libsodium leaks 2-4 halves of the secret key to the stack after a single poly1305 calculation.
>
> sqleet/crypto.c:L180-184 shows how it should be done. Go tell the libsodium suckers to use sqleet's implementation instead. Btw, our ChaCha20 and PBKDF2-HMAC-SHA256 primitives are also rock solid ;)

**Comment by jedisct1** [comment]
The state is cleared after finalization: https://github.com/jedisct1/libsodium/blob/2a9c81b5c422f20e1f701109e1e9073fe2cef9b3/src/libsodium/crypto_onetimeauth/poly1305/sse2/poly1305_sse2.c#L872

**Comment by FSMaxB** [comment]
@jedisct1 that clears the structure, but not the local variables `r0` through `r1`!

If `st->r[0]` actually still contains secret key material at the time of the assignment to local variables, then I agree with @resilar that it could actually leak private data.

**Comment by jedisct1** [comment]
Registers contain sensitive data all the time, and that's acceptable, especially when these are not SIMD registers; they will be quickly reused, and unless the implementation is written in pure assembly, this is difficult to avoid.

**Comment by FSMaxB** [comment]
So what if `r0-4` are put on the stack? E.g. because the target architecture doesn't have enough registers. The only hope there would be that the stack frame of `poly1305_finish` or another function will overwrite the part of the stack where the stack frame of `poly1305_blocks` with the sensitive data was, or not?

**Comment by jedisct1** [comment]
You can't make any assertions about what the compiler will store in register or on the stack, and when. The content of a general purpose register can be put onto the stack and restored later. Inlining and LTO make this even less controllable.

Using a volatile pointer makes more harm than good; it stores an extra copy of the value on the stack, only to overwrite it right after. The `volatile` attribute should be applied to the object itself. But this implies a huge performance penalty, and more leakage in virtualized environments.

There were proposals to add gcc and clang extensions to tag variables holding sensitive data, but this was never actually implemented.

**Comment by FSMaxB** [comment]
Ok, thanks for explaining that.

Ok, so if I understand it correctly, even if no intermediate variables are used (meaning direct access via `st->r[index]`) the compiler might still produce code that puts that data on the stack. Which means that there is absolutely no way around this (without writing assembly yourself).

**Comment by jedisct1** [comment]
Using volatile objects may be occasionally acceptable (as in libsodium [crypto_verify_*() functions](https://github.com/jedisct1/libsodium/blob/2a9c81b5c422f20e1f701109e1e9073fe2cef9b3/src/libsodium/crypto_verify/sodium/verify.c#L34-L59), but this is still not bullet proof.

Your application can wipe the stack (max stack usage with secrets in libsodium is salsa20-avx2 with about 1700 bytes), but that won't get rid of registers. So, live with it, especially in the context of poly1305 one-time keys.

**Comment by FSMaxB** [comment]
I understand, I just wanted to be aware of the tradeoffs that are being made.

Thanks again for your explanation.
