### ISSUE TITLE
Possible problem with cpu capabilities detection

### ISSUE THREAD

**Issue by ismail** [jedisct1/libsodium#604]
On some openSUSE build machines (all x86_64 hosts) 32bit builds randomly fail with:

> [  135s] ../../build-aux/test-driver: line 107: 17974 Illegal instruction     "$@" > $log_file 2>&1                              
   [  135s] FAIL: aead_xchacha20poly1305                                                                                            
   [  135s] PASS: aead_aes256gcm                                                                                                    
   [  135s] PASS: auth                                                                                                              
   [  135s] ../../build-aux/test-driver: line 107: 17981 Illegal instruction     "$@" > $log_file 2>&1                              
   [  135s] FAIL: aead_chacha20poly1305                                                                                             
   [  135s] PASS: auth2                                                                                                             
   [  135s] PASS: auth3                                                                                                             
   [  135s] PASS: auth6                                                                                                             
   [  135s] ../../build-aux/test-driver: line 107: 18126 Illegal instruction     "$@" > $log_file 2>&1                              
   [  135s] FAIL: box                                                                                                               
   [  135s] ../../build-aux/test-driver: line 107: 18130 Illegal instruction     "$@" > $log_file 2>&1                              
   [  135s] FAIL: box2                                                                                                              
   [  135s] ../../build-aux/test-driver: line 107: 18168 Illegal instruction     "$@" > $log_file 2>&1                              
   [  135s] FAIL: box7                                                                                                              
   [  135s] ../../build-aux/test-driver: line 107: 18195 Illegal instruction     "$@" > $log_file 2>&1                                
   .... and a lot more of these  .... 

Since all the machines have up to SSE2 and such I believe the problem is in AVX{2} detection. But since the problem comes up randomly I am not really sure how to debug this. Any pointers appreciated!

Btw. tested both 1.0.12 and 1.0.14.

**Comment by ismail** [comment]
Just an update, the builds were using LTO which now I disabled and I'll see if that fixes the problem.

**Comment by jedisct1** [comment]
Please just use the `configure` script as-is. Don't mess with CFLAGS, CPPFLAGS, and LDFLAGS, and don't use `--enable-opt`.

**Comment by jedisct1** [comment]
Were you able to reproduce this without LTO and other additional flags?

**Comment by ismail** [comment]
No, this seems to work fine without LTO. Thank you!

**Comment by michelmno** [comment]
I would suggest to re-open this issue as reported failure still valid for PowerPC and ARM for openSUSE distro.
 An easy correction would be to replace AC_COMPILE_IFELSE by AC_LINK_IFELSE for cpuid checking in configure.ac as per patch suggested in openSUSE https://build.opensuse.org/request/show/723945

**Comment by jedisct1** [comment]
@michelmno This has been changed in `stable`, but can you explain why this is necessary? 

If this is necessary when inline asm is used, why change this specific instance and not, e.g. the `HAVE_AMD64_ASM_V` check?

**Comment by michelmno** [comment]
> @michelmno This has been changed in `stable`, but can you explain why this is necessary?
> 
> If this is necessary when inline asm is used, why change this specific instance and not, e.g. the `HAVE_AMD64_ASM_V` check?

this is necessary because when build with LTO, the related AC_COMPILE_IFELSE completed with no error for ppc64/ppc64le, so that cpuid is abnormally enabled and so package build failed ultimately with:
```
[  223s] /tmp/ccs8V3vP.s: Assembler messages:
[  223s] /tmp/ccs8V3vP.s:21220: Error: unrecognized opcode: `cpuid'
[  223s] /tmp/ccs8V3vP.s:21245: Error: unrecognized opcode: `cpuid'
...
[  223s] lto-wrapper: fatal error: make returned 2 exit status
[  223s] /usr/lib64/gcc/powerpc64le-suse-linux/9/../../../../powerpc64le-suse-linux/bin/ld: error: lto-wrapper failed
[  223s] collect2: error: ld returned 1 exit status
```

**Comment by jedisct1** [comment]
Sure, but why does the compiler behave that way?

Is it expected?

What about other inline asm blocks?

**Comment by michelmno** [comment]
> Sure, but why does the compiler behave that way?
> 
> Is it expected?
> 
> What about other inline asm blocks?

I did not analyzed the lto internals as documented in https://gcc.gnu.org/wiki/LinkTimeOptimization  but at least reported behavior is not new, and need to go up to link step is expected.

I did not identified other asm blocks in configure.ac that would need similar change; did you ?
* the "checking whether we can use inline asm code" do not need changes for my used arches
* others are protected by "# error !x86_64"

**Comment by jedisct1** [comment]
Mmm... so we don't know what this happens, and the original issue from this ticket is different (since this is a run-time issue), but we also don't know what happens and why.

So we should better replace `should not use LTO` with `must not`, and try to enforce this in the configure script.
