### ISSUE TITLE
Mismatch between crypto_pwhash_argon2id_OPSLIMIT_MIN declaration and crypto_pwhash_argon2id behavior

### ISSUE THREAD

**Issue by lmctv** [jedisct1/libsodium#606]
While the declared value of crypto_pwhash_argon2id_OPSLIMIT_MIN is  1, at the beginning of  crypto_pwhash_argon2id https://github.com/jedisct1/libsodium/blob/3659d342af0b3aee953b11fbbd48986c39f60cab/src/libsodium/crypto_pwhash/argon2/pwhash_argon2id.c#L138

the requested opslimit is compared with ARGON2_MIN_TIME and a call with opslimit equal to 1 or 2 fails.

**Comment by jedisct1** [comment]
Ha, good catch. I don’t have a computer right now, but I will merge a fix to the stable branch tomorrow.

**Comment by lmctv** [comment]
The joys coming out from generating the test vectors before writing the python bindings and their tests... Since opslimit was randomly generated with values between 1 and 5, I got into a couple of failed tests.
Funny thing, I wrote a small C driver to confirm the bug before reading the sources!

**Comment by lmctv** [comment]
Since PyNaCl bundles only released versions of libsodium, I'm inserting work-arounds both for this and d338ae9; if at all possible, a quick .15 release would surely be useful to us...

**Comment by jedisct1** [comment]
.15 will probably be released today.
