### ISSUE TITLE
Feature request: password needs rehash function

### ISSUE THREAD

**Issue by Andy-2639** [jedisct1/libsodium#607]
PHP has a function to tell me whether I should rehash a password. It takes a password hash and the currently used algorithm + options.
https://secure.php.net/manual/function.password-needs-rehash.php

I'd like to see a similar function in libsodium to support updating the password hash on the fly when logging in a user.

**Comment by jedisct1** [comment]
It already exists, and it even has pretty much the same name :)

**Comment by jedisct1** [comment]
Look for `crypto_pwhash_str_needs_rehash` here: https://download.libsodium.org/doc/password_hashing/the_argon2i_function.html

**Comment by Andy-2639** [comment]
Thank you very much. I can't belive that I'm so blind to miss it.
