### ISSUE TITLE
make check on LATEST (1.0.15) tar gz fails with two errors

### ISSUE THREAD

**Issue by Manbearpixel** [jedisct1/libsodium#612]
Attempted to install libsodium using the latest release and I receive two Errors after running `make check`. Reproduction steps:
- `wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz`
- `tar -xvzf LATEST.tar.gz`
- `./configure`
- `make`
- `make check`

Everything *passes* except for `ed25519_convert` and `sign` and is shown in the summary:
```
============================================================================
Testsuite summary for libsodium 1.0.15
============================================================================
# TOTAL: 70
# PASS:  68
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 2
============================================================================
```

Comparitively, when I run through the same steps above but with the previous release, **libsodium-1.0.14.tar.gz** everything passes fine:
```
============================================================================
Testsuite summary for libsodium 1.0.14
============================================================================
# TOTAL: 70
# PASS:  70
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

Not sure why this is, but I'm going to go ahead and install 1.0.14 for now. I'm just reporting what I ran into here. Cheers~

**Comment by lmctv** [comment]
If it can be of any use, I'm appending the output of both the failed tests:
[sign_res.txt](https://github.com/jedisct1/libsodium/files/1378469/sign_res.txt)
[ed25519_convert_res.txt](https://github.com/jedisct1/libsodium/files/1378473/ed25519_convert_res.txt)
Thanks.

**Comment by jedisct1** [comment]
Repaired. Tarballs have been updated. Sorry for that :/
