### ISSUE TITLE
pwhash_scrypt test OOM on aarch64

### ISSUE THREAD

**Issue by wizeman** [jedisct1/libsodium#615]
Hi,

I'm trying to build libsodium 1.0.15 on aarch64 (hardware is a Raspberry Pi 3) but when it goes into the `make check-TESTS` phase, the `pwhash_scrypt` test process keeps getting killed by the kernel due to OOM.

The machine has 822 MB of RAM + 458 MB of swap available when I start the build, yet the `pwhash_scrypt` process seems to use all available RAM and all available swap before it's killed.

Is this expected or do you think it's a bug?

Thanks in advance.

**Comment by wizeman** [comment]
BTW, libsodium 1.0.13 did build fine in the same machine, so perhaps something changed in-between...

**Comment by wizeman** [comment]
I forgot to mention that my swap space is composed of zram devices, so there may not actually be as much available swap space as I mentioned, because the compressed swap pages are kept in RAM. In fact, if the swap pages aren't compressible, it's as if there wasn't any available swap space at all...

**Comment by FSMaxB** [comment]
In case of scrypt they are definitely not compressible. Pseudo random numbers don't compress very well ...

**Comment by jedisct1** [comment]
zram will even *increase* the number of pages in that scenario.

**Comment by jedisct1** [comment]
I couldn't reproduce this on a Raspberry Pi3, running a stock Pi64 distribution (so, without zram).

**Comment by luckygoodness** [comment]
but i have good iphones if you want to buy

**Comment by jedisct1** [comment]
Can you check without zram?

Or maybe comment specific tests in `tests/default/*scrypt*.c` to find the culprit?

**Comment by wizeman** [comment]
It still fails in the same way without zram.

**Comment by jedisct1** [comment]
I tried to reproduce this on the same hardware (Rpi 3) with a fresh Pi64 install, to no avail.

I even tried Raspbian (just in case, even though you mentioned aarch64); couldn't reproduce it either.

If you can pinpoint the exact test that fails on your system, that may be really useful.
