### ISSUE TITLE
crypto_secretbox_open_easy successfully decrypts ciphertext with incorrect nonce length

### ISSUE THREAD

**Issue by ivRodriguezCA** [jedisct1/libsodium#616]
Hi @jedisct1,

I'm not sure if this is an actual issue, but thought I'd share it to make sure it's fine.

### Description
While testing an iOS app with `crypto_secretbox_*` functions to encrypt/decrypt data, I had a bug and the nonce was being truncated to **8 bytes** and not `crypto_secretbox_NONCEBYTES`. The `crypto_secretbox_open_easy` operation was **correctly** failing (ciphertext's tag verification was returning -1) and my suspicion was that I was providing a wrong `key` or `nonce` so I tried decrypting the ciphertext in the very next instruction after encrypting; but to my surprise, it didn't fail and was successfully verifying the tag and decrypting the ciphertext.

### How
Created a method (objc) called `encrypt:key:nonce:` using `crypto_secretbox_easy` to encrypt a  message.
```Objc
- (NSData *)encrypt:(NSData *)message key:(NSData *)key nonce:(NSData *)nonce {
    unsigned char ciphertext[message.length + crypto_secretbox_MACBYTES];
    
    crypto_secretbox_easy(ciphertext, message.bytes, message.length, nonce.bytes, key.bytes);
    
    unsigned char decrypted[message.length];
    if (crypto_secretbox_open_easy(decrypted, ciphertext, sizeof ciphertext, nonce.bytes, key.bytes) != 0) {
        return nil;
    }
    
    return [NSData dataWithBytes:ciphertext length:sizeof ciphertext];
}
```
Created a method (obj) called `decrypt:key:nonce:` using `crypto_secretbox_open_easy` to decrypt an encrypted message.
```Objc
- (NSData *)decryptMessage:(NSData *)message key:(NSData *)key nonce:(NSData *)nonce {
    unsigned char decrypted[message.length -  crypto_secretbox_MACBYTES];
    
    if (crypto_secretbox_open_easy(decrypted, message.bytes, message.length, nonce.bytes, key.bytes) != 0) {
        return nil;
    }
    
    return [NSData dataWithBytes:decrypted length:message.length -  crypto_secretbox_MACBYTES];
}
```
The helper methods:
```Objc
- (NSData *)incorrectNonce {
    unsigned char nonce[8] = {0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF};
    return [NSData dataWithBytes:nonce length:8];
}

- (NSData *)key {
    unsigned char key[32] = {0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61,0x61};
    return [NSData dataWithBytes:key length:32];
}
```
As you can see `incorrectNonce` returns a nonce that is 8 bytes long (which is incorrect), when calling in `viewDidLoad`:
```Objc
- (void)viewDidLoad {
     NSData *message = [@"Incorrect Nonce" dataUsingEncoding:NSUTF8StringEncoding];
     self.incorrectLengthCiphertext = [self.crypto encrypt:message key:[self key] nonce:[self incorrectNonce]];
}
```
And then calling in `viewDidAppear:`
```Objc
- (void)viewDidAppear:(BOOL)animated {
     [super viewDidAppear:animated];
     NSData *plaintext = [self.crypto decryptMessage:self.incorrectLengthCiphertext key:[self key] nonce:[self incorrectNonce]];
     //plaintext is nil
}
```
`crypto_secretbox_open_easy` would fail (return -1) therefore `plaintext` would be nil. After testing many scenarios, I found that this was failing if the decryption method was called in a different thread or "many" app cycles later.

### Bug/Issue?
On the other hand, if the decryption method was the instruction right after the encryption one it would succeed, **even though the nonce length was incorrect**.
```Objc
- (void)viewDidLoad {
     NSData *message = [@"Secret message with incorrect nonce" dataUsingEncoding:NSUTF8StringEncoding];
     self.incorrectLengthCiphertext = [self.crypto encrypt:message key:[self key] nonce:[self incorrectNonce]];

     NSData *plaintext = [self.crypto decryptMessage:self.incorrectLengthCiphertext key:[self key] nonce:[self incorrectNonce]];
     //plaintext is "Secret message with incorrect nonce"
}
```

**Comment by jedisct1** [comment]
`incorrectNonce` doesn't seem to be defined anywhere in your examples. 

I guess an `NSData` object contains a length followed by the actual data bytes. If you change the length, it just changes the first value. The address of the actual data doesn't change especially if the number of pages remains the same.

So the previous data are still here in memory. When you're passing this pointer to the C function, it reads past the logical end address, which sometimes works, but only by accident.

**Comment by ivRodriguezCA** [comment]
I updated the text with the definition of `incorrectNonce` and `key` methods. Sorry, I should've added it before.

Although I don't really know how `NSData` works behind the scenes, the `incorrectNonce` method was returning a new instance of `NSData` on each call.

But you might be right and there is some memory optimization and that's why it works when the operations are close in the stack.

**Comment by jedisct1** [comment]
For performance reasons, the memory allocator on macOS tends to immediately reuse regions previous allocated from the same bucket size.

**Comment by jedisct1** [comment]
Also, the [malloc debugging features](https://developer.apple.com/library/content/documentation/Performance/Conceptual/ManagingMemory/Articles/MallocDebug.html) can be very helpful to debug this.
