### ISSUE TITLE
Supporting VXEdDSA

### ISSUE THREAD

**Issue by bunsim** [jedisct1/libsodium#618]
Would it be possible for libsodium to support VXEdDSA? It's a VRF, something that can be quite useful in many scenarios but very difficult to find in crypto libraries, and well-documented, but has surprisingly few implementations; the [reference implementation](https://github.com/pfork/xeddsa/blob/master/vxeddsa.c) is under the GPL, which is fairly unsuitable for libraries, and there aren't many other ones around.

**Comment by jedisct1** [comment]
VRFs (not necessarily VXEdDSA) are great, but I'd be a bit reluctant to implementing them in sodium/hydrogen if very few people eventually use them.

Could you describe your use case?

**Comment by bunsim** [comment]
My use case is rather peculiar; essentially I have an operator that maintains a namespace (like in CONIKS), but with an ever-growing binary search tree with all the nodes logged to a public append-only log. Since the log is append-only, past pointers in the BST cannot be rewritten, so though new key-value pairs can be added, the tree cannot be rebalanced etc. A VRF is needed so that adversarial clients cannot force the operator to grossly unbalance the tree simply by registering the right names in the right order --- the tree would be sorted by the VRF of the name.

**Comment by jedisct1** [comment]
> My use case is rather peculiar

That's why it will not happen in a near future.

**Comment by jedisct1** [comment]
To clarify: it doesn't mean no :)

Especially since VXEdDSA was already in the [roadmap](https://download.libsodium.org/doc/internals/roadmap.html).

Just that it's not at the top of my list of things to implement, unless this is contracted work.

This requires more general use cases, and more people asking about common problems that would be solved with a VRF.

**Comment by Scratch-net** [comment]
VRF's are a good way of provable obfuscating identities(emails/phones, etc) as well as many other things you don't want people to know about. Blockchains, messengers, you name them. Miss this feature a lot.
