### ISSUE TITLE
Invalid library (maybe not a PHP library) 'sodium.so' in Unknown on line 0 ....

### ISSUE THREAD

**Issue by v1n11** [jedisct1/libsodium#619]
Hi All,

I've been struggling since days to install libsodium on my Debian9/php7.0(with fpm) server ...
When I follow the steps outlined on https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium everything seems to work, however I get this error at PHP startup:

Invalid library (maybe not a PHP library) 'sodium.so' in Unknown on line 0 ....

So the extension is not loaded ...

Hope someone can help me,
Thx !
Vincent.

**Comment by jedisct1** [comment]
Hi,

You may have more success asking in the correct repository for the PHP extension: https://github.com/jedisct1/libsodium-php as more people familiar with PHP are likely to see your message than here.

I don't use PHP, I don't use Debian either, so I can't really help with such a cryptic error, but the main PHP repository for Debian has pre-built, up-to-date packages, that include php-sodium:

https://deb.sury.org/

So, maybe the easiest and safest way to go is just to install these packages.

**Comment by jedisct1** [comment]
Maybe not so up-to-date after all (latest is 2.0.9): https://packages.sury.org/php/pool/main/p/php-sodium/ but it should work.
