### ISSUE TITLE
APIs to add / subtract / negate elliptic curve points?

### ISSUE THREAD

**Issue by ivmaykov** [jedisct1/libsodium#620]
We'd like to prototype an implementation of MuHash (an incremental hashing scheme) on elliptic curves, specifically using curve 25519. Since libsodium already has a high-quality implementation of curve 25519, we would like to use it. To implement MuHash, we need:
1) A function to add arbitrary curve points A + B
2) Either a function to subtract arbitrary curve points A - B, or a function to negate the point B so we can then call A + (-B).

I assume that these functions must exist somewhere in libsodium to implement Ed25519 / X25519 operations (i.e. to implement montogmery ladder you need to double-and-add). Are they exposed in public APIs? If not, what are the private functions we could call (for now, while prototyping)? Thanks!

**Comment by ivmaykov** [comment]
Hmm, I think we can use ge_sub(), ge_add(), etc from https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_core/curve25519/ref10/curve25519_ref10.c. Let me know if I'm way off though :)

**Comment by jedisct1** [comment]
Hi Ilya,

These are indeed the internal functions for point addition and substraction.

These operations are not available in public APIs yet, but that might eventually be the case.

**Comment by jedisct1** [comment]
If you need an API that accepts traditional compressed points, use something like this:

```c
int
crypto_core_ed25519_add(unsigned char *r,
                        const unsigned char *p, const unsigned char *q)
{
    ge_p3     p_p3, q_p3, r_p3;
    ge_p1p1   r_p1p1;
    ge_cached q_cached;

    if (ge_frombytes_negate_vartime(&p_p3, p) != 0 ||
        ge_frombytes_negate_vartime(&q_p3, q) != 0) {
        return -1;
    }
    ge_p3_to_cached(&q_cached, &q_p3);
    ge_add(&r_p1p1, &p_p3, &q_cached);
    ge_p1p1_to_p3(&r_p3, &r_p1p1);
    ge_p3_tobytes(r, &r_p3);
    r[31] ^= 0x80;

    return 0;
}
```
