### ISSUE TITLE
detecting lack on entropy sources

### ISSUE THREAD

**Issue by chantra** [jedisct1/libsodium#625]
libsodium version: libsodium-1.0.15

`sodium_init` aborts when no source of entropy is found. In https://www.nlnetlabs.nl/bugs-script/show_bug.cgi?id=2141 unbound would abort without any user facing warning because the user process chroot into a directory where no source of entropy is defined.
The lack of error message makes it harder to troubleshoot or to give the user some actionable error.

This can be reproduced with the following program:
https://gist.github.com/chantra/4c13f696b3645961d6749651d1a093f7

I originally expected that the RC code of `sodium_init` would be enough to decide whether or not the system would pass the checks, but apparently not.
What I am trying to find is a portable way to detect that the initialization will fail in order to give an actionable item to the end user. I though of using `sodium_set_misuse_handler` but this does not seem to work. Here is how I used it: https://gist.github.com/chantra/df4f94992aea0109bd21d6646d4de208

Am I not using `sodium_set_misuse_handler` properly? should the handler be called before aborting? If not, what is a good way to detect whether or not the entropy sources are available other than stabbing at /dev/random (unless it it sufficient to do so?).

Note: I remember reading that one way to sort this is to call `sodium_init` before  chroot-ing so a handle to /dev/random is held open. While that may be doable, I would rather avoid the initialization of dnscrypt earlier in unbound initialization.

**Comment by jedisct1** [comment]
This should be fixed in the `stable` branch.

But the best way do handle chroot environments is as you described, to call `sodium_init()` before the `chroot` call. You don't need to initialize anything else. It's also safe to call `sodium_init()` again later if you have to.

**Comment by chantra** [comment]
ok, so I tried against master, still no avail. the issue is that when entering `sodium_init`, the lock is held: https://github.com/jedisct1/libsodium/blob/802830e4e6c1f3fb3d00c79e8e2c99b029d3efa6/src/libsodium/sodium/core.c#L43

Then we enter `randombytes_stir`: https://github.com/jedisct1/libsodium/blob/802830e4e6c1f3fb3d00c79e8e2c99b029d3efa6/src/libsodium/sodium/core.c#L53

which fails:
https://github.com/jedisct1/libsodium/blob/802830e4e6c1f3fb3d00c79e8e2c99b029d3efa6/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c#L267

which in turn requires a lock:
https://github.com/jedisct1/libsodium/blob/802830e4e6c1f3fb3d00c79e8e2c99b029d3efa6/src/libsodium/sodium/core.c#L181

`sodium_crit_enter` then return `11` (**EDEADLK**) hence aborting without calling the handler.

**Comment by jedisct1** [comment]
`stable` (or `libsodium-latest.tar.gz` on the distribution site), not `master`.

**Comment by chantra** [comment]
🤦‍♂️ yes https://github.com/jedisct1/libsodium/commit/5d484e6cb2ea1f2d4d052e31627be6ee2e2477c3 does the tricks. Thanks!

**Comment by chantra** [comment]
how about #626
