### ISSUE TITLE
Support of Elligator

### ISSUE THREAD

**Issue by rbost** [jedisct1/libsodium#628]
Being able to convert curve points to random byte strings (and vice-versa) would be great, as it is very useful for censorship circumvention (and other applications).
[Elligator](https://elligator.cr.yp.to) (and in particular Elligator2)  has been designed explicitly for that.

Among useful applications, we can find censorship circumvention (undetectable transmission of ephemeral keys for a key exchange), multiset hash functions, and VXEdDSA (which is in libsodium's roadmap). 

Elligator 2 is already [implemented in C in Signal](https://github.com/WhisperSystems/libsignal-protocol-c/blob/922d7da7ef75a8e5e52498b9404e933860b316f6/src/curve25519/ed25519/additions/elligator.c) and their code could be used as a source of inspiration ...

Addition of Elligator in libsodium would be great!

**Comment by jedisct1** [comment]
Hash-to-string using elligator2 is already implemented for SPAKE2-EE, that will get merged after 1.0.16 is released.

**Comment by jedisct1** [comment]
Hash-to-point, obviously :)

**Comment by rbost** [comment]
Never mind then :)
Is the code already available anywhere? I could not find it in the public branches.

Thanks!

**Comment by jedisct1** [comment]
Too ugly to be public yet :)
