### ISSUE TITLE
Add cmake file

### ISSUE THREAD

**Issue by HaochenLiu** [jedisct1/libsodium#636]
I would like to integrate the code instead of dll in my system, so cmake file is preferred.

**Comment by BurningEnlightenment** [comment]
This already has been discussed and the final decision was:
> cmake: this is never going to happen.

- jedisct1 https://github.com/jedisct1/libsodium/issues/378#issuecomment-231419858

**Comment by jedisct1** [comment]
There is a [Findsodium.cmake](https://github.com/jedisct1/libsodium/blob/master/contrib/Findsodium.cmake) that you may find useful in order to integrate the library in your cmake projects.
