### ISSUE TITLE
32 Bit builds won't accept arguments in Microsoft Access

### ISSUE THREAD

**Issue by BitSprocket** [jedisct1/libsodium#637]
I'm trying to make libsodium work as a dll for use with Microsoft Access and the problem I'm running into is that it builds 64bit dlls and works just fine but the 32bit build won't accept parameters for any functions that require them.  init_sodium() works as does randombytes_radom() but any function that requires parameters causes the 32bit Office to crash.  Specifically, I've tried randombytes_buf(), crypto_hash_sha256() and crypto_shorthash().

I"m using visual studio 2017 community to build the project.  Note, if I set the calling convention in the project properties to __stdcall then I can use functions that have 2 parameters but any more than that fails.

**Comment by ektrah** [comment]
The 32-bit libsodium DLL uses the **cdecl** calling convention, not **stdcall**.

**Comment by BitSprocket** [comment]
Can it be recompiled to use stdcall?  I need that because I’m calling it from VBA and it will only handle DLLs using stdcall.  I would be happy to do it myself if you can give me some guidance.  I have Visual Studio Community 2017 installed.

 

Thanks!

 

Scott

**Comment by ektrah** [comment]
No idea; maybe @jedisct1 can answer that. If not, you could write your own DLL in C that uses **stdcall** and wraps libsodium.

**Comment by BitSprocket** [comment]
I don't know C well enough to do that.  Is there another option?

Again, many thanks.

**Comment by jedisct1** [comment]
I don't know Windows well enough to do that :)

**Comment by jedisct1** [comment]
Maybe adding the `/Gz` flag would do it? https://msdn.microsoft.com/en-us/library/46t77ak2.aspx?f=255&MSPPError=-2147217396

**Comment by BitSprocket** [comment]
You closed this without a verified solution?

**Comment by jedisct1** [comment]
Doesn't the `/Gz` flag achieve this?

**Comment by BitSprocket** [comment]
I lack the knowledge to try it for the moment.  It is on my short list though.
