### ISSUE TITLE
Ambigious test case?

### ISSUE THREAD

**Issue by emilbayes** [jedisct1/libsodium#638]
Isn't this test case ambiguous, in that it could also be failing because of the missing additional data?

https://github.com/jedisct1/libsodium/blob/4098a126354089d6e1de7b5c832827aa2d143c0d/test/default/secretstream.c#L112-L117

Sorry if this is being very nitpicky, but I'm porting the tests for sodium-native, so I want to make sure I'm not misunderstanding! :)

**Comment by jedisct1** [comment]
Good catch!

Fixed in 46e2a4649063fd8bfbf0a44ee3355098d49a6361 -- Thanks!
