### ISSUE TITLE
crypto_box_keypair vs crypto_kx_keypair

### ISSUE THREAD

**Issue by clbuttic** [jedisct1/libsodium#639]
Both functions generate a keypair.  Both eventually call the same functions (randombytes_buf for secret key, crypto_scalarmult_curve25519_base for public key) and both create keys of the same length.

At this time, it appears that a keypair generated by crypto_box_keypair can be used in crypto_kx_* functions and one generated by crypto_kx_keypair can be used in crypto_box_* functions. 

Is there any reason for two functions to produce the exact same types of keys? Is there any intention for keys to become non-compatible?

**Comment by clbuttic** [comment]
Not essential to me, I'm just trying to understand libsodium. From a protocol perspective, I have the following:

1. A pair of static keys is generated server-side. The client secret (shared_client_secret) and server public (shared_server_public) are given to the client out-of-band. This pair of static key pairs is unique per customer, shared across multiple devices (An API key if you will).
2. Device and server generate a new static keys pairs, unique per device. These public keys are exchanged, encrypted using crypto_box_easy with the relevant public keys, authenticated with the relevant secret keys. These device static keys are persisted on device, hopefully in a protected region.
3. When a session is required, an ephemeral key pair is generated with crypto_kx_keypair, the public keys are exchanged again encrypted with crypto_box_easy, using the device static keys. Shared keys are calculated using crypto_kx_client_session_keys, and used to encrypt the payloads with crypto_secretbox_*.

**Comment by jedisct1** [comment]
Both operations use the same primitive to compute a shared key. `kx_keypair()` and `box_keypair()` can be used interchangeably. But having both improves consistency and code clarity.

Can you describe the problem you want to solve (not the protocol)?
