### ISSUE TITLE
Test of secretstream rekey

### ISSUE THREAD

**Issue by emilbayes** [jedisct1/libsodium#641]
Another test review 😅 

Was either of the messages here intended to have the `*_TAG_REKEY` and check that they key on `state` changed in the `*_pull` part?

https://github.com/jedisct1/libsodium/blob/46e2a4649063fd8bfbf0a44ee3355098d49a6361/test/default/secretstream.c#L148-L153

**Comment by jedisct1** [comment]
Not here. The intent was to have the same test set twice. First without, and then with rekeying. And implicit rekeying happens later, with a simulated counter overflow. Maybe an additional test with a `_REKEY` tag wouldn't be a bad thing to add.

**Comment by jedisct1** [comment]
Done in e89c43edf6ef50945735be63b4b2577101395431
