### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by My1** [jedisct1/libsodium#643]
I wanted to ask, how does the version work because the versioning seems kinda complicated, I mean for one part we have the full version number which for example on the server of a friend is
1.0.14
but then we have the major and minor versions which apparently seem to be something entirely different. in the same version the major and minor numbers seem to be  9 and 6 respectively.

so how do these versions work and is there a documentation on which versions are which major/minors and which features they have (to properly get a version check before doing stuff that wont work)

**Comment by jedisct1** [comment]
Hi!

This is actually quite simple. "1.0.14" is just a tag, only useful for people building packages for various operating systems. Stable releases don't even have tags.

`SODIUM_LIBRARY_VERSION_MAJOR` and `SODIUM_LIBRARY_VERSION_LIBRARY` represent the library version. This is what your application should use.

`SODIUM_LIBRARY_VERSION_MAJOR` is bumped when a backward-incompatible change is made, such as a function that gets removed. The minor version is reset to `0` when this happens.

`SODIUM_LIBRARY_VERSION_MINOR` is bumped when additional features are introduced, but everything remains backward compatible.

For example, if no changes are made to the API, except to fix compilation issues, there will be a new tag (or an update to the stable branch), but the library version will remain exactly the same.

**Comment by jedisct1** [comment]
And you shouldn't assume anything about these values being within a range. The current stable version is 1.0.15 and has `SODIUM_LIBRARY_VERSION_MAJOR` set to `10` and `MINOR` set to `0`.

1.0.16 which is round the corner introduces new features, but remains API compatible with 1.0.15 so it has `MAJOR` set to `10` and `MINOR` set to 1.

**Comment by My1** [comment]
but why couldnt the tag be for example major.minor.patch like in the so-called semantic versioning or some other system? because if I would need to tell the user that at least version major 10 minor 0 is needed he wont really know which one is needed which is kinda chaos.

**Comment by jedisct1** [comment]
Tell them to use at least the package version that introduced major 10.

Semver doesn't work as a package versioning scheme. It doesn't reflect the changes being made. Just API compatibility. 
Oh, and also nobody knows how to parse semver correctly. Want a [recent example](https://www.reddit.com/r/rust/comments/7i4kjq/til_100beta9_100beta10_as_per_semver_spec/)?

**Comment by My1** [comment]
well I used sem just as example, there are probably other versions that may work better, it was just the first one that came to mind.

I I think it's just slightly confusing to have 2 totally independent versioning schemes.
