### ISSUE TITLE
Please keep the AES-GCM api

### ISSUE THREAD

**Issue by alfredh** [jedisct1/libsodium#644]
Hi,

I noticed that the AES-CTR mode was removed from the code. I would just like to
ask you kindly to keep the AES-GCM api and not delete it.

I am planning to add libsodium as a crypto backend for libre,
a Protocol stack library:

  https://github.com/creytiv/re

The main use-cases are:

* SRTP stack with AES-GCM
* TLS stack with AES-GCM and Elliptic Curve

The sodium API is very nice and easy to use, and I am very pleased that you
guys have written such high quality software that is also Free Software.

Many thanks, please close this issue after you read it.

Alfred

**Comment by jedisct1** [comment]
Don't worry AES-GCM is here to stay, like everything present in `--enable-minimal` builds.

**Comment by alfredh** [comment]
Thank you, Frank
