### ISSUE TITLE
Impossible to verify HMAC-SHA-256/512 with non 32 bytes keys

### ISSUE THREAD

**Issue by nsheremet** [jedisct1/libsodium#646]
The problem is that when you need to use `crypto_auth_hmacsha256_verify` function for non 32 bytes key, you will always get an wrong answer. Because this func calling `crypto_auth_hmacsha256` function, which is only for 32 bytes key.

I thinks for `verify` case, we should use multipart api function (`init, update, final`)

**Comment by jedisct1** [comment]
Use the multipart API, that supports any key size. For verification, just compute the HMAC and compare it with `crypto_verify_32()` or `crypto_verify_64()`.

**Comment by nsheremet** [comment]
@jedisct1 Why you don't want to add any key size supporting? Did you see that https://tools.ietf.org/html/rfc2104#section-3 ?
