### ISSUE TITLE
OSS-Fuzz integration

### ISSUE THREAD

**Issue by derwolfe** [jedisct1/libsodium#647]
Hi @jedisct1,

I've been doing a little bit of preliminary work to try to build some fuzzers for libsodium that would integrate with google's [oss-fuzz](https://github.com/google/oss-fuzz) project. Before I get too far, is this something that you'd be open to?

Thanks for libsodium!
Chris

**Comment by jedisct1** [comment]
Hey, definitely! That would be awesome!

libhydrogen might be a better place to start, though.

**Comment by derwolfe** [comment]
Excellent, thanks! 

I'll go ahead and start with libsodium mainly because I'm already consuming it in a few places :).

**Comment by jedisct1** [comment]
Sounds good! Thanks a lot for your help, Chris!

**Comment by jedisct1** [comment]
Note that you will probably have to override the default `sodium_misuse()` handler. Something that just calls `exit(0)` might be enough.

**Comment by derwolfe** [comment]
I meant to ask about this earlier and forgot :)

[OSS-fuzz](https://github.com/google/oss-fuzz#accepting-new-projects) prefers that the e-mail of the engineering contact person to be CCed on new issues should both belong to someone whose been primarily involved in the project based on VCS commit history and that the email for this account be a google account. 

I think you should definitely be the primary contact. Do you have a specific google or gmail account that you'd like me to use?

**Comment by jedisct1** [comment]
Thanks a lot Chris! Looks promising!

I don't use Gmail, but I can still create an account just for this.

**Comment by jedisct1** [comment]
Ok, done. `ossfuzzz@gmail.com` :)
