### ISSUE TITLE
Xamarin crossplatform libsodium nuget

### ISSUE THREAD

**Issue by skunadt** [jedisct1/libsodium#649]
Hey, I tried to use libsodium in my Xamarin Project(PCL 4.5, Visual Studio 7.3.2 for macOS). 
With nuget Packages it is possible to bind libsodium and another lib that is called lib sodium_vc120.
My problem with this libs seems to that they aren't for portable class library use at all. 
When I try to "using 'lib...'" there is no lib in this namespace.

Any suggestions ? 

PS: I hope this is the right place for this, because the nugget package links to this GitHub repo "https://raw.github.com/jedisct1/libsodium/master/ChangeLog".

**Comment by ektrah** [comment]
Generally, you need to use one of the available language bindings for .NET, a list of which is available [here](https://download.libsodium.org/doc/bindings_for_other_languages/). The libsodium and libsodium_vc120 packages on nuget.org do not provide any .NET API; the libsodium package only contains some shared assets for the language bindings and the libsodium_vc120 package is for Visual C++.

Specifically, for Xamarin, I believe there aren't currently any language bindings available. So your options right now are to checkout out the cryptography APIs that come with Xamarin (recommended) or one of the cryptography libraries on nuget.org that advertise support for PCLs.

**Comment by skunadt** [comment]
Thx for the fast answer, can be closed now.
