### ISSUE TITLE
VS2017 for Mac - Native library not found

### ISSUE THREAD

**Issue by christancho** [jedisct1/libsodium#650]
Hi,
When I try to install libsodium-net package on VS2017 CE for Mac I get this error:

Could not install package 'Baseclass.Contrib.Nuget.Output 2.1.0'. You are trying to install this package into a project that targets 'Xamarin.iOS,Version=v1.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I raised this [issue](https://github.com/tabrath/libsodium-core/issues/17) on Libsodium-Core & libsodium-net repository... the maintainers send me here (hopefully I'm in the right place)

am I missing something?

Thanks for your help
Christian

**Comment by ektrah** [comment]
The problem with the "Baseclass.Contrib.Nuget.Output" package is an issue of libsodium-net, but for the issue you initially reported (Native library not found) you're in the right place.

Both libsodium-core and libsodium-net do not actually implement the cryptographic algorithms; they depend on a native library for that. Native libraries are currently provided for Windows (x64 and x86), Linux (x64), and macOS (x64). A native library for iOS is currently not provided (and, if it was, I'm not sure if Xamarin would actually be able to pick it up).

@jedisct1 - What's your opinion on a small landing page for the libsodium nuget package that lists supported platforms and directs users to the language bindings?

**Comment by jedisct1** [comment]
@ektrah Sounds good, but where would such a page be located at? Should it be in the gitbook documentation?

**Comment by jedisct1** [comment]
(@ektrah , by the way: a huge *thank you* for your continued, invaluable help regarding Windows and dotNet issues)

**Comment by jedisct1** [comment]
Hi @ektrah! Where do you suggest adding such documentation?

**Comment by ektrah** [comment]
@jedisct1 I was thinking about a section or page in the gitbook documentation, but I leave this entirely up to you where to place it. 😀
