### ISSUE TITLE
Issue compiling on OS Lion System

### ISSUE THREAD

**Issue by mav2287** [jedisct1/libsodium#652]
I am running an older XSERVER that is stuck at OS X Lion (10.7) When I tried to do a make check I got the following output

libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
  CCLD     libavx512f.la
  CC       randombytes/salsa20/librdrand_la-randombytes_salsa20_random.lo
libtool: warning: '-version-info/-version-number' is ignored for convenience libraries
/usr/bin/ranlib: file: .libs/libavx512f.a(libavx512f_la-argon2-fill-block-avx512f.o) has no symbols
ranlib: file: .libs/libavx512f.a(libavx512f_la-argon2-fill-block-avx512f.o) has no symbols
ranlib: warning for library: .libs/libavx512f.a the table of contents is empty (no object file members in the library define global symbols)
{standard input}:105:no such instruction: `pclmulqdq $17, %xmm1,%xmm0'
{standard input}:106:no such instruction: `pclmulqdq $1, %xmm1,%xmm4'
{standard input}:107:no such instruction: `pclmulqdq $0, %xmm1,%xmm3'
{standard input}:108:no such instruction: `pclmulqdq $16, %xmm1,%xmm2'
{standard input}:192:no such instruction: `pclmulqdq $1, %xmm3,%xmm4'
{standard input}:193:no such instruction: `pclmulqdq $16, %xmm3,%xmm2'
{standard input}:197:no such instruction: `pclmulqdq $0, %xmm3,%xmm1'
{standard input}:198:no such instruction: `pclmulqdq $17, %xmm3,%xmm0'
{standard input}:478:no such instruction: `pclmulqdq $0, %xmm5,%xmm15'
{standard input}:480:no such instruction: `pclmulqdq $0, %xmm4,%xmm1'
{standard input}:482:no such instruction: `pclmulqdq $0, %xmm3,%xmm14'
{standard input}:485:no such instruction: `pclmulqdq $0, %xmm0,%xmm13'
{standard input}:488:no such instruction: `pclmulqdq $17, %xmm4,%xmm14'
{standard input}:491:no such instruction: `pclmulqdq $17, %xmm5,%xmm1'
{standard input}:497:no such instruction: `pclmulqdq $17, %xmm3,%xmm12'
{standard input}:499:no such instruction: `pclmulqdq $0, %xmm5,%xmm1'
{standard input}:504:no such instruction: `pclmulqdq $17, %xmm0,%xmm10'
{standard input}:506:no such instruction: `pclmulqdq $0, %xmm4,%xmm1'
{standard input}:513:no such instruction: `pclmulqdq $0, %xmm3,%xmm1'
{standard input}:517:no such instruction: `pclmulqdq $0, %xmm0,%xmm3'
{standard input}:717:no such instruction: `pclmulqdq $0, %xmm6,%xmm7'
{standard input}:719:no such instruction: `pclmulqdq $0, %xmm5,%xmm13'
{standard input}:722:no such instruction: `pclmulqdq $0, %xmm4,%xmm12'
{standard input}:726:no such instruction: `pclmulqdq $0, %xmm1,%xmm11'
{standard input}:729:no such instruction: `pclmulqdq $17, %xmm6,%xmm7'
{standard input}:733:no such instruction: `pclmulqdq $17, %xmm5,%xmm7'
{standard input}:739:no such instruction: `pclmulqdq $0, %xmm5,%xmm14'
{standard input}:741:no such instruction: `pclmulqdq $17, %xmm4,%xmm7'
{standard input}:746:no such instruction: `pclmulqdq $0, %xmm6,%xmm9'
{standard input}:754:no such instruction: `pclmulqdq $17, %xmm1,%xmm7'
{standard input}:757:no such instruction: `pclmulqdq $0, %xmm4,%xmm9'
{standard input}:762:no such instruction: `pclmulqdq $0, %xmm1,%xmm14'
{standard input}:803:no such instruction: `pclmulqdq $0, %xmm3,%xmm6'
{standard input}:808:no such instruction: `pclmulqdq $0, %xmm0,%xmm15'
{standard input}:814:no such instruction: `pclmulqdq $17, %xmm2,%xmm8'
{standard input}:820:no such instruction: `pclmulqdq $17, %xmm3,%xmm6'
{standard input}:827:no such instruction: `pclmulqdq $17, %xmm0,%xmm7'
{standard input}:832:no such instruction: `pclmulqdq $0, %xmm0,%xmm12'
{standard input}:834:no such instruction: `pclmulqdq $0, %xmm2,%xmm4'
{standard input}:838:no such instruction: `pclmulqdq $0, %xmm3,%xmm0'
{standard input}:842:no such instruction: `pclmulqdq $0, %xmm5,%xmm1'
{standard input}:844:no such instruction: `pclmulqdq $17, %xmm5,%xmm4'
{standard input}:848:no such instruction: `pclmulqdq $0, %xmm2,%xmm3'
{standard input}:852:no such instruction: `pclmulqdq $0, %xmm5,%xmm3'
{standard input}:1140:no such instruction: `pclmulqdq $17, %xmm1,%xmm10'
{standard input}:1146:no such instruction: `pclmulqdq $0, %xmm6,%xmm2'
{standard input}:1149:no such instruction: `pclmulqdq $0, %xmm4,%xmm13'
{standard input}:1153:no such instruction: `pclmulqdq $0, %xmm1,%xmm13'
{standard input}:1154:no such instruction: `pclmulqdq $0, %xmm5,%xmm2'
{standard input}:1159:no such instruction: `pclmulqdq $17, %xmm5,%xmm12'
{standard input}:1162:no such instruction: `pclmulqdq $17, %xmm6,%xmm2'
{standard input}:1167:no such instruction: `pclmulqdq $17, %xmm4,%xmm12'
{standard input}:1170:no such instruction: `pclmulqdq $0, %xmm6,%xmm2'
{standard input}:1175:no such instruction: `pclmulqdq $0, %xmm5,%xmm2'
{standard input}:1182:no such instruction: `pclmulqdq $0, %xmm4,%xmm2'
{standard input}:1186:no such instruction: `pclmulqdq $0, %xmm1,%xmm4'
{standard input}:1295:no such instruction: `pclmulqdq $0, %xmm2,%xmm11'
{standard input}:1308:no such instruction: `pclmulqdq $0, %xmm6,%xmm3'
{standard input}:1311:no such instruction: `pclmulqdq $0, %xmm7,%xmm1'
{standard input}:1314:no such instruction: `pclmulqdq $0, %xmm5,%xmm3'
{standard input}:1319:no such instruction: `pclmulqdq $17, %xmm7,%xmm3'
{standard input}:1323:no such instruction: `pclmulqdq $17, %xmm6,%xmm3'
{standard input}:1330:no such instruction: `pclmulqdq $17, %xmm5,%xmm3'
{standard input}:1334:no such instruction: `pclmulqdq $17, %xmm2,%xmm3'
{standard input}:1338:no such instruction: `pclmulqdq $0, %xmm7,%xmm3'
{standard input}:1344:no such instruction: `pclmulqdq $0, %xmm6,%xmm7'
{standard input}:1347:no such instruction: `pclmulqdq $0, %xmm2,%xmm1'
{standard input}:1349:no such instruction: `pclmulqdq $0, %xmm5,%xmm7'
{standard input}:1410:no such instruction: `pclmulqdq $0, %xmm12,%xmm15'
{standard input}:1411:no such instruction: `pclmulqdq $0, %xmm7,%xmm5'
{standard input}:1414:no such instruction: `pclmulqdq $0, %xmm6,%xmm2'
{standard input}:1416:no such instruction: `pclmulqdq $17, %xmm7,%xmm5'
{standard input}:1419:no such instruction: `pclmulqdq $17, %xmm12,%xmm9'
{standard input}:1424:no such instruction: `pclmulqdq $0, %xmm8,%xmm5'
{standard input}:1429:no such instruction: `pclmulqdq $17, %xmm6,%xmm2'
{standard input}:1433:no such instruction: `pclmulqdq $0, %xmm3,%xmm1'
{standard input}:1434:no such instruction: `pclmulqdq $17, %xmm3,%xmm2'
{standard input}:1436:no such instruction: `pclmulqdq $0, %xmm7,%xmm5'
{standard input}:1445:no such instruction: `pclmulqdq $0, %xmm6,%xmm5'
{standard input}:1448:no such instruction: `pclmulqdq $0, %xmm3,%xmm5'
make[3]: *** [crypto_aead/aes256gcm/aesni/libaesni_la-aead_aes256gcm_aesni.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [check-recursive] Error 1
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1

Not sure what to try or where to start on this one.

**Comment by jedisct1** [comment]
Your compiler toolchain is broken and produces code that it itself is unable to assemble.

I don't think Lion is the issue here. It's rather a mix of very old and new software, that don't play well with each other.

Unfortunately, I can't reasonably support such an unusual environment. Even if hacks could eventually make it compile, you would end up with something that has never been tested and never will, and that could be completely broken/insecure.

**Comment by mav2287** [comment]
I know you already answered this, but I just wanted to leave a trail for the next guy that gets stuck on this. The solution was to use macports. They have managed to get it to compile and run.
