### ISSUE TITLE
Is crypto_box + sealed_box combo a safe construction?

### ISSUE THREAD

**Issue by sbredahl** [jedisct1/libsodium#654]
I would like to feed the output of crypto_box _easy into a sealed box like this:

```
cbox_ciphertext = crypto_box_easy(plaintext, nonce, bob_pk, alice_sk)
sbox_ciphertext = crypto_box_seal(cbox_ciphertext, bob_pk)
```

and at the receiver (bobs) end:

```
cbox_ciphertext = crypto_box_seal_open(sbox_ciphertext, bob_pk, bob_sk)
plaintext = crypto_box_open_easy(cbox_ciphertext,  nonce, alice_pk, bob_sk)
```

The purpose would be to create a forward-secrecy box that alice cannot decrypt herself (as implied by the outer sealed box) while maintaining the mutual alice/bob authentication from the inner crypto_box.

Do you think this “hybrid” is safe (eg. does not weaken the inner crypto_box) or have I overlooked something?

Thanks for any advice here!

**Comment by jedisct1** [comment]
Hi Sune,

Just use `crypto_box_seal`, and sign the ciphertext (or even just the first `crypto_box_SEALBYTES` bytes) using `crypto_sign`.

Checking the signature will be enough to verify the originator of the ciphertext before decrypting it.

**Comment by sbredahl** [comment]
Yes that is a better solution. Thanks!
