### ISSUE TITLE
Support argon2d algorithm

### ISSUE THREAD

**Issue by droidmonkey** [jedisct1/libsodium#656]
Good day, I would love to use libsodium for my project [KeePassXC](https://github.com/keepassxreboot/keepassxc/), but you guys don't support the argon2d algorithm. Unfortunately we are stuck between a rock and hard place since the original KeePass only supports argon2d and we need to maintain compatibility with their database format. Would this be a possibility in future libsodium release?

**Comment by jedisct1** [comment]
Hi,

Unfortunately, this is very unlikely.

Argon2d doesn't have any major benefits over Argon2id. It's not the one its authors recommend. It's also by far the least deployed variant. It's probably not a good idea to add and maintain code that nobody will use.

So, if you specifically need this variant, your best bet is to use libargon2.
