### ISSUE TITLE
crypto_box_seal lacks deterministic test vectors

### ISSUE THREAD

**Issue by robbat2** [jedisct1/libsodium#657]
Working on my own tests to ensure comparability between other implementations, and ran into a gotcha that the `crypto_box_seal` API, as a side effect of the design to generate ephemeral keys internally (a good choice to avoid user error), does not have a way to compare against known test vectors.

I'm stuck with a few choices, none of which feel very good:

1. deliberate `crypto_box_seal` variant for manual generation of the ephemeral keys (will be abused by users).
2. manual implementation outside `crypto_box_seal`.
3. preseeded RNG to known state (hard between languages)

As bad as the first option is, I'm leaning to that, with large warnings, because it's the least likely to go wrong.

**Comment by jedisct1** [comment]
4) Register a [custom RNG](https://download.libsodium.org/doc/advanced/custom_rng.html) just to run the test suite?

**Comment by robbat2** [comment]
Anything with the RNG is fine in libsodium itself, but problematic if we construct a Sealed Box elsewhere and want a test like ciphertext-libsodium eq ciphertext-otherlib.

**Comment by jedisct1** [comment]
Create a ciphertext using lib A, try to decrypt it using lib B, and the other way round.

Or contribute to [crypto-test-vectors](https://github.com/jedisct1/crypto-test-vectors) :)

**Comment by robbat2** [comment]
I'm fine contributing to test vectors, but think adding a variant for testing that takes the manual key would alleviate the issue. Would a change to implement such be accepted or rejected?

**Comment by jedisct1** [comment]
What are these functions supposed to do?
- `seal_open()` must be able to decrypt something encrypted by `seal()`
- `seal_open()` must reject ciphertexts that have been tampered with.

This is how these functions are defined. `seal()` can return anything, as long as `open()` can decrypt it.
What `seal()` returns is not defined by a specific way to generate the nonce.

For misuse resistance, it would be perfectly fine for `seal()` to use a hash of the message as the nonce. That wouldn't violate anything to the way these functions work. `seal_open()` would still be able to decrypt the output.

If `open()` accepts public keys in non-canonical form (and it probably does), it would perfectly valid for `seal()` to generate non-canonical public keys as well. So you would have two completely equivalent ciphertexts, that `open()` would decrypt just fine. And that's okay.

So, you should test these functions on what they are documented to do.

And once again, if you really want `open()` to use a specific nonce,  just define a custom random number generator.

**Comment by robbat2** [comment]
I was planning on much stricter requirements than what you suggest. Quick prototype patch to follow in a day or two, as I have other things competing for the start of the week.

**Comment by jedisct1** [comment]
If you want to write a patch, please implement readers/writers for sodium and for your implementations for the crypto-test-vectors project.

Do not add functions to libsodium that would not be required by any applications.

**Comment by robbat2** [comment]
Specifically: it would be `crypto_box_seal` with extra params to specify the ephemeral key instead of generating it.

**Comment by jedisct1** [comment]
So, that's `crypto_box()`.
