### ISSUE TITLE
sodium_hex2bin should fail if bin_len is NULL but bin_pos != bin_maxlen

### ISSUE THREAD

**Issue by ciphergoth** [jedisct1/libsodium#658]
sodium_bin2hex supports a NULL value for bin_len, but it's currently never safe to use it; if the hex is shorter than expected, the resulting buffer has uninitialized bytes, but the user doesn't discover that.

I think the correct fix is to fail if bin_len is NULL but fewer than the maximum bytes are read.

https://github.com/jedisct1/libsodium/blob/3e0b4dec6e819b75d2245b9a2fbaad2153364e79/src/libsodium/sodium/codecs.c#L97

**Comment by jedisct1** [comment]
If the buffer is shorter than expected, you should check `hex_pos`. It points to the last valid character, and should match the end of the string if everything was properly parsed.

**Comment by ciphergoth** [comment]
hex_pos tells me that the whole of my hex_string was consumed, but not that the whole of my binary buffer was filled.

**Comment by jedisct1** [comment]
If this is what you want, set `bin_pos` to a valid pointer :)

Setting it to `NULL` is very useful when you trust the input, and don't want to pass a useless pointer.

**Comment by ciphergoth** [comment]
Are there circumstances where you trust the input, but the result might be shorter than bin_len, and you don't want it to fail if it is?

**Comment by jedisct1** [comment]
Probably not :)

But it's too late to change the libsodium API at this point. But libhydrogen has similar functions and now is a good time to change them if needed!

**Comment by jedisct1** [comment]
I just tried that change, and it broke the test suite :)

```
Assertion failed: (hydro_hex2bin(x, sizeof x, "452a", 4, NULL, NULL, NULL) == 0), function test_core, file tests/tests.c, line 147.
/bin/sh: line 1: 54844 Abort trap: 6           tests/tests
make: *** [test] Error 134
```

The reason being that `x` is a buffer reused for other tests, and I just provide the allocated size for that buffer, not the exact number of bytes that are expected, since it's going to be constant no matter what.

This is just a test, but it still illustrates that this would be a breaking change.

**Comment by ciphergoth** [comment]
Darn :( Yes, definitely desirable to fix this for libhydrogen then.

**Comment by jedisct1** [comment]
I'm not convinced that returning an error in this specific case would be a good thing.

The `bin_maxlen` parameter would have a different meaning when an unrelated pointer is set to `NULL`. This is inconsistent and confusing.

Also, overallocating or reusing buffers, and just using their allocated size is a common pattern in C, used with functions such as `snprintf()`. This is totally fine when the number of bytes being written is known in advance.

I think `bin_maxlen` should stay `bin_maxlen`, and always do what the name suggests.

But as you emphasize, having to pass a pointer and checking it to see if the expected number of bytes have been written may not be convenient nor intuitive.

Here's what I would suggest: remove the `bin_len` pointer, and return the number of written bytes (or `-1` on error) as a `ssize_t` instead. Similar to what `read(2)` does.

That sounds more intuitive. With a function documented (and even self-documented) as returning the number of written bytes, it becomes obvious that this is something you need to check if you expect partial writes. And it's easier to do than through a pointer.

**Comment by ciphergoth** [comment]
Sure, that seems like a reasonable fix!

**Comment by jedisct1** [comment]
Done for hydrogen!

Thanks for pointing out that the function should be improved.
