### ISSUE TITLE
Changes in signature & public key validation for 1.0.16 cause problems for uses requiring strict consensus

### ISSUE THREAD

**Issue by daira** [jedisct1/libsodium#662]
https://github.com/jedisct1/libsodium/commit/afabd7e7386e11949064719b0c9f468c6172388a , for example, will cause a problem for Zcash in upgrading to libsodium 1.0.16 (we're currently on 1.0.15). Any change in which signatures or public keys are considered valid can potentially be used to provoke a Zcash chain fork. We can work around it by reverting this patch, but that's obviously not ideal for maintenance. Is it possible to have a LIBSODIUM_STABLE_VALIDATION #define that would disable any changes like this?

**Comment by daira** [comment]
BTW I realize that this change was well-motivated (https://eprint.iacr.org/2017/806.pdf). Basically we have to review all such changes to see whether they affect our use of the cryptography, and possibly schedule them for a hard fork if they're needed.

**Comment by daira** [comment]
Other related consensus changes:
* https://github.com/jedisct1/libsodium/commit/ac8dffbecb3025a66547fbe8479deb156f2ba64b
* https://github.com/jedisct1/libsodium/commit/c190574cee382ace1ee0f8fdacc136f1797287e6
* possibly https://github.com/jedisct1/libsodium/commit/0b734963db125474f5b14561548da4bbebaf51b9

**Comment by daira** [comment]
Ah, I see there's ED25519_COMPAT for the public key validation change (https://github.com/jedisct1/libsodium/commit/1cd063318647bc073467acfdb91af4f3e36e324c), but not for the other changes.

**Comment by jedisct1** [comment]
It is very unlikely that you are using the `scalarmult_ed25519` API since it was only introduced in 1.0.16.

Other changes affect DH using X25519. After performing the multiplication, an all-zero output was already rejected. Now, low-order points leading to this output are checked before the computation. The set of rejected points remains the same.

**Comment by daira** [comment]
OK thanks. I'll have to go over all the changes thoroughly but I think you're right that we're not affected, in that case.

**Comment by daira** [comment]
It looks like https://github.com/jedisct1/libsodium/commit/89bc2d69762d841463133f62dbfa5d58cba17f12 is still problematic. If I'm understanding correctly, this newly rejects public keys where the encoding of the y-coordinate (in the notation of the [Ed25519 paper](https://ed25519.cr.yp.to/ed25519-20110926.pdf)) in the little-endian first 255 bits of the key representation is >= 2<sup>255</sup>-19.

(This code was later modified by https://github.com/jedisct1/libsodium/commit/1cd063318647bc073467acfdb91af4f3e36e324c but we don't set ``ED25519_COMPAT`` in Zcash, so the latter commit has no effect for us.)
