### ISSUE TITLE
Android feature testing improvement

### ISSUE THREAD

**Issue by noloader** [jedisct1/libsodium#664]
The source code for [`runtime.c`](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/sodium/runtime.c) uses the following pattern for Android features:

```
# elif defined(HAVE_ANDROID_GETCPUFEATURES) && ...
    cpu_features->has_neon =
        (android_getCpuFeatures() & ANDROID_CPU_ARM_FEATURE_NEON) != 0x0;
```

I believe the Android folks say to test the CPU family first, before testing for the CPU feature. Also see [Runtime Detection](https://developer.android.com/ndk/guides/cpu-arm-neon.html#rd) in the Android docs. So the test should be something like:

```
# elif defined(HAVE_ANDROID_GETCPUFEATURES) && ...
    cpu_features->has_neon =
        (android_getCpuFamily() & ANDROID_CPU_FAMILY_ARM) &&
        ((android_getCpuFeatures() & ANDROID_CPU_ARM_FEATURE_NEON) != 0x0);
```

I seem to recall the Aarch64 gear uses different defines for ASIMD, so you should probably have a separate path for Aarch64 similar to:

```
    ...
    cpu_features->has_neon =
        (android_getCpuFamily() & ANDROID_CPU_FAMILY_ARM64) &&
        ((android_getCpuFeatures() & ANDROID_CPU_ARM64_FEATURE_ASIMD != 0x0);
```

And in case you were not aware, the latest NDK's have the `cpufeatures` library. The idea is, you copy a header file and source files from the NDK into your source tree, compile it into an object file, and then link it. Also see [The cpufeatures Library](https://developer.android.com/ndk/guides/cpu-features.html) in the Android docs.

-----

You might also be interested in these feature detections for Linux. Forgive me if you knew ASIMD is Aarch64's version of NEON.

```
#elif defined(__linux__) && defined(__aarch64__)
    if (getauxval(AT_HWCAP) & HWCAP_ASIMD)
        return true;
#elif defined(__linux__) && defined(__aarch32__)
    if (getauxval(AT_HWCAP2) & HWCAP2_ASIMD)
        return true;
#elif defined(__linux__) && defined(__arm__)
    if (getauxval(AT_HWCAP) & HWCAP_ARM_NEON)
        return true;
```

-----

You can test Aarch64 on the [GCC Compile Farm](https://gcc.gnu.org/wiki/CompileFarm). GCC117 and GCC118 are Aarch64 machines with the optional CRC and Crypto gear. The Mustang boards at GCC113-GCC116 are early Aarch64, and they lack CRC and Crypto extensions. All the Aarch64 machines have ASIMD because it is a core feature like SSE2 on x86_64.

The compile farm is open to anyone who works on free and open source software. You can sign up for an account at [Request an Account](https://cfarm.tetaneutral.net/users/new/).

**Comment by jedisct1** [comment]
Hi,

and thanks for your feedback!

We don't have any NEON implementations yet, but this is something I'd like to work on next, so having proper feature detection is pretty essential.

Thanks again!
