### ISSUE TITLE
Version String Changed in Windows Release

### ISSUE THREAD

**Issue by m4dc4p** [jedisct1/libsodium#665]
The  value returned from `sodium_version_string` seems to have changed in recent Windows builds. Previously, it report `1.0.14` (or similar). Now it says `1.0.16 xsalsa20`. 

I am seeing this using the the latest MSVC build (https://download.libsodium.org/libsodium/releases/libsodium-1.0.16-msvc.zip), using the DLL `\x64\Release\v110\dynamic\libsodium.dll`.

Is this expected behavior? It sure doesn't look like the verison number should change.

Note this seems to have been introduced in the 1.0.15 build.

**Comment by m4dc4p** [comment]
Would a test case using Java (Kalium) or Ruby (RbNacl) be acceptable? I
don't think I could put a C or C++ one together.

**Comment by ektrah** [comment]
The pointer returned by `sodium_version_string` in the 1.0.16 DLL points at this:

    "1.0.16\0\0xsalsa20\0\0"

Since strings in C are null-terminated, the version string is only the first part until the first "\0".

**Comment by m4dc4p** [comment]
What is the value of that string in 1.0.14? Is it terminated differently?

**Comment by ektrah** [comment]
In the 1.0.14 DLL the memory looks like this:

    1.0.14\0\0\0\0\0\0...

So there change in that it's null-terminated.

**Comment by m4dc4p** [comment]
I'm seeing this using Kalium, a Java project, so there may be some weirdness in how the value is retrieved. A null-terminated string should be a null-terminated string tho. I don't see any difference between 1.0.16 and 1.0.14 in that sense. They both end in `\0`. Seems like not a bug in libsodium.

**Comment by ektrah** [comment]
I suspect the code reads a fixed number of characters from the memory and removes the null characters instead of stopping at the first null character. Then it will look as if the string changed from "1.0.14" to "1.0.16xsalsa20".

**Comment by m4dc4p** [comment]
Yes I found a bug in the jnr-ffi library that addresses this issue exactly - https://github.com/jnr/jnr-ffi/issues/108. Thanks for your help and research!

**Comment by jedisct1** [comment]
Great!

You may want to check that this doesn't also happen with other functions returning a NUL-terminated string (off the top of my head: `pwhash_str`, `bin2hex` and `base642hex`.

**Comment by m4dc4p** [comment]
Excellent idea, appreciate it!
