### ISSUE TITLE
libsodium 0.7.3 over-aggressively uses unhandledRejection

### ISSUE THREAD

**Issue by andrewferrier** [jedisct1/libsodium#672]
I am using libsodium 0.7.3 (via libsodium-wrappers). In the minified version of libsodium.js (`node_modules/dist/modules/libsodium.js` in my filesystem) is the incantation `process.on("unhandledRejection",function(A,I){process.exit(1)})`. In my opinion this is overzealous; it causes an immediate exit from the NodeJS process on any unhandled promise rejection anywhere. In my application, I want to do some (async) processing logic on that event, but as soon as I include libsodium-wrappers, I cannot; even if libsodium.js is included after, any async/Promise behaviour in my event handler is skipped because the process ends before. I think libsodium is overreaching a bit here by affecting Promises anywhere in the process. It would be great to improve this as it's not easy to patch.

Thanks for your work on libsodium!

**Comment by jedisct1** [comment]
Hi!

That was done to address https://github.com/jedisct1/libsodium.js/issues/59

If you have a better fix, your pull request would be more than welcome, but to the right project: https://github.com/jedisct1/libsodium.js

Thanks!

**Comment by jedisct1** [comment]
Just noticed that you were referring to `unhandledRejection`, not `uncaughtException`.

Maybe a similar workaround needs to be applied.

**Comment by jedisct1** [comment]
Can you try the same workaround? `process.removeAllListeners("unhandledRejection")` ?

**Comment by andrewferrier** [comment]
Yes, after reading #59 I figured out it was basically the same issue. I've tried the same workaround with `unhandledRejection` and it works. Thanks. Looks like Emscripten being over-zealous to me.

**Comment by andrewferrier** [comment]
And sorry, I didn't spot the difference between https://github.com/jedisct1/libsodium.js and https://github.com/jedisct1/libsodium ;)

**Comment by jedisct1** [comment]
No problem Andrew. Glad that this workaround does the trick! Thanks for bringing this to my attention as well.
