### ISSUE TITLE
What is xsalsa20 internal chunk size?

### ISSUE THREAD

**Issue by S1owaway** [jedisct1/libsodium#678]
Hello!
I use crypto_secretbox_xsalsa20poly1305_open function for symmetric encryption from Java code (with libsodium-jni wrapper). How do libsodium encrypt large byte array? I think it should have some "internal" chunk of bytes. For example, if we have 1024 * 1024 * 2 data bytes (2mb), libsodium encrypt these all bytes at once? And for decryption I need decrypt these all bytes at once too?
I need to decrypt large files by chunks (for example by 1mb). Can I do that, if my old files (size more then 1mb) were encrypted with xsalsa20?

**Comment by jedisct1** [comment]
The limit is how much memory you have. There is a single authenticator for the whole block, so either everything or nothing is decrypted.

If you need to encrypt large files processed in smaller chunks, use the `crypto_secretstream()` API: https://download.libsodium.org/doc/secret-key_cryptography/secretstream.html
