### ISSUE TITLE
Why does Key Exchange use unkeyed blake2b?

### ISSUE THREAD

**Issue by riobard** [jedisct1/libsodium#681]
https://github.com/jedisct1/libsodium/blob/8b9b6a54be5490449e0c5e535aa257d6406b04b2/src/libsodium/crypto_kx/crypto_kx.c#L58

The construction is `x || tx = BLAKE2B-512(p.n || client_pk || server_pk)`. I'm wondering what's the security of prepending the key vs using keyed blake2b instead?

**Comment by jedisct1** [comment]
It doesn't make any difference from a security perspective, but it can be generalized.

The same construction can be made with any key size and any hash function.

**Comment by jedisct1** [comment]
The input length is fixed and this is not authenticating anything. Length extension attacks are irrelevant.

**Comment by riobard** [comment]
I see. Thanks!
