### ISSUE TITLE
libsodium install problem in PHP 7.0

### ISSUE THREAD

**Issue by ajaybairagi** [jedisct1/libsodium#683]
My PHP version  is 7.0.17 
I want to enable libsodium. I have follow below steps but not install.
1) For libsodium.dll, copy the DLL to  the same directory as php.exe
2) For php_libsodium.dll, copy it to the extension directory
The extension directory is usually, but not always, ext/ from the directory that contains php.exe
The extension_dir configuration directive in php.ini will point you in the right place
3) Add extension=php_libsodium.dll to your php.ini file.
https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium 

How to install in PHP 7.0 version

**Comment by jedisct1** [comment]
Hi!

This repository is about the library itself. Unfortunately I use neither Windows nor PHP so the only way I could help is by doing Google searches the same way you can :)

You should ask on forums about PHP.
