### ISSUE TITLE
libsodium in SGX

### ISSUE THREAD

**Issue by rbost** [jedisct1/libsodium#685]
For a project, I would like to compile libsodium so it can be used in an Intel SGX enclave. This would (from what I see and understand at this moment) require changes to the autoconf script and some additional code for the RNG.

I will do that myself, so as to learn more about libsodium and SGX, but I wanted to know if that was something that would be considered for inclusion in libsodium's source when it will be done?

**Comment by jedisct1** [comment]
That would definitely be awesome!

I was planning to do it for libhydrogen, but if you feel like doing it for libsodium, go, go, go!

**Comment by rbost** [comment]
So, I have a first working version [here](https://github.com/rbost/libsodium/tree/sgx).

Using the resulting compiled lib, I was able to build an app hashing the same string in the enclave and out of the enclave. And you know what? They hashed to the same value!!!!

For the moment, I see one security issue: sgx_read_rand generates pseudo-random bytes (and not truly random ones) when building the enclave in simulation mode, and I don't think this is good at all. I believe that, even in simulation mode, libsodium must remain cryptographically sound. Yet I don't not see a secure straightforward solution. Ideas are appreciated ...

The question of how to test the build remains: it would be great if we could test the execution of the library inside SGX by building an app that would create an enclave that would run the tests. Yet, that would require changing a lot the testing architecture that relies on many independent executables each testing a single feature. Again, suggestions will be necessary 😃

**Comment by rbost** [comment]
This is exactly the conclusion I came to, and I am not super thrilled about any of those two options.

Strictly speaking, I think that you can use the simulation mode on a platform that does not support RDRAND. So, if you want to build something that is still cryptographically correct, this would be a problem (sure, one might ask why we want to do this in the simulation mode, and what is the point in term of security, but still, we shouldn't jeopardise the crypto of the library in any way).
Also, if you look at the [implementation of `sgx_read_rand`](https://github.com/intel/linux-sgx/blob/master/common/src/sgx_read_rand.cpp), it seems that whenever RDRAND is available, it is used (even in SIM mode). It is also where you realize that, despite what is announced, there is a way to call CPUID from within the enclave without making an OCALL. It is annoying, but it is another problem ...

The belt-and-suspenders approach (i.e. making OCALLs to seed the RNG) would be completely valid for the simulation mode: the enclave would run on "untrusted" HW anyway, so it would not make any difference from this point of view. Still, I see two issues. First, it would require to add a app-side helper to answer the seeding OCALLs, and I am not sure to see how we could integrate that in libsodium's architecture. Then, it does not seem possible to determine at runtime if the library is run in SIM mode or not. You can do it for the debug mode (see [this](https://software.intel.com/en-us/node/709097) or [this](https://github.com/intel/linux-sgx/blob/master/common/inc/sgx_attributes.h)), but I could not find anything in the APIs for the simulation env. And compiling two versions of libsodium does not look like a great idea to me.


PS: I highly recommend reading [this paper](https://eprint.iacr.org/2014/504) for a formal analysis of RDSEED and RDRAND.

**Comment by tarcieri** [comment]
> Then, it does not seem possible to determine at runtime if the library is run in SIM mode or not.

Simulation mode links to a completely different set of RTS libraries, so you need to produce two separate executables for sim vs non-sim anyway.

For the sim case, you could package randombytes as a separate library which includes an OCALL helper, and have separate linking instructions for sim vs non-sim.

**Comment by rbost** [comment]
> Simulation mode links to a completely different set of RTS libraries, so you need to produce two separate executables for sim vs non-sim anyway.

Yes, this is completely true for *executables*, but here, we are trying to build a library that can be used in both simulation and hardware modes, so the RTS libs can be linked after the build of the library.

> For the sim case, you could package randombytes as a separate library which includes an OCALL helper, and have separate linking instructions for sim vs non-sim.

Agreed. But this is not very elegant, and it is a shame for something as easy to use as libsodium, and that tries to be secure by default (this is not OpenSSL, right?). 
@jedisct1 Any thoughts on that?

**Comment by mouse07410** [comment]
>>>  I see one security issue: sgx_read_rand generates pseudo-random bytes (and not truly random ones) when building the enclave in simulation mode
>>
>> In either mode you can (directly) invoke RDRAND directly to obtain output that should be at least as trustworthy as SGX itself (in for a penny, in for a pound).
>
> Strictly speaking, I think that you can use the simulation mode on a platform that does not support RDRAND.... Also, if you look at the [implementation of `sgx_read_rand`](https://github.com/intel/linux-sgx/blob/master/common/src/sgx_read_rand.cpp), it seems that whenever RDRAND is available, it is used (even in SIM mode).

In general, RDRAND is good, especially if you intend to trust SGX - and it's been around since 2011. I personally see no point playing with SGX if the platform doesn't even support RDRAND. 

You must have some assumptions about the platform your code is going to run on. If that platform provides an RNG - why don't you mix the `six_read_rand` output with the output of that RNG, and get the best of both? And if that platform does not provide any RNG - well, I'd pick a different one then...

**Comment by rbost** [comment]
> In general, RDRAND is good, especially if you intend to trust SGX - and it's been around since 2011. I personally see no point playing with SGX if the platform doesn't even support RDRAND.

Again, we definitely agree on these points :)  Trusting SGX but not RDRAND makes absolutely no sense. 

I know/understand that the problem I want to solve is not necessary interesting in terms of practical security. Again, I just want to understand what one can and cannot do with SGX. If the only way to get a reliable and secure randomness source without OCALLs is to use sgx_read_rand/RDRAND, I am perfectly fine with that.

**Comment by jedisct1** [comment]
Totally fine with that as well.

**Comment by mouse07410** [comment]
> I just want to understand what one can and cannot do with SGX

:-)  If one has SGX, one definitely has RDRAND as well (and RDSEED, and some other goodies too ;).

> If the only way to get a reliable and secure randomness source without OCALLs is to use `sgx_read_rand/RDRAND`, I am perfectly fine with that.

What I'm saying is that given the likely platform considerations, this is not only an "acceptable" way, but the only *reasonable* way IMHO.

**Comment by rbost** [comment]
A quick head's up: I was able to port the test programs, and all the checks pass. I still have to clean up the automake files (eg. so that make clean actually removes the enclaves), but the PR should come soon.

The code is still [there](https://github.com/rbost/libsodium/tree/sgx).

**Comment by rbost** [comment]
PR #688, which includes all the changes needed to compile on SGX, has been around for week, but still no comment on it 😢. If someone could give me some his thoughts on this, that would be great!

**Comment by jedisct1** [comment]
Hi Raphael,

Sorry, I've been swamped with work and I really haven't had time to write or review any code.

I don't have any Linux machine to test this on at the moment, but I'll do my best to find one and test this as soon as possible.

The first issue that will be open after this gets merged is bound to be "why doesn't this work on Windows?"

Have you looked at what it would take to make this work on Windows as well?

**Comment by mouse07410** [comment]
And the second issue that will be open is bound to be "why doesn't it work on MacOS?"

I will try it on Mac, but most likely would need help.

P.S. Are there any Linux distribution/version restrictions, aka "it works on distro X but not on Y, Z, etc."?

**Comment by jedisct1** [comment]
The SGX SDK doesn't exist on MacOS AFAIK.

**Comment by mouse07410** [comment]
Correct. But most likely it can be ported.

**Comment by rbost** [comment]
> Sorry, I've been swamped with work and I really haven't had time to write or review any code.

No problem, I just wanted to make sure this did not go unnoticed 😃.

> The first issue that will be open after this gets merged is bound to be "why doesn't this work on Windows?"
> 
> Have you looked at what it would take to make this work on Windows as well?

From what I understood from the SGX documentation, the code would not need any modification. Still, the Visual Studio project file would have to be modified to produce a library that correctly links to the SGX SDK, and to produce test programs that run in an SGX enclave.
I merely use Windows, and in particular not for development, so I am not sure I can really help here.

> Correct. But most likely it can be ported.

Looks very annoying. For example, even on Linux, I was not able to build the SDK with clang, so you might want to fix that first (which is ironic as a lot of the code comes from llvm). It does not look too hard (I was able to compile the trusted stdc and stdc++ by changing the code only at a few places) but still ... Porting on MacOS looks worse (I quickly tried, without success).

Anyways, the PR should work on MacOS as it uses the same build system as Linux.

> P.S. Are there any Linux distribution/version restrictions, aka "it works on distro X but not on Y, Z, etc."?

Intel's readme says that Ubuntu 16 LTS, RHEL 7.4, CentOS 7.4, and SUSE 12 (all in 64 bits) are required.

**Comment by mouse07410** [comment]
I have working GCC 7.3.0 installed via Macports, so perhaps if Clang doesn't do the job - GCC would?

Anyway, I had in mind long ago to play with SGX in Mac (despite BIOS not supporting it ;), maybe this is a good stimulus to start. ;-)

I'll move slowly, and keep you guys informed.

P.S. Of course, libsodium works on Mac smoothly.
