### ISSUE TITLE
warning C4197: 'volatile const unsigned char *volatile ': top-level volatile in cast is ignored

### ISSUE THREAD

**Issue by Robinson-George** [jedisct1/libsodium#687]
When compiling the libsodium library the following warning is generated: 
C4197: 'volatile const unsigned char *volatile ': top-level volatile in cast is ignored

This is caused by  code that does not adhere to the C standard (section 6.5.3), namely: "properties associated with qualified types are meaningful only for l-value expressions", thus the top-level volatile in cast is ignored with a warning.

For an example of these errors see: https://github.com/jedisct1/libsodium/issues/655

**Comment by jedisct1** [comment]
This is intentional. It doesn't violate the C standard, but its implications are not defined.
It is required to prevent some optimizations that have been observed with gcc, but that can also affect other compilers. There have been a couple discussions about this in the past.

**Comment by jedisct1** [comment]
Here's an example: https://godbolt.org/g/xP4eGz

See how in the first example, the call to `memset_s()` doesn't do anything in spite of the `volatile` qualifiers on the content.

**Comment by Robinson-George** [comment]
They guys at Stackoverflow think that the R-value cast is not necessary.
See:  https://stackoverflow.com/questions/49084430/using-volatile-twice-in-an-r-value
