### ISSUE TITLE
ED25519 Signature Check broken on big endian systems

### ISSUE THREAD

**Issue by rincewound** [jedisct1/libsodium#697]
Hey everybody, I'm in the process of implementing a libSodium based signature check on a big endian MCU, and as far as I've been able to figure it out, the code involved does not seem to be endian agnostic, leading to crypto_sign_ed25519_verify_detached failing on the target (big endian) system but not on the (little endian!) development machine.
Debugging the relevant code side-by-side yields fe_25519_sq as the first culprit (called by ge25519_frombytes_negate_vartime), at least this is the point, where the data starts to differ on both targets i.e.:
Calling fe25519_sq on the LE system (ed25519_ref10.c, Ln 287) yields the following values for u:
		[0x00000000]	0x0163a522	
		[0x00000001]	0x00ad59b4	
		[0x00000002]	0xfe4a6785	
		[0x00000003]	0xff5fb924	
		[0x00000004]	0x0119f87c	
		[0x00000005]	0x00b4922b	
		[0x00000006]	0x008cdf6d	
		[0x00000007]	0x0091f5a2	
		[0x00000008]	0x00bd7131	
		[0x00000009]	0xff9211c7	

whereas doing the same thing on the BE target we get:
0x00644611
0x0047D6DA
0xFEDB09A5
0x0002864F
0x00D49094
0xFF5E671D
0xFECF0571
0xFFFFDE95
0xFF07FF51
0xFF453DA9

A look at fe25519_sq (in ed25519_ref_fe_25_5.h) shows a rather suspicious implementation in the last third of the function (lines 743).

Now, I admit that my usecase is probably not the one libSodium is targeted for, however, I would have expected this to work, as the documentation of libSodium states:

> All operations work on big endian and little endian systems, and do not require pointers to be aligned.

Note that I've stuck to the reference C implementations that don't use any specific hardware features.

**Comment by jedisct1** [comment]
Can you post the `config.log` file you get on that LE host somewhere?

**Comment by rincewound** [comment]
I'm afraid I don't have one, as libSodium ist compiled from within the project (i.e. the relevant bits of libSodium are part of the project). 

However, I did some digging in the sourcecode. It turns out, that the actual issue here is the code generated by the compiler (IAR ICC). The interesting bit is, that fe25519_sq actually does not do anything that strikes me as particularly dangerous, except for the bitshifting in the last third (however, debugging revealed that things already went wrong before that point and the calculated hX (calculated ln 722 - 731) values were plain wrong to begin with), i.e. there is apparently something wrong 64 bit additions and multiplications and the way they are translated by the compiler.

The mentioned method seems to work okay, when I make all variables volatile, however, I immediatly get even more problems when the next function is called by ge25519_frombytes_negate_vartime, in this case fe25519_mul.

**Comment by jedisct1** [comment]
Sorry, this is an unsupported configuration.
