### ISSUE TITLE
Tests fail if built with -DNDEBUG

### ISSUE THREAD

**Issue by emmenlau** [jedisct1/libsodium#698]
When I add -DNDEBUG to CPPFLAGS environment variable before running configure, then libsodium `make check` fails. Is that expected? NDEBUG is part of my standard build flags for a release build. It took me quite a while to find the problem.

**Comment by jedisct1** [comment]
Yes, this is expected, and if you change compiler flags, you're on your own.

The build script even tries to [remove this definition](https://github.com/jedisct1/libsodium/blob/7d4976a304c777c2925f67a7df1a390ca8742f30/configure.ac#L820) even though I just noticed that the generated script doesn't include this.

**Comment by emmenlau** [comment]
Ok fair enough! I'm building for a self-maintained distro so there are CFLAGS and CPPFLAGS that I can not avoid (i.e. I need to set the target host type for gcc).

Just to kindly ask, would it be possible that the generated configure script is patched to include this definition?

**Comment by jedisct1** [comment]
Do you know how to have this definition added? I tried `AH_TOP` but it didn't seem to end up in the generated `configure` script either.
