### ISSUE TITLE
cppcheck: Uninitialized variable

### ISSUE THREAD

**Issue by javabeanz** [jedisct1/libsodium#700]
running cppcheck gives :

libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:149]: (error) Uninitialized variable: pk

**Comment by enkore** [comment]
Looks like a false positive, since pk is an output parameter of edwards_to_montgomery.

**Comment by jedisct1** [comment]
Yes, it's an output variable, it doesn't have to be initialized.

**Comment by javabeanz** [comment]
the CWE description for unitionialized variable https://cwe.mitre.org/data/definitions/457.html makes no distinction for output variables. are you really sure ?
