### ISSUE TITLE
Documentation about "in-place" encryption/decryption in authenticated encryption

### ISSUE THREAD

**Issue by sijohans** [jedisct1/libsodium#701]
For the functions *crypto_box_easy* and *crypto_box_open_easy* the cipher and clear text message may overlap to enable for in-place encryption/decryption. This feature is not documented in API targeting the precalculation interface. This however seems to be a "hidden" feature, but it doesn't feel comfortable to rely on such a feature. Are there any plans including this in the API?

**Comment by jedisct1** [comment]
This has been added to the documentation.

Thanks!

**Comment by sijohans** [comment]
Thank you. I know that the crypto_box_afternm and crypto_box_open_afternm functions are not recommended by the libsodium API (hard API, easy to misuse). But does this in-place functionality also includes them? The project this is used also support TweetNaCl (the in-place functionality seems to be a hidden feature in that library to) for development purposes (very easy to just  include one header and source file).

**Comment by jedisct1** [comment]
This works, but not on older versions (as shipped with Debian Jessie).
