### ISSUE TITLE
XOR cipher support

### ISSUE THREAD

**Issue by lars18th** [jedisct1/libsodium#703]
Hi,

I'm sure a lot of people will think that I'm such a fool for requesting this. But, in order to have the option for running it at full speed, and for checking the performance results over different ciphers. I suggest to support a simple (fake) XOR cipher, almost with a _debug_ or special (non default) compilation.

I'm sorry if you found this stupid. However, I hope someone likes to implement it.
Thank you for this great library!

**Comment by jedisct1** [comment]
Maybe for April 1st :)
