### ISSUE TITLE
libsodium binaries

### ISSUE THREAD

**Issue by mattraffel** [jedisct1/libsodium#707]
I realize this is a newbie question.  My apologizes.  Not sure where to ask this.

I ran the build commands (make && make check).   Now I want to add this library to my rust project.  **Where does make output the build to?  which folder?**  

I was expecting to find a libsodium.so file somewhere in the source path.   **While library do I use?**

Thnx
Matt

**Comment by jedisct1** [comment]
Type `make install` to install it, and if you are on Linux `ldconfig` for the linker to pick up the new library :)
