### ISSUE TITLE
errno on windows

### ISSUE THREAD

**Issue by emilbayes** [jedisct1/libsodium#711]
Hi!

In `sodium-native` we link against libsodium as a shared library from our node.js bindings, which are also small shared libraries, since we do prebuilt binaries for a range of node.js and electron versions, and try to not make the tarball that is downloaded from npm too large. When a libsodium function returns `!= 0` (in appropriate cases) we construct an error message from `errno`. I just learnt that on Windows, errno is only global to the DLL itself, and therefore cannot be read from the linking binary/library. Is there a workaround to this except introducing a new `int sodium_errno()`-like function, or am I treating `errno`s wrong? I know that you have said elsewhere that the `errno` are not documented since they're not exactly 100% supported across platforms and not all libsodium functions set them when there's a non-zero return. Is it wrong of me/us to use `errno` for reporting errors considering that we support both various UNIXs and Windows?

**Comment by jedisct1** [comment]
Unfortunately I don't know how to handle this. Introducing a `sodium_errno()` function would be pretty ugly, especially since it would be useless except on Windows.
