### ISSUE TITLE
Why no sodium_base64_DECODED_LEN ?

### ISSUE THREAD

**Issue by udf2457** [jedisct1/libsodium#713]
Forgive the potentiallly stupid question, but why do we have no `sodium_base64_DECODED_LEN()` ?

In the almighty docs, you make a big song and dance over `ENCODED_LEN()` being the best thing since sliced bread because:

> Computing a correct size for b64_maxlen is not straightforward and depends on the chosen variant. etc.

So, call me stupid, but if you consider computing b64 output is best done using a helper function, then how come computing the reverse is suddenly so simple that you don't need a helper function ?

**Comment by jedisct1** [comment]
The reverse cannot be computed at compilation time due to ignored characters.
