### ISSUE TITLE
XChaCha20 Nonce Extension

### ISSUE THREAD

**Issue by markuskasper** [jedisct1/libsodium#715]
Hi,

I feel there might be an implementation error in 
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_core/hchacha20/core_hchacha20.c Lines 59-66: 

According to Dan Bernstein (http://cr.yp.to/snuffle/xsalsa-20110204.pdf) we should use 
(x′1,x′2,x′3,x′4,x′11,x′12,x′13,x′14) = (z0,z5,z10,z15,z6,z7,z8,z9) while extending the nonce using HChaCha20.
 
If I read libsodiums implementation correctly libsodium is actually outputting words (z0, z1, z2, z3, z12, z13, z14, z15) of the extra round instead.

Could you please check?

Thanks,
Markus

**Comment by jedisct1** [comment]
Constants are not at the same position in salsa and chacha.

**Comment by markuskasper** [comment]
Thx. for the super fast reply. Missed the adoption to the "public inputs" of ChaCha20.
