### ISSUE TITLE
LIBSODIUM_FULL_BUILD nativeclient-x86_64

### ISSUE THREAD

**Issue by joshjdevl** [jedisct1/libsodium#716]
When LIBSODIUM_FULL_BUILD is enabled, it appears that on Ubuntu 16.04.4 LTS not all symbols are being included when running nativeclient-x86_64.sh . Thus, it doesn't appear that the full sodium build is being performed.

I've included the results of running `nm` where the "scrypt" related methods are not included.

http://termbin.com/jc3e

**Comment by jedisct1** [comment]
```
if [ -z "$LIBSODIUM_FULL_BUILD" ]; then
...
```

It needs to be defined, but it also has to contain something

**Comment by joshjdevl** [comment]
Correct, I've done `export LIBSODIUM_FULL_BUILD="true"` as well as modify `nativeclient-x86_64.sh ` directly.

Are you seeing all the symbols when you do a full build?

**Comment by jedisct1** [comment]
nativeclient is dead.
