### ISSUE TITLE
PHP 7.2.5 Extension not loaded

### ISSUE THREAD

**Issue by Sparkeroo96** [jedisct1/libsodium#720]
I a running xampp with php 7.2.5
When I run get_loaded_extensions(), sodium is not loaded up but in the phpinfo under modules I can see Sodium and Author "Frank Denis"

I tried 
`var_dump([
    SODIUM_LIBRARY_MAJOR_VERSION,
    SODIUM_LIBRARY_MINOR_VERSION,
    SODIUM_LIBRARY_VERSION
]);`
and I got 
`Warning: Use of undefined constant SODIUM_LIBRARY_MAJOR_VERSION - assumed 'SODIUM_LIBRARY_MAJOR_VERSION'`
for each of them

I have also followed this guide:
https://paragonie.com/book/pecl-libsodium/read/00-intro.md#installing-libsodium
and seen no results, do you know what I have done wrong

**Comment by enkore** [comment]
This repository is about the core library; the PHP extension is hosted there: https://github.com/jedisct1/libsodium-php

**Comment by jedisct1** [comment]
This is the wrong repository for this.

But XAMPP probably doesn't include support for libsodium.

**Comment by Sparkeroo96** [comment]
Sorry thanks, will move it to there :/
