### ISSUE TITLE
Could anybody give me a demo of simple libSodium SSL Client/Server?

### ISSUE THREAD

**Issue by PeterBethlyFord** [jedisct1/libsodium#723]
Could anybody give me a demo of simple libSodium SSL Client/Server?
Or tell me where I can get it instead.

**Comment by jedisct1** [comment]
libsodium doesn't implement TLS. It does the crypto, not the networking part.

You need to add [MatrixSSL](https://github.com/matrixssl/matrixssl) on top of it for TLS.
