### ISSUE TITLE
secretstream TAG_FINAL does nothing?

### ISSUE THREAD

**Issue by samscott89** [jedisct1/libsodium#724]
From the docs: 

> crypto_secretstream_xchacha20poly1305_TAG_FINAL: indicates that the message marks the end of the stream, and erases the secret key used to encrypt the previous sequence.

But `TAG_FINAL` doesn't seem to be used anywhere in https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretstream/xchacha20poly1305/secretstream_xchacha20poly1305.c

**Comment by jedisct1** [comment]
```c
#define crypto_secretstream_xchacha20poly1305_TAG_FINAL \
    (crypto_secretstream_xchacha20poly1305_TAG_PUSH | \
crypto_secretstream_xchacha20poly1305_TAG_REKEY)
```
