### ISSUE TITLE
crypto_sign_ed25519_pk_to_curve25519 vs x25519

### ISSUE THREAD

**Issue by aep** [jedisct1/libsodium#726]
i'm confused what crypto_sign_ed25519_pk_to_curve25519 does, since i dont end up with the x25519 public key. am i missing another transformation?

```
seed = some_random
public_ed, private_ed = crypto_sign_seed_keypair(some_random)
public_x1, private_x1 = crypto_kx_seed_keypair(some_random)

public_x2 = crypto_sign_ed25519_pk_to_curve25519(public_ed)
public_x1 != public_x2
```

**Comment by enkore** [comment]
I don't think there is some transitive guarantee that {sign,kx}_seed_keypair() generate the same keys when transformed into compatible formats. I'd expect that seed_keypair generates the key simply by fetching 32 random bytes; so you end up with the private X25519 key being some_random, and also the private Ed key being some_random. Then it is expected that the public Ed key won't match the public Curve key.

**Comment by aep** [comment]
yep, apparantly you need to use both crypto_sign_ed25519_pk_to_curve25519 and 
crypto_sign_ed25519_sk_to_curve25519 to derive a x25519 from an ed which is actually fine for my use case (do ECDH on the internet after having verified signatures offline)

apparantly crypto_sign_ed25519_sk_to_curve25519 is just sha5125 over the ed secret, but my math is too weak to understand if this means my above idea should somehow work. Probably not.

thanks!
