### ISSUE TITLE
Should --enable-minimal disable xchacha?

### ISSUE THREAD

**Issue by pysiak** [jedisct1/libsodium#731]
Ubuntu keeps on shipping libsodium-dev without support for xchacha20.
I checked and it's because they use --enable-minimal

What makes more sense? Ask Ubuntu not to use --enable-minimal or perhaps xchacha20 could be included in the minimal build?

**Comment by jedisct1** [comment]
No other operating system or distribution ships packages compiled with `--enable-minimal`.

It would make more sense to have Ubuntu remove this, and ship packages consistent with other distributions. Having the same version offer different features on Ubuntu compared to everywhere else is going to cause a lot of pain to users and developers.

**Comment by pysiak** [comment]
Thanks, I raised a bug with Ubuntu: https://bugs.launchpad.net/ubuntu/+source/libsodium/+bug/1780563
