### ISSUE TITLE
Error with r a n d o m b y t e s / r a n d o m b y t e s . c

### ISSUE THREAD

**Issue by Serasar** [jedisct1/libsodium#733]
Have this program written in Nim(I use this binding https://github.com/FedericoCeratto/nim-libsodium):
```
var key = randombytes(crypto_secretbox_KEYBYTES())
let c = crypto_secretbox_easy(key, "test")
let d = crypto_secretbox_easy(key, c)
echo(d)
```
Get this error:
A s s e r t i o n f a i l e d !

P r o g r a m : C : \ D e v \ n i m _ e n c \ c r y p t o . e x e
F i l e : r a n d o m b y t e s / r a n d o m b y t e s . c , L i n e 2 0
4

E x p r e s s i o n : b u f _ l e n < = S I Z E _ M A X

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
SIGABRT: Abnormal termination.
It seems that this error only happens on 32 bit install for some reason. Everything works fine on 64 bits.

Also this issue is here https://github.com/FedericoCeratto/nim-libsodium/issues/8

**Comment by jedisct1** [comment]
I'm not familiar with Nim, but an error on Line 20 for a source code that is only 4 lines long doesn't seem right :) Neither seems to be the double call to `secretbox()`.

Can you post the actual test case?

**Comment by jedisct1** [comment]
Glad that we have these assertions :)

So this is a bug in the Nim wrapper that you should report to the author!
