### ISSUE TITLE
"void * const addr" should be "void const *addr"

### ISSUE THREAD

**Issue by sunqingyao** [jedisct1/libsodium#734]
I saw these two functions in the [document](https://download.libsodium.org/doc/helpers/memory_management.html):

```
int sodium_mlock(void * const addr, const size_t len);
int sodium_munlock(void * const addr, const size_t len);
```

Since parameters are copied when a function is called, qualifying a parameter with `const` in function declaration is pointless: you can never modify its original value anyway.

You might want to change it to `void const *addr`, which means the function will not modify the data `addr` _points to_.

Further reading: https://stackoverflow.com/q/51353648/5399734

**Comment by jedisct1** [comment]
These functions definitely have side effects on the data at `addr`, so `*addr` cannot be `const`.

The implementation doesn't change `addr` itself, so it can be `const`.

**Comment by sunqingyao** [comment]
I’m confused. If the secret data (say cleartext password) is changed upon locking its memory, how can I subsequently hash it? In other words, the password I’m hashing may not be what a user have inputted, if there is a side effect introduced by these functions.

Also, it’s impossible for any implementation to change ‘addr’, because C is call by value.

**Comment by jedisct1** [comment]
Before a call to `sodium_mlock()`, `*addr` can be written to to. After a call to `sodium_mlock()`, writing to `*addr` will cause an exception. So it had a side effect on `*addr`. The behavior wouldn't change if `*addr` had been `const`.
