### ISSUE TITLE
Cross compile failed

### ISSUE THREAD

**Issue by cocoismywife** [jedisct1/libsodium#735]
Hello jedisct1 

I'm try to cross compile on armv7l-unknown-linux-gnueabihf， but  finally it failed.

Making install in builds
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in contrib
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in dist-build
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in msvc-scripts
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in src
Making install in libsodium
Making install in include
make[4]: Nothing to be done for `install-exec-am'.
 ../../../build-aux/install-sh -c -d '/tmp/synology/include'
 ../../../build-aux/install-sh -c -d '/tmp/synology/include/sodium'
 /usr/bin/install -c -m 644  sodium/core.h sodium/crypto_aead_aes256gcm.h sodium/crypto_aead_chacha20poly1305.h sodium/crypto_aead_xchacha20poly1305.h sodium/crypto_auth.h sodium/crypto_auth_hmacsha256.h sodium/crypto_auth_hmacsha512.h sodium/crypto_auth_hmacsha512256.h sodium/crypto_box.h sodium/crypto_box_curve25519xchacha20poly1305.h sodium/crypto_box_curve25519xsalsa20poly1305.h sodium/crypto_core_ed25519.h sodium/crypto_core_hchacha20.h sodium/crypto_core_hsalsa20.h sodium/crypto_core_salsa20.h sodium/crypto_core_salsa2012.h sodium/crypto_core_salsa208.h sodium/crypto_generichash.h sodium/crypto_generichash_blake2b.h sodium/crypto_hash.h sodium/crypto_hash_sha256.h sodium/crypto_hash_sha512.h sodium/crypto_kdf.h sodium/crypto_kdf_blake2b.h sodium/crypto_kx.h sodium/crypto_onetimeauth.h sodium/crypto_onetimeauth_poly1305.h sodium/crypto_pwhash.h sodium/crypto_pwhash_argon2i.h sodium/crypto_pwhash_argon2id.h sodium/crypto_pwhash_scryptsalsa208sha256.h sodium/crypto_scalarmult.h sodium/crypto_scalarmult_curve25519.h sodium/crypto_scalarmult_ed25519.h sodium/crypto_secretbox.h sodium/crypto_secretbox_xchacha20poly1305.h sodium/crypto_secretbox_xsalsa20poly1305.h sodium/crypto_secretstream_xchacha20poly1305.h sodium/crypto_shorthash.h sodium/crypto_shorthash_siphash24.h '/tmp/synology/include/sodium'
 ../../../build-aux/install-sh -c -d '/tmp/synology/include/sodium'
 /usr/bin/install -c -m 644  sodium/crypto_sign.h sodium/crypto_sign_ed25519.h sodium/crypto_sign_edwards25519sha512batch.h sodium/crypto_stream.h sodium/crypto_stream_chacha20.h sodium/crypto_stream_salsa20.h sodium/crypto_stream_salsa2012.h sodium/crypto_stream_salsa208.h sodium/crypto_stream_xchacha20.h sodium/crypto_stream_xsalsa20.h sodium/crypto_verify_16.h sodium/crypto_verify_32.h sodium/crypto_verify_64.h sodium/export.h sodium/randombytes.h sodium/randombytes_salsa20_random.h sodium/randombytes_sysrandom.h sodium/runtime.h sodium/utils.h '/tmp/synology/include/sodium'
 /usr/bin/install -c -m 644  sodium.h '/tmp/synology/include/.'
 ../../../build-aux/install-sh -c -d '/tmp/synology/include'
 ../../../build-aux/install-sh -c -d '/tmp/synology/include/sodium'
 /usr/bin/install -c -m 644  sodium/version.h '/tmp/synology/include/sodium'
 ../../build-aux/install-sh -c -d '/tmp/synology/lib'
 /bin/sh ../../libtool   --mode=install /usr/bin/install -c   libsodium.la '/tmp/synology/lib'
libtool: install: /usr/bin/install -c .libs/libsodium.so.23.1.0 /tmp/synology/lib/libsodium.so.23.1.0
install: .libs/libsodium.so.23.1.0: No such file or directory
make[4]: *** [install-libLTLIBRARIES] Error 71
make[3]: *** [install-am] Error 2
make[2]: *** [install-recursive] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
There is no lib to copy. Could you help me to take look of it ? Thank you in advance.

**Comment by cocoismywife** [comment]
Plus this is my config params, thanks
./configure --build=mac --host=armv7l-unknown-linux-gnueabihf --prefix=/tmp/synology

**Comment by jedisct1** [comment]
Looks like you don't have the correct cross-compilation toolchain installed.

Do you have a `armv7l-unknown-linux-gnueabihf-gcc` (or `armv7l-unknown-linux-gnueabihf-clang`) command?
