### ISSUE TITLE
Possible typo in documentation

### ISSUE THREAD

**Issue by KrzysztofSakowski** [jedisct1/libsodium#738]
I have a question about [generating_random_data](https://download.libsodium.org/doc/generating_random_data/), function: _randombytes_buf_deterministic_. 

> For a given seed, this function will always output the same sequence. size can be up to 2^70 (256 GB).

Why is it stated that 2^70 is 256GB?
2^38 bytes ~ 274GB, if size_t is 64 bit variable 2^70 won't even fit into it.

**Comment by enkore** [comment]
256 GB is correct, 2^70 is wrong.

**Comment by KrzysztofSakowski** [comment]
@enkore thanks for so swift fix :+1:
