### ISSUE TITLE
Does/Can libsodium support AES CCM?

### ISSUE THREAD

**Issue by Max9403** [jedisct1/libsodium#739]
Looking through the documentation/issues I can't find any references to CCM mode, so I was wondering if it is/could be supported.

My use case for it is for encryption UDP traffic data in the form of the |session id|iv|encrypted data| where session id is a random value generated to allow for a look up to the session's unique key so the server can decrypt the key. GCM isn't applicable since the IV is randomly generated per request and transmitted over the internet multiple times per second throughout the lifetime of the client.

I hope this the appropriate place to ask this.

**Comment by enkore** [comment]
The long term direction of libsodium lies more with "a select set of good constructions & useful APIs" and less with "a bunch of algorithms of various redundancy and vintage" (~OpenSSL).

> My use case for it is for encryption UDP traffic data in the form of the |session id|iv|encrypted data| where session id is a random value generated to allow for a look up to the session's unique key so the server can decrypt the key.

Why not use crypto_secretbox (symmetric) or crypto_box (asymmetric)?

**Comment by Max9403** [comment]
Sorry I'm not very familiar with libsodium more so than that it is the encryption library to use (for that matter I haven't needed to other than to use argon2 for password hashes and setting up SSL) but

> Why not use crypto_secretbox (symmetric) or crypto_box (asymmetric)?

That looks like exactly what I need thanks

> This is a bit ambiguous, so take this with a grain of salt:

The way that it is planned to be setup is through a https request for auth using a standard username and password system.

The website then replies with the unique session key that's randomly generated (currently a float but could be substituted with a byte array) the key that will be used by the client for encryption as well as writing the same data to a shared redis store (with an undecided expiration between 2 days and a week). 
This data can have any data added to it, so from your comment I guess this would be the key for the session on the server (so that the client -> server and server -> client keys are different) and the nonce's seed/iteration for the server?

Then the client creates their stateful nonce and sends data as |session id|nonce used|data|
also the full UDP packet data should be as small as possible to stay under the 502 byte size (the effective max UDP packet size that the packet won't be fragment during transit) so if I read the code correctly that would make |4 bytes|24 bytes|~474 bytes| 

Out of curiosity after what amount of iteration of the stateful nonce should both be the key and it be regenerated?

In case it is of interest currently the client will be in C#/C++ to a java server and the website in javascript (node)

There is a plan to allow for a fallback TCP connection as well, however UDP would stay preferred and developed first

Thanks so much for the informative reply
