### ISSUE TITLE
XChaCha20-Poly1305 tests have short nonce

### ISSUE THREAD

**Issue by FiloSottile** [jedisct1/libsodium#742]
`crypto_aead_xchacha20poly1305_ietf_NPUBBYTES` is 24, but the nonce in the test case is 16 bytes. This would not detect issues processing the last 2 32-bit limbs of the nonce, which in XChaCha20 are indeed special (as they are fed into the proper ChaCha20 instance, not HChaCha20).

https://github.com/jedisct1/libsodium/blob/7cdf3f0e8419aa1be306effd11a20d980c118e04/test/default/aead_xchacha20poly1305.c#L25-L27

**Comment by jedisct1** [comment]
Good catch, thanks!
