### ISSUE TITLE
The recipe libsodium-1.0.11-r0 do_fetch fails because the tar ball is not found any more 

### ISSUE THREAD

**Issue by beltagymohamed** [jedisct1/libsodium#748]
The recipe libsodium-1.0.11-r0 do_fetch fails because the tar ball is not found any more http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-support/libsodium/libsodium_1.0.11.bb?h=rocko

The link that is fetched and not working is 
ttps://download.libsodium.org/libsodium/releases/libsodium-1.0.11.tar.gz

**Comment by jedisct1** [comment]
The current stable version is 1.0.16.

1.0.11 is very old and shouldn't be used any more. If you really need it, it's in the `old` directory.

**Comment by beltagymohamed** [comment]
The correct url is https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.11.
