### ISSUE TITLE
Stable Download isn't a stable URL

### ISSUE THREAD

**Issue by rmeyer-taos** [jedisct1/libsodium#767]
This afternoon while using Ansible as a build tool for my Docker container, 
I got a 404 on download of the stable image.

It turns out that your stable image changes names. While I'm all for this, there should be a repository of the old stable images so that automated build tools using older stable images can still be found. In this case it went from 
`https://download.libsodium.org/libsodium/releases/libsodium-stable-2018-10-04.tar.gz` to `https://download.libsodium.org/libsodium/releases/libsodium-stable-2018-10-05.tar.gz`

Stable images are great for those of us that want to ensure consistent functionality and downloads but the inability to download previous stable images, or a stable image with a consistent name is detrimental to DEVOPS practices. 

Suggestions on ways to mitigate this issue?

**Comment by jedisct1** [comment]
Use LATEST.tar.gz
