### ISSUE TITLE
'SIZE_MAX' undeclared (first use in this function)

### ISSUE THREAD

**Issue by Tom3141** [jedisct1/libsodium#768]
Hi,
I was attempting to compile turtl (which uses libsodium) on ubuntu 16.04 64 bit using a script I got from here:
https://gitlab.com/fdroid/rfp/uploads/65dcd8fc5d19702c9e61ae2e8dfa5249/turtl-fdroid.tar.gz
This script uses https://github.com/jedisct1/libsodium/releases/download/1.0.16/libsodium-1.0.16.tar.gz

Running the script it is bombing out here:

```
 make[3]: Entering directory '/tmp/turtl-build/libsodium/libsodium-1.0.16/src/libsodium/include'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/turtl-build/libsodium/libsodium-1.0.16/src/libsodium/include'
make[3]: Entering directory '/tmp/turtl-build/libsodium/libsodium-1.0.16/src/libsodium'
  CC       crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo
  CC       crypto_aead/xchacha20poly1305/sodium/libsodium_la-aead_xchacha20poly1305.lo
  CC       crypto_auth/libsodium_la-crypto_auth.lo
  CC       crypto_auth/hmacsha256/libsodium_la-auth_hmacsha256.lo
  CC       crypto_auth/hmacsha512/libsodium_la-auth_hmacsha512.lo
  CC       crypto_auth/hmacsha512256/libsodium_la-auth_hmacsha512256.lo
  CC       crypto_box/libsodium_la-crypto_box.lo
  CC       crypto_box/libsodium_la-crypto_box_easy.lo
  CC       crypto_box/libsodium_la-crypto_box_seal.lo
  CC       crypto_box/curve25519xsalsa20poly1305/libsodium_la-box_curve25519xsalsa20poly1305.lo
crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c: In function 'crypto_box_curve25519xsalsa20poly1305_messagebytes_max':
crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c:155:12: error: 'SIZE_MAX' undeclared (first use in this function)
crypto_box/curve25519xsalsa20poly1305/box_curve25519xsalsa20poly1305.c:155:12: note: each undeclared identifier is reported only once for each function it appears in
Makefile:2254: recipe for target 'crypto_box/curve25519xsalsa20poly1305/libsodium_la-box_curve25519xsalsa20poly1305.lo' failed
make[3]: *** [crypto_box/curve25519xsalsa20poly1305/libsodium_la-box_curve25519xsalsa20poly1305.lo] Error 1
make[3]: Leaving directory '/tmp/turtl-build/libsodium/libsodium-1.0.16/src/libsodium'
Makefile:2981: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/turtl-build/libsodium/libsodium-1.0.16/src/libsodium'
Makefile:399: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/turtl-build/libsodium/libsodium-1.0.16/src'
Makefile:515: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

fwiw (I had a issue thread going on turtl as well)
https://github.com/turtl/tracker/issues/157

**Comment by Tom3141** [comment]
I did a bit of googling and I managed and I found a solution here: https://stackoverflow.com/questions/30472731/which-c-standard-header-defines-size-max
I wound up adding the following to the header file, which made the error move:
#include <limits.h>#
ifndef SIZE_MAX
# ifdef __SIZE_MAX__
#  define SIZE_MAX __SIZE_MAX__
# else
#  define SIZE_MAX std::numeric_limits<size_t>::max()
# endif
#endif
I also had to wind up adding this to the following header files where I eventually got it to compile:
crypto_box_curve25519xsalsa20poly1305.h
crypto_secretbox.h
crypto_secretbox_xsalsa20poly1305.h
crypto_sign.h
crypto_sign_ed25519.h
crypto_stream_chacha20.h
crypto_stream.h
crypto_stream_salsa20.h
crypto_stream_salsa2012.h
crypto_stream_salsa208.h
crypto_aead_aes256gcm.h

I built the libraries, but I haven't run the programs yet, so I can't say yet if this "solves" it.
I don't if this an issue unique to gcc and ubuntu 16.04 64 bit, but this is what I did to make it go away.

Is this something that should be incorporated here:
https://github.com/jedisct1/libsodium/blob/master/src/libsodium/include/sodium/crypto_box.h#L17 ?

**Comment by jedisct1** [comment]
`<limits.h>` is already included in `export.h`, which is itself included in everything using `SIZE_MAX`, but the actual header defining it is `<stdint.h>` which is also included.

Redefining `SIZE_MAX` shouldn't be required, and doing so can probably cause more harm than good.

The Stackoverflow discussion is about C++, but libsodium is written in C, not C++.

Pretty sure quite a lot of people still use this old Ubuntu version, but nobody ever reported that issue, so it's a bit puzzling.

If you use a C++ compiler instead of a C compiler, on older Linux systems, what you apparently need to do is define `-D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS`.

**Comment by Tom3141** [comment]
Yah I was thinking I might have some unintended bad consequences to doing this, but I just wanted to get this to build.   (I just started playing with the new 7.1 build from the play store on Andriod) it probably going to take a few days till I get my data converted over to the new format before I start getting the itch to roll my own again ;)
Do you have the bandwidth to refactor your install script to address the issues I ran across?
I should probably update to 18.04.   I just haven't had the time/need to do it yet.
