### ISSUE TITLE
Unifying Ed25519 and Curve25519

### ISSUE THREAD

**Issue by CodesInChaos** [jedisct1/libsodium#77]
Curve25519 and Ed25519 are closely related, yet your code treats them as completely separate. It might be a good idea to move those code-bases closer together, perhaps even offering support for the same kind of key-pair.

Some ideas:

1. Add a Curve25519 implementation that builds on the Ref10 Ed25519 code. This only requires copying a few files from SUPERCOP.
2. Use the Ed25519 scalarmult_base function followed by a conversion to Montgomery coordinates to generate Curve25519 public keys. This quite simple and should speed up key-pair generation about two fold.
3. Offer a key-exchange API that works on Ed25519 keys. This allows people to use the same key-pair for both signatures and key-exchange, instead of using Ed25519 for one, and Montgomery Curve25519 for the other.

    A naive implementation (convert to montgomery before key-exchange) will be about 6% slower than Montgomery based key-exchange, but I believe key-exchange using Edwards coordinates can be sped up to the same level as Montogmery coordinates by modifying the scalar_mult implementation a bit.

My C# implementation already uses those techniques, so I can help you with making those changes.

**Comment by schnef** [comment]
I am very much a newbie at this subject, so please forgive me if I make stupid mistakes.

Since I needed a function to verify a message using a curve25519 public key instead of a ed25519 public key, I took the code from [trevp](https://github.com/trevp/ref10_extract/blob/master/ed25519/additions/curve_sigs.c) and added a function in ` libsodium-1.0.2/src/libsodium/crypto_sign/ed25519/ref10/open.c`. The functions reads:
```
int
crypto_sign_verify_curve25519_detached(const unsigned char *sig, const unsigned char *m,
                                       unsigned long long mlen, const unsigned char *curve25519_pk)
{
  fe mont_x, mont_x_minus_one, mont_x_plus_one, inv_mont_x_plus_one;
  fe one;
  fe ed_y;
  unsigned char ed_pk[32];

  fe_frombytes(mont_x, curve25519_pk);
  fe_1(one);
  fe_sub(mont_x_minus_one, mont_x, one);
  fe_add(mont_x_plus_one, mont_x, one);
  fe_invert(inv_mont_x_plus_one, mont_x_plus_one);
  fe_mul(ed_y, mont_x_minus_one, inv_mont_x_plus_one);
  fe_tobytes(ed_pk, ed_y);

  /* Copy the sign bit, and remove it from signature */
  ed_pk[31] &= 0x7F;  /* bit should be zero already, but just in case */
  ed_pk[31] |= (sig[63] & 0x80);

  return crypto_sign_verify_detached(sig, m, mlen, ed_pk);
}
```
It seems to work properly. Since performance is not my top priority, I haven't considered that point at all. 

I am so new to the this subject that I have no idea if this is a proper solution, if it is correct or that anybody else would need this.

**Comment by CodesInChaos** [comment]
I'd use a separate function to do the conversion, instead of inlining it
into the sign/verification functions.

**Comment by jedisct1** [comment]
Inlining it in the sign/verification functions makes sense in order to add the sign bit to the signature.

**Comment by DragonWork** [comment]
I'm not sure, but as of today, there is no cryptographic proof that using the same key pair for Curve25519 and Ed25519 is secure. Do you have details about this?

**Comment by tarcieri** [comment]
@DragonWork I believe it has been proven secure in the general sense of ECDH and Schnorr, although I don't have a link for you. I can ask some people...

**Comment by DragonWork** [comment]
@tarcieri I've read that already somewhere. Still, a proof that explicitly indicates that it is 100% secure would be great. :)

**Comment by coruus** [comment]
@CodesInChaos: Is there some reason that you can't afford the 32 bytes for key separation?

I'm pretty sure that you won't find a half-ways decent reduction for joint use of ECDH+Schnorr to anything stronger than Gap-DH (which is not a particularly nice assumption).

If you do, I'd love a cite.

**Comment by seb-m** [comment]
I think @tarcieri is referring to [this thread](https://www.ietf.org/mail-archive/web/cfrg/current/msg03142.html) and the linked paper [2011/615](http://eprint.iacr.org/2011/615).

**Comment by burdges** [comment]
Just fyi, there is another example here : https://github.com/agl/ed25519/blob/master/extra25519/extra25519.go

**Comment by jeroenooms** [comment]
+1 for efforts towards a single type of key for both encryption and signing. A single unambiguous pubkey per user would get us closer towards a gpg-like public key infrastructure.

**Comment by dominictarr** [comment]
since aug '14 there has been support for converting an ed25519 to curve25519 key, so you can make the signing key the main key, and convert it to an exchange key when you need that.

https://github.com/jedisct1/libsodium/blob/4705c0a06681d48ceec5ecbb66d496fd70c59bba/src/libsodium/crypto_sign/ed25519/ref10/keypair.c#L42

**Comment by jedisct1** [comment]
1. and 2. are done.
3. is a different topic.

**Comment by tarcieri** [comment]
If anyone would like to continue discussion about using Curve25519/X25519 to create/verify Ed25519 signatures, I've opened #335

**Comment by FSMaxB** [comment]
So is it secure to only have one Ed25519 keypair, use that for signing and derive the X25519 keypair for authenticated encryption and ECDH  using `crypto_sign_ed25519_pk_to_curve25519` and `crypto_sign_ed25519_pk_to_curve25519`?

Or do I require two separate keypairs (The Ed25519 could then be used to sign the X25519 one)?

**Comment by jedisct1** [comment]
If you can use two separate keypairs, use two separate keypairs.

**Comment by FSMaxB** [comment]
Okay. So If I use two keypairs, can I, when personally meeting my correspondent, only exchange public keys of the Ed25519 keypair for verification and rely on a Ed25519 signature for verifying the authenticity of the X25519 public key?

**Comment by jedisct1** [comment]
You totally can.

This is also how the dnscrypt protocol works.

**Comment by FSMaxB** [comment]
Okay, thanks.

**Comment by jedisct1** [comment]
Btw, hats off for the excellent work you've been doing on Molch.

**Comment by FSMaxB** [comment]
Thanks, I'm doing my best. You're library and support have been quite helpful.
