### ISSUE TITLE
add source code use cmake

### ISSUE THREAD

**Issue by zhouyouWiFiSong** [jedisct1/libsodium#771]
is there any solution to add source codes into my project using CMake？ could you tell me some Tutorials

**Comment by jedisct1** [comment]
The source code includes a [`Findsodium.cmake`](https://github.com/jedisct1/libsodium/blob/master/contrib/Findsodium.cmake) file to do so.

**Comment by zhouyouWiFiSong** [comment]
if use Findsodium.cmake， the library file must be compiled in advanced  for different platforms，i want Compilate it with my project，like CMakeLists

**Comment by zhouyouWiFiSong** [comment]
@jedisct1 I don't want  compile a dll for every platform ，is there a solution?3ks

**Comment by jedisct1** [comment]
I don't know much about cmake, but a quick Google search seems to suggest the `ExternalProject_Add` function to run `./configure` and `make check` in a dependency:

https://stackoverflow.com/questions/5971921/building-a-library-using-autotools-from-cmake
