### ISSUE TITLE
randombytes_buf_deterministic

### ISSUE THREAD

**Issue by mcgunay** [jedisct1/libsodium#774]
I am using c language. How can I generate same sequence with given seed value each and every time. Should I pass the generated  buffer for example? Because everytime the below is called a new sequence is generated.

randombyte_buf_deterministic(myString, 32, Myseed);
randombytes_uniform(30);

**Comment by woobs** [comment]
`randombyte_buf_deterministic` does what you want, with the deterministic sequence stored in `myString`.  Just use that.

`randombytes_uniform` should always generate a unique sequence, as that is what it is designed to do

**Comment by jedisct1** [comment]
If you don't always get the same output in `myString` (which, hopefully, is not a string), you need to make sure that `Myseed` is always the same, and has the proper length.

Maybe posting a short self-contained example reproducing the issue you are facing would help.

**Comment by mcgunay** [comment]
with `randombyte_buf_deterministic` I could generate unique myString everytime. Could you please tell me how I can generate integer sequence with given range from myString? (another function etc.)

**Comment by jedisct1** [comment]
```c
    int seq[100];
    randombytes_buf_deterministic(seq, sizeof seq, seed);
```
