### ISSUE TITLE
make check fails on Xeon W-2150B with Docker for Mac with current stable, 1.0.16 and 1.0.15

### ISSUE THREAD

**Issue by ChristianUlbrich** [jedisct1/libsodium#776]
`make check` fails  inside a Docker container (using gcc) on a Xeon W-2150B on macOS 10.13.4 with Docker CE 18.06-1. I have tested with another Mac (older....) having the same Docker + macOS version and it runs fine.

Reproduction:
* `docker run --rm -it -v $PWD:/mnt debian:jessie bash` (inside extracted tarball)
* `cd /mnt`
* `apt-get update && apt-get -y install build-essential`
* `./configure && make clean && make && make check` 

```
# cat /proc/cpuinfo inside the container
processor	: 9
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz
stepping	: 4
cpu MHz		: 3000.000
cache size	: 14080 KB
physical id	: 9
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 9
initial apicid	: 9
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc eagerfpu pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid dca sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch kaiser fsgsbase bmi1 hle avx2 bmi2 erms rtm avx512f avx512cd xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local arat
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 6180.66
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Error**:
```
../../build-aux/test-driver: line 107: 46990 Illegal instruction     "$@" > $log_file 2>&1
FAIL: pwhash_argon2i
../../build-aux/test-driver: line 107: 47014 Illegal instruction     "$@" > $log_file 2>&1
FAIL: pwhash_argon2id
```
Because building lib-sodium locally on macOS works fine, I can only guess, that the Linux build toolchain does some optimizations that let the tests fail.

I have tested with `debian:jessie`, `ubuntu:16.04` and both with gcc vs. clang. The problem persists.

Luckily my CI server is not that beefy and will happily build it (actually I was trying to install Ansible via pip).

This breaks for me a lot of seemingly totally unrelated stuff - i.e. building docker images with Ansible embedded (that will try to install PyNaCl that in turn tries to build lib-sodium from scratch).

**Comment by jedisct1** [comment]
Can you send a Mac Pro my way, so I can investigate this bug?

More seriously, I don't have any computer with such a modern CPU, so this will be difficult for me to replicate.

Can you try with a more recent operating system/distribution?

Old versions of clang didn't properly compile AVX512 opcodes, and that may also be the case with gcc.

`-stable` was updated with a check that disables AVX512 when using old gcc versions. Give it a spin, and feel free to reopen this ticket if it doesn't work, or if using a more current toolchain doesn't fix this either.
