### ISSUE TITLE
Implement support for sha512/224, sha512/256 algorithms

### ISSUE THREAD

**Issue by AnythingTechPro** [jedisct1/libsodium#777]
I have a project that uses sha256 to calculate hash outputs, however due to the nature of the sha256 algorithm and it’s 32bit math... Optimal performance is a downside to the sha256 hashing algorithm, I believe the sha512/256 truncated algorithm would work a lot more efficiently in this case. OpenSSL has recently implemented the algorithm, it would be a great feature to have in libsodium. 

OpenSSL implementation: 
https://github.com/openssl/openssl/commit/4bed94f0c11ef63587c6b2edb03c3c438e221604

**Comment by enkore** [comment]
Check #739

**Comment by jedisct1** [comment]
`crypto_hash()` is SHA512/256, or, rather, SHA512 truncated to 256 bits.

The main motivation for this was to avoid length-extension attacks, that the full-length functions are vulnerable to.

This motivation is not relevant any more, as all modern hash functions are not vulnerable to that kind of attack (that was a requirement for the SHA3 competition).

The default hash function in libsodium, accessible through `crypto_generichash()`, doesn't have this issue, let you choose the output size, supports an optional key (+salt and context) and is always faster than SHA512.

**Comment by enkore** [comment]
(There is SHA512/256 as in "FIPS SHA", which is both truncated and has a different IV, and then there is SHA512/256 as in "SHA512 but the output truncated to the first 256 bits" — the two are of course incompatible).

**Comment by jedisct1** [comment]
Hence "or, rather, SHA512 truncated to 256 bits".

The original NaCl library decided to use the same IV, and it's probably not worth adding the FIPS variant. BLAKE2 is now widely implemented. It is of course also present in OpenSSL.

**Comment by AnythingTechPro** [comment]
Thanks! Good to know.

**Comment by tarcieri** [comment]
In what case are you bottlenecked on SHA-256 where something SHA-512 based actually sufficiently improves performance to matter?

Regardless, the next generation of Intel CPUs will ship with SHA Extensions which will accelerate SHA-256 but not SHA-512. Before you go microoptimizing, keep this in mind: SHA-512 will soon be much, much slower relatively.

**Comment by enkore** [comment]
Ryzen already ships with these extensions.
