### ISSUE TITLE
Scalar multiplications

### ISSUE THREAD

**Issue by Oxmoze** [jedisct1/libsodium#780]
Hi,

It looks like it is possible to perform a scalar multiplication using the low level function `crypto_scalarmult_*()`.
But as far as I understand, it is only possible to do that over the X25519 curve and not other curves like `secp256k1` for example.

For those curves, I have the X,Y point of the receiver and the secret of the sender.

Is there a convenient way do compute that shared secret using libSodium?

**Comment by jedisct1** [comment]
Scalar multiplications can only be done over Curve25519 and Ed25519. There are no plans to support secp256k1 ever.
