### ISSUE TITLE
Argon2d vs Argon2i?

### ISSUE THREAD

**Issue by OlafvdSpek** [jedisct1/libsodium#781]
> Argon2 has three variants: Argon2d, Argon2i and Argon2id. 
> Argon2i uses data-independent memory access, which is preferred for password hashing and password-based key derivation. Argon2i also makes multiple passes over the memory to protect from tradeoff attacks. Argon2id combines both.

Argon2d isn't described. Is the first Argon2i supposed to be Argon2d?

https://libsodium.gitbook.io/doc/password_hashing

**Comment by jedisct1** [comment]
Argon2d is not implemented. Argon2i was the original recommendation from the Argon2 authors.

Then, Argon2id, which combines advantages of both Argon2i and Argon2d, replaced it.

**Comment by OlafvdSpek** [comment]
It's not clear what the `both` in `Argon2id combines both.` refers to.

**Comment by jedisct1** [comment]
Argon2id is half of the rounds with Argon2d and the other half with Argon2i.

From the [Argon2 RFC](https://www.ietf.org/archive/id/draft-irtf-cfrg-argon2-03.txt):

    The Argon2id variant with t=1 and maximum available memory is recommended as a default setting for all environments.
