### ISSUE TITLE
Problem while trying to prove an equation using scalar multiplication and point addition

### ISSUE THREAD

**Issue by thantsintoe** [jedisct1/libsodium#783]
Hi,

I would like to ask a question about scalar multiplication and point addition functions.

I am trying to prove `r x Pk == Pk + (r - 1) x Pk` where `r` is a scalar and `Pk` is a point on elliptic curve using `crypto_scalarmult_ed25519()` function for scalar multiplication and `crypto_core_ed25519_add()` function for point addition. However, I am getting different results from `r x Pk` and `Pk + (r - 1) x Pk`. My code is something like this. I used Node and `sodium-native` binding:
```
let pkBuf = Buffer.from('509b2d71922f726cce631ec3b6380ccb2583f72609400f6e02756819624896b3', 'hex')
if (!sodium.crypto_core_ed25519_is_valid_point(pkBuf)) throw new Error('Not a valid point on Elliptic Curve')

let v1 = Buffer.alloc(sodium.crypto_sign_PUBLICKEYBYTES)
let v2 = Buffer.alloc(sodium.crypto_sign_PUBLICKEYBYTES)
let r_minus_1xP = Buffer.alloc(sodium.crypto_sign_PUBLICKEYBYTES)

// generate a random integer
let randomNumber = Buffer.alloc(sodium.crypto_scalarmult_ed25519_SCALARBYTES)
sodium.randombytes_buf(randomNumber)

// use bignumber.js to calculate (r - 1)
let r = new BigNumber(randomNumber.toString('hex'), 16)
let rminus1 = r.minus(1)

// convert big number to buffer
let rBuf = Buffer.from(r.toString(16), 'hex')
let rminus1Buf = Buffer.from(rminus1.toString(16), 'hex')

// calculate v1 and v2
sodium.crypto_scalarmult_ed25519(v1, rBuf, pkBuf) // v1 = r x Pk
sodium.crypto_scalarmult_ed25519(r_minus_1xP, rminus1Buf, pkBuf)// (r - 1) x Pk
sodium.crypto_core_ed25519_add(v2, pkBuf, r_minus_1xP) // v2 = Pk + (r - 1) x Pk

console.log(v1.toString('hex')) // output -> 'f33ad8f293eb6f3a59c6072bcff5d2c26e3d93356d279adefa5c72a7cb22e424'
console.log(v2.toString('hex')) // output -> 'fc411af79156860f21cbc8a208c26ac3b30345eca50b2d8441e744654e643a80'
```
Is there something wrong with my implementation ? I noticed that scalar `r` will be clamped to make it a multiple of the cofactor before multiplication. Could it be the reason `r x Pk` and `Pk + (r - 1) x Pk` outputs different results ?

What could be the best way to compute `r x Pk` and `Pk + (r - 1) x Pk` such that results can be compared to be equal ?

Thanks.

**Comment by jedisct1** [comment]
`scalarmult()` computes `clamp(r).Pk`.

For your use case, you should rather use a prime-order group, Ristretto or the decaf variant.
