### ISSUE TITLE
Missing `ge25519_is_canonical` edge case?

### ISSUE THREAD

**Issue by justicz** [jedisct1/libsodium#784]
`ge25519_is_canonical` accepts both of the following encoded points as canonical:

`\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80`

and

`\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`

(note the flipped sign bit) even though both represent the point at infinity. This seems like it could be a bug to me -- or is this the expected behavior?

**Comment by jedisct1** [comment]
The public interface is `crypto_core_ed25519_is_valid_point()`, which always returns `false` for the point at infinity.

Internally, `ge25519_is_canonical()` is always used in combination with `ge25519_has_small_order()`.
