### ISSUE TITLE
Visual Studio configuration for AArch64

### ISSUE THREAD

**Issue by raddinet** [jedisct1/libsodium#787]
As MSVC, starting with version 15.9, now officially supports compiling for Windows 10 running on AArch64, I'd like to ask for a project configuration update to build DLL and static library for this architecture.

**Comment by jedisct1** [comment]
Does Visual Studio Community support this? I don't think so :(

**Comment by raddinet** [comment]
Can't confirm, I'm using Professional, but the announcement article doesn't mention the feature being edition-specific: https://blogs.windows.com/buildingapps/2018/11/15/official-support-for-windows-10-on-arm-development/

Either way, once my Windows 10 ARM laptop arrives I'll start tinkering with it myself, although I still would be way more confident if there was an authoritative configuration for a project like this. If it's indeed not supported by VS Community then perhaps I could submit pull request when (if) I get it working myself.

**Comment by jedisct1** [comment]
It doesn't seem to be present in the community edition :( And I wouldn't have any ways to test this, so this configuration cannot be officially supported for now.

**Comment by raddinet** [comment]
Understood. If my project receives any significant donation I'll get you a Windows ARM laptop and VS subscription :)

**Comment by raddinet** [comment]
Hi, I wanted to report that simply adding ARM64 build target is enough for MSVC to produce working AArch64 EXEs (or DLLs) of libsodium. I've not yet run the test suite, but my project that uses D-H (scalarmult), blake2b (generichash), aead_chacha20poly1305_ietf, sign_ed25519ph and some of the helper functions works flawlessly.

**Comment by jedisct1** [comment]
This is great news!
