### ISSUE TITLE
Restoring blake2s

### ISSUE THREAD

**Issue by ozaki-r** [jedisct1/libsodium#788]
Is there a chance to make blake2s back?

It is now used by WireGuard and if libsodium has it, we can implement WireGuard only using libsodium, which is pretty nice.

(I'm implementing WireGuard in the NetBSD kernel using libsodium.)

**Comment by jedisct1** [comment]
Nope, sorry.

**Comment by jedisct1** [comment]
I wrote a very small BLAKE2S implementation that you can use. It's a single `.c` file to include in your project: https://github.com/jedisct1/hashseq/tree/master/blake2s

**Comment by ozaki-r** [comment]
I see. I'll try to use it. Thanks.
