### ISSUE TITLE
Building a selectively featured / only what's needed (for my app) version of libsodium

### ISSUE THREAD

**Issue by NullVoxPopuli** [jedisct1/libsodium#792]
I'm doing a progressive-web-app, so every KB matters.
I'm not using any of the secret box or streaming ciphers, so I'm wondering if there is an easy way to choose what gets compiled, or if I should just start editing `src/libsodium/Makefile.in`?

thanks!

**Comment by NullVoxPopuli** [comment]
This file is gigantic -- is in auto-generated?

**Comment by jedisct1** [comment]
Yes, it's automatically generated.

If size is a concern, you should rather use [libhydrogen](https://libhydrogen.org) instead.

Or for something that uses JavaScript server-side and client-side, https://github.com/jedisct1/wasm-crypto may be a better fit.

**Comment by NullVoxPopuli** [comment]
I knew about libhydrogen but didn't know about wasm-crypto.
Both are very neat projects!

Though, do they do box encryption? I see that they mention Ed25519, but I don't explicitly see anything saying that support the public box family of algorithms

**Comment by NullVoxPopuli** [comment]
built and gzipped wasm-crypto:
![image](https://user-images.githubusercontent.com/199018/50305832-0e9d3280-0462-11e9-945e-a2ac9461183f.png)

very nice!

**Comment by jedisct1** [comment]
And some protocols that can be built using wasm-crypto cannot be built using libsodium yet, except using development code.

wasm-crypto still lacks documentation and high-level TypeScript wrappers; these will be added soon. Feel free to help :)

**Comment by NullVoxPopuli** [comment]
I may poke around during my Christmas break if/when I have downtime. Been wanting to _actually_ see how WASM works anyway :)
