### ISSUE TITLE
crypto_generichash_statebytes() rounding up unecessary?

### ISSUE THREAD

**Issue by cakoose** [jedisct1/libsodium#793]
https://github.com/jedisct1/libsodium/blob/fdeb11d81c6024960e12bc1bb0975e78bd30e7b1/src/libsodium/crypto_generichash/crypto_generichash.c#L47-L51

Why is it rounding up?  `crypto_generichash_state` is marked as having 64-byte alignment, so doesn't `sizeof` already round up for us?

**Comment by jedisct1** [comment]
The C language doesn't have any ways to specify alignment. This is a compiler extension, so the `CRYPTO_ALIGN()` macro can be a no-op.

**Comment by cakoose** [comment]
Ah yeah, I wondered if that might be the issue.

What's libsodium's stance on compilers that don't support the extension?  Does libsodium still try to work correctly?  If so, maybe libsodium should expose a constant or function that returns the alignment requirements for each structure?
