### ISSUE TITLE
Cannot compile when using macOS' libtool

### ISSUE THREAD

**Issue by theodelrieu** [jedisct1/libsodium#795]
Hello,

I'm currently trying to migrate from using `ar` + `ranlib` to macOS' `libtool`. (For the exact reason why, you can see https://github.com/conan-community/community/issues/76).

Unfortunately it is not a drop-in replacement, for example one must pass the `-o` flag, whereas `ar` just takes the first argument without any dash-option.

I saw in your `Makefile` that this was already handled:

```makefile
libavx2_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(libavx2_la_LDFLAGS) $(LDFLAGS) -o $@
```

However, I get the following error at link time:

>error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no output file specified (specify with -o output)

I patched the `libtool` script generated by autotools to print the archiver invocation:

>/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool cru .libs/libsse41.a crypto_generichash/blake2b/ref/libsse41_la-blake2b-compress-sse41.o~/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib .libs/libsse41.a

As you can see, it tries to use `AR_FLAGS`.

I saw in the script's code that there is a code path for shared libraries (using correct libtool arguments) and another one for static libraries (referred to as `old archive`, and using `ar`).

So I tried to set custom `AR_FLAGS` with `-static -o` to emulate `ar` behavior.
It worked until linking `libsodium.la`, because of the line 3725 in `ltmain.sh`:

```shell
    func_show_eval "(cd \$f_ex_an_ar_dir && $AR x \"\$f_ex_an_ar_oldlib\")" \
		   'stat=$?; rm -f "$lockfile"; exit $stat'
```

That explicit `$AR x` part just breaks `libtool`, additionally there is no way to extract an archive with `libtool` (from what I've read in the man page at least),.

---

I'd like to know why there are two different code paths for static/shared libs, why not using libtool for both?

I could not check if only building shared libs works, since it still built `.la` files (even if I gave `--disable-static --enable-shared` to `configure`). Do you know if there is a simple solution to this? My autotools skills are very low, so I might have missed something obvious.

**Comment by jedisct1** [comment]
You don't need any `libtool` installed at all.

Just download a release or use the `stable` branch.

**Comment by theodelrieu** [comment]
Sorry I should have detailled my problem more, I'm using the 1.0.16 release, and I wish to cross-build it for iOS.

For that purpose I use a cross-build toolchain which sets `libtool` as archiver (it is required to build `Boost`, I cannot simply replace it with `ar`). I simply wish to use a different archiver than the one used by the Autotools scripts.

Note that Apple recommends using `libtool` instead of `ar`/`ranlib`, here is what the `libtool` man page says on macOS:

>Libtool with **-static** is intended to replace ar(5) and ranlib.

**Comment by jedisct1** [comment]
To compile for iOS, you can run the `ios.sh` script present in the [`dist-build`](https://github.com/jedisct1/libsodium/tree/master/dist-build) directory. There is also a similar script for watchOS. None of these require `libtool`.

**Comment by theodelrieu** [comment]
The thing is I am not looking at this from the regular user point of view, but rather as a packager. Long story short I'm writing a Conan package which helps cross-building to every Darwin platform (iOS, macOS, watchOS and tvOS).

One of the main advantages of it is that libraries do not have to provide custom scripts for X or Y platform, just relying on `CFLAGS`, `LDFLAGS` is enough for the vast majority of cases.

I use a similar package to cross-build for Android, and at my work we did build `libsodium` by using the regular `configure && make` way.

Anyway, I guess it will be easier to stop trying using a different archiver, and fix the original problem that made me try in the first place.

Thanks for your time.
