### ISSUE TITLE
core_ed25519 - Assertion failed: sodium_is_zero; master (1.0.17?)

### ISSUE THREAD

**Issue by plluksie** [jedisct1/libsodium#797]
Hello,
 I tried to compile and check the library on SmartOS for master branch. Except the issue with memory fault on randombytes, there is a failure for core_ed25519. Please see attached script file for the details. 
Excerpt:
```
$ more test/default/core_ed25519.log 
Assertion failed: sodium_is_zero(sc3, crypto_core_ed25519_SCALARBYTES), file core_ed25519.c, line 303, function xmain
FAIL core_ed25519 (exit status: 262)
```
 I performed this test using:
`--without-threads --disable-shared  --without-pic`

Using:
`--with-threads --enable-shared --with-pic`
I'm able to build the library and there is no issue with test
[libsodium_master_w-thread_ena-shared_w-pic.log](https://github.com/jedisct1/libsodium/files/2730851/libsodium_master_w-thread_ena-shared_w-pic.log)
[libsodium_master_wo-thread_dis-shared_wo-pic.log](https://github.com/jedisct1/libsodium/files/2730852/libsodium_master_wo-thread_dis-shared_wo-pic.log)

.

**Comment by jedisct1** [comment]
The lines in the error message don't match with the current code, so I think this has been fixed since.

Feel free to reopen if it still happens on `stable`.
