### ISSUE TITLE
libsodium-1.0.16 and 1.0.17

### ISSUE THREAD

**Issue by kille72** [jedisct1/libsodium#798]
We cannot get dnscrypt to work together with libsodium-1.0.16 & 1.0.17 in the Tomato project. No errors in the compilation, everything works but not dnscrypt, with version 1.0.15 there is no problem and everything works perfectly.

Tomato source: https://bitbucket.org/kille72/freshtomato-arm/commits/all

What information do you need, which logs etc?

Thanks for your work!

**Comment by jedisct1** [comment]
Hi,

What exact software are you talking about? dnscrypt-wrappers maybe?

Can you clarify what you mean by "work"?

**Comment by jedisct1** [comment]
The major library version changed between version 1.0.15 and 1.0.16, so you need to recompile software that was compiled and linked against an old version.
