### ISSUE TITLE
Add linux-arm in your NuGet Package

### ISSUE THREAD

**Issue by p3root** [jedisct1/libsodium#801]
Could you add a built version for linux-arm  of your library to the nuget package?´

Cheers,
root

**Comment by jedisct1** [comment]
I have absolutely no idea how to do that, as I don't use either.

Can you send a pull request with the required changes to build this along with the rest?

**Comment by p3root** [comment]
I can provide you a built version of the library. Who makes and deploys the nuget package?

**Comment by jedisct1** [comment]
They are built by the `packaging/dotnet-core/prepare.py` script.

**Comment by p3root** [comment]
So I assume you don't have a CI/CD? When using Azure DevOps for example, we could build linux-arm, linux-x64 and linux-x86 versions of the lib.

**Comment by jedisct1** [comment]
For CI, every change automatically runs via Travis.

CD, no, I don't deploy this anywhere.

But the script can certainly be changed to cross-compile it for arm and add the result to the Nuget package. Give it a try :)
