### ISSUE TITLE
Problems with __attribute__((nonnull))

### ISSUE THREAD

**Issue by ivmaykov** [jedisct1/libsodium#803]
Hi Frank,

I am trying to upgrade our libsodium dependency from 1.0.13 to the recently released 1.0.17, and am running into a bunch of UBSAN failures related to the `__attribute__((nonnull))` tags that have been added to many of libsodium's public API methods sometime between the two releases. None of these UBSAN failures are real bugs, since the null pointer is always accompanied by a 0 length and therefore the called function never attempts to read from it. The fixes are cumbersome, since I have to turn code that looks like this:

`sodium_memzero(array_.data(), array_.size());`

into this:

```
if (array_.size() > 0) {
  sodium_memzero(array_.data(), array_.size());
}
```

Similar issues exist with `sodium_memcmp()`, `sodium_bin2hex()`, `sodium_hex2bin()`, and likely others.

In the worst case, in code that computes blake2b hashes of buffers and allows them to be empty, we end up with ugliness like this:

```
  // If in is empty, in.data() might be null. This triggers UBSAN failures
  // because the argument to the blake2b function is marked with the nonnull
  // attribute. So if in.size() is 0, use a different pointer which is
  // guaranteed to be not null as the input. It doesn't matter, because when
  // the input size is 0, no data is actually read from the pointer anyway.
  const uint8_t* const inptr = in.size() == 0 ? hash.data() : in.data();
  int result = crypto_generichash_blake2b_salt_personal(
      hash.data(),
      hash.size(),
      inptr,
      in.size(),
      /* key = */ nullptr,
      /* keylen = */ 0,
      get_salt().data(),
      /* personal = */ nullptr);
```

It definitely makes sense to tag pointer arguments which don't have a corresponding length and are non-optional with the `nonnull` attribute (such as the salt parameter to `crypto_generichash_blake2b_salt_personal()`, but is it expected that ready-only pointer arguments with a corresponding length must be `nonnull`? It seems like if the length is 0 then the pointer will never be read and it's ok for it to be null, and this was the case in earlier versions of libsodium. It's quite a bit of work to find all call sites in our rather large code base and make sure all of them do the size check before calling a libsodium function, so I'm wondering if the current behavior will persist, or if some of the `nonnull` attributes might get removed in the future. Please let me know what you think, thanks!

**Comment by jedisct1** [comment]
Thanks Ilya!

Adding these attributes is a boring and tedious task, and I probably got some of these wrong.

For empty messages, it makes sense to accept a `NULL` pointer, so the attribute can be relaxed here. This property doesn't hold true for `memcpy()` and friends, so this would just be moving the extra `NULL` checks in the library itself, but that makes more sense than at application level.

I'll try to find some time to review all these functions again, but your help would also be more than welcome :)

**Comment by jedisct1** [comment]
Passing `NULL` to `sodium_memcmp()` is a little bit debatable, though. I see more opportunities for that being due to a bug than a valid use case.

**Comment by ivmaykov** [comment]
> Passing `NULL` to `sodium_memcmp()` is a little bit debatable, though. I see more opportunities for that being due to a bug than a valid use case.

If size is 0 then it's valid. I'm pretty sure that would be consistent behavior with libc's `memcmp`. But could always do something like this:

```
// Public API declaration
SODIUM_EXPORT
int sodium_memcmp(const void * const b1_, const void * const b2_, size_t len)
    __attribute__ ((warn_unused_result));

// Private API declaration, not exported
int _sodium_memcmp(const void * const b1_, const void * const b2_, size_t len)
    __attribute__ ((warn_unused_result)) __attribute__((nonnull));

// Implementation of public API
int sodium_memcmp(const void * const b1_, const void * const b2_, size_t len) {
  if (len == 0) {
    return 0;
  }
  return _sodium_memcmp(b1, b2, len);
}
```

**Comment by ivmaykov** [comment]
In fact, at the cost of having to write a bunch of boring boilerplate code, this could be done for many of the public API functions that take (pointer, length) pairs. Would be nice if there was a way to express "argument X must be nonnull when argument Y is non-zero" via attributes but I don't think that exists.

**Comment by ivmaykov** [comment]
I can put up a PR with some fixes, it likely won't be comprehensive - I will just fix the APIs that are used from our code, since I have an easy way to test those fixes.

**Comment by jedisct1** [comment]
Unfortunately, "argument X must be nonnull when argument Y is non-zero" cannot be expressed as far as I know (at least not in C). The way C solved it in the standard library is by making `NULL` pointers with a `0` length an undefined behavior. Which isn't great :(

**Comment by ivmaykov** [comment]
> Unfortunately, "argument X must be nonnull when argument Y is non-zero" cannot be expressed as far as I know (at least not in C). The way C solved it in the standard library is by making `NULL` pointers with a `0` length an undefined behavior. Which isn't great :(

Huh, I did not realize that was UB. So you mean the following code is UB?

```
int foo = 42;
int res = memcmp(&foo, NULL, 0);
```
According to `man memcmp`, "zero-length strings are always identical" so I think this is defined, at least in this case. Do you have any examples of libc functions where passing `(NULL, 0)` results in UB?

**Comment by jedisct1** [comment]
https://en.cppreference.com/w/c/string/byte/memcmp - "The behavior is undefined if access occurs beyond the end of either object pointed to by lhs and rhs. The behavior is undefined if either lhs or rhs is a null pointer". (I'm too lazy to look at the exact reference in the standard, but this is explicitly mentioned).

Ditto for pretty much everything in `<string.h>`. The justification here is that, for example, a compiler can emit code that loads one or more bytes first, and decides how many of these bytes to copy next.

In libhydrogen, variable-size copies/comparisons/etc. use reimplementations of these basic functions with simple loops in order to prevent this kind of UB. Compilers usually get the pattern and replace these with calls to the standard functions if this is safe. Unfortunately, this is not always the case.

**Comment by ivmaykov** [comment]
> The justification here is that, for example, a compiler can emit code that loads one or more bytes first, and decides how many of these bytes to copy next.

Wow, that seems a bit insane. What if len = 1, but the compiler preloads >1 bytes? And what if that ends up crossing a page boundary, and the next page is not mapped? I'm sure they've thought this through, but it still seems like a crazy optimization. TIL.

Anyway, I'm almost done with the PR, will put it up soon. You will probably reject at least half of it :)

**Comment by ivmaykov** [comment]
See #804
