### ISSUE TITLE
Support for .NET 3.5

### ISSUE THREAD

**Issue by mlhDevelopment** [jedisct1/libsodium#805]
The libsodium Nuget package contains a dependency to Microsoft.NETCore.Platforms which targets .NET Standard framework 1.1. I cannot tell why Platforms is needed but this dependency blocks .NET 3.5 framework from referencing libsodium (via libsodium-net, [issue #172 in that repo](https://github.com/adamcaudill/libsodium-net/issues/172) ). Is it possible to remove or refactor that dependency so .NET 3.5 is supported?

**Comment by ektrah** [comment]
No, .NET Framework 3.5 isn’t supported. The cause isn’t the dependency but that older .NET Framework versions cannot pick up native libraries from NuGet packages.

**Comment by mlhDevelopment** [comment]
I started using the nuget package [Liphsoft.Crypto.Argon2](https://www.nuget.org/packages/Liphsoft.Crypto.Argon2/) which comes from [csharp-argon2](https://github.com/alipha/csharp-argon2/) and I was able to at least get unit tests against my 3.5 library working. It may be 'cheating' (it just creates a target to copy the dll to the bin folder upon build, then uses `[DllImport]` methods to call into it) and I don't know if that is compatible or comparable to libsodium's goals & agenda, but it was an alternative at the least.

**Comment by ektrah** [comment]
That 'cheat' is an endless source of trouble and something that is best avoided. Luckily, .NET Core and  recent versions of .NET Framework have built-in support, so the workaround is no longer needed.

**Comment by mlhDevelopment** [comment]
Fair enough. I'm stuck maintaining a 3.5 web site solution so hacks are a part of my normal routine. Closing as wontfix.
