### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by 0fork** [jedisct1/libsodium#806]
I ran FOSSA on my libraries that use libsodium and got a warning that a lot of files here are licensed under GPL-2.0. For example, https://github.com/jedisct1/libsodium/blob/master/m4/ax_check_compile_flag.m4.

The main library is licensed under ISC so I'm wondering that doesn't GPL-2.0 on those /m4/ files force the license to be GPL-compatible?

**Comment by jedisct1** [comment]
These files are not part of the library and are not required to build the library. This is similar to using GCC to build BSD code. But IANAL and this is probably not the best place to ask about licensing issues.
If this is an issue, you may want to consider libhydrogen instead.
