### ISSUE TITLE
NAAEADNonceSize change

### ISSUE THREAD

**Issue by Zara-Digital** [jedisct1/libsodium#807]
crypto_aead_chacha20poly1305_NPUBBYTES has changed from 12U to 8U. May I know how do I get back the same value?

**Comment by jedisct1** [comment]
I think you are confusing `crypto_aead_chacha20poly1305_ietf_*()` and `crypto_aead_chacha20poly1305_*()`.

See [this page](https://download.libsodium.org/doc/secret-key_cryptography/aead) for the difference betweens these constructions, and other AEADs.
