### ISSUE TITLE
Generating random numbers of uint32_t result in negative outputs?

### ISSUE THREAD

**Issue by AnythingTechPro** [jedisct1/libsodium#809]
It seems that when i try to generate a random number using both functions of the random utilities randombytes_random and randombytes_uniform the result can be a negative even though the type is casted to a uint32_t which has a range of 0, 4,294,967,295. Any thoughts on this?

**Comment by enkore** [comment]
If your variable is unsigned, it is technically unable to represent negative numbers.

If your variable is unsigned, and you are using something like printf for printing it, make sure you are using the correct format specifier. `%d` is `int`. You would need to use '%u' for unsigned. '%d' would interpret the MSB of the unsigned integer as the sign bit.

**Comment by AnythingTechPro** [comment]
Just figured out the issue, seems i had switched unsigned and signed values in my codebase, sorry for the inconvenience, thanks.

**Comment by jedisct1** [comment]
You should actually use `"%" PRIu32` to format `uint32_t` values.

```c
#include <inttypes.h>

printf("%" PRIu32 "\n", randombytes_random());
```

**Comment by enkore** [comment]
True! "unsigned" is not necessarily the same width as uint32_t and so the actual required formatter might be different. (%u for uint32_t acts "somewhat portable", since it works on both LP64, LLP64 and most 32 bit environments, but still - not correct).
