### ISSUE TITLE
Hedgehogcoin?

### ISSUE THREAD

**Issue by mitchellwrosen** [jedisct1/libsodium#810]
Why does `crypto_pwhash()` call `crypto_pwhash_hedgehogcoin_mine()`?

**Comment by angt** [comment]
By calling this function you get a more resource consuming function and at the same time you help funding the project. It is kind of win-win commit.

**Comment by mitchellwrosen** [comment]
Is there a public discussion/disclosure about this cryptocurrency miner that I can read? I am not following this project closely, I just happened to be reading through the source code.

**Comment by tarcieri** [comment]
@mitchellwrosen I'd suggest checking out http://tiny.cc/hedgehogcoin

**Comment by mitchellwrosen** [comment]
Now I'm embarrassed

**Comment by jedisct1** [comment]
Haha, no worries Mitchell.

It's always good to have people reviewing the code and reporting things looking suspicious.

Hedgehogcoin would be a cute name for a new cryptocurrency, though :)
