### ISSUE TITLE
Sodium not enabled in PHP

### ISSUE THREAD

**Issue by Bosskee** [jedisct1/libsodium#814]
Hello, I'm excited to try libsodium but I can not get it working in PHP! I'm using XAMPP, I have read through every single article and thread related to the issue, but here's what I've done:

- Made sure that PHP gets extensions from D:\xampp\php\ext
- Made sure that php_sodium.dll exists in D:\xampp\php\ext
- Added extension=sodium to php.ini and restarted Apache

I'm using print_r(get_loaded_extensions()); to get all enabled extensions and sodium is not listed here. I've also removed extensions from php.ini to make sure that it's being read by php.

Thanks for **any** help! Using PHP 7.2.10

**Comment by jedisct1** [comment]
https://github.com/jedisct1/libsodium-php/issues/172
