### ISSUE TITLE
Generate plain text keys?

### ISSUE THREAD

**Issue by Bosskee** [jedisct1/libsodium#815]
Hello!

I finally got libsodium working, but I have one question. The keys that are generated right now look something like this: "&w��x�QK��|D���z�����", they're unreadable. I would need to have the keys be in plaintext so that I can send them back to the user in a proper way. Maybe a key that looks something like this: "aHJj8kd9Jbf7N6d3BD"

I'm using this function:
```
?php
declare(strict_types=1);

/**
 * Encrypt a message
 * 
 * @param string $message - message to encrypt
 * @param string $key - encryption key
 * @return string
 * @throws RangeException
 */
function safeEncrypt(string $message, string $key): string
{
    if (mb_strlen($key, '8bit') !== SODIUM_CRYPTO_SECRETBOX_KEYBYTES) {
        throw new RangeException('Key is not the correct size (must be 32 bytes).');
    }
    $nonce = random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);

    $cipher = base64_encode(
        $nonce.
        sodium_crypto_secretbox(
            $message,
            $nonce,
            $key
        )
    );
    sodium_memzero($message);
    sodium_memzero($key);
    return $cipher;
}

/**
 * Decrypt a message
 * 
 * @param string $encrypted - message encrypted with safeEncrypt()
 * @param string $key - encryption key
 * @return string
 * @throws Exception
 */
function safeDecrypt(string $encrypted, string $key): string
{   
    $decoded = base64_decode($encrypted);
    $nonce = mb_substr($decoded, 0, SODIUM_CRYPTO_SECRETBOX_NONCEBYTES, '8bit');
    $ciphertext = mb_substr($decoded, SODIUM_CRYPTO_SECRETBOX_NONCEBYTES, null, '8bit');

    $plain = sodium_crypto_secretbox_open(
        $ciphertext,
        $nonce,
        $key
    );
    if (!is_string($plain)) {
        throw new Exception('Invalid MAC');
    }
    sodium_memzero($ciphertext);
    sodium_memzero($key);
    return $plain;
}
```

**Comment by jedisct1** [comment]
The PHP extension is a different project, whose repository is here: https://github.com/jedisct1/libsodium-php

Keys are fixed-size binary blobs. They're not passwords and are not designed to be printed. Just like printing an `MP3` file would not be very useful. You're supposed to read and write them as binary data.

**Comment by jedisct1** [comment]
Not sure why you are encoding everything as base64. PHP can handle binary data, even in its `string` type.

**Comment by Bosskee** [comment]
> Not sure why you are encoding everything as base64. PHP can handle binary data, even in its `string` type.

Which method would be better?

**Comment by jedisct1** [comment]
No encoding is needed. PHP strings can store anything, even a JPG image.
