### ISSUE TITLE
make check 56/72 fails on macOS Mojave 10.14.4

### ISSUE THREAD

**Issue by mlg556** [jedisct1/libsodium#818]
I am using a macOS Mojave 10.14.4 system with 
```
uname -a
Darwin oolonmac.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```
```
make -v
GNU Make 4.2.1
Built for x86_64-apple-darwin18.2.0
```
 and
 ```
gcc -v
gcc version 8.2.0 (Homebrew GCC 8.2.0)
```

on `libsodium-1.0.16`, `make check` passes some test and fails on others like

```
PASS: verify1
PASS: sodium_utils2
PASS: sodium_utils3
../../build-aux/test-driver: line 107: 32069 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: core_ed25519
../../build-aux/test-driver: line 107: 32088 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: pwhash_scrypt
../../build-aux/test-driver: line 107: 32107 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: pwhash_scrypt_ll
../../build-aux/test-driver: line 107: 32126 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: scalarmult_ed25519
============================================================================
Testsuite summary for libsodium 1.0.16
============================================================================
# TOTAL: 72
# PASS:  16
# SKIP:  0
# XFAIL: 0
# FAIL:  56
# XPASS: 0
# ERROR: 0
```

Attached is [test-suite.log](https://github.com/jedisct1/libsodium/files/3104860/test-suite.log)

**Comment by jedisct1** [comment]
Can you:

1) Use the current stable version (1.0.17-stable). Version 1.0.16 doesn't receive any updates any more.
2) Describe all the exact steps to reproduce this. Homebrew will never add `/usr/local/opt/gcc/bin` to the `PATH`, expecting you to define `CC=gcc-8` instead. I wasn't able to reproduce this by installing `gcc` from Homebrew, and defining `CC` or temporarily changing to path to add `/usr/local/opt/gcc/bin` to it.
3) Attach the `config.log` file.

Thanks!

**Comment by mlg556** [comment]
Apologies for the confusion about `gcc`, I had manually symlinked it to the brew version, so in `usr/local/bin` there is a `gcc@ -> /usr/local/Cellar/gcc/8.2.0/bin/gcc-8`.

I have downloaded and installed 1.0.17-stable, now the output of `make check` is 
```
(...)
============================================================================
Testsuite summary for libsodium 1.0.17
============================================================================
# TOTAL: 75
# PASS:  16
# SKIP:  0
# XFAIL: 0
# FAIL:  59
# XPASS: 0

# ERROR: 0
```
Taking a peek at the attached config.log, is looks like it indeeds sees the Homebrew version.
Attached are [config.log](https://github.com/jedisct1/libsodium/files/3105121/config.log) and [test-suite.log](https://github.com/jedisct1/libsodium/files/3105123/test-suite.log)

**Comment by mlg556** [comment]
I have also tried to unlink gcc and install the latest CommandLineTools for macOS, so now
```
gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Reinstalling libsodium once again, here is the `make check` output
```
============================================================================
Testsuite summary for libsodium 1.0.17
============================================================================
# TOTAL: 75
# PASS:  20
# SKIP:  0
# XFAIL: 0
# FAIL:  55
# XPASS: 0
# ERROR: 0
```
Attached is the new [config.log](https://github.com/jedisct1/libsodium/files/3105158/config.log)

**Comment by mlg556** [comment]
Confusing.. I have reinstalled the library and now all seem to be okay. I guess it is not a good idea to mix-up brew gcc and CommandLineTools. I think we can close the issue, thank you for your time and suggestions.
