### ISSUE TITLE
Public and private keys to KeySec

### ISSUE THREAD

**Issue by rcamparoML** [jedisct1/libsodium#819]
Is there any way to convert public and privates keys generated from a sealed box to KeySec ? I need to store the private key in the keychain and I can't find the way.
I trying to create a KeySec using this [method](https://developer.apple.com/documentation/security/1643701-seckeycreatewithdata) 
Thanks in advance :)

**Comment by jedisct1** [comment]
This is more of an Objective C programming question than a libsodium question.

But in the method you link, a key is simply represented as a `CFData` object. So you can use `CFDataCreate()` to create such an object from a pointer and length.
