### ISSUE TITLE
Some problems when using static link for KMDF windows driver project

### ISSUE THREAD

**Issue by GreatFireWall** [jedisct1/libsodium#822]
My project is KMDF windows kernel mode driver project.

First, I add header files in my project like this:

![image](https://user-images.githubusercontent.com/4510984/56747638-ee370900-67b0-11e9-905f-ac3ce966cc26.png)

Then add lib files to here: `Configuration Properties => Linker => Input => Additional dependencies`

![image](https://user-images.githubusercontent.com/4510984/56747956-7ddcb780-67b1-11e9-982a-2f55e303fe3c.png)

Note that I rename them append with `32` and `64` for condition build.

![image](https://user-images.githubusercontent.com/4510984/56748146-e461d580-67b1-11e9-8157-d62637016726.png)

Now I simply add some test codes and try build my project:
```c
#include "ThirdParty/libsodium/sodium.h"
...
NTSTATUS DriverEntry( ... ) {
    ...
    int status = sodium_init();
    ...
}
...
```

But get some building errors about `stdint.h` not found.

OK, `stdint.h` is not include for driver project in default. I include those headers in `Configuration Properties => VC++ Directories => Include Directories` like this:

![image](https://user-images.githubusercontent.com/4510984/56748743-f1cb8f80-67b2-11e9-9f3f-b979880370ca.png)

Now, the building errors solved. But get a link warning: 

```libsodium64.lib(core.obj) : warning LNK4257: linking object not compiled with /KERNEL ; image may not run```

### My question is:

**Is it safe to ignore this warning ? Or is there another solution ?**

**Comment by GreatFireWall** [comment]
Unfortunately, I read the sources and found some `malloc` call, that means it's **not** out of box in kernel driver. 

So I consider use [CNG](https://docs.microsoft.com/zh-cn/windows/desktop/SecCNG/cng-portal) instead of it.

**Comment by jedisct1** [comment]
Memory allocation is only required if you explicitly call `sodium_malloc()` or for password hashing functions.

**Comment by GreatFireWall** [comment]
Does `sodium_malloc()` depends user-mode paged memory ? I read the source code of `sodium_malloc()`, but I didn't understand it. 

In the other words, is it means I can define a `malloc` macro for different platform like this ?

```c
#if WINDOWS_DRIVER
    #define MALLOC( ... ) ExAllocPoolWithTag( ... )
#else
    #define MALLOC( ... ) malloc( ... )
#endif
```

**Comment by jedisct1** [comment]
`sodium_malloc()` is not used internally. So, unless your driver uses it, you don't need it.

**Comment by GreatFireWall** [comment]
I had try build `libsodium` with `/kernel` option, link in my project, the warning `LNK4257` disappear, but a lot of link error about `abort` `malloc` etc.. and the `#define TLS __declspec(thread)` macro. They're not avaliable in kernel. 

It seems to not kernel-friendly, I have to spend a lot of time modifying these incompatible calls. But my project is on schedule. So I give up. 😢
