### ISSUE TITLE
build: bazel.build

### ISSUE THREAD

**Issue by rynz** [jedisct1/libsodium#824]
Is this something libsodium would like implemented?

**Comment by rynz** [comment]
@jedisct1 https://github.com/iotaledger/rules_iota/blob/master/build/BUILD.libsodium has an example of how they are building `libsodium`. What's your opinion on this approach and would it be worthwhile implementing this?

**Comment by jedisct1** [comment]
The compile-time checks currently being done are all here for a reason.

Without them, compilation will break, including on supported system, performance may not be great, or the functions may not behave as expected.

The test and benchmark suite is also here for a reason.

Removing all of these to simply compile `*.c` is not a good idea, and a clear regression over what we currently have.
