### ISSUE TITLE
BLAKE2B-160, BLAKE2B-256, BLAKE384, & BLAKE512 Support

### ISSUE THREAD

**Issue by bingchengWong** [jedisct1/libsodium#826]
Dear developer, I would like to find out if libsodium support the following hash format of BAKE2B-160, BLAKE2B-256, BLAKE384, & BLAKE512.  If it supports, may I know what are the keys and key length required as the input for the crypto_generichash function to generate the same result. I have attached a link below to an online BLAKE2B calculator for your references. Link: https://8gwifi.org/MessageDigest.jsp

**Comment by jedisct1** [comment]
`crypto_generichash()` supports arbitrary output sizes, from 128 to 512 bits.

**Comment by jedisct1** [comment]
Ditto for the key size. It supports any key size, from 128 to 512 bits.

**Comment by jedisct1** [comment]
Relevant documentation: https://download.libsodium.org/doc/hashing/generic_hashing
