### ISSUE TITLE
Looking for ristretto

### ISSUE THREAD

**Issue by Warchant** [jedisct1/libsodium#827]
Documentation [says](https://download.libsodium.org/doc/advanced/point-arithmetic/ristretto#note) ristretto is introduced in libsodium 1.0.18, but github's [release page](https://github.com/jedisct1/libsodium/releases) shows that latest is 1.0.17. 

Is 1.0.18 released at all?

**Comment by jedisct1** [comment]
Version 1.0.18 hasn't been released yet. You can give the current development code a try, but the actual release will probably be in 3 or 4 weeks.

**Comment by ivmaykov** [comment]
Cc @kevinlewi
