### ISSUE TITLE
Verification of Blake2 result

### ISSUE THREAD

**Issue by bingchengWong** [jedisct1/libsodium#828]
Dear developer, I noticed that it is possible to hash a plain text using blak2 algo without a key. However, Is there a way to verify the digest message generated? Thank you.

Relevant documentation: https://download.libsodium.org/doc/hashing/generic_hashing

**Comment by bingchengWong** [comment]
I would like to find out if there is a way to validate the generated blake2 digest when no key is used. To add on, what I am suggesting is a blake2b_selftest function. I have attached a link to the self-test function for your references. Link: https://tools.ietf.org/html/rfc7693#appendix-E

**Comment by sbredahl** [comment]
@bingchengWong: Why not use the test values from https://en.wikipedia.org/wiki/BLAKE_(hash_function) ? These are without key and match the output from libsodium.
