### ISSUE TITLE
Libsodium differential fuzzing at Google OSS-Fuzz

### ISSUE THREAD

**Issue by guidovranken** [jedisct1/libsodium#829]
Hello,

I've built a [differential cryptography implementation fuzzer](https://github.com/guidovranken/cryptofuzz) and it has been running for a few weeks on Google [OSS-Fuzz](https://github.com/google/oss-fuzz). It has so far found an impressive +/- [20 bugs in OpenSSL, LibreSSL and BoringSSL](https://github.com/guidovranken/cryptofuzz#hall-of-fame).

I've already implemented libsodium support and will merge it into OSS-Fuzz soon. What it does is both find memory bugs (with the sanitizers) and compare the results against other libraries, like OpenSSL, to find incorrect implementations.

If you, the maintainer, would like to get automated bug reports mailed to you, please let me know and I'll add you to the project's CC's. If you decline, that's fine, and I'll manually report bugs in libsodium to you.

**Comment by jedisct1** [comment]
Hi,

This is great, and can be a good addition to `libsodium-validation`.

Sure, I'd love to get the reports. Send them to `github `[@at@]` pureftpd `[.]` org`.

Thanks!
