### ISSUE TITLE
Feature request: (partially) blind signatures

### ISSUE THREAD

**Issue by njor** [jedisct1/libsodium#831]
Hello,

First thank you for all the work in maintaining this library and making it as easy as possible to understand and use (and hard to misuse) for non-cryptographers.

Is there any plan to implement blind signature schemes or even partially blind signature ? These could be useful for a number of common use cases, like voting, custom cryptocurrency, or allowing truly anonymous and untraceable communication between users of an application while still preventing resource abuse…

If there are currently no plans to add these to libsodium, do you have any pointers to resources on that subject that would be understandable by a non cryptographer, and (in the same way) minimize the risk of misuse ?

Thank you.

**Comment by jedisct1** [comment]
These may eventually be implemented in wasm-crypto, but there are no plans to add this to libsodium. 

However, the public libsodium API already provides all the building blocks to implement this. And Schnorr blind signatures are quite easy to implement.

Matthew Green wrote a good intro to this: https://blog.cryptographyengineering.com/a-note-on-blind-signature-schemes/

This presentation also presents them in a very comprehensive way: https://nickler.ninja/slides/2018-bob.pdf

**Comment by njor** [comment]
Thank you for the pointers, I will read that (and try to understand it).
