### ISSUE TITLE
Hex encoded ECDSA keypair for Sealed box ecnryption

### ISSUE THREAD

**Issue by christianzammit1989** [jedisct1/libsodium#834]
Hey, 

Not sure if this is possible, however in my use case I have a hex encoded ECDSA keypair in strings (generated elsewhere, such as shown underneath) and want to use the public key together with the crypto_box_seal method to encrypt a byte array, while of course be able to use its corresponding private key to decrypt (again which is in a hex encoded string format). Is this achievable? If so how?

Note that I'm relatively new to c++ and any help would be greatly appreciated.

Thanks

Private Key: 0xb2f52c44ba9810af1b39f81c6450d4ad4f67791df9f89900c462470b842c7d90

Public Key: 0x048159e68ae71717c4b6a455de7ab1fc1a9de70bcc735deb7895b0acbf577e0aa50fa458691c3af8fb0285109e0610e6db452fb12623a95291d391c8c1dabcdce4

**Comment by enkore** [comment]
crypto_box_seal use X25519 and those are not X25519 keys.

**Comment by christianzammit1989** [comment]
Oh I see. Thanks for clearing that up. So say I want to use the sealed box encryption using X25519 keys (which following the documentation I managed), how can I export and import the keys as strings for distribution or storage purposes? Looked at the helper methods but to be honest was unable to follow 100%.

**Comment by paragonie-scott** [comment]
`sodium_bin2hex()` and `sodium_hex2bin()`

**Comment by jedisct1** [comment]
These keys (or any data, actually) can be encoded to text using the functions @paragonie-scott mentioned. Base64 conversion is also supported.

This is documented here: https://download.libsodium.org/doc/helpers#hexadecimal-encoding-decoding
