### ISSUE TITLE
Providing prebuilt cross platform libraries

### ISSUE THREAD

**Issue by martinstoeckli** [jedisct1/libsodium#835]
It would be extremely helpful, if there where precompiled libraries available for cross platform development. At the moment the Windows library libsodium.dll is included in the mingw releases, but there is no library libsodium.so available for ARM.

It would make cross platform development much easier, if one could download the latest prebuilt libraries.

**Comment by jedisct1** [comment]
Hi Martin,

Unfortunately, I don't use Windows and I don't have any ARM platform to install it to.

And Visual Studio Community Edition doesn't seem to support ARM targets.

So, you are in a much better position to maintain prebuilt Windows/ARM libraries, especially since you will be extensively testing them on these platforms.

This is also something I could do, but as contracted work.

**Comment by martinstoeckli** [comment]
Thanks for the fast reply, so then I'm not the only one struggling with platform independency. I couldn't produce a library for Android so far, hoped this would be an easy task for you. Never mind, glad you are maintaining this remarkable library.

**Comment by jedisct1** [comment]
Android libraries can be built using the scripts present in the `dist-build` directory.

Running `dist-build/android-armv8-a.sh` for example will build a distribution for armv8.

You just need to install the Android NDK prior to this.

**Comment by martinstoeckli** [comment]
As far as I understood, this must be done on an Android device(?), and the only device I have is my old smartphone (the emulators on my Windows dev machine run on x64). That's where I'm struggling, I don't know how to setup a building environment on my only device, thus the enquiry.

**Comment by jedisct1** [comment]
The NDK can be installed on Windows, MacOS and Linux. But to run the script itself on Windows, you will have to use MSYS2 or WSL.

**Comment by martinstoeckli** [comment]
Thanks for the tip, I will have a look at those tools.
