### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by ChackBox** [jedisct1/libsodium#841]
--2019-06-27 09:00:10--  https://github.com/jedisct1/libsodium/releases/download/1.0.18/libsodium-1.0.18.tar.gz
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-06-27 09:00:10 ERROR 404: Not Found.

**Comment by jedisct1** [comment]
Releases and stable builds are available here: https://download.libsodium.org/libsodium/releases/
