### ISSUE TITLE
Possibly implement a bignum implementation for libsodium

### ISSUE THREAD

**Issue by AnythingTechPro** [jedisct1/libsodium#843]
I'm currently using OpenSSL's bignum implementation for a project of mine, though i don't really like the idea of having to include OpenSSL when i am focusing on libsodium integration instead. Is anyone opposed to this? If not, i can begin working on a port of OpenSSL's bignum implementation and move it here...

**Comment by jedisct1** [comment]
Hi,

Unfortunately this is out of that project’s scope.
