### ISSUE TITLE
Citation?

### ISSUE THREAD

**Issue by Qomo-CHENG** [jedisct1/libsodium#844]
I would like to cite this very nice lib, but I didn't find a good one.

It would be very helpful if there is a citation as in BibTeX or other format.

**Comment by jedisct1** [comment]
Hi,

There is no associated publication, but you can use something like this

```latex
@misc{libsodium, title={The Sodium cryptography library},
      url={https://download.libsodium.org/doc/}, author={Denis, Frank}, journal={Libsodium},
      year={2013}, month={Jun}}
```

**Comment by Qomo-CHENG** [comment]
> Hi,
> 
> There is no associated publication, but you can use something like this
> 
> ```
> @misc{libsodium, title={The Sodium cryptography library},
>       url={https://download.libsodium.org/doc/}, author={Denis, Frank}, journal={Libsodium},
>       year={2013}, month={Jun}}
> ```

Thanks a lot!  This solves my problem!
Since lots of authors contributed to this lib, I'm thinking how to cite it properly.

**Comment by jedisct1** [comment]
The list of authors keep changing as implementations are added or changed. A URL for the authors list would be ideal, but unfortunately, this is not something supported by Bibtex.
