### ISSUE TITLE
v1.0.18 release missing assets

### ISSUE THREAD

**Issue by ndon55555** [jedisct1/libsodium#846]
Hi @jedisct1 

For each of the previous releases, there is a `libsodium-<version>.tar.gz` artifact included in the assets. It seems to be missing for 1.0.18.

**Comment by jedisct1** [comment]
Hi!

You can get tarballs of that version, as well as the latest stable version here: https://download.libsodium.org/libsodium/releases/

**Comment by ndon55555** [comment]
Thanks!
