### ISSUE TITLE
cross-compilation of arm 

### ISSUE THREAD

**Issue by adityaK18** [jedisct1/libsodium#847]
I am trying to cross-compile the Linux PAM code for the arm.  The configuration is ailed with error "could not read symbols: File in wrong format".

"
.libs/pam_prelude.o: could not read symbols: File in wrong format
collect2: ld returned 1 exit status
Makefile:368: recipe for target 'libpam.la' failed
make[2]: *** [libpam.la] Error 1
make[2]: Leaving directory '/home/aditya/Linux-PAM-1.1.3.tar/Linux-PAM-1.1.3/libpam'
Makefile:341: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/aditya/Linux-PAM-1.1.3.tar/Linux-PAM-1.1.3'
Makefile:271: recipe for target 'all' failed
make: *** [all] Error 2
aditya@aditya-VirtualBox:~/Linux-PAM-1.1.3.tar/Linux-PAM-1.1.3$

"

the configuration command used is 
./configure --prefix=/home/aditya/Linux-PAM-1.1.3.tar/Linux-PAM-1.1.3/output/pre --exec-prefix=/home/aditya/Linux-PAM-1.1.3.tar/Linux-PAM-1.1.3/output/epre CC=/home/aditya/ami_toolchain_rr11/arm-linux/arm-2011.09/bin/arm-none-linux-gnueabi-gcc ARCH=arm --host=arm-none-linux-gnueabi

**Comment by jedisct1** [comment]
This project has nothing to do with "Linux PAM". Wrong repository, sorry.
