### ISSUE TITLE
cmake not finding libsodium on MacOS

### ISSUE THREAD

**Issue by rsn8887** [jedisct1/libsodium#849]
I installed libsodium on MacOS via cloning the repo and issuing `configure && sudo make install` command. I also tried `brew install libsodium`. The following problem occurs either way.

Using the command 
```
find_package(sodium REQUIRED)
```
inside CMAKELISTS.TXT, and running cmake results in the following error message from cmake:
```
CMake Error at /usr/local/Cellar/cmake/3.15.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find sodium (missing: sodium_LIBRARY_RELEASE
  sodium_LIBRARY_DEBUG)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.15.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  CMake/Findsodium.cmake:227 (find_package_handle_standard_args)
  CMakeLists.txt:74 (find_package)
```

**Comment by stv0g** [comment]
Can you check if there is a file named `Findsodium.cmake` somewhere under `/usr/local/`?

**Comment by rsn8887** [comment]
There is a file called `Findsodium.cmake` in the `CMAKE` subdirectory of the source code I am trying to compile. And it is using it it seem. I copied that file to `/usr/local/` still the same error.

**Comment by jedisct1** [comment]
This is how `libsodium` is used with `cmake` in `minisign`: https://github.com/jedisct1/minisign/blob/7cc9b23ed9ae19024094cbab105afd988c976138/CMakeLists.txt#L51-L72

It probably doesn't work on Windows, but it seems to be okay on other platforms.

**Comment by rsn8887** [comment]
This file fixed my problem:
https://github.com/facebookincubator/fizz/blob/master/fizz/cmake/FindSodium.cmake

I suggest maybe fixing the FindSodium.cmake file here in this repo, using the fix that was applied to the working one in above link.

**Comment by rsn8887** [comment]
Also some kind of versioning of the dozens of different `Findsodium.cmake` files floating around on the internets would be nice. Cmake surely seems ill-thought out for this kind of stuff doesn't it.

**Comment by rsn8887** [comment]
Nevermind. Cmake ran, but now the linking gives me errors, so lib sodium is still not correctly used.

**Comment by rsn8887** [comment]
Ok I can confirm the facbookincubator file works just fine. I restarted from scratch and did the following:
- `brew install libsodium`
- Replace official `cmake/FindSodium.cmake` in code repo with the file from here: https://github.com/facebookincubator/fizz/blob/master/fizz/cmake/FindSodium.cmake
- `cmake ../ && make`
- Worked perfectly!

So it looks like the Findsodium.cmake needs to be updated with whatever magic the facebookincubator repo fixed it with.

**Comment by stv0g** [comment]
By looking at the Makefile [in the `contrib/`](https://github.com/jedisct1/libsodium/tree/master/contrib) directory, I am wondering if the bundled Findsodium.cmake in this repo is even properly installed to the correct locations.

In my macOS it is usually one of the following locations (see [`CMAKE_MODULE_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_MODULE_PATH.html)):

- `/usr/local/share/cmake/`
- `/usr/local/share/cmake/Modules/`
- `/usr/local/lib/cmake/`
- `/usr/local/lib64/cmake/`

Usually, you would install the `Findsodium.cmake` with a `make install` so that your own application would find the proper file in the system folders.

Alternatively, you can also add libsodium as a submodule to your own code directory and include it with CMake's `add_subdirectory()`.

**Comment by rsn8887** [comment]
Whether `Findsodium.cmake` is installed correctly by `make install` or not is a different issue. I agree it should be correctly installed.

The issue here is specifically that using `find_package(sodium REQUIRED)` in cmake does not find an installed libsodium correctly even if `Findsodium.cmake` is correctly present.

The fix I found was to use a different `Findsodium.cmake`, the one from facebookincubator, see above. So I suggest to update `contrib/Findsodium.cmake` in this repo with the working version of the file.

Of course it is possible to make cmake find libsodium in some other way, for example via pkg_config, like it was suggested. This issue here is just about using `find_package(sodium)` to find it.

**Comment by jedisct1** [comment]
Here are the difference between the file in `contrib` and the one from Facebook:

https://gist.github.com/jedisct1/73b8e52fe220fcd2b6b07455be65c2d2

The current one has fixed that the Facebook version doesn't have. For example, `sodium_VERSION` (which is actually the version string, not the version) probably doesn't return the correct string in the Facebook version.

Changes were made to fix issues in the original version (e.g. https://gist.github.com/jedisct1/73b8e52fe220fcd2b6b07455be65c2d2 https://github.com/jedisct1/libsodium/commit/06739323d520b5c11d4d231f77ccb268a1a67a92#diff-c171eed4a719f1b9a4d810d459e2ee08 https://github.com/jedisct1/libsodium/commit/5dcf78a14c75b0feec59344a7a2e0afd861752b6#diff-c171eed4a719f1b9a4d810d459e2ee08 https://github.com/jedisct1/libsodium/commit/95a1f7d6266d2d6cd161c05430c56df322c1863b#diff-c171eed4a719f1b9a4d810d459e2ee08) that may not be in the Facebook version.

Looks like fixing a bug in cmake systematically introduces a different bug.

**Comment by jedisct1** [comment]
That file is not installed anywhere, at least not by `make install`.
