### ISSUE TITLE
configure script missing in tar.gz of libsodium 1.0.18 (stable)

### ISSUE THREAD

**Issue by kerlerm** [jedisct1/libsodium#851]
Package https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
  does provide a configure script where as 
package https://github.com/jedisct1/libsodium/archive/1.0.18.tar.gz does not and fails to compile for me. 

The downloads differ. Which is the "official" source for download?

**Comment by jedisct1** [comment]
Whenever a tag is added, GitHub automatically creates a tarball that's just an archive of all the files in the repository. This is what that `1.0.18.tar.gz` file is. And it is very annoying, but I've never found how to avoid or delete these files.

As [documented](https://download.libsodium.org/doc/installation), tarballs of 1.0.18-stable are available [here](https://download.libsodium.org/libsodium/releases/).
