### ISSUE TITLE
Secret key in crypto_sign is overwritten with seed value.

### ISSUE THREAD

**Issue by jjoganic** [jedisct1/libsodium#852]
libsodium/src/libsodium/crypto_sign/ed25519/ref10/keypair.c

In crypto_sign_ed25519_seed_keypair(), the secret key is generated from the seed using SHA512 and then promptly overwritten with the seed by memmove immediately thereafter.  This appears to have been this way from the get go.  Can someone explain?

**Comment by jjoganic** [comment]
So we're clear, that code does not appear in the original NaCl code.

**Comment by tarcieri** [comment]
That function doesn't exist in NaCl (source: I sent the original PR to add it to libsodium), which only allows for randomly generated keypairs. This precludes deterministic key derivation.

An Ed25519 keypair is the concatenation of `seed || pk`, so this is expected behavior. The seed is re-expanded with each use into a canonical scalar (which is subsequently "clamped" before being used in a signing operation). The re-expansion is necessary, among other reasons, to re-derive the nonce prefix.

**Comment by jjoganic** [comment]
My confusion here is that I already have a public/private key pair.  This signing API only appears to allow signing using a known seed (which I don't have) or a random seed, which defeats the purpose.  Is there some other signing API that just takes sign(private, data) -> sig and verify(pub, data, sig)?  Or is this library strictly for ephemeral keys?

**Comment by tarcieri** [comment]
If you have a keypair, as I mentioned earlier the seed is the first 32 bytes.

**Comment by jjoganic** [comment]
I've returned to this problem after a short hiatus, and I'm no further along.  Is it possible to reproduce the test vectors in https://tools.ietf.org/html/rfc8032 using this library?  The key pair I am working with is from a known private key, not something that was randomly generated or from a seed value.  I don't see any mention of a seed being used in this capacity in the RFC.  Am I misunderstanding something about the theory or practice of libsodium?  Should I be using a lower-level API that implements ed25519ph directly?

**Comment by jjoganic** [comment]
I have found the problem.  This is a terminology issue.  What libsodium is calling the "seed" _is_ the "private key" in RFC8032.  This is confirmed by passing the test vector's "SECRET KEY" into crypto_sign_seed_keypair as the seed parameter.  This is frustrated by the fact that Section 5.1.5 refers to this same value as the "Private Key" and the compliment to the public key merely as secret scalar s.

**Comment by jedisct1** [comment]
Yes, this is a terminology issue. There is a bitstring that the signer must keep secret. This is the only secret visible to applications.

And there is an internal secret key, derived from the seed, and from which the public key is directly computed. But applications never see or provide that one, as something else, also derived from the seed, is also required for signing.

**Comment by jedisct1** [comment]
First test vector:

```c
    unsigned char pk[crypto_sign_PUBLICKEYBYTES], sk[crypto_sign_SECRETKEYBYTES],
        seed[crypto_sign_SEEDBYTES], sig[crypto_sign_BYTES];
    char sig_hex[crypto_sign_BYTES * 2 + 1];

    (void) sodium_init();
    sodium_hex2bin(seed, sizeof seed,
                   "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60", -1, NULL,
                   NULL, NULL);
    crypto_sign_seed_keypair(pk, sk, seed);
    crypto_sign_detached(sig, NULL, NULL, 0, sk);
    puts(sodium_bin2hex(sig_hex, sizeof sig_hex, sig, sizeof sig));
```

**Comment by tarcieri** [comment]
> This is frustrated by the fact that Section 5.1.5 refers to this same value as the "Private Key" and the compliment to the public key merely as secret scalar s.

Note that I did explain all of this back here: https://github.com/jedisct1/libsodium/issues/852#issuecomment-515707326
