### ISSUE TITLE
aead: (x)chacha20poly1305: Safe to use input buffer as target buffer in encrypt/decrypt?

### ISSUE THREAD

**Issue by zia942** [jedisct1/libsodium#856]
### Update:

My apologies, I found exactly what I was looking for. The in-place thing was brought up in #701 and I found it documented under [xchacha20](https://libsodium.gitbook.io/doc/advanced/stream_ciphers/xchacha20#usage) as well (Ctrl+F, "in-place").

I am leaving this issue open anyway, so maintainers can point out other places in the documentation where this is mentioned, and confirm that said about xchacha20 applies to xchacha20poly1305 as well (I don't see why it wouldn't, the MAC is written _after_ the ciphertext so as long as enough memory is allocated for it, should be fine). **Please close the issue as you see fit.**

-------

I've come across xchacha20poly1305 implementations (in other languages) where the memory that can write ciphertext to the same memory location as plaintext (as long as there's enough allocation for the +16 tag bytes), encrypting the input _in-place_, so to speak. I admit I don't know why that would be desirable other than conserving allocated memory in some applications, but I was still curios if it works (and is safe) in libsodium too.

e.g. consider the following program.

```c
#include <stdio.h>
#include <string.h>
#include <sodium.h>

#define MESSAGE_SRC ((const unsigned char*) "Hello, world!")
#define MESSAGE_LEN 13LLU
#define ADDITIONAL_DATA ((const unsigned char*) "Hello again.")
#define ADDITIONAL_DATA_LEN 12LLU

unsigned char nonce[crypto_aead_xchacha20poly1305_ietf_NPUBBYTES];
unsigned char key[crypto_aead_xchacha20poly1305_ietf_KEYBYTES];
unsigned char workbuffer[MESSAGE_LEN + crypto_aead_xchacha20poly1305_ietf_ABYTES];

int main(void)
{
  unsigned long long ciphertext_len;
  unsigned long long deciphered_len;

  if (sodium_init() < 0) {
    fprintf(stderr, "sodium_init() failed, exit\n");
    return -1;
  }

  printf("libsodium version: %s\n", sodium_version_string());
  
  memcpy(workbuffer, MESSAGE_SRC, MESSAGE_LEN);
  crypto_aead_xchacha20poly1305_ietf_keygen(key);
  randombytes_buf(nonce, (sizeof(nonce)/sizeof(*nonce)));

  if (!! crypto_aead_xchacha20poly1305_ietf_encrypt(
        workbuffer, &ciphertext_len,
        workbuffer, MESSAGE_LEN,
        ADDITIONAL_DATA, ADDITIONAL_DATA_LEN,
        NULL, nonce, key
  )) {
    fprintf(stderr, "_encrypt() failed, exit\n");
    return 1;
  }

  if (0 == memcmp(workbuffer, MESSAGE_SRC, MESSAGE_LEN)) {
    fprintf(stderr, "workbuffer not overwritten by encrypt as expected");
    return 2;
  }

  if (!! crypto_aead_xchacha20poly1305_ietf_decrypt(
        workbuffer, &deciphered_len,
        NULL,
        workbuffer, ciphertext_len,
        ADDITIONAL_DATA, ADDITIONAL_DATA_LEN,
        nonce, key
  )) {
    fprintf(stderr, "_decrypt() failed, exit\n");
    return 3;
  }

  if (0 != memcmp(workbuffer, MESSAGE_SRC, MESSAGE_LEN)) {
    fprintf(stderr, "deciphered != plaintext");
  }

  return 0;
}
```

Here I'm using the same buffer (`workbuffer`) for holding the plaintext and ciphertext (and plaintext again) which has allocation for expected ciphertext length. This seems to work on my setup (see details below) without problem (returns 0). That leads me to believe that using the same buffer for reading plaintext and writing ciphertext is safe with libsodium too. But I don't have the expertise to mathematically prove that.

**My issue/question is:**

- Is what I'm trying to do in the program above generally correct?
- If so, does this work only for xchacha20poly1305 or does this apply to other AEAD ciphers, too?
- If so, Is this documented anywhere? _Should_ it be documented?
- If so, how can I contribute to the documentation? e.g. what would be a good place to put this? Maybe the [xchacha20poly1305 example](https://libsodium.gitbook.io/doc/secret-key_cryptography/aead/chacha20-poly1305/xchacha20-poly1305_construction#example-combined-mode) can be modified to demonstrate this?

**Environment**
- MacBook, OSX Mojave 10.14.6
- uname -v =
    ```Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64```
- gcc -v =
    ```
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
    Apple LLVM version 10.0.1 (clang-1001.0.46.4)
    Target: x86_64-apple-darwin18.7.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
    ```
- libsodium version: 1.0.18

**Comment by jedisct1** [comment]
Hi,

In-place encryption is perfectly fine and supported by all ciphers. This is something applications frequently do.

The test suite also includes specific tests for this configuration.

So, yes, what you are doing is perfectly fine!
