### ISSUE TITLE
How integrate libsodium on android application?

### ISSUE THREAD

**Issue by SebastianoLpwave** [jedisct1/libsodium#860]
Hi all,

i need to update an old version of libsodium  "kalium-jni-1.0.0-SNAPSHOT.jar". 
Someone can tell me how to create the jar from the library? 

Thanks,

Sebastiano

**Comment by jedisct1** [comment]
Kalium has a dedicated repository: https://github.com/abstractj/kalium

So you'd better ask there :)

Also, there are [other options](https://download.libsodium.org/doc/bindings_for_other_languages) for Android, such as [lazysodium-android](https://github.com/terl/lazysodium-android).
