### ISSUE TITLE
Any suggest for building dlls for .Net P/Invoke without msvc dll dependencies ?

### ISSUE THREAD

**Issue by GreatFireWall** [jedisct1/libsodium#873]
I have read #614, but I only use `libsodium.dll` for my .net app, will this cause the issues whick talks in #614 ?

And I had try to build Dll with /MT, but get the similar result like #246 : 
`error LNK2019: unresolved external symbol __imp___ftime64`

**Comment by ektrah** [comment]
The conclusion of #614 was that the only dependency of libsodium is the Universal C Runtime, which comes pre-installed on Windows 10. I don't think it gets any more minimal than that.

**Comment by GreatFireWall** [comment]
I had use the static library (.lib) to build a /MT dll that exports some function what I need, thanks.
