### ISSUE TITLE
pwhash_argon2i/d Segmentation fault

### ISSUE THREAD

**Issue by ghazel** [jedisct1/libsodium#878]
started after installing macOS Catalina (previous macOS with same Xcode worked fine). Happens on `1.0.18` and `master`. 

```
../../build-aux/test-driver: line 107: 52089 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: pwhash_argon2i
../../build-aux/test-driver: line 107: 52095 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: pwhash_argon2id
```

**Comment by emilbayes** [comment]
Have you seen this? https://github.com/jedisct1/libsodium/issues/848

**Comment by ghazel** [comment]
No. I looked for open issues, since this is clearly still an issue.

**Comment by angt** [comment]
Hi ghazel,
This look like #848 indeed.
Can you post more info about your toolchain ?

**Comment by ghazel** [comment]
```
% clang --version
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by emilbayes** [comment]
@ghazel see this bug report to Apple: https://forums.developer.apple.com/thread/121887

**Comment by jedisct1** [comment]
Use `stable` releases (or the `stable` branch).

**Comment by ghazel** [comment]
> Use `stable` releases (or the `stable` branch).

I was using the `1.0.18-RELEASE` tag, which is a `stable` release, no?

**Comment by jedisct1** [comment]
Current stable is `1.0.18-stable`. This is where all the post-release fixes such as the one required here go.

https://download.libsodium.org/doc/installation
