### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by mattproch** [jedisct1/libsodium#880]
MacOS 10.15 Catalina
All versions of libsodium, but Mamp comes with v1.0.16 and it works there.

../../build-aux/test-driver: line 107: 58195 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: pwhash_argon2i
../../build-aux/test-driver: line 107: 58219 Segmentation fault: 11  "$@" > $log_file 2>&1
FAIL: pwhash_argon2id

**Comment by jedisct1** [comment]
https://github.com/jedisct1/libsodium/issues/878

**Comment by mattproch** [comment]
#848 really helped me, it was the same issue actually

My solution (I have php installed with brew):

1. Download different version of llvm with brew: `brew install llvm`
2. Remove brew version of libsodium: `brew uninstall libsodium --ignore-dependencies`
3. Make the downloaded clang the default compiler just for the bash instance: `CC=/usr/local/Cellar/llvm/9.0.0/bin/clang CXX=/usr/local/Cellar/llvm/9.0.0/bin/clang++``
4. Download libsodium and follow the installation instruction in [download.libsodium.org/doc/installation](https://download.libsodium.org/doc/installation)
5. Done
