### ISSUE TITLE
Libsodium under memsan

### ISSUE THREAD

**Issue by Erop147** [jedisct1/libsodium#882]
I am using libsodium crypto_secretbox_easy/crypto_secretbox_open_easy in my project and I have an issue while testing my app with memsan enabled when crypto_stream_salsa20_xmm6_implementation is chosen (https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_stream/salsa20/stream_salsa20.c#L81).
It seems that initializing (or unpoisoning with __msan_unpoison) block0 from https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_secretbox/crypto_secretbox_easy.c#L89 fixes the problem.

Also tried to run builtin tests with memsan, using following command: `env CC=clang-8 CFLAGS="-fsanitize=memory -g" ./configure && make check`
11 tests broke, the results in the attachment
[test-suite.log](https://github.com/jedisct1/libsodium/files/3707632/test-suite.log)

**Comment by jedisct1** [comment]
https://clang.llvm.org/docs/MemorySanitizer.html#handling-external-code
"MemorySanitizer requires that all program code is instrumented. This also includes any libraries that the program depends on, even libc. Failing to achieve this may result in false reports. For the same reason you may need to replace all inline assembly code that writes to memory with a pure C/C++ code."

The `xmm6` implementation is written in assembly,  so memsan cannot follow what it does.
