### ISSUE TITLE
Add bcrypt to libsodium

### ISSUE THREAD

**Issue by timoh6** [jedisct1/libsodium#888]
Given the earlier tweets by @jmgosney and @Sc00bzT, it seems bcrypt is still the recommended password hashing function for interactive requirements (web applications).

https://twitter.com/TerahashCorp/status/1155129705034653698
https://twitter.com/Sc00bzT/status/1164213102071734272

In addition, yescrypt has the needed tunable cache hardness, but maybe adding bcrypt for now is more conservative movement. But on the other hand, yescrypt is backwards compatible with scrypt, updating libsodium's scrypt to yescrypt could make sense.

Thoughts?

(found https://github.com/jedisct1/libsodium/issues/267 but couldn't comment on it anymore)

**Comment by jedisct1** [comment]
> Thoughts?

No.
