### ISSUE TITLE
question about aegis256

### ISSUE THREAD

**Issue by patrickkh7788** [jedisct1/libsodium#891]
·aegis256· vs ·chacha20` or `aes-gcm-256`,  are they has same security level ? or more strong？

**Comment by angt** [comment]
Hi,

If you are looking for the most secure option, just use chacha20poly1305.
Sometimes, performance matters, so aegis/aesgcm are good solutions on architectures that support hardware encryption.

Regards.

**Comment by jedisct1** [comment]
Use XChaCha20Poly1305.

AEGIS-256 is not in any libsodium release yet.

AES-GCM is tricky to use correctly, and you may end up with something completely insecure even though it says "AES".

**Comment by patrickkh7788** [comment]
Thanks for explain.  I will use XChaCha20Poly1305.

`aegis256` vs `AES-GCM`,   are they in same security level ?

**Comment by jedisct1** [comment]
Same, but AEGIS256 large nonce size is a clear advantage.
