### ISSUE TITLE
** Unable to use libsodium in macOS **

### ISSUE THREAD

**Issue by gilgameshskytrooper** [jedisct1/libsodium#892]
** Update: this seems to have been fixed in Xcode 11.2 **

^ I'm not sure if this is correct. I recently upgraded to Catalina, and installed XCode 11.2. I am building a forked version of [this repo](https://github.com/jpiechowka/libsodium-file-crypter) ([my fork which attempts to add macOS support](https://github.com/gilgameshskytrooper/libsodium-file-crypter)). This seems to work fine in Ubuntu 18.04 as long as I install `libsodium-dev` from apt. But on mac, I get a `SIGENV` when running `crypto_pwhash()` (line 22 of `crypto/encrypt_file.c` my fork).

Because I started this project after I installed Catalina, I am unable to verify if this is a coding error on my part, or a problem with XCode.

_Originally posted by @jedisct1 in https://github.com/jedisct1/libsodium/issues/881#issuecomment-549049136_

**Comment by gilgameshskytrooper** [comment]
^ This is in fish. Produces a seg fault in zsh

**Comment by gilgameshskytrooper** [comment]
Because it's not confirmed that it is even the fault of libsodium, I'm just going to close this until I get more information.

**Comment by jedisct1** [comment]
See the pinned issue:

<img width="521" alt="Screen Shot 2019-11-05 at 02 10 53" src="https://user-images.githubusercontent.com/124872/68170817-82103b80-ff71-11e9-89f6-b5cc10016579.png">

**Comment by gilgameshskytrooper** [comment]
I saw this. But you made the issue collaborator contribution only. Hence, I couldn't comment.
