### ISSUE TITLE
version.h include file name is too general.

### ISSUE THREAD

**Issue by junyoun-kim** [jedisct1/libsodium#895]
include "version.h" in version.c is too general to crash with other library "version.h" header file.

Could you guard it with namespace like "sodium/version.h" or "sodium_version.h"?

**Comment by jedisct1** [comment]
You should not include it directly, but include `<sodium.h>` instead.

**Comment by junyoun-kim** [comment]
I got that. But what I'm encountering now is compiling sodium source code with other library. I don't use library(.a) but compile source codes. So when it compile sodium/version.c, it include other library's version.h header file so it got error.

**Comment by jedisct1** [comment]
If you invented your own way to compile libsodium, you are on your own, sorry.

**Comment by junyoun-kim** [comment]
Okay. Thank you for reply. It just suggestion. There might other guys have similar issues.

Actually I try import sodium on Mbed OS now. And there is some chances for sodium/version.c to include mbed-os/features/mbedtls/inc/mbedtls/version.h depend on search order.

Just want you to know that. Thank you anyway.

**Comment by jedisct1** [comment]
https://download.libsodium.org/doc/installation#cross-compiling
