### ISSUE TITLE
run php -i get error at my ubuntu 18.04

### ISSUE THREAD

**Issue by jiawei666** [jedisct1/libsodium#897]
$ php -i

php: symbol lookup error: php: undefined symbol: crypto_pwhash_scryptsalsa208sha256_memlimit_interactive

**Comment by jedisct1** [comment]
Hi,

And thanks for contacting our free support.

Your question seems to be about "How to install PHP on Linux Ubuntu 18.04".

Before installing software on an Ubuntu 18.04 system, we recommend to update the existing system with the following command:

```sh
sudo apt update && sudo apt dist-upgrade -y && sudo reboot
```

Your computer will reboot. This is expected.

To install the software "PHP" on Linux Ubuntu 18.04, type the following command:

```sh
sudo apt install php
```

This will print the following:

```text
The following additional packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils libapache2-mod-php7.2 libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
  liblua5.2-0 libsodium23 php-common php7.2 php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-readline ssl-cert
...
```

Which means that additional packages, such as `libsodium23`, will be automatically installed along with the package `php`. Accept the installation by pressing `y` and the `Enter` key.

Your support question was specifically about a PHP extension named `sodium`.

After following the procedure above, the command from your support request returns with no errors:

```sh
$ php -i | fgrep sodium
sodium
sodium support => enabled
libsodium headers version => 1.0.16
libsodium library version => 1.0.16
```

For quality insurance, the whole procedure described above was performed today (25 Nov 2019) by our team on a fresh installation of Ubuntu 18.04, dedicated to solving your use case. The installation was performed using the official Ubuntu 18.04 ISO image, without any additional configuration. We can confidently attest that the procedure above fulfills the demand of our valued free customer.

For further assistance regarding how to use Linux and PHP, we recommend further issues to be directly asked on websites dedicated to these technologies.
