### ISSUE TITLE
Why did you call it 'crypto_generichash()'?

### ISSUE THREAD

**Issue by Kaulkwappe** [jedisct1/libsodium#899]
I have a question regarding [crypto_generichash()](https://libsodium.gitbook.io/doc/hashing/generic_hashing) which (only) uses BLAKE2b. Why exactly is it called _generichash_, why didn't you call it _generichash_blake2b_ or _hash_blake2b_?

**TLDR**: What is your plan if you think you need to replace BLAKE2b in future?

Although that case is very unlikely, but if any practical attacks would be found in BLAKE2b which would lead to a change from BLAKE2b to another algorithm, the _crypto_generichash()_ couldn't be safely used any more for existing hashes if the algorithm for _crypto_generichash()_ would be changed. So, you would need to create a _crypto_generichash2()_. Same applies if we should see a BLAKE3 or any other much better algorithm you want to use as default hashing algorithm in future.

For me, it would made more sense to provide functions where the developer could choose from, e.g.

```
crypto_generichash_blake2b()
crypto_generichash_sha3_256()
```

**Comment by jedisct1** [comment]
This is a high-level API. The fact that it currently uses BLAKE2b shouldn’t even be relevant to applications. They shouldn’t assume any particular algorithm. The high-level APIs are intentionally generic.

A practical attack BLAKE2 is unlikely, but if that ever happened, there would be a major revision of the library.

**Comment by jedisct1** [comment]
And no, there wouldn’t be a `crypto_generichash2()`. If a primitive is broken, it has to be replaced.

**Comment by Kaulkwappe** [comment]
> This is a high-level API. The fact that it currently uses BLAKE2b shouldn’t even be relevant to applications. They shouldn’t assume any particular algorithm. The high-level APIs are intentionally generic.
I see, thanks for explanation.

> And no, there wouldn’t be a `crypto_generichash2()`. If a primitive is broken, it has to be replaced.
Why not? It would use another algorithm, so it is replaced.

**Comment by jedisct1** [comment]
Because this is not OpenSSL. Algorithms known to be broken and that no one should use shouldn’t be left around.

**Comment by jedisct1** [comment]
That’s also why libraries have major versions. The same function can behave differently, disappear or have a different interface between major versions.

**Comment by Kaulkwappe** [comment]
Well, today you don't know what a major version is. That differs from project to project.

But now I know what I wanted to know: When there is a need to change the algorithm behind _crypto_generichash()_, it will be replaced in the next available major version. That doesn't allow a transition period and will break environments which are not up to date. But that is fine since this will only happen due to a major version and security is way more important for the libsodium project than compatibility.
