### ISSUE TITLE
How can I increase more secure memory size for sodium_malloc

### ISSUE THREAD

**Issue by AlexiaChen** [jedisct1/libsodium#901]
on my laptop:

system : 8G ubuntu 18.04

sodium_malloc maybe run 16000 to 18000 times stop with returned nullptr

my test code as follows:

```cpp
    sodium_init();
    for (int i = 0; i < 100000; ++i)
    {
        unsigned char *p = (unsigned char *)sodium_malloc(64);
   std::cout
           << "current  " << i  << " times"<< std::endl;
        
        if (p == NULL)
        {
            std::cout << "stop with " << i << " times" << std::endl;
            printf("errno %d\n", errno);
            return 1-;
        } 
    }

``` 

16 G MacOSX:

sodium_malloc run around 70000 times stop with returned nullptr.

But, on my 8G ubuntu enviroment, the total size of sodium_malloc malloced is: 18000 * 64 = 1152000 bytes = 1125 K bytes = 1M bytes。1M bytes  is far from the 8G physical memory limit.

on 16G MaxOSX    the total size of sodium_malloc malloced is 70000 * 64 = 4480000 bytes = 4375 K bytes = 4M bytes. 4M bytes is also  far from the 16G physical memory limit.

Frankly, 1 ~ 4M bytes is very very small for my requirement.

I kwon the concept "secure memory" for libsodium is different with normal heap memory , but Is there a way to change some OS system configuration to fix the problem to meet my needs?

**Comment by emilbayes** [comment]
Just FYI, you're allocating much more memory than 64 bytes at a time: https://github.com/jedisct1/libsodium/blob/dcc2e06c93067f421ab549550b89fec45993b7a7/src/libsodium/sodium/utils.c#L600

The documentation also mentions this

**Comment by AlexiaChen** [comment]
Additional information:

 on AWS 32G server, sodium_malloc run 24000+ times stop with return nullptr. the result is totally different from 8G ubuntu and 16G MacOSX.

**Comment by emilbayes** [comment]
@AlexiaChen You are probably hitting the system limit for locked memory. Check RLIMIT_MEMLOCK (from: http://man7.org/linux/man-pages/man2/getrlimit.2.html)

**Comment by AlexiaChen** [comment]
but some cases are: I need to call many many times with sodium_malloc(sizeof(myStruct)),  myStruct size maybe small. but the library actual allocated more memory to caller.

**Comment by AlexiaChen** [comment]
> @AlexiaChen You are probably hitting the system limit for locked memory. Check RLIMIT_MEMLOCK (from: http://man7.org/linux/man-pages/man2/getrlimit.2.html)

Thanks, I will try
