### ISSUE TITLE
Use prlimit set RLIMIT_MEMLOCK to 1G or bigger size but it  did not work

### ISSUE THREAD

**Issue by AlexiaChen** [jedisct1/libsodium#902]
my test code with privileged process:

```cpp
 struct rlimit old, newlimit;
    struct rlimit *newp;
    pid_t pid = getpid();

    newp = NULL;

    newlimit.rlim_cur = 16 * 1024 * 1024;
    newlimit.rlim_max = 1024 * 1024 * 1024;
    newp = &newlimit;

    if (prlimit(pid, RLIMIT_MEMLOCK, newp, &old) == -1)
    {
        printf("prlimit set memlock size failed\n");
        return -1;
    }

    printf("Previous limits: soft=%lld; hard=%lld\n",
           (long long)old.rlim_cur, (long long)old.rlim_max);

    /* Retrieve and display new MEMLOCK time limit */

    if (prlimit(pid, RLIMIT_MEMLOCK, NULL, &old) == -1)
    {
        printf("prlimit get new memlock size failed\n");
        return -1;
    }

    printf("New limits: soft=%lld; hard=%lld\n",
           (long long)old.rlim_cur, (long long)old.rlim_max);

  
```

Then I use ulimit command line ulimit -l unlimited  also not working.

The test result is all the same(sodium_malloc run 16000 ~ 18000 times stop with return nullptr) on ubuntu 18.04 with issue #901 ， Looks like the sodium_malloc success times is not increase.

Is it must restart OS could be working? 

so I can write the following bash to .bashrc and restart system?

```bash
ulimit -l unlimited 
```

**Comment by AlexiaChen** [comment]
Solution 2 is also not working:

edit file /etc/security/limits.conf:

```conf
myuser soft memlock 1048576
myuser hard memlock 1048576
```
save it and reboot my OS. check ulimit -a and max lock memory result is setted right size write above. 

Finally, I run my test code, and it does not work. the test result is same as I mentioned above.

**Comment by emilbayes** [comment]
Assuming a page size of `4096` bytes, you are not allocating `16000 * 64`, but somewhere between `16000 * 3  * 4096` – `16000 * 4 * 4096`

**Comment by AlexiaChen** [comment]
@emilbayes  errno is always 12

**Comment by emilbayes** [comment]
>        ENOMEM No memory is available.
> 
>        ENOMEM The process's maximum number of mappings would have been
>               exceeded.  This error can also occur for munmap(), when
>               unmapping a region in the middle of an existing mapping, since
>               this results in two smaller mappings on either side of the
>               region being unmapped.
> 
>        ENOMEM (since Linux 4.7) The process's RLIMIT_DATA limit, described
>               in getrlimit(2), would have been exceeded.

**Comment by AlexiaChen** [comment]
Assume one memory page is 4 Kb,  the sodium_malloc run 16000 times actual allocate  16000 * 3 * 4096 – 16000 * 4 * 4096 bytes (187M - 250M bytes) secure memory give to caller. but 187M - 250M is very small compared with the current locked memory size(1GB) that I set using ulimit -l . 

Sorry, I am not fammiliar with the principle of Operating System,  Could you explain more details about this?   Is This related to aligned memory?  the library cannot allocate aligned Locked memory?
