### ISSUE TITLE
Does libsodium support Saving of key pairs(crypto_box_keypair) to local file?

### ISSUE THREAD

**Issue by KotaHemanthIITD** [jedisct1/libsodium#903]
Hi, 
 I was looking for libsodium API support(if exists) to save public key, private key to a filepath, retrieve it when needed. I couldn't find any info about saving or loading keys(searched source code and previous issues). I guess, it's most likely that they are supported. Can someone confirm this? If not supported, is there any security reason for deciding not to?

**Comment by jedisct1** [comment]
Keys are just numbers encoded as byte arrays. So you can load and save them like any byte array.

They don’t include any internal pointers or anything that would require additional serialization.
