### ISSUE TITLE
crypto_box_*(): derivating order of public + secret keypair in >= PHP 7.2

### ISSUE THREAD

**Issue by Kaulkwappe** [jedisct1/libsodium#904]
I may miss something here, but I noticed something which could be dangerous under some unusual circumstances.

When you have a look into the documentation and the examples, you will notice that the order for the crypto box keypair in libsodium will be always 1) public and then 2) secret:

```
crypto_box_keypair(recipient_pk, recipient_sk);
crypto_box_seal_open(decrypted, ciphertext, CIPHERTEXT_LEN, recipient_pk, recipient_sk);
```
https://libsodium.gitbook.io/doc/public-key_cryptography/sealed_boxes

However, I can confirm that PHP [\sodium_crypto_box_keypair()](https://www.php.net/manual/en/function.sodium-crypto-box-keypair.php) returns not a public+secret pair, but a secret+public pair. This corresponds to the doc:

> sodium_crypto_box_keypair — Randomly generate a secret key and a corresponding public key

https://www.php.net/manual/en/function.sodium-crypto-box-keypair.php

Same applies to the [\sodium_crypto_box_seal_open()](https://www.php.net/manual/en/function.sodium-crypto-box-seal-open.php):

`$decrypted = \sodium_crypto_box_seal_open($ciphertext, $secretKey . $publicKey);`

As long helpers like [\sodium_crypto_box_secretkey()](https://www.php.net/manual/de/function.sodium-crypto-box-secretkey.php) and [\sodium_crypto_box_publickey()](https://www.php.net/manual/de/function.sodium-crypto-box-publickey.php) are used, that should not be a huge problem.

However, developers may interchange the keys due to the differing order in libsodium and the PHP implementation. I don't understand for what reason the order was changed in PHP.

**Comment by jedisct1** [comment]
The PHP function returns a single, opaque bit string. You should assume anything about its structure or even its size.

**Comment by Kaulkwappe** [comment]
Why do you think that? First, we're talking here about the sodium implementation, not a PHP feature which hiddenly uses libsodium in the background. At this point, it absolutely does not make sense to change the public and secret pair order.

People will both use the libsodium and PHP docs since the PHP docs are not very exploratory at the moment. Additionally, of course you have to know the sizes when the byte string isn't only used in the memory. Furthermore, developers may also decide to split the byte string and store only an encrypted version of the secret key (using a KDF) into the database.

Anyway, this issue can lead to a confusion of the secret with the public key. Now it happened and cannot be changed, but I think someone should add a note to the PHP docs regarding this issue.

**Comment by jedisct1** [comment]
>  the PHP docs are not very exploratory at the moment
>  someone should add a note to the PHP docs

Nobody wants to write documentation. Not even you.

**Comment by Kaulkwappe** [comment]
Well, don't be so pessimistic. I already try to add a note into the PHP doc (never used the docbook online editor before).

**Comment by Kaulkwappe** [comment]
I have added this note (which is not visible yet), I hope my assumption that libsodium always uses the order public, secret is correct:

> **Caution:** This function returns a raw byte string of a random secret key and public key combination in the order secret, public despite the order of the underlying Sodium library will be always public, secret.

**Comment by jedisct1** [comment]
One shouldn't assume anything about how PHP returns a key pair. In fact, this is likely to be changed from a string to an opaque object.

**Comment by jedisct1** [comment]
PHP-related things are better discussed here: https://github.com/jedisct1/libsodium-php
