### ISSUE TITLE
Problems in configuring project in CMake

### ISSUE THREAD

**Issue by Mposki** [jedisct1/libsodium#906]
I managed problem while configuring project in CMake with use of libsodium.

First, I added all necessary sodium variables to CMake, but it couldn't configure, which was ended with CMake Error.  After adding only sodium_DIR path, CMake still cannot configure program properly.

My program, CMake output log, CMake messages and CMake lists are there: https://github.com/Mposki/SodiumTest.

Thanks for help!

**Comment by jedisct1** [comment]
Here's a working `CMakeList.txt` file of a project that uses libsodium: https://github.com/jedisct1/minisign/blob/master/CMakeLists.txt

**Comment by jedisct1** [comment]
There is also a [`findsodium.Cmake`](https://github.com/jedisct1/libsodium/blob/master/contrib/Findsodium.cmake) file that may or may not work.
