### ISSUE TITLE
Security impact of not calling `sodium_init`

### ISSUE THREAD

**Issue by FedericoCeratto** [jedisct1/libsodium#908]
Hello. Can you please clarify the security impact of using any libsodium function without calling `sodium_init` in advance?

E.g. according to the documentation in https://download.libsodium.org/doc/usage#sodium_init-stalling-on-linux - would the function in https://download.libsodium.org/doc/generating_random_data simply stall in absence of enough entropy or generate predictable data?

If there are security risks, should the affected functions check for initialization and refuse to run otherwise (or initialize libsodium on the fly)?
Thanks

(edit: related to #625)

**Comment by enkore** [comment]
Without sodium_init,

- you will not get optimized implementations
- guarded allocations do not work
- RNG will be initialized at the first call, instead of through sodium_init. This might be relevant if you chroot.

**Comment by jedisct1** [comment]
So, do not do that and call `sodium_init()` as documented since the library exists :)
