### ISSUE TITLE
Wrong math for crypto_core_ristretto255_scalar_complement?

### ISSUE THREAD

**Issue by joernheissler** [jedisct1/libsodium#911]
Hello,

`crypto_core_ristretto255_scalar_complement` returns `-s + 1 (mod L)`.
Is that by intention? For a 2's complement I would have expected `-s - 1 (mod L)` instead.
For example the complement of 0 would be -1 and not +1.

**Comment by jedisct1** [comment]
It works as documented:

![Screen Shot 2019-12-31 at 14 28 00](https://user-images.githubusercontent.com/124872/71622991-c1f24880-2bd9-11ea-975c-4f111317c15c.png)

**Comment by jedisct1** [comment]
Similarly, 2's complement means that `x + comp ≡ 1 (mod 2)`.

With 4 bits limbs, `1101`'s complement would be `0010`, since we have `1101 + 0010 ≡ 1 (mod 2)`.

**Comment by joernheissler** [comment]
> It works as documented:

It does. But it's not what I expect a complement function to return.

**Comment by jedisct1** [comment]
Sorry. It does what I need.
