### ISSUE TITLE
[Invalid] ld: warning: building for macOS, but linking in object file built for iOS Simulator

### ISSUE THREAD

**Issue by caobug** [jedisct1/libsodium#912]
Hello, I used libsodium-1.0.18/dist-build/ios.sh script to build static lib. but crash when I call sodium_init()

```
#include <sodium.h>

int main(void)
{
    if (sodium_init() == -1) {
        return 1;
    }
    ...
}
```
OSX Version: 10.15.2 (19C57)

<img width="831" alt="pic" src="https://user-images.githubusercontent.com/7737673/71788260-a369d280-305b-11ea-9159-9ea7df1fb8fa.png">

**Comment by jedisct1** [comment]
What does `sysconf(_SC_PAGESIZE)` return?

**Comment by caobug** [comment]
@jedisct1 `printf("%ld\n", sysconf(_SC_PAGESIZE));` output: 4096

**Comment by jedisct1** [comment]
iOS applications don't have a `main()` function. How do you compile and run that code?

**Comment by caobug** [comment]
it's macOS type project, other openssl, c-ares, pcre... static libs is ok, just the libsodium not working.

**Comment by jedisct1** [comment]
I don't understand. If this is a MacOS project, why are you trying to link a library for iOS?

**Comment by jedisct1** [comment]
Didn't you notice a compilation warning message that says (about 40 times)

```text
ld: warning: building for macOS, but linking in object file built for iOS Simulator
```

?

**Comment by jedisct1** [comment]
For a MacOS app, you need to use libraries compiled for MacOS.

Libraries compiled for a different operating system are not going to work.

**Comment by caobug** [comment]
^__^

Thanks.
