### ISSUE TITLE
The warning info in src\libsodium\include\sodium\private\common.h 

### ISSUE THREAD

**Issue by jhc80** [jedisct1/libsodium#913]
In the latest release version 1.0.18, there are still some warning comments in src\libsodium\include\sodium\private\common.h.

can you double check if these warning info can be removed in release version?

```c
#if !defined(_MSC_VER) && !defined(DEV_MODE) && 0
# warning *** This is unstable, untested, development code.
# warning It might not compile. It might not work as expected.
# warning It might be totally insecure.
# warning Do not use this except if you are planning to contribute code.
# warning Use releases available at https://download.libsodium.org/libsodium/releases/ instead.
# warning Alternatively, use the "stable" branch in the git repository.
#endif

#if !defined(_MSC_VER) && (!defined(CONFIGURED) || CONFIGURED != 1)
# warning *** The library is being compiled using an undocumented method.
# warning This is not supported. It has not been tested, it might not
# warning work as expected, and performance is likely to be suboptimal.
#endif
```

**Comment by jedisct1** [comment]
The code you quoted is not going to trigger the warnings. `&& 0` is always false.

If you see them, the code you are compiling is not the one you quoted. Make sure to download an actual release (`libsodium-1.0.18-stable.tar.gz`). If you need help with compiling it, refer to the [documentation](https://download.libsodium.org/doc/installation).
