### ISSUE TITLE
Error building libsodium-sys

### ISSUE THREAD

**Issue by hubbabubbagump** [jedisct1/libsodium#914]
When I try importing sodiumoxide, which in turns imports libsodium-sys, the build crashes during `make check -j8`.

According to the test suite, the failing tests are:
```
FAIL: pwhash_argon2i
FAIL: pwhash_argon2id
```

Not too sure what's going on here, but I believe the command is seg faulting due to the errors:
```
../../build-aux/test-driver: line 107: 45211 Segmentation fault: 11  "$@" > $log_file 2>&1
../../build-aux/test-driver: line 107: 45222 Segmentation fault: 11  "$@" > $log_file 2>&1
```

Any help would be appreciated!

Output file for reference:
[output.txt](https://github.com/sodiumoxide/sodiumoxide/files/4039185/output.2.txt)

**Comment by hubbabubbagump** [comment]
Looks like it's a Catalina issue - closing.

**Comment by cakoose** [comment]
The fix is to upgrade Xcode: https://github.com/jedisct1/libsodium/issues/848#issuecomment-549163810
