### ISSUE TITLE
any plan for BLAKE3?

### ISSUE THREAD

**Issue by burmecia** [jedisct1/libsodium#915]
As the BLAKE3 came out (https://github.com/BLAKE3-team/BLAKE3) and looks like it has great performance against BLAKE2b, is there any plan to include it in libsodium in the near future?

**Comment by jedisct1** [comment]
See the roadmap: https://download.libsodium.org/doc/roadmap

**Comment by angt** [comment]
![](https://i.giphy.com/fnK0jeA8vIh2QLq3IZ.gif)
