### ISSUE TITLE
secretstream & zero byte frames

### ISSUE THREAD

**Issue by insasho** [jedisct1/libsodium#916]
What is the expected behavior of secretstream when handling messages that are 0 bytes long?

In Python, the behavior is that _pull() refuses to decode output that is generated by _push():

```
c = bindings.crypto_secretstream_xchacha20poly1305_push(state, 
  bytes(),                                                                
  tag=bindings.crypto_secretstream_xchacha20poly1305_TAG_FINAL)
# len(c) == 17 == crypto_secretstream_xchacha20poly1305_ABYTES
...
# this throws an exception: Ciphertext is too short
bindings.crypto_secretstream_xchacha20poly1305_pull(
            state,
            c,
            None)
```

The exception is thrown in crypto_secretstream.py crypto_secretstream_xchacha20poly1305_pull:

```
    ensure(
        len(c) > crypto_secretstream_xchacha20poly1305_ABYTES,
        'Ciphertext is too short',
        raising=exc.ValueError,
    )
```

Should padding be applied when using secretstream, or is this a bug?

Thanks.

**Comment by jedisct1** [comment]
This is a bug in that Python code. len(c) can be equal to ABYTES.
