### ISSUE TITLE
parameter documetation for "crypto_aead_aes256gcm_encrypt_detached".. and other public functions

### ISSUE THREAD

**Issue by jadamcrain** [jedisct1/libsodium#917]
I'm implementing a standard that requires particular AEADs so I need to use the particular functions. I'm starting w/ AES-GCM in detached mode.

I think I've been able to infer what most of the parameters are, but I don't know how to interpret the two nonce paramters. I guess I was expecting a single pointer to a single buffer 12 bytes in length.

I take it from the variable names `nsec` and `npub` that the nonce can somehow be secret or public?

```
// ciphertext output - length must be at least plaintext length since this is CTR
unsigned char *c,
                                           
// MAC output - returns the mac length in specified pointer?
unsigned char *mac,
unsigned long long *maclen_p,

// plaintext input
const unsigned char *m,
unsigned long long mlen,

// additional data
const unsigned char *ad,
unsigned long long adlen,

// two parameters for the nonce?!
const unsigned char *nsec,
const unsigned char *npub,

// key - 32 bytes
const unsigned char *k)
```

**Comment by jadamcrain** [comment]
Update: I see from the exported macros that `crypto_aead_aes256gcm_NSECBYTES == 0`. I think that I am understanding now that this interface is for some more generic AEAD interface where an algorithm might have a secret part of the nonce, but this function can take NULL for this argument.

**Comment by jedisct1** [comment]
https://download.libsodium.org/doc/secret-key_cryptography/aead/aes-256-gcm

**Comment by jadamcrain** [comment]
Actually did read the doc, but was unable to find this section.
