### ISSUE TITLE
crypto_core_ristretto255_scalar_reduce WEIRD BEHAVIOR

### ISSUE THREAD

**Issue by ToraNova** [jedisct1/libsodium#919]
While using the function crypto_core_ristretto255_scalar_reduce I stumbled on a peculiar pattern.
Here's the issue :

Suppose I have a 64 byte array "tmp"
tmp = 4ED43CCB2023FE63F7F22953CFDF29385079E6F5F36D39A1BDABC8185051DE5C

I hash 'tmp' in program A and got the output "out"
out = 04ABD7468553BFD870CD4FDFAC8416C62F6CF19E17172E0239E439DC6F171402

Now if I run the another program B which has the same "tmp" value, I get a different output "dif"
dif = DBE13CD3E11215E34ACE0E4FF5A26EC80C5825551A5229281A8CBFC343DFF90C

When I run program B again, I got the output "dif" again.

Snippet from Program A
```			
crypto_core_ristretto255_from_hash( tmp1 , (const unsigned char *)hshe );
//tmp1 is an element, we perform reduction into a scalar, x (2nd 32byte on obuffer)

size_t j;
debug("Post_HASH:Pre_REDUCTION");
for(j=0;j<ELE;j++){
	printf("%02X",(tmp1)[j]);
}
printf("\n");

crypto_core_ristretto255_scalar_reduce( (*obuffer+SCA), tmp1); //x = H(m, U, V)

debug("x");
for(j=0;j<SCA;j++){
	printf("%02X",(*obuffer+SCA)[j]);
}
printf("\n");
```
Output : 
```
DEBUG src/i25519.cpp:sign:L168: Post_HASH:Pre_REDUCTION
4ED43CCB2023FE63F7F22953CFDF29385079E6F5F36D39A1BDABC8185051DE5C
DEBUG src/i25519.cpp:sign:L176: x
04ABD7468553BFD870CD4FDFAC8416C62F6CF19E17172E0239E439DC6F171402
```
Snippet from Program B
```                       
crypto_core_ristretto255_from_hash( tmp1 , (const unsigned char *)hshe );
//tmp1 is an element, we perform reduction into a scalar, x

size_t j;
debug("Post_HASH:Pre_REDUCTION");
for(j=0;j<ELE;j++){
	printf("%02X",(tmp1)[j]);
}
printf("\n");

crypto_core_ristretto255_scalar_reduce( tmp, tmp1); //x = H(m, U', V')

debug("EQUALITY TEST (x' vs x)");
for(j=0;j<SCA;j++){
	printf("%02X",tmp[j]);
}
printf("\n");
for(j=0;j<SCA;j++){
	printf("%02X",(obuffer+SCA)[j]);
}
printf("\n");
```
Output : 
```
DEBUG src/i25519.cpp:verify:L282: Post_HASH:Pre_REDUCTION
4ED43CCB2023FE63F7F22953CFDF29385079E6F5F36D39A1BDABC8185051DE5C
DEBUG src/i25519.cpp:verify:L290: EQUALITY TEST (x' vs x)
DBE13CD3E11215E34ACE0E4FF5A26EC80C5825551A5229281A8CBFC343DFF90C
04ABD7468553BFD870CD4FDFAC8416C62F6CF19E17172E0239E439DC6F171402
```

What is wrong with my code ? I'm expecting tmp and (obuffer+SCA) to be the same... as (obuffer+SCA) is read in from program A. If I rerun program B again, the same output appears. Why is it non-deterministic across different programs ? Or perhaps I have mistaken somethings ?

OS and library details :
```
uname -a
Linux cj-basepc 5.4.7-arch1-1 #1 SMP PREEMPT Tue, 31 Dec 2019 17:20:16 +0000 x86_64 GNU/Linux
ldconfig -p
libsodium.so.23 (libc6,x86-64) => /usr/lib/libsodium.so.23
libsodium.so (libc6,x86-64) => /usr/lib/libsodium.so
pacman -Ss sodium
community/libsodium 1.0.18-1 [installed]
    P(ortable|ackageable) NaCl-based crypto library
```

**Comment by ToraNova** [comment]
Update.
I found out that if I perform
```crypto_core_ristretto255_scalar_reduce( tmp, tmp1);```
with a constant 'tmp1' throughout both programs. 'tmp' is the same. Same goes if the 64byte 'hshe' is constant. I'm trying to work outwards to see from where it causes the output to differ.

What could possibly cause the output of `crypto_core_ristretto255_scalar_reduce( tmp, tmp1)` to differ other than 'tmp1' ??

**Comment by jedisct1** [comment]
You're probably reading uninitialized memory, partially initialized memory, accessing data out of bounds, or hitting an undefined C behavior.

Tools such as Valgrind and your compiler's sanitizers (ASAN, UBSan, etc) can help find that can of bugs.

Good luck!

**Comment by ToraNova** [comment]
thanks
