### ISSUE TITLE
[FEATURE] Incorporate Ulam's Spiral for faster generation of primes

### ISSUE THREAD

**Issue by prabhatsoni99** [jedisct1/libsodium#925]
Ulam's spiral is a pattern in mathematics. We know of a particular equation whose `y` value has approx 20X more chance of being a prime number (a high density distribution of numbers):  
`y = x^2 + x + 3399714628553118047`  
  
What are the thoughts on incorporating this to generate primes faster?
  
Resources for Ulam's Spiral:  
https://en.wikipedia.org/wiki/Ulam_spiral  
https://www.youtube.com/watch?v=iFuR97YcSLM

**Comment by jedisct1** [comment]
Nothing on Libsodium needs to generate primes. RSA is intentionally not implemented.
