### ISSUE TITLE
on your realse page,the download url is changed,differ then before

### ISSUE THREAD

**Issue by youxiaojie** [jedisct1/libsodium#926]
dear sir,
as a openwrt developer,I found your download url is changed from
https://github.com/jedisct1/libsodium/releases/download/1.0.17/libsodium-1.0.17.tar.gz
to
https://github.com/jedisct1/libsodium/releases/download/1.0.18-RELEASE/libsodium-1.0.18.tar.gz
after the version number you add "-RELEASE", so, if it is temporary, could you mind changing to original naming format? or if later you will naming by this method, I would make a pull request to openwrt.thanks!!

**Comment by jedisct1** [comment]
This is GitHub, not my release page. There's not much I can do about how GitHub presents things. I wish there was a way to hide tags from the GitHub release page :(

`1.0.18` is just a tag, to remember when a release was made, it doesn't contain usable code (files are missing).

Releases and stable versions are available [here](https://download.libsodium.org/libsodium/releases/).
