### ISSUE TITLE
Performance of crypto_scalarmult_curve25519 and crypto_scalarmult_curve25519_base

### ISSUE THREAD

**Issue by xipki** [jedisct1/libsodium#927]
I tested both functions in three different PCs with Ubuntu as OS (one laptop, one desktop PC, and one server). In all cases, the behavour is similar. Here is data of the desktop PC.

- If the `sodium_init()` is called first, **40,000** `crypto_scalarmult_curve25519_base`, but only **14,000** `crypto_scalarmult_curve25519` will be executed in 1 second.
- Otherwise, only **23,000** `crypto_scalarmult_curve25519_base`, but **22,000** `crypto_scalarmult_curve25519` will be executed in 1 second. The computation result is correct even without calling `sodium_init()` before.

Could you please optimize the code to achieve best performance for both functions after calling sodium_init()?

**Comment by jedisct1** [comment]
> Could you please optimize the code to achieve best performance for both functions after calling sodium_init()?

Sure. I'm available for contracting work. Please reach out privately to discuss this.

**Comment by angt** [comment]
I'm also available for contracting work about optimization :P
