### ISSUE TITLE
[linux-ppc64le] CMake failed to find libsodium

### ISSUE THREAD

**Issue by runlevel5** [jedisct1/libsodium#929]
**Describe**

The [devilutionX](https://github.com/diasurgical/devilutionX) project uses the [Findsodium.cmake](https://github.com/jedisct1/libsodium/blob/master/contrib/Findsodium.cmake ).

The CMake failed to detect libsodium on my Linux PPC64le box:

```
$ uname -a
Linux orion.dev 5.5.0+ #1 SMP Mon Feb 3 08:17:51 EST 2020 ppc64le ppc64le ppc64le GNU/Linux

$ cat /etc/redhat-release
Fedora release 31 (Thirty One)

$ dnf info libsodium-devel
Name         : libsodium-devel
Version      : 1.0.18
Release      : 2.fc31
Architecture : ppc64le
Size         : 3.6 M
Source       : libsodium-1.0.18-2.fc31.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Development files for libsodium
URL          : http://libsodium.org/
License      : ISC
Description  : This package contains libraries and header files for
             : developing applications that use libsodium libraries.
```

**To Reproduce**

Steps to reproduce the behaviour:

```
$ git clone https://github.com/diasurgical/devilutionX.git
$ cd devilutionX/build
$ cmake ..
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find sodium (missing: sodium_LIBRARY_RELEASE
  sodium_LIBRARY_DEBUG) (found version "1.0.18")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  CMake/Findsodium.cmake:224 (find_package_handle_standard_args)
  CMakeLists.txt:126 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/tle/src/devilutionX/build/CMakeFiles/CMakeOutput.log".
See also "/home/tle/src/devilutionX/build/CMakeFiles/CMakeError.log".
```

For your investigation, the full [CMakeError|Output.log](https://gist.github.com/runlevel5/1a0d7b415adad6429478608d2245be97)

**Expected behaviour**

the libsoidum is picked up correctly and the build files would be written successfully

```
$ cmake ..
-- Found Sodium: /usr/lib64/libsodium.so
-- Found SDL2_ttf: /usr/lib64/libSDL2_ttf.so
-- Found SDL2: /usr/lib64/libSDL2.so
-- Found SDL2_mixer: /usr/lib64/libSDL2_mixer.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tle/src/devilutionX/build
```

**Additional context**

The [facebookincubator/fizz's FindSodium.cmake](https://github.com/facebookincubator/fizz/blob/master/fizz/cmake/FindSodium.cmake) works for me.

**Comment by jedisct1** [comment]
The file has been removed, thanks!

**Comment by AJenbo** [comment]
@jedisct1 where may we find a maintained version of this file? The one from  facebookincubator /
fizz doesn't work correctly on macOS and some other systems, and hasn't been updated since September 2018.

**Comment by jedisct1** [comment]
Damn. The documentation was updated to point at the Facebook version, but if it's a Linux-only thing, it is not going to be very useful.

I don't use `cmake`, so the best thing I can do is merge whatever change people submit for the one in this repository, but apparently, it never ended up building something that works.

My only attempt to use `cmake` was in `minisign`. It links `libsodium`, so if you don't need Visual Studio support maybe you can reuse this as it seems to do the job: https://github.com/jedisct1/minisign/blob/master/CMakeLists.txt

**Comment by AJenbo** [comment]
The one you had was actually working for Linux (Debian and Arch. Also cross compiling for Windows and Switch), Visual Studio, Xcode on macOS, Haiku, FreeBSD and OpenBSD (all we have tested up to this point).

If I step up as maintainer for findlibsodium.cmake, would you be willing to keep it in this repo?

I can probably figure out what needs to be adjusted for it to also work on Fedora in this case.

**Comment by jedisct1** [comment]
@AJenbo If you have some cmake expertise, sure!

Maybe you can create a dedicated repository so that people can test it on different environments. It could also be a good opportunity to add some documentation about how to use it.
