### ISSUE TITLE
All function pointers misaligned by 1byte when compiled for ARM Cortex M0+

### ISSUE THREAD

**Issue by dyntaos** [jedisct1/libsodium#931]
I am trying to get the library working for an ARM Cortex M0+ (ATSAMD21G18).
I have compiled using this shell script:

```#!/bin/sh -x
cd ../libsodium
SODIUMDIR=`pwd`
export PATH=$HOME/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin:$PATH
export LDFLAGS='--specs=nosys.specs'
export CFLAGS='-Os -mcpu=cortex-m0plus'
./configure --host=arm-none-eabi --prefix="${SODIUMDIR}/build-cortex-m0" && make install

if [ $? -eq 0 ]
then
	echo libsodium was successfully compiled for ARM Cortex M0 in: ../libsodium/build-cortex-m0/lib/libsodium.a
else
	echo Error compiling libsodium for ARM Cortex M0!
fi
```
I have defined/provided a custom RNG struct and confirmed it works.
This compilation succeeds, but resulted in the device hanging. When I examined the resulting ELF file in Ghidra, all function pointers (such as the "implementation->function_pointer" constructs).
Every function pointer within the library is misaligned by 1 byte.
An example of this:
https://github.com/jedisct1/libsodium/blob/afae623190f025e7cf2fb0222bfe796b69a36941/src/libsodium/crypto_generichash/blake2b/ref/blake2b-ref.c#L28
`blake2b_compress` ends up with the value 0x00016D65, when `blake2b_compress_ref()` begins at 0x00016d64.

When I remove the function pointers and just hardcode the functions, everything works as expected.

**Comment by jedisct1** [comment]
Sorry, this target is completely unsupported.

And looks like this is more of a toolchain issue than something with the code itself.

So, you're on your own, sorry.
