### ISSUE TITLE
How to benchmark WebAssembly runtime?

### ISSUE THREAD

**Issue by ifyouseewendy** [jedisct1/libsodium#932]
👋 Hello, I'm in the research of benchmarking the various WebAssembly runtimes. The most useful information I can get is the blog post on [Updated WebAssembly benchmark using libsodium](https://00f.net/2019/10/22/updated-webassembly-benchmark/). That's super helpful and awesome. Thanks a lot for making it!

It's been a while since the last update. I'm thinking about running it again with the up to date runtimes. By poking around in the code base, I get to the point that I can get test results for individual runtime. I'm wondering 

* if there is a flag I can turn on to quickly generate the native benchmark
* if there is a way to gather test results from each `*.log` and generate a holistic report

Thanks!

**Comment by jedisct1** [comment]
All you need is run the `./dist-build/wasm32-wasi.sh` script with the `--bench` flag.

The tests themselves are run through the `test/default/wasi-test-wrapper.sh` script, that lets you choose a runtime using the `WASI_RUNTIME` environment variable. If not defined, it is going to try a bunch of common runtimes.

It is also recommended to have the `wasm-opt` (from `binaryen`) tool around, as it will perform additional optimizations on the compiled webassembly module.

When run in `bench` mode, the tests are run for multiple iterations, and report the execution time in their resulting log file.

Of course, you should use the `stable` version of `libsodium`, not a release, as the scripts in the release are now a little bit old and I don't even remember if they supported benchmarking for the webassembly target.

**Comment by ifyouseewendy** [comment]
Thanks for the reply. I believe I've got all the env set up correctly, as I can see the test result for wavm and wasmer.

```
vagrant@vagrant:~/libsodium/test/default $ cat box.log
273740000
PASS box (exit status: 0)
```

However, as I was asking, I wonder if there is a flag I could use to turn on the bench on native. Thanks!

**Comment by jedisct1** [comment]
Sure, just configure as follows

```sh
env CPPFLAGS="${CPPFLAGS} -DBENCHMARKS -DITERATIONS=100"` ./configure --enable-opt
```

The number of iterations can be changed. It is set to `100` in the WASI compilation script, and to `10` for the Javascript target.

`dist-build/emscripten.sh` creates a Javascript+WebAssembly build for web browsers, and can build test pages running the benchmark, too. This is what the `--browser-test` option does.

But you can also just test them directly here: https://download.libsodium.org/libsodium.js/browsers-test/

**Comment by ifyouseewendy** [comment]
Awesome, I'll try it out. Thanks again!
