### ISSUE TITLE
Libsodium blocks indefinitely in environments with low entropy (f.e. newly spinned up VMs/containers)

### ISSUE THREAD

**Issue by Ocramius** [jedisct1/libsodium#933]
Similar to https://github.com/jedisct1/libsodium/issues/49, `/dev/random` is a problematic source of random bytes for downstream consumers, because the system in which libsodium operates may not have accumulated enough entropy, or may be consuming it faster than it becomes available.

As it currently is implemented (if I read it correctly, I couldn't pinpoint my userland issue precisely, sorry) `randombytes_internal_random_random_dev_open` uses a blocking poll, and can lead to processes hanging while waiting for libsodium:

https://github.com/jedisct1/libsodium/blob/4f5e89fa84ce1d178a6765b8b46f2b6f91216677/src/libsodium/randombytes/internal/randombytes_internal_random.c#L249-L274

If I misread this, or if this is controlled by a build-time flag, then I'll see if I can fix it downstream instead.

Given that #49 is now almost 7 years old, I suggest re-evaluating it, since the crypto community pretty much goes into the ["just use `/dev/urandom`" camp](http://research.jvroig.com/linuxrand/DevsJustUSeUrandPlease_Templated_2018-05-19.pdf) these days (seems like library authors also agree in https://github.com/jedisct1/libsodium/issues/280#issuecomment-120950496)

Possibly related, btw: Linux 5.3 may fix this too (https://lwn.net/Articles/802360/)

**Comment by jedisct1** [comment]
This is documented.

**Comment by Ocramius** [comment]
Yeah, I don't think https://download.libsodium.org/doc/usage#sodium_init-stalling-on-linux is really useful though: it reads more like a dead end :-(

As mentioned in #280 (https://github.com/jedisct1/libsodium/issues/280#issuecomment-120950496 by @jedisct1):

 > /dev/urandom (or, actually getrandom(2) on Linux) is fine, even for secret keys.
 > 
 > http://www.2uo.de/myths-about-urandom/
 > http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/

**Comment by jedisct1** [comment]
Waiting on `/dev/random` is not even enough to guarantee that the kernel RNG has been properly seeded.

But it hangs for a reason. The solution is to fix the root cause, not to ignore and be completely insecure.

**Comment by Ocramius** [comment]
Not sure what you're saying here though: on one end, `/dev/urandom` is fine for private keys, and here `/dev/random` is required? Or is there (newer than above mentioned) agreement that `/dev/random` is required and must be blocking?

Considering a system with a limited amount of randomness (booted seconds ago), wouldn't it be acceptable to use `/dev/urandom` for things like a password salt?

**Comment by jedisct1** [comment]
`/dev/random` is never used to get random data.

On Linux, it uses `getrandom(2)`, on Windows it uses `RtlGenRandom` and on other systems `/dev/urandom`.

The check on `/dev/random` is only done during initialization to wait for `getrandom(2)` (and `/dev/urandom`) to be safe to use.

If you prefer an early failure/error, you can simply copy&paste the code from the documentation that does exactly that :)

**Comment by Ocramius** [comment]
Fair enough, thanks!
