### ISSUE TITLE
crypto_sign_ed25519_seed_keypair expect public key to be right after private key in memory

### ISSUE THREAD

**Issue by p-col-ledger** [jedisct1/libsodium#940]
Hello,

I am using the function `crypto_sign_ed25519_seed_keypair()` found here: https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_sign/ed25519/ref10/keypair.c

The end of the function ends with:
`    
     memmove(sk, seed, 32);
     memmove(sk + 32, pk, 32);
`

This  looks like an error as it expect `pk` to be right after `sk` in memory (which can produce an overflow when this is not the case).

**Comment by enkore** [comment]
No, pk is written in the earlier line that produces the public key (ge25519_p3_tobytes). The part you noticed simply copies the public key to after the secret key; that's simply an optimization on libsodium's part to always have the public key together with the corresponding secret key.

Note that crypto_sign_ed25519_SECRETKEYBYTES is 2*32 byte to account for this.

**Comment by jedisct1** [comment]
This is even [mentioned in the documentation](https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures#extracting-the-seed-and-the-public-key-from-the-secret-key).
