### ISSUE TITLE
Unable to build on 18.04.4 LTS (Bionic Beaver)

### ISSUE THREAD

**Issue by MarkLTZ** [jedisct1/libsodium#943]
Hello,

compiling libsodium from source I have this error:

make[3]: Entering directory '/home/ubuntu/build/litecoinz/depends/work/build/x86_64-linux-gnu/libsodium/1.0.18-c091a4f9aa3/src/libsodium'
  CC       crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo
gcc-8: error: 1.0.18": No such file or directory
Makefile:2200: recipe for target 'crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo' failed
make[3]: *** [crypto_aead/chacha20poly1305/sodium/libsodium_la-aead_chacha20poly1305.lo] Error 1

Could you please help me to solve this issue?

Thanks
Mark

**Comment by jedisct1** [comment]
That doesn’t seem to be the original source code, but a (modified?) copy bundled with another project.

Maybe some files are missing or the installation procedure for that project requires some steps that you missed? Unfortunately, I can’t help much. You’d better ask that project directly.

The regular instructions to install libsodium from source are here: https://doc.libsodium.org/installation and should work out of the box on Ubuntu 18.04.

**Comment by MarkLTZ** [comment]
@jedisct1 well the source is the original from you (not modified) and it's compiled as dependency of my project, but I assure that the copy & paste I sent was made after tried manually to compile it using:
./autogen.sh
./configure
make V=1

**Comment by jedisct1** [comment]
Mmmm that's weird.

But where does that `1.0.18-c091a4f9aa3` version come from? Why the `./autogen.sh` command? Releases and stable versions are available [here](https://download.libsodium.org/libsodium/releases/).

**Comment by MarkLTZ** [comment]
tarball comes from https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz

1.0.18-c091a4f9aa3 is just the name where it was expanded.

Anyway I saw the issue was caused by the PACKAGE_STRING. If I remove it from the Makefile everything is compiled. Of course the issue is not the presence of the PACKAGE_STRING so I'm debugging more my VM to find the root issue. I will let you know

**Comment by MarkLTZ** [comment]
ok, issue was on the bitcoin build script due a missing quote. Thanks for you patience
