### ISSUE TITLE
using libsoduim in dart ffi

### ISSUE THREAD

**Issue by phanirithvij** [jedisct1/libsodium#947]
Hi, I'd like to use this library in a flutter app that runs on both android and ios.
I need to encrypt and decrypt files using libsodium for that I'm planning to use `dart ffi`.

I see that there are build scripts under `dist-builds/` how can I build for android and ios? What should I have installed on my windows system? (ios is not possible as I don't have a Mac)

**Comment by jedisct1** [comment]
Have you looked at [flutter-sodium](https://github.com/firstfloorsoftware/flutter_sodium)?

**Comment by phanirithvij** [comment]
Yeah I've looked at it but it doesn't  use dart ffi. Because ffi is still in beta so I wanted to make a PR there by starting the migration to ffi.
