### ISSUE TITLE
Interop with djb's poly1305aes ?..

### ISSUE THREAD

**Issue by ulidtko** [jedisct1/libsodium#948]
Hi @jedisct1!

I guess you're well familiar with [this MAC construction][poly1305aes] by djb — and I don't find any mention of it in libsodium docs, neither in the source.

There's #443 which mentions the algo; and it's locked down. You wrote there [years ago]:

> `crypto_aead_aes256gcm*()` (AES256+GCM. AES+Poly1305 would work, but nobody uses it)

Well... All generalizations are wrong — including this one :smile:

Would you rethink and possibly reconsider if libsodium should support poly1305aes?

---------------------------------

I'll tell you my background here: I'm part of a team, and we're building a "Server Platform" product (read: special-purpose linux distro), and we currently ship our product with:
 * openssl (of course);
 * libgcrypt;
 * gnutls;
 * cryptography.io;
 * libsodium too;
 * a bunch of password hashing libs, libxcrypt, libscrypt, bcrypt via python FFI, libmcrypt.

All are used one way or another, mostly as indirect dependencies. `libsodium` (which has damn good name BTW, gulp of fresh air!) is used directly by some of our code; I brought it in for `crypto_auth()`, `crypto_sign()`, `crypto_generichash()` and also for `minisign`. Great stuff.

But you see where I'm going: that's a bit of a crypto zoo going on. It'd be nice to try to keep it tame, by not adding yet another one crypto library. So, just as it often happens, we get a requirement to support another new thing — and it uses poly1305aes in its protocol.

I'd really hoped we could get this job done easily with libsodium. It implements the primitives already, right? But alas, the combined construction isn't there.

What would you say? Am I making sense, or horribly mistaken/uninformed and saying rubbish?

[poly1305aes]: https://cr.yp.to/mac.html

**Comment by jedisct1** [comment]
Choosing poly1305-AES for your protocol was a really weird decision. There is nothing wrong with it, but it's not used anywhere, and it wouldn't have any benefits over existing constructions.

So, it is not going to be added, sorry.

**Comment by ulidtko** [comment]
Hey, where did I say that I made that choice? I wasn't the one to design the protocol :(

**Comment by ulidtko** [comment]
Also I don't quite understand how you know it's not used anywhere... Did you read the source code for everything?

**Comment by ulidtko** [comment]
For anyone landing here later — see https://crypto.stackexchange.com/questions/80155/what-happened-to-poly1305aes-is-it-obsolete
