### ISSUE TITLE
Use Neon for chacha20 (and others)?

### ISSUE THREAD

**Issue by Mygod** [jedisct1/libsodium#949]
This repo mentioned at https://github.com/jedisct1/libsodium/issues/257#issuecomment-98544987 has chacha implementations for neon: https://github.com/floodyberry/chacha-opt/blob/d69e5acbc632ded477fa7056564c8a830c457de0/app/extensions/chacha/chacha_neon-32.inc

See also: https://github.com/torvalds/linux/blob/18bf34080c4c3beb6699181986cc97dd712498fe/arch/arm/crypto/chacha-neon-core.S

**Comment by jedisct1** [comment]
libsodium has a Neon implementation of AEGIS-256.

Other Neon optimizations can be added later, as mentioned in the roadmap.

Good to hear that you found what you were looking for elsewhere until then.

**Comment by Mygod** [comment]
Thanks! Where can I find this roadmap so that I can watch for updates?

**Comment by jedisct1** [comment]
https://doc.libsodium.org/roadmap
