### ISSUE TITLE
AEGIS availability

### ISSUE THREAD

**Issue by Avatat** [jedisct1/libsodium#951]
Hi!

[Mumble](https://github.com/mumble-voip/mumble/) is looking for modern encryption mechanisms. Now we use AES-OCB, but we consider a switch to AES-GCM-256, ChaCha20-Poly1305, or AEGIS. You are the only project I know, which has at least partially implemented AEGIS algorithm :)

@jedisct1, @angt, what's the progress of AEGIS-256 implementation? Are you plan to implement AEGIS-128L too? I'm not a developer, but I will ask - do you need any help with AEGIS things?

I asked the second question because we need encryption with the lowest latency possible, and AEGIS-128L is almost [two times faster](http://competitions.cr.yp.to/round3/aegisv11.pdf) than AEGIS-256.

**Comment by jedisct1** [comment]
Hi,

AEGIS-256 is implemented, for the Intel and ARM crypto extensions. Not in the stable branch, though, so you may want to use angt's standalone implementation for now

There are no plans to add other variants. AEGIS-256 has the advantage of having a large nonce size, and it is plenty fast enough to saturate the network way before the CPU.

**Comment by mouse07410** [comment]
1. What properties of AES-OCB are you unhappy with? Why are you looking to replace it? In what ways do you expect the replacement to be better?

2. People don't select algorithm strength based on performance - you either need the security of 256-bit keys, or you don't. If you don't - stay with shorter keys, as they almost always guarantee better performance.

**Comment by Avatat** [comment]
Thank you for your quick reply!
@jedisct1, do AEGIS-256 support non-accelerated environments? I'm asking because I know, that your AES-256-GCM implementation requires AES-NI.
I wanted to benchmark AEGIS-128L too because it can give us the lowest latency.

@mouse07410, thanks for joining the discussion :)
1. As I understand, we want to change it, because AES-OCB is old, slow, and patented. We are looking for modern, fast (with and without hardware acceleration), and patent-free algorithm and its implementation. Here is [my summary](https://github.com/Avatat/sandbox/blob/master/project_work/topic.md), and here is the [original issue](https://github.com/mumble-voip/mumble/issues/3918).
2. There is no much difference in speed between AEGIS-256 and AEGIS-128, but there is a huge difference comparing to AEGIS-128L.

**Comment by jedisct1** [comment]
AEGIS was specifically designed to leverage AES-NI and its parallelism. It would be very slow without hardware acceleration.

**Comment by Avatat** [comment]
But it will be faster than AEG-GCM-256 and ChaCha20-Poly1305, right?

**Comment by angt** [comment]
Hello all,
I should point that it's also very hard to make it constant time without AES-NI.

**Comment by Avatat** [comment]
@jedisct1, @angt, so the best solution for our case will be the use of AEGIS-256 in accelerated environments (AES-NI or ARM NEON), and ChaCha20-Poly1305, where acceleration isn't available?

**Comment by jedisct1** [comment]
That's exactly what [glorytun](https://github.com/angt/glorytun) does.

**Comment by Avatat** [comment]
Thank you for all answers and effort!
