### ISSUE TITLE
Emscripten libsodium as a library

### ISSUE THREAD

**Issue by DiachenkoIgor** [jedisct1/libsodium#952]
Thank you, for your library, but i have issue with emscripten compiler. I have simple application, that used your library. I have compiled libsodium to libsodium.bc file based on libsodium/dist-build/emscripten.sh script and add this file as library for my own application. But when my application starts it throws error "Module.getRandomValue() is not a function". I noticed, that you create custom libsodium.js file by merging asm and wasm file. Can you please provide decision for this or algorithm, how use your library in such situation?

**Comment by jedisct1** [comment]
Take a look at [libsodium.js](https://github.com/jedisct1/libsodium.js/).
