### ISSUE TITLE
Module.getRandromValue function not exist

### ISSUE THREAD

**Issue by DiachenkoIgor** [jedisct1/libsodium#953]
After building library for webassembly using script emscripten.sh, i have received error "Module.getRandromValue function not exist". I checked file  libsodium/src/libsodium/randombytes/randombytes.c and added logging. I understood, that function "randombytes_stir" never calls , so function isn't configured. However, i checked "master" branch and i noticed changes. With "master" changes my project started to work. Why doesn't "stable" brunch have this changes? In your wiki you said that if i want to use library, you have to download "stable" brunch.

**Comment by jedisct1** [comment]
Check out https://github.com/jedisct1/libsodium.js
