### ISSUE TITLE
Building windows static library

### ISSUE THREAD

**Issue by carlo-quinonez** [jedisct1/libsodium#955]
We use libsodium when building a native module for NodeJS and would like to statically link the library.

On Ubuntu, we can build libsodium with `./configure --with-pic --disable-pie --enable-static` and can link against the `libsodium.a` file without having to include any additional files when we distribute our native Node module.

How can we accomplish the same thing on Windows?

**Comment by jedisct1** [comment]
The [pre-built files](https://doc.libsodium.org/installation#pre-built-libraries) include libraries that can be statically linked.

And in your project, define [`SODIUM_STATIC`](https://doc.libsodium.org/installation#note-for-visual-studio).
