### ISSUE TITLE
Sign by 32-byte nacl.box secretKey and verify by 32-byte publicKey

### ISSUE THREAD

**Issue by username1565** [jedisct1/libsodium#956]
You can rewrite this from JavaScript and add yourself.
See this commit: https://github.com/username1565/nanoboard-javascript-captcha/commit/1bcefd221d430e630e8f4b999ce0eadfaa6e7e85

In this case no need to generate another public key to sign messages and verify this.
And one keyPair can be used to encrypt/decrypt and sign/verify.
This is Tox private key and public key in ToxID: https://tox.chat/download.html

_Best regards._

**Comment by jedisct1** [comment]
?

**Comment by username1565** [comment]
Demo - here: https://username1565.github.io/nanoboard-javascript-captcha/index.html#/sign
Press `Random32`-button to generate two 32-bytes .box-keys, sign the message of this and verify it.
This is base64-encoded `.box-keysPair`, not a `sign-keyPair`.
