### ISSUE TITLE
Unable to install PHP 7: error undefined symbol: crypto_pwhash_scryptsalsa208sha256_memlimit_interactive

### ISSUE THREAD

**Issue by mrsof** [jedisct1/libsodium#957]
Hey,
I've opened an [issue](https://serverfault.com/questions/1016495/unable-to-install-php-7-error-undefined-symbol-crypto-pwhash-scryptsalsa208sha) in StackOverfolw.
Can you help me to solve my problem as it seems to be linked to Libsodium ?
Thanks.

**Comment by jedisct1** [comment]
Sorry, I don't use PHP nor Linux.
