### ISSUE TITLE
New Windows precompiled binaries and MinGW

### ISSUE THREAD

**Issue by nurupo** [jedisct1/libsodium#96]
Windows precompiled binaries are missing `include` directory, which was previously present in windows-tar files. `include` from the source-tar doesn't work, since some headers are not complete, they require to be processed by some kind of configuring tool.

Also, manually replacing all `#ifdef @ ... @` in `*.h.in` files with `0`, setting `version.h.in` right, renaming them to `*.h` and statically linking with the `libsodium.lib` causes undefined reference to function errors, using MinGW, even though `sodium.h` is included.

Linking with `libsodium.dll` instead worked fine, but it asked for `MSVCR120.dll`, which comes with MSVC installation, which I don't have since I use MinGW, so I couldn't run my executable.

Maybe you could resume providing MinGW precompiled binaries as you did before?

tagging @sneves

**Comment by goldsky** [comment]
I'm interested to try https://github.com/jedisct1/libsodium-php, but I'm banging my head on installing libsodium on my Windows box.
I'm not clever enough to understand https://download.libsodium.org/doc/installation/index.html#pre-built-libraries

I'm not a MinGW user either, so I'm completely lost.
What to do?
Copy over `libsodium-1.0.3-mingw\libsodium-win32\`'s contents to `C:\MinGW\`?
(Tried that, and ran `mingw-get.exe`, didn't bring any clue for me)
I was really expecting 1-click installer, but seems it's not an option here.
Do you mind to provide clearer explanation for Win's users?

**Comment by Asmod4n** [comment]
@goldsky I believe you need to put the dll's somewhere in your %PATH% and change
```
extension=libsodium.so
```
to
```
extension=libsodium.dll
```

If that doesn't work i don't know it either :/

**Comment by jedisct1** [comment]
PHP officially supports building with Microsoft's Visual C++ compilers. MinGW and other compilers are NOT supported or even known to work.

https://wiki.php.net/internals/windows/stepbystepbuild

**Comment by goldsky** [comment]
Downloaded Ms Visual Studio 2010 express, and tried to load `libsodium.sln`, it returned error:

>'D:\libsodium-1.0.3\libsodium.vcxproj' cannot be opened because its project type (.vcxproj) is not supported by this version of the application.
>
>To open it, please use a version that supports this type of project.

And VS couldn't 
Again... hitting a brick wall.

@Asmod4n, nope, it doesn't.

@jedisct1, are you now suggesting compiling entire PHP's source?
I don't follow, because I only need to **get** the Windows library of libsodium, and don't want to fix something that doesn't break.

**Comment by goldsky** [comment]
On https://download.libsodium.org/doc/installation/index.html#pre-built-libraries, it states
> Pre-built x86 and x64 libraries for Visual Studio 2010, 2012, 2013 and 2015 are available

But on https://github.com/jedisct1/libsodium/issues/84#issuecomment-25946296, you said
> Only Visual Studio 2013 is supported for now.

I believe the later is the valid one?

**Comment by jedisct1** [comment]
#84 is a comment from 2013. Things have changed since. The documentation is up-to-date; Builds for MSVC 2010, 2012, 2013 and 2015 are available.
