### ISSUE TITLE
Clarify/document in-place crypto_box_seal

### ISSUE THREAD

**Issue by roshanr95** [jedisct1/libsodium#961]
I was trying to figure out if I could do a `crypto_box_seal` in-place with a big enough buffer to contain the ciphertext and managed to do it with some constraints.

Essentially, it doesn't work if the plaintext buffer and the ciphertext buffer have the same start point as is usually the case. It requires that `plaintext_start >= ciphertext_start + 32`. I presume this is because the ephemeral key is first written out to the ciphertext buffer (possibly overwriting the plaintext) and then the encryption happens.

I mainly wanted to check if libsodium could make any guarantees on this (subject to the above constraint) similar to other in-place encryption guarantees in the docs regarding overlapping buffers. Also, a minor thing, but it would be nice if the ephemeral key could be written in the end after encryption so that the above constraint disappears and buffers can overlap without restriction.

**Comment by jedisct1** [comment]
Fixed, thanks!

**Comment by oconnor663** [comment]
Related to this, is it intended for `crypto_aead_xchacha20poly1305_ietf_decrypt_detached` (and other detached AEAD APIs) to be safe to use in-place? It looks in the code like they should be, but it's not documented the way it is for `crypto_secretbox_easy`. Actually, even `crypto_secretbox_detached` isn't documented to be safe to use in-place.

**Comment by jedisct1** [comment]
Yes, they are safe to use in-place.

This is indeed something worth mentioning everywhere in the documentation. Thanks for the heads up!
