### ISSUE TITLE
Different types for opslimit

### ISSUE THREAD

**Issue by jakob** [jedisct1/libsodium#966]
The opslimit parameter has type `unsigned long long` here:
```C
int
crypto_pwhash(unsigned char * const out, unsigned long long outlen,
              const char * const passwd, unsigned long long passwdlen,
              const unsigned char * const salt,
              unsigned long long opslimit, size_t memlimit, int alg);
```

But the functions that return min/max/interactive values have type `size_t`
```C
size_t
crypto_pwhash_opslimit_min(void);

size_t
crypto_pwhash_opslimit_max(void);

size_t
crypto_pwhash_opslimit_interactive(void);
```

This causes issues when importing the library in Swift.

**Comment by angt** [comment]
Hi,
I have no idea about your swift issue.
But `size_t` will always fit in an `unsigned long long` if that's your concern.

**Comment by jedisct1** [comment]
The type has been changed, thanks!

As it would be an ABI change, this is not going to be backported to `stable`. But as @angt said, you can upcast to `size_t` to `unsigned long long`.
