### ISSUE TITLE
Can I use Authenticated encryption with chacha20?

### ISSUE THREAD

**Issue by fangchaooo** [jedisct1/libsodium#982]
In this [document page](https://doc.libsodium.org/public-key_cryptography/authenticated_encryption), It introduces the Authenticated encryption that is encrypted using XSalsa20 stream cipher. But now I want to use ChaCha20 replace it. 
Please tell me what should I do?

**Comment by emilbayes** [comment]
It’s in the docs under the other modes. Both the IETF and original version
