### ISSUE TITLE
Is there any way to control parallelism degree in crypto_pwhash?

### ISSUE THREAD

**Issue by guojize** [jedisct1/libsodium#986]
The Argon2 specification says that there is a parallelism degree which defines the number of parallel threads.

[The documentation of libsodium](https://doc.libsodium.org/password_hashing/default_phf#guidelines-for-choosing-the-parameters) also says: 

> What will be the highest number of threads/processes evaluating the function simultaneously (ideally, no more than 1 per CPU core)? 

But, I couldn't find an API for that. Is there any way to control the parallelism degree?

I'm interested in libsodium and my application needs to use that feature.

All in all, thanks you `libsodium`developers who make such good crypto library!

**Comment by jedisct1** [comment]
Hi,

Although existing hashes with a parallelism > 1 can be verified, `crypto_pwhash` doesn’t support thread-level parallelism.

Maybe this will be added at some point, for platforms that have support for threads, especially if other algorithms can take advantage of this.

But I’m not really convinced that this is necessary as more threads don’t provide a significant slowdown of the hash computation.
