### ISSUE TITLE
fail to "./autogen.sh " 

### ISSUE THREAD

**Issue by KermitLee** [jedisct1/libsodium#988]
`./autogen.sh`
I ran the above command,.It's always the output below, and I can't continue running ./configure && make check...
`A development environment was not created.`
I tried many ways, but nothing worked...

**Comment by jedisct1** [comment]
The `./autogen.sh` is only for developers. You don't need to run it.

If you want to compile it from source, installation instructions are available here: https://doc.libsodium.org/installation
