### ISSUE TITLE
Libhydrogen-style N-Variant Key Exchange

### ISSUE THREAD

**Issue by jfkimmes** [jedisct1/libsodium#991]
Does libsodium offer an [N-Variant Key Exchange](https://github.com/jedisct1/libhydrogen/wiki/N-variant) like libhydrogen?

I am aware of the [sealed box](https://doc.libsodium.org/public-key_cryptography/sealed_boxes) encryption scheme but to my knowledge that doesn't give the server a way to respond. Is there an easy way to emulate the libhydrogen functionality?

**Comment by jedisct1** [comment]
Encrypt a client-generated secret in a sealed box, then use that secret to encrypt the rest of the session.
