### ISSUE TITLE
Disable -fPIC flag when building for embedded

### ISSUE THREAD

**Issue by sijohans** [jedisct1/libsodium#992]
Hello,

I am building this library for en embedded target (nRF52840) using arm-none-eabi-gcc 7.3.1. When i am linking the static library i encounter runtime errors. I have found out that if compiling libsodium without -fPIE and -fPIC it works well.

I cannot understand how i disable PIC using the configure script. Is this supported?

**Comment by jedisct1** [comment]
These are automatically disabled on that target. Make sure that you're not using an old version.

https://doc.libsodium.org/installation#cross-compiling
https://doc.libsodium.org/installation#stable-branch

**Comment by sijohans** [comment]
Thank you, saw in the build script that the tag 1.0.18 was used. When checking out stable i did indeed not get the -fPIC or -fPIE flag. Thanks again.
