### ISSUE TITLE
is it possible to build only the necessary part of the library?

### ISSUE THREAD

**Issue by niXman** [jedisct1/libsodium#997]
Hi,

I need to build the library so that I can use the following functions: `crypto_sign_keypair()`, `crypto_sign_detached()` and `crypto_sign_verify_detached()`

is it possible?

thanks.

**Comment by jedisct1** [comment]
Nope, but you already have a fantastic tool to only import the functions an application needs from a library: the linker :)

**Comment by niXman** [comment]
yes, it's a super utility!
but my question is related to the fact I need to be able to build a small program that uses libsodium as quickly as possible, every time a user runs some script...

**Comment by enkore** [comment]
LTO (the modern way to get rid off unwanted symbols) is not recommended for libsodium, but the old way (function-sections) might work (but is, I assume, wholly unsupported).
